export const getCelebrationsDuJour = (date: Date): string[] => {
  const jour = String(date.getDate()).padStart(2, '0');
  const mois = String(date.getMonth() + 1).padStart(2, '0');
  const cle = `${jour}-${mois}`;

  const data: Record<string, string[]> = {
    "01-01": ["Jour de l'An", "Journée mondiale de la paix", "Fête nationale de Haïti", "Fête nationale du Soudan"],
    "02-01": ["Journée mondiale de l'introversion", "Fête de la Saint-Basile (Grèce)"],
    "03-01": ["Sainte-Geneviève (Patronne de Paris)", "Commémoration de la fin de l'invasion de la Grenade"],
    "04-01": ["Journée mondiale du Braille", "Fête de l'Indépendance (Birmanie)"],
    "05-01": ["Tuguri (Corée)", "Veille de l'Épiphanie"],
    "06-01": ["Épiphanie (Fête des Rois)", "Journée mondiale des orphelins de guerre", "Noël Arménien"],
    "07-01": ["Noël Orthodoxe", "Journée de la Victoire (Cambodge)", "Journée de la quenouille (Écosse)"],
    "08-01": ["Journée mondiale de la dactylographie", "Boun Phra Vet (Laos)"],
    "09-01": ["Journée mondiale de la Corse", "Journée des martyrs (Panama)"],
    "10-01": ["Journée mondiale de Tintin", "Fête du vaudou (Bénin)"],
    "11-01": ["Journée mondiale du Merci", "Manifeste de l'Indépendance (Maroc)"],
    "12-01": ["Journée mondiale des roux", "Zanzibar Revolution Day (Tanzanie)"],
    "13-01": ["Journée mondiale sans Facebook", "Lohri (Inde)", "Fête de la Saint-Knut (Suède)"],
    "14-01": ["Nouvel An Orthodoxe", "Journée mondiale de la logique (UNESCO)"],
    "15-01": ["Journée mondiale du chewing-gum", "Fête de la culture (Inde / Pongal)", "Journée de l'Arbre (Égypte)"],
    "16-01": ["Journée mondiale de la cuisine belge", "Martin Luther King Day (USA - variable)"],
    "17-01": ["Journée mondiale de la cuisine italienne", "Fête de la Saint-Antoine (Bénédiction des animaux)"],
    "18-01": ["Journée mondiale de la neige", "Semaine de l'unité des chrétiens"],
    "19-01": ["Fête du Pop-Corn", "Timkat (Éthiopie)"],
    "20-01": ["Journée mondiale de l'acceptation", "Fête des Amoureux (Brésil)"],
    "21-01": ["Journée internationale des câlins (Hug Day)", "Fête de la grand-mère (Pologne)"],
    "22-01": ["Journée franco-allemande", "Fête de la Saint-Vincent (Patron des vignerons)"],
    "23-01": ["Journée mondiale de l'écriture manuscrite", "Bounty Day (Îles Pitcairn)"],
    "24-01": ["Journée internationale de l'éducation", "Journée mondiale de la culture africaine"],
    "25-01": ["Journée nationale de lutte contre le sexisme", "Nuit de Robert Burns (Écosse)"],
    "26-01": ["Journée mondiale des douanes", "Australia Day (Fête nationale Australie)", "Fête de la République (Inde)"],
    "27-01": ["Journée internationale à la mémoire des victimes de la Shoah", "Sainte-Dévote (Monaco)"],
    "28-01": ["Journée mondiale de la protection des données", "Journée de la mobilisation contre la lèpre"],
    "29-01": ["Journée mondiale des lépreux", "Constitution Day (Gibraltar)"],
    "30-01": ["Journée mondiale des maladies tropicales", "Journée de la non-violence dans les écoles"],
    "31-01": ["Journée mondiale de la vie en colocation", "Fête nationale de Nauru"],

// --- FÉVRIER ---
    "01-02": ["Semaine mondiale de l'harmonie interreligieuse", "Fête de la Saint-Brigitte (Irlande)"],
    "02-02": ["La Chandeleur", "Journée mondiale des zones humides", "Journée mondiale de la vie consacrée"],
    "03-02": ["Fête de la Saint-Blaise (Bénédiction des gorges)", "Setsubun (Japon)"],
    "04-02": ["Journée mondiale contre le cancer", "Journée internationale de la fraternité humaine"],
    "05-02": ["Journée mondiale du Nutella", "Journée internationale de la tolérance zéro à l'égard des mutilations génitales féminines"],
    "06-02": ["Journée mondiale sans téléphone portable", "Fête des Sâmes (Laponie)", "Waitangi Day (Nouvelle-Zélande)"],
    "07-02": ["Journée mondiale du ballet", "Fête de l'Indépendance (Grenade)"],
    "08-02": ["Journée mondiale de l'épilepsie", "Journée internationale de prière contre la traite des êtres humains"],
    "09-02": ["Journée mondiale de la pizza", "Fête de la Saint-Maron (Liban)"],
    "10-02": ["Journée internationale des légumineuses", "Fête de la Saint-Paul (Malte)"],
    "11-02": ["Journée internationale des femmes et des filles de science", "Journée mondiale du malade", "Notre-Dame de Lourdes"],
    "12-02": ["Journée internationale de Darwin", "Journée mondiale de la radio", "Journée de la main rouge (Enfants soldats)"],
    "13-02": ["Journée mondiale de la radio (UNESCO)", "Fête du cinéma (certaines régions)"],
    "14-02": ["Saint-Valentin (Fête des amoureux)", "Journée internationale de la cardiopathie congénitale"],
    "15-02": ["Journée internationale du cancer de l'enfant", "Fête du Drapeau (Canada)", "Journée de la libération (Afghanistan)"],
    "16-02": ["Journée mondiale de l'anthropologie", "Fête de l'Indépendance (Lituanie)"],
    "17-02": ["Journée mondiale de la résilience du tourisme", "Journée des actes de gentillesse spontanés"],
    "18-02": ["Journée internationale du syndrome d'Asperger", "Fête de l'Indépendance (Gambie)"],
    "19-02": ["Journée internationale des baleines", "Fête de la Constitution (Népal)"],
    "20-02": ["Journée mondiale de la justice sociale", "Fête du patrimoine (Canada)"],
    "21-02": ["Journée internationale de la langue maternelle (UNESCO)", "Fête des guides touristiques"],
    "22-02": ["Journée mondiale du scoutisme", "Journée européenne des victimes", "Fête de l'Indépendance (Sainte-Lucie)"],
    "23-02": ["Journée mondiale de la compréhension et de la paix", "Fête nationale (Brunei)", "Fête du défenseur de la patrie (Russie)"],
    "24-02": ["Journée mondiale des barmen", "Fête du Drapeau (Mexique)", "Fête de l'Indépendance (Estonie)"],
    "25-02": ["Journée mondiale du personnel de cabine", "Fête de la Révolution (Suriname)", "Fête nationale (Koweït)"],
    "26-02": ["Journée mondiale du pistage", "Fête de la Libération (Koweït)"],
    "27-02": ["Journée mondiale de l'ONG", "Journée internationale de l'ours polaire", "Fête de l'Indépendance (République Dominicaine)"],
    "28-02": ["Journée mondiale des maladies rares", "Journée sans Facebook (fin)", "Fête de l'Andalousie"],
    "29-02": ["Journée internationale des maladies rares (les années bissextiles)", "Journée mondiale des sauteurs"],

// --- MARS ---
    "01-03": ["Journée \"zéro discrimination\" (ONU)", "Journée mondiale du compliment", "Fête de la Saint-David (Pays de Galles)"],
    "02-03": ["Journée mondiale de la santé mentale des adolescents", "Fête de la Saint-Chad"],
    "03-03": ["Journée mondiale de la vie sauvage", "Journée mondiale de l'audition", "Fête des filles (Hina Matsuri - Japon)"],
    "04-03": ["Journée mondiale de l'obésité", "Journée mondiale de l'ingénierie pour le développement durable"],
    "05-03": ["Journée mondiale de l'efficacité énergétique", "Fête de la coutume (Vanuatu)"],
    "06-03": ["Journée européenne de l'orthophonie", "Fête de l'Indépendance (Ghana)"],
    "07-03": ["Journée mondiale du tennis", "Sainte-Félicité et Sainte-Perpétue"],
    "08-03": ["Journée internationale des droits des femmes", "Fête de la Révolution (Syrie)"],
    "09-03": ["Journée mondiale du rein (variable)", "Fête du Baron Bliss (Belize)"],
    "10-03": ["Journée internationale des femmes juges", "Fête nationale (Tibet)"],
    "11-03": ["Journée mondiale de la plomberie", "Journée européenne des victimes du terrorisme"],
    "12-03": ["Journée mondiale contre la cyber-censure", "Fête nationale (Maurice)"],
    "13-03": ["Journée mondiale du sommeil (variable)", "Fête des éléphants (Thaïlande)"],
    "14-03": ["Journée internationale des mathématiques (Pi Day)", "Journée mondiale de l'action pour les rivières"],
    "15-03": ["Journée mondiale des droits des consommateurs", "Journée internationale de lutte contre l'islamophobie"],
    "16-03": ["Journée mondiale du travail social", "Fête de la liberté (Hongrie)"],
    "17-03": ["Saint-Patrick (Fête nationale irlandaise)", "Journée mondiale de la viande de bœuf (clin d'œil à l'Irlande)"],
    "18-03": ["Journée mondiale du recyclage", "Fête du Drapeau et de l'Hymne (Aruba)"],
    "19-03": ["Journée nationale du souvenir (Guerre d'Algérie)", "Fête de la Saint-Joseph"],
    "20-03": ["Journée internationale de la Francophonie", "Journée mondiale du bonheur", "Équinoxe de printemps (variable)"],
    "21-03": ["Journée mondiale de la poésie", "Journée internationale pour l'élimination de la discrimination raciale", "Journée mondiale de la trisomie 21", "Journée internationale des forêts"],
    "22-03": ["Journée mondiale de l'eau"],
    "23-03": ["Journée météorologique mondiale", "Fête nationale (Pakistan)"],
    "24-03": ["Journée mondiale de lutte contre la tuberculose", "Journée internationale pour le droit à la vérité"],
    "25-03": ["Journée internationale de commémoration des victimes de l'esclavage", "Annonciation", "Fête nationale (Grèce)"],
    "26-03": ["Journée mondiale pour l'épilepsie (Purple Day)", "Fête de l'Indépendance (Bangladesh)"],
    "27-03": ["Journée mondiale du théâtre", "Journée nationale du fromage (France)"],
    "28-03": ["Journée mondiale de l'endométriose"],
    "29-03": ["Journée mondiale du piano (88e jour de l'année)", "Fête des martyrs (Madagascar)"],
    "30-03": ["Journée mondiale des troubles bipolaires", "Journée internationale du zéro déchet"],
    "31-03": ["Journée internationale de visibilité transgenre", "Fête de la liberté (Malte)"],

// --- AVRIL ---
    "01-04": ["Poisson d'avril", "Journée mondiale de la blague", "Fête de la Saint-Hugues"],
    "02-04": ["Journée mondiale de sensibilisation à l'autisme", "Journée internationale du livre pour enfants"],
    "03-04": ["Journée mondiale du travail invisible", "Fête de la Saint-Richard"],
    "04-04": ["Journée internationale pour la sensibilisation au problème des mines", "Fête de la Saint-Isidore"],
    "05-04": ["Journée internationale de la conscience", "Fête de la Saint-Iréne"],
    "06-04": ["Journée internationale du sport pour le développement et la paix", "Journée mondiale du tennis de table"],
    "07-04": ["Journée mondiale de la santé", "Journée internationale de réflexion sur le génocide au Rwanda"],
    "08-04": ["Journée internationale des Roms", "Fête de la Saint-Albert"],
    "09-04": ["Journée mondiale de la licorne (insolite)", "Fête de la Saint-Gautier"],
    "10-04": ["Journée mondiale de l'homéopathie", "Journée internationale des frères et sœurs"],
    "11-04": ["Journée mondiale de la maladie de Parkinson", "Fête de la Saint-Stanislas"],
    "12-04": ["Journée internationale du vol spatial habité", "Journée mondiale des enfants des rues"],
    "13-04": ["Journée mondiale du Scrabble", "Fête de la Saint-Ida"],
    "14-04": ["Journée mondiale de la maladie de Chagas", "Fête de la Saint-Maxime"],
    "15-04": ["Journée mondiale de l'art", "Fête de la Saint-Paterne"],
    "16-04": ["Journée mondiale contre l'esclavage des enfants", "Journée mondiale de la voix"],
    "17-04": ["Journée mondiale de l'hémophilie", "Journée internationale des luttes paysannes"],
    "18-04": ["Journée mondiale des monuments et des sites", "Journée mondiale du radioamateur"],
    "19-04": ["Journée mondiale du foie", "Fête de la Saint-Emma"],
    "20-04": ["Journée de la langue chinoise (ONU)", "Fête de la Saint-Odette"],
    "21-04": ["Journée mondiale de la créativité et de l'innovation", "Fête de la Saint-Anselme"],
    "22-04": ["Journée mondiale de la Terre", "Fête de la Saint-Alexandre"],
    "23-04": ["Journée mondiale du livre et du droit d'auteur", "Journée de la langue anglaise"],
    "24-04": ["Journée mondiale des animaux de laboratoire", "Journée internationale du multilatéralisme"],
    "25-04": ["Journée mondiale contre le paludisme", "Journée mondiale des manchots", "Fête de la Saint-Marc"],
    "26-04": ["Journée mondiale de la propriété intellectuelle", "Journée mondiale des secrétaires"],
    "27-04": ["Journée mondiale du design graphique", "Fête de la Saint-Zita"],
    "28-04": ["Journée mondiale de la sécurité et de la santé au travail"],
    "29-04": ["Journée internationale de la danse", "Journée mondiale de la médecine vétérinaire"],
    "30-04": ["Journée internationale du jazz", "Journée mondiale des mobilités douces"],

// --- MAI ---
    "01-05": ["Fête du Travail", "Journée mondiale du rire", "Fête du muguet"],
    "02-05": ["Journée mondiale du thon", "Journée internationale contre le harcèlement scolaire"],
    "03-05": ["Journée mondiale de la liberté de la presse", "Journée mondiale du soleil"],
    "04-05": ["Journée internationale des pompiers", "Journée mondiale du jardinage nu (insolite)", "Star Wars Day (May the 4th)"],
    "05-05": ["Journée mondiale de l'hygiène des mains", "Journée internationale des sages-femmes", "Fête de l'Europe (Conseil de l'Europe)"],
    "06-05": ["Journée internationale sans régime", "Fête de la Saint-Prudence"],
    "07-05": ["Journée mondiale de l'asthme", "Fête de la Sainte-Gisèle"],
    "08-05": ["Fête de la Victoire 1945", "Journée mondiale de la Croix-Rouge"],
    "09-05": ["Journée de l'Europe (Union Européenne)", "Fête de la Saint-Pacôme"],
    "10-05": ["Journée nationale de commémoration de l'esclavage", "Journée mondiale du Lupus"],
    "11-05": ["Journée mondiale des espèces menacées", "Fête de la Sainte-Estelle"],
    "12-05": ["Journée internationale des infirmières", "Journée mondiale de la fibromyalgie"],
    "13-05": ["Journée mondiale de l'ingénierie pour le développement durable", "Fête de la Saint-Rolande"],
    "14-05": ["Journée mondiale du commerce équitable", "Fête de la Saint-Matthias"],
    "15-05": ["Journée internationale des familles", "Journée mondiale de la maladie de Huntington"],
    "16-05": ["Journée internationale de la lumière (UNESCO)", "Journée internationale du vivre-ensemble en paix"],
    "17-05": ["Journée mondiale contre l'homophobie et la transphobie", "Journée mondiale des télécommunications"],
    "18-05": ["Journée internationale des musées", "Journée mondiale du vaccin contre le SIDA"],
    "19-05": ["Journée mondiale des maladies inflammatoires de l'intestin (MICI)", "Fête de la Saint-Yves"],
    "20-05": ["Journée mondiale des abeilles", "Journée européenne de la mer"],
    "21-05": ["Journée mondiale de la diversité culturelle pour le dialogue et le développement", "Journée internationale du thé"],
    "22-05": ["Journée internationale de la diversité biologique", "Fête de la Sainte-Émile"],
    "23-05": ["Journée mondiale des tortues", "Journée internationale pour l'élimination de la fistule obstétricale"],
    "24-05": ["Journée européenne des parcs naturels", "Journée mondiale de la schizophrénie"],
    "25-05": ["Journée mondiale de l'Afrique", "Journée internationale des enfants disparus", "Geek Pride Day"],
    "26-05": ["Journée mondiale de la loutre", "Fête de la Saint-Bérenger"],
    "27-05": ["Journée nationale de la Résistance", "Journée mondiale de la médecine d'urgence"],
    "28-05": ["Journée mondiale de l'hygiène menstruelle", "Journée internationale d'action pour la santé des femmes"],
    "29-05": ["Journée internationale des Casques bleus de l'ONU", "Journée mondiale de la santé digestive"],
    "30-05": ["Journée mondiale de la sclérose en plaques", "Fête de la Sainte-Jeanne d'Arc"],
    "31-05": ["Journée mondiale sans tabac", "Journée mondiale des perroquets"],

// --- JUIN ---
    "01-06": ["Journée mondiale des parents", "Journée mondiale du lait"],
    "02-06": ["Journée européenne contre l'obésité", "Fête de la Sainte-Blandine"],
    "03-06": ["Journée mondiale de la bicyclette", "Fête de la Saint-Kévin"],
    "04-06": ["Journée internationale des enfants victimes innocentes d'agression"],
    "05-06": ["Journée mondiale de l'environnement", "Journée internationale de la lutte contre la pêche illicite"],
    "06-06": ["Journée mondiale de la maladie de Verneuil", "Anniversaire du Débarquement"],
    "07-06": ["Journée mondiale de la sécurité sanitaire des aliments", "Fête de la Saint-Gilbert"],
    "08-06": ["Journée mondiale de l'océan", "Journée mondiale des tumeurs cérébrales"],
    "09-06": ["Journée mondiale de l'accréditation", "Fête de la Saint-Félicien"],
    "10-06": ["Journée mondiale de l'art nouveau", "Fête de la Saint-Landry"],
    "11-06": ["Journée mondiale du bien-être", "Fête de la Saint-Barnabé"],
    "12-06": ["Journée mondiale contre le travail des enfants", "Fête de la Saint-Guy"],
    "13-06": ["Journée internationale de sensibilisation à l'albinisme", "Fête de la Saint-Antoine de Padoue"],
    "14-06": ["Journée mondiale du donneur de sang", "Fête de la Saint-Élisée"],
    "15-06": ["Journée mondiale de sensibilisation à la maltraitance des personnes âgées", "Journée européenne du vent"],
    "16-06": ["Journée de l'enfant africain", "Journée internationale des transferts de fonds familiaux"],
    "17-06": ["Journée mondiale de la lutte contre la désertification et la sécheresse"],
    "18-06": ["Journée de la gastronomie durable", "Appel du 18 juin", "Journée mondiale de l'orgueil autiste"],
    "19-06": ["Journée mondiale de la drépanocytose", "Journée internationale pour l'élimination de la violence sexuelle en temps de conflit"],
    "20-06": ["Journée mondiale des réfugiés", "Solstice d'été (selon l'année)"],
    "21-06": ["Fête de la Musique", "Journée internationale du yoga", "Journée mondiale de la SLA (maladie de Charcot)", "Journée internationale de la girafe"],
    "22-06": ["Journée nationale de réflexion sur le don d'organes et la greffe", "Journée mondiale des amoureux de la forêt"],
    "23-06": ["Journée des Nations Unies pour la fonction publique", "Journée internationale des veuves", "Journée Olympique"],
    "24-06": ["Fête de la Saint-Jean", "Journée internationale des femmes dans la diplomatie"],
    "25-06": ["Journée mondiale du vitiligo", "Journée internationale des gens de mer"],
    "26-06": ["Journée internationale contre l'abus et le trafic de drogues", "Journée internationale de soutien aux victimes de la torture"],
    "27-06": ["Journée des micro, petites et moyennes entreprises", "Journée mondiale des travailleurs de la pêche"],
    "28-06": ["Journée mondiale du dépistage de la PCU", "Fête de la Saint-Irénée"],
    "29-06": ["Journée internationale des tropiques", "Fête de la Saint-Pierre et Saint-Paul"],
    "30-06": ["Journée internationale des astéroïdes", "Journée internationale du parlementarisme"],

// --- JUILLET ---
    "01-07": ["Journée mondiale du bandeau (insolite)", "Fête du Canada", "Fête de la Saint-Thierry"],
    "02-07": ["Journée mondiale des OVNIS", "Journée mondiale des journalistes sportifs"],
    "03-07": ["Journée mondiale sans sacs plastique", "Fête de la Saint-Thomas (calendrier moderne)"],
    "04-07": ["Fête d'indépendance des États-Unis (Independence Day)", "Fête de la Sainte-Élisabeth"],
    "05-07": ["Journée mondiale du bikini", "Fête d'indépendance du Venezuela", "Fête d'indépendance de l'Algérie"],
    "06-07": ["Journée internationale du baiser", "Journée mondiale des zoonoses"],
    "07-07": ["Journée mondiale du chocolat", "Journée de la langue kiswahili (UNESCO)"],
    "08-07": ["Journée mondiale du mal de dos", "Fête de la Saint-Thibaut"],
    "09-07": ["Journée de la destruction des armes légères", "Fête d'indépendance de l'Argentine"],
    "10-07": ["Journée mondiale de l'énergie libre", "Fête de la Saint-Ulrich"],
    "11-07": ["Journée mondiale de la population", "Fête de la Saint-Benoît"],
    "12-07": ["Journée internationale de Malala (éducation des filles)", "Fête de la Saint-Olivier"],
    "13-07": ["Journée mondiale des frites belges", "Fête de la Saint-Henri"],
    "14-07": ["Fête Nationale Française", "Journée mondiale des requins"],
    "15-07": ["Journée mondiale des compétences des jeunes", "Fête de la Saint-Donald"],
    "16-07": ["Journée mondiale des serpents", "Fête de Notre-Dame du Mont-Carmel"],
    "17-07": ["Journée mondiale de la justice pénale internationale", "Journée mondiale des émojis"],
    "18-07": ["Journée internationale Nelson Mandela"],
    "19-07": ["Journée mondiale des châteaux de sable", "Fête de la Saint-Arsène"],
    "20-07": ["Journée mondiale du jeu d'échecs", "Journée internationale de la Lune"],
    "21-07": ["Fête nationale belge", "Journée mondiale de la malbouffe"],
    "22-07": ["Journée mondiale du cerveau", "Fête de la Sainte-Marie-Madeleine"],
    "23-07": ["Journée mondiale du dauphin", "Fête de la Sainte-Brigitte"],
    "24-07": ["Journée internationale des assistants sociaux", "Fête de la Sainte-Christine"],
    "25-07": ["Journée mondiale de la prévention des noyades", "Fête de la Saint-Jacques"],
    "26-07": ["Journée internationale pour la conservation de l'écosystème des mangroves"],
    "27-07": ["Journée mondiale de la tête et du cou", "Fête de la Sainte-Nathalie"],
    "28-07": ["Journée mondiale contre l'hépatite", "Journée mondiale de la conservation de la nature"],
    "29-07": ["Journée internationale du tigre", "Fête de la Sainte-Marthe"],
    "30-07": ["Journée internationale de l'amitié", "Journée mondiale de la dignité des victimes de la traite d'êtres humains"],
    "31-07": ["Journée internationale de la femme africaine", "Journée mondiale des gardes forestiers (Rangers)"],

// --- AOÛT ---
    "01-08": ["Journée mondiale de l'allaitement maternel", "Fête nationale de la Suisse", "Fête de la Saint-Alphonse"],
    "02-08": ["Journée mondiale de la bière (variable)", "Fête de la Saint-Julien"],
    "03-08": ["Journée mondiale de la planification familiale", "Fête de la Sainte-Lydie"],
    "04-08": ["Journée internationale du léopard nébuleux", "Fête de la Saint-Jean-Marie Vianney"],
    "05-08": ["Journée mondiale de l'huître", "Fête de la Saint-Abel"],
    "06-08": ["Journée mondiale pour la fin de la pêche", "Anniversaire d'Hiroshima"],
    "07-08": ["Journée mondiale des phares", "Fête de l'Indépendance (Côte d'Ivoire)"],
    "08-08": ["Journée internationale du chat", "Fête de la Saint-Dominique"],
    "09-08": ["Journée internationale des populations autochtones", "Fête de la Saint-Amour"],
    "10-08": ["Journée mondiale du lion", "Nuit des étoiles filantes (Saint-Laurent)"],
    "11-08": ["Journée mondiale du steelpan", "Fête de la Sainte-Claire"],
    "12-08": ["Journée internationale de la jeunesse", "Journée mondiale de l'éléphant"],
    "13-08": ["Journée internationale des gauchers", "Fête de la Saint-Hippolyte"],
    "14-08": ["Journée mondiale du lézard", "Fête de la Saint-Evrard"],
    "15-08": ["Assomption", "Journée mondiale des lémuriens"],
    "16-08": ["Journée mondiale du cerf-volant", "Fête de la Saint-Armel"],
    "17-08": ["Journée mondiale du chat noir", "Fête de la Saint-Hyacinthe"],
    "18-08": ["Journée mondiale de la recherche sur le cancer du sein", "Fête de la Sainte-Hélène"],
    "19-08": ["Journée mondiale de l'aide humanitaire", "Journée mondiale de la photographie"],
    "20-08": ["Journée mondiale du moustique", "Fête de la Saint-Bernard"],
    "21-08": ["Journée internationale du souvenir des victimes du terrorisme", "Fête de la Saint-Christophe"],
    "22-08": ["Journée mondiale du lait végétal", "Fête de la Saint-Fabrice"],
    "23-08": ["Journée internationale du souvenir de la traite négrière et de son abolition"],
    "24-08": ["Journée mondiale étrange (insolite)", "Fête de la Saint-Barthélemy"],
    "25-08": ["Libération de Paris", "Fête de la Saint-Louis"],
    "26-08": ["Journée mondiale du chien", "Journée internationale de l'égalité des femmes"],
    "27-08": ["Journée mondiale de la boxe", "Fête de la Sainte-Monique"],
    "28-08": ["Journée mondiale du nœud papillon", "Fête de la Saint-Augustin"],
    "29-08": ["Journée internationale contre les essais nucléaires", "Fête de la Sainte-Sabine"],
    "30-08": ["Journée internationale des victimes de disparitions forcées", "Journée mondiale du requin-baleine"],
    "31-08": ["Journée mondiale de la blogosphère", "Journée internationale des personnes d'ascendance africaine"],

// --- SEPTEMBRE ---
    "01-09": ["Journée mondiale de prière pour la sauvegarde de la Création", "Fête de la Saint-Gilles"],
    "02-09": ["Journée mondiale de la fin de la Seconde Guerre mondiale", "Fête de la Sainte-Ingrid"],
    "03-09": ["Journée mondiale de l'hygiène dentaire", "Fête de la Saint-Grégoire"],
    "04-09": ["Journée mondiale de la santé sexuelle", "Sainte-Rosalie"],
    "05-09": ["Journée internationale de la charité", "Fête de la Sainte-Raïssa"],
    "06-09": ["Journée mondiale de la lutte contre la procrastination", "Fête de la Saint-Bertrand"],
    "07-09": ["Journée internationale de l'air pur pour des ciels bleus", "Fête de la Sainte-Reine"],
    "08-09": ["Journée internationale de l'alphabétisation", "Journée mondiale de la kinésithérapie", "Nativité de la Vierge"],
    "09-09": ["Journée mondiale de sensibilisation au syndrome d'alcoolisation fœtale", "Fête de la Saint-Alain"],
    "10-09": ["Journée mondiale de prévention du suicide", "Journée mondiale de la gynécologie"],
    "11-09": ["Journée mondiale des premiers secours", "Commémoration des attentats du 11 septembre"],
    "12-09": ["Journée des Nations Unies pour la coopération Sud-Sud", "Fête de la Saint-Apollinaire"],
    "13-09": ["Journée mondiale des développeurs (256e jour)", "Journée mondiale de lutte contre la septicémie"],
    "14-09": ["Exaltation de la Sainte-Croix", "Fête de la Sainte-Adelphe"],
    "15-09": ["Journée internationale de la démocratie", "Journée mondiale du lymphome"],
    "16-09": ["Journée internationale de la protection de la couche d'ozone", "Journée mondiale de l'arthrose"],
    "17-09": ["Journée mondiale de la sécurité des patients", "Journée européenne du patrimoine (variable)"],
    "18-09": ["Journée mondiale du contrôle de l'eau", "Journée internationale de l'égalité salariale"],
    "19-09": ["Journée internationale du parler pirate (insolite)", "Fête de la Saint-Émilie"],
    "20-09": ["Journée mondiale du sport universitaire", "Journée internationale de la liberté"],
    "21-09": [
      "Journée internationale de la paix (ONU)",
      "Journée mondiale de la maladie d'Alzheimer",
      "Journée mondiale de la gratitude",
      "Fête nationale de l'Arménie",
      "Fête nationale du Belize",
      "Journée nationale de l’arbre (Brésil)",
      "Fête nationale de Malte",
      "Fête de Mabon (Néopaganisme)",
      "Nativité de la Théotokos (Orthodoxie)"
    ],
    "22-09": ["Journée mondiale sans voiture", "Journée mondiale du rhinocéros", "Équinoxe d'automne (variable)"],
    "23-09": ["Journée internationale des langues des signes", "Journée de la bisexualité"],
    "24-09": ["Journée mondiale du cancer de la thyroïde", "Fête de la Saint-Thècle"],
    "25-09": ["Journée mondiale des pharmaciens", "Journée mondiale du rêve"],
    "26-09": ["Journée européenne des langues", "Journée internationale pour l'élimination totale des armes nucléaires"],
    "27-09": ["Journée mondiale du tourisme", "Journée mondiale du lait scolaire"],
    "28-09": ["Journée mondiale contre la rage", "Journée mondiale du droit à l'avortement"],
    "29-09": ["Journée mondiale du cœur", "Journée internationale de sensibilisation aux pertes et gaspillages de nourriture", "Fête de la Saint-Michel"],
    "30-09": ["Journée internationale de la traduction", "Journée mondiale de la mer"],

// --- OCTOBRE ---
    "01-10": ["Journée internationale des personnes âgées", "Journée mondiale du végétarisme", "Journée mondiale du chocolat (autre date)", "Lancement d'Octobre Rose"],
    "02-10": ["Journée internationale de la non-violence", "Journée mondiale de la ferme"],
    "03-10": ["Journée mondiale de l'habitat", "Fête de la Saint-Gérard"],
    "04-10": ["Journée mondiale des animaux", "Fête de la Saint-François d'Assise"],
    "05-10": ["Journée mondiale des enseignants", "Journée mondiale du sourire (variable)"],
    "06-10": ["Journée mondiale de la paralysie cérébrale", "Journée nationale des aidants"],
    "07-10": ["Journée mondiale du coton", "Journée mondiale pour le travail décent"],
    "08-10": ["Journée mondiale de la vue", "Journée internationale de la prévention des catastrophes naturelles"],
    "09-10": ["Journée mondiale de la poste", "Journée européenne du don d'organes"],
    "10-10": ["Journée mondiale de la santé mentale", "Journée mondiale contre la peine de mort", "Journée européenne des langues"],
    "11-10": ["Journée internationale de la fille", "Journée mondiale de l'obésité"],
    "12-10": ["Journée mondiale des soins palliatifs", "Journée mondiale de l'arthrite"],
    "13-10": ["Journée internationale pour la réduction des risques de catastrophes", "Journée mondiale de l'œuf (insolite)"],
    "14-10": ["Journée mondiale de la normalisation", "Journée mondiale du futur"],
    "15-10": ["Journée mondiale du lavage des mains", "Journée internationale des femmes rurales", "Journée mondiale de la canne blanche"],
    "16-10": ["Journée mondiale de l'alimentation", "Journée mondiale de la colonne vertébrale", "Journée mondiale du pain"],
    "17-10": ["Journée internationale pour l'élimination de la pauvreté", "Journée mondiale du don d'organes et de la greffe"],
    "18-10": ["Journée mondiale de la ménopause", "Fête de la Saint-Luc"],
    "19-10": ["Journée mondiale de la reconstruction mammaire", "Fête de la Saint-René"],
    "20-10": ["Journée mondiale de l'ostéoporose", "Journée mondiale de la statistique", "Journée internationale des cuisiniers"],
    "21-10": ["Journée mondiale de l'iode", "Fête de la Sainte-Céline"],
    "22-10": ["Journée mondiale du bégaiement", "Journée internationale de la connaissance des papillons"],
    "23-10": ["Journée mondiale du léopard des neiges", "Fête de la Saint-Jean-de-Capistran"],
    "24-10": ["Journée des Nations Unies", "Journée mondiale d'information sur le développement"],
    "25-10": ["Journée mondiale des pâtes", "Journée européenne de la justice", "Journée mondiale de l'opéra"],
    "26-10": ["Journée mondiale de la visibilité intersexe", "Fête de la Saint-Dimitri"],
    "27-10": ["Journée mondiale du patrimoine audiovisuel", "Journée mondiale de l'ergothérapie"],
    "28-10": ["Journée mondiale de l'animation", "Journée internationale de la langue et de la culture créoles"],
    "29-10": ["Journée mondiale de l'AVC", "Journée mondiale du psoriasis"],
    "30-10": ["Journée mondiale de la vie", "Fête de la Saint-Bienvenu"],
    "31-10": ["Halloween", "Journée mondiale des villes", "Journée mondiale de l'épargne"],

// --- OCTOBRE ---
    "01-10": ["Journée internationale des personnes âgées", "Journée mondiale du végétarisme", "Journée mondiale du chocolat (autre date)", "Lancement d'Octobre Rose"],
    "02-10": ["Journée internationale de la non-violence", "Journée mondiale de la ferme"],
    "03-10": ["Journée mondiale de l'habitat", "Fête de la Saint-Gérard"],
    "04-10": ["Journée mondiale des animaux", "Fête de la Saint-François d'Assise"],
    "05-10": ["Journée mondiale des enseignants", "Journée mondiale du sourire (variable)"],
    "06-10": ["Journée mondiale de la paralysie cérébrale", "Journée nationale des aidants"],
    "07-10": ["Journée mondiale du coton", "Journée mondiale pour le travail décent"],
    "08-10": ["Journée mondiale de la vue", "Journée internationale de la prévention des catastrophes naturelles"],
    "09-10": ["Journée mondiale de la poste", "Journée européenne du don d'organes"],
    "10-10": ["Journée mondiale de la santé mentale", "Journée mondiale contre la peine de mort", "Journée européenne des langues"],
    "11-10": ["Journée internationale de la fille", "Journée mondiale de l'obésité"],
    "12-10": ["Journée mondiale des soins palliatifs", "Journée mondiale de l'arthrite"],
    "13-10": ["Journée internationale pour la réduction des risques de catastrophes", "Journée mondiale de l'œuf (insolite)"],
    "14-10": ["Journée mondiale de la normalisation", "Journée mondiale du futur"],
    "15-10": ["Journée mondiale du lavage des mains", "Journée internationale des femmes rurales", "Journée mondiale de la canne blanche"],
    "16-10": ["Journée mondiale de l'alimentation", "Journée mondiale de la colonne vertébrale", "Journée mondiale du pain"],
    "17-10": ["Journée internationale pour l'élimination de la pauvreté", "Journée mondiale du don d'organes et de la greffe"],
    "18-10": ["Journée mondiale de la ménopause", "Fête de la Saint-Luc"],
    "19-10": ["Journée mondiale de la reconstruction mammaire", "Fête de la Saint-René"],
    "20-10": ["Journée mondiale de l'ostéoporose", "Journée mondiale de la statistique", "Journée internationale des cuisiniers"],
    "21-10": ["Journée mondiale de l'iode", "Fête de la Sainte-Céline"],
    "22-10": ["Journée mondiale du bégaiement", "Journée internationale de la connaissance des papillons"],
    "23-10": ["Journée mondiale du léopard des neiges", "Fête de la Saint-Jean-de-Capistran"],
    "24-10": ["Journée des Nations Unies", "Journée mondiale d'information sur le développement"],
    "25-10": ["Journée mondiale des pâtes", "Journée européenne de la justice", "Journée mondiale de l'opéra"],
    "26-10": ["Journée mondiale de la visibilité intersexe", "Fête de la Saint-Dimitri"],
    "27-10": ["Journée mondiale du patrimoine audiovisuel", "Journée mondiale de l'ergothérapie"],
    "28-10": ["Journée mondiale de l'animation", "Journée internationale de la langue et de la culture créoles"],
    "29-10": ["Journée mondiale de l'AVC", "Journée mondiale du psoriasis"],
    "30-10": ["Journée mondiale de la vie", "Fête de la Saint-Bienvenu"],
    "31-10": ["Halloween", "Journée mondiale des villes", "Journée mondiale de l'épargne"],

// --- DÉCEMBRE ---
    "01-12": ["Journée mondiale de lutte contre le SIDA", "Fête de la Saint-Éloi (Patron des métallurgistes)"],
    "02-12": ["Journée internationale pour l'abolition de l'esclavage", "Journée mondiale de la samba"],
    "03-12": ["Journée internationale des personnes handicapées", "Journée mondiale du 3D"],
    "04-12": ["Journée internationale des banques", "Fête de la Sainte-Barbe (Patronne des pompiers)"],
    "05-12": ["Journée mondiale des sols", "Journée internationale des bénévoles"],
    "06-12": ["Fête de la Saint-Nicolas", "Journée mondiale du mot de passe (autre date)"],
    "07-12": ["Journée internationale de l'aviation civile", "Fête de la Saint-Ambroise"],
    "08-12": ["Fête de l'Immaculée Conception", "Journée mondiale du climat", "Fête des Lumières (Lyon)"],
    "09-12": ["Journée internationale de lutte contre la corruption", "Journée de la laïcité (France)"],
    "10-12": ["Journée internationale des droits de l'homme", "Journée internationale pour les droits des animaux"],
    "11-12": ["Journée internationale de la montagne", "Journée mondiale de l'asthme (autre date)"],
    "12-12": ["Journée internationale de la couverture sanitaire universelle", "Journée internationale de la neutralité"],
    "13-12": ["Journée mondiale de la raclette (insolite)", "Fête de la Sainte-Lucie"],
    "14-12": ["Journée mondiale du singe", "Fête de la Saint-Jean de la Croix"],
    "15-12": ["Journée internationale du thé (autre date)", "Fête de la Sainte-Ninon"],
    "16-12": ["Journée mondiale du pull de Noël (variable)", "Fête de la Sainte-Alice"],
    "17-12": ["Journée internationale pour la fin des violences sexistes", "Fête de la Saint-Gaël"],
    "18-12": ["Journée internationale des migrants", "Journée de la langue arabe (UNESCO)"],
    "19-12": ["Journée éternelle (insolite)", "Fête de la Saint-Urbain"],
    "20-12": ["Journée internationale de la solidarité humaine", "Fête de la Saint-Théophile"],
    "21-12": ["Journée mondiale de l'orgasme (Solstice)", "Journée mondiale du basket-ball", "Hiver (Solstice)"],
    "22-12": ["Journée mondiale du plaisir d'offrir", "Fête de la Sainte-Françoise-Xavière"],
    "23-12": ["Journée mondiale des racines", "Fête de la Saint-Armand"],
    "24-12": ["Réveillon de Noël", "Fête de la Sainte-Adèle"],
    "25-12": ["Noël", "Fête de la Sainte-Eugénie"],
    "26-12": ["Boxing Day (Lendemain de Noël)", "Fête de la Saint-Étienne"],
    "27-12": ["Journée internationale de la préparation aux épidémies", "Fête de la Saint-Jean l'Évangéliste"],
    "28-12": ["Journée mondiale du cinéma", "Fête des Saints Innocents"],
    "29-12": ["Journée internationale de la diversité biologique (ancienne date)", "Fête de la Saint-David"],
    "30-12": ["Journée mondiale du rangement de bureau (avant l'an neuf)", "Fête de la Saint-Roger"],
    "31-12": ["Réveillon de la Saint-Sylvestre", "Journée mondiale de la paix (Veille)"]
  };

  return data[cle] || ["Journée de découverte et de partage"];
};