export const getDictonDuJour = (date: Date): string => {
  const jour = String(date.getDate()).padStart(2, '0');
  const mois = String(date.getMonth() + 1).padStart(2, '0');
  const cle = `${jour}-${mois}`;

  const dictons: Record<string, string> = {
    // --- JANVIER ---
    "01-01": "Jour de l'An beau, mois d'août très chaud.",
    "02-01": "Le temps du deux janvier prévient celui de septembre.",
    "03-01": "Sainte-Geneviève ne sort point, si Saint-Marcel ne la rejoint.",
    "04-01": "Le jour de la Saint-Odilon souvent n'amène rien de bon.",
    "05-01": "À la Saint-Gerlac, le temps est souvent au vrac.",
    "06-01": "Pluie aux Rois, blé jusqu'au toit.",
    "07-01": "S'il neige à la Saint-Raymond, l'hiver est encore long.",
    "08-01": "Temps de Saint-Lucien, temps de chien.",
    "09-01": "Pour Saint-Adrien, le froid nous revient.",
    "10-01": "S'il pleut à la Saint-Guillaume, peu de blé, beaucoup de chaume.",
    "11-01": "À la Saint-Paulin, on compte les hirondelles.",
    "12-01": "Arcade et Hilaire gèlent les rivières.",
    "13-01": "Janvier d'eau chiche fait le paysan riche.",
    "14-01": "Soleil de Saint-Hilaire, rentre du bois pour ton aire.",
    "15-01": "À la Saint-Maur, tout est mort.",
    "16-01": "Prépare pour Saint-Marcel, tes tisons et ton sel.",
    "17-01": "Saint-Antoine sec et beau, remplit la cave et le tonneau.",
    "18-01": "Janvier sec et sage est un bon présage.",
    "19-01": "À la Saint-Sulpice, le temps est souvent complice.",
    "20-01": "S'il gèle à la Saint-Sébastien, l'hiver reprend de plus bel.",
    "21-01": "À la Sainte-Agnès, l'hiver s'en va ou se déchaîne.",
    "22-01": "À la Saint-Vincent, tout dégèle ou tout fend.",
    "23-01": "Saint-Barnard ensoleillé rend le vigneron gai.",
    "24-01": "Saint-François de Sales à la main, sème ton grain.",
    "25-01": "À la Saint-Paul, l'hiver se casse le col.",
    "26-01": "Sainte-Paule sèche et belle, année de fruits nous appelle.",
    "27-01": "Saint-Julien brise la glace, s'il ne la brise, c'est qu'il l'embrasse.",
    "28-01": "À la Saint-Charlemagne, les glaces nous accompagnent.",
    "29-01": "S'il pleut à la Saint-Gildas, le paysan n'est pas las.",
    "30-01": "Sainte-Martine, de la neige dans la farine.",
    "31-01": "À la Saint-Marcelle, on voit les hirondelles.",

// --- FÉVRIER ---
    "01-02": "À la Sainte-Ella, on ne sait pas si l'hiver restera là.",
    "02-02": "À la Chandeleur, l'hiver cesse ou prend vigueur.",
    "03-02": "S'il ne pleut ni ne neige à la Saint-Blaise, en mars le froid en prendra à son aise.",
    "04-02": "À la Saint-Isidore, si le soleil dore, le blé sera fort.",
    "05-02": "Si l'eau gèle à la Sainte-Agathe, la récolte ne sera pas hâte.",
    "06-02": "À la Saint-Gaston, surveille tes bourgeons.",
    "07-02": "À la Sainte-Eugénie, le temps est souvent à la pluie.",
    "08-02": "À la Saint-Jean-de-Matha, l'hiver ne s'en ira pas.",
    "09-02": "À la Sainte-Apolline, l'hiver quitte la colline.",
    "10-02": "À la Sainte-Arnaud, il fait souvent beau.",
    "11-02": "À la Sainte-Adeline, la neige nous chagrine.",
    "12-02": "Si le soleil luit pour la Sainte-Eulalie, pommes et poires à la folie.",
    "13-02": "De Sainte-Béatrice la nuée, assure une bonne année.",
    "14-02": "À la Saint-Valentin, tous les vents sont marins.",
    "15-02": "À la Saint-Claude, le temps est souvent chaud.",
    "16-02": "S'il pleut à la Sainte-Julienne, la pluie est souvent vaine.",
    "17-02": "Février de tous les mois, est le plus court et le moins courtois.",
    "18-02": "À la Sainte-Bernadette, souvent le soleil se fête.",
    "19-02": "À la Saint-Gabin, la pluie est au chemin.",
    "20-02": "À la Sainte-Aimée, la neige est aimée.",
    "21-02": "À la Saint-Pierre-Damien, l'hiver ne vaut plus rien.",
    "22-02": "À la Sainte-Isabelle, si le soleil luit, le temps sera beau la nuit.",
    "23-02": "À la Saint-Lazare, la pluie n'est jamais rare.",
    "24-02": "À la Saint-Mathias, la neige n'est jamais lasse.",
    "25-02": "Février qui gèle et tonne, annonce un bel automne.",
    "26-02": "À la Saint-Nestor, le temps est souvent fort.",
    "27-02": "À la Sainte-Honorine, la pluie nous domine.",
    "28-02": "Beau février, c’est de l’or au pommier.",
    "29-02": "L'année bissextile, soyez tranquille, le blé sera facile.",

// --- MARS ---
    "01-03": "Si mars commence en courroux, il finira tout doux.",
    "02-03": "À la Saint-Jacob, prépare tes bœufs.",
    "03-03": "S'il tonne en mars, le vigneron est à l'aise.",
    "04-03": "De Saint-Casimir la douceur, fait peur au laboureur.",
    "05-03": "À la Saint-Adrien, le froid nous revient.",
    "06-03": "Au jour de la Sainte-Colette, commence à chanter l'alouette.",
    "07-03": "Le soleil de mars donne des rhumes de cerveau.",
    "08-03": "À la Saint-Jean-de-Dieu, les vaches au pré.",
    "09-03": "S'il pleut à la Saint-Françoise, tout va de travers.",
    "10-03": "S'il gèle à la Saint-Vivien, cinquante jours de gêne reviennent.",
    "11-03": "Bon réveil à Saint-Constant, ramène le beau temps.",
    "12-03": "Saint-Pol de Léon, n'est jamais sans glaçon.",
    "13-03": "À la Sainte-Euphrasie, pointe l'herbe au prairie.",
    "14-03": "À la Sainte-Mathilde, le givre est docile.",
    "15-03": "À la mi-mars, le coucou est rare.",
    "16-03": "Quand mars bien mouillé sera, bien du fruit tu récolteras.",
    "17-03": "À la Saint-Patrice, le froid se glisse.",
    "18-03": "À la Saint-Cyrille, le temps brille.",
    "19-03": "À la Saint-Joseph, beau temps, promesse de bon an.",
    "20-03": "Quand mars fait avril, avril fait mars.",
    "21-03": "S'il pleut à la Saint-Benoît, il pleut quarante jours après.",
    "22-03": "À la Sainte-Léa, le printemps est là.",
    "23-03": "S'il gèle à la Saint-Victorien, on ne récoltera rien.",
    "24-03": "À la Sainte-Catherine, tout bois prend racine.",
    "25-03": "S'il pleut le jour de l'Annonciation, la pluie est sans fin.",
    "26-03": "Le mois de mars doit être sec, froid et piquant.",
    "27-03": "Le beau temps de mars n'est pas bon, s'il ne gèle pas au déclin.",
    "28-03": "À la Saint-Gontran, si la température est douce, l'herbe pousse.",
    "29-03": "Mars venteux, verger pommeux.",
    "30-03": "À la Saint-Amédée, la neige est envolée.",
    "31-03": "À la fin mars, les giboulées sont de la partie.",

// --- AVRIL ---
    "01-04": "Pluie de Saint-Hugues, remplit les luges.",
    "02-04": "À la Sainte-Sandrine, le temps s'illumine.",
    "03-04": "S'il pleut à la Saint-Richard, la terre est au buvard.",
    "04-04": "À la Saint-Isidore, si le soleil dore, le blé sera fort.",
    "05-04": "Fleur d'avril ne tient qu'à un fil.",
    "06-04": "Au jour de la Saint-Prudence, s'il pleut, c'est de l'abondance.",
    "07-04": "Le vent d'avril n'a pas de fils.",
    "08-04": "À la Sainte-Julie, le temps est à la pluie.",
    "09-04": "Quand avril est froid et pluvieux, les moissons n'en vont que mieux.",
    "10-04": "À la Saint-Fulbert, la terre est à découvert.",
    "11-04": "À la Saint-Stanislas, la neige n'est jamais lasse.",
    "12-04": "À la Saint-Jules, les beaux jours sont en recul.",
    "13-04": "À la Sainte-Ida, le temps est souvent là.",
    "14-04": "À la Saint-Maxime, le temps est à l'estime.",
    "15-04": "À la mi-avril, le coucou doit chanter, s'il n'a pas chanté, il est tué ou caché.",
    "16-04": "À la Saint-Benoît, le coucou chante dans les bois.",
    "17-04": "À la Saint-Anicet, le temps est un secret.",
    "18-04": "À la Saint-Parfait, le temps est souvent fait.",
    "19-04": "À la Sainte-Emma, le printemps est bien là.",
    "20-04": "À la Sainte-Odette, on voit souvent l'alouette.",
    "21-04": "À la Saint-Anselme, le temps est souvent ferme.",
    "22-04": "À la Saint-Alexandre, tout bois prend racine.",
    "23-04": "À la Saint-Georges, sème ton orge.",
    "24-04": "À la Saint-Fidèle, si le soleil brille, l'année sera belle.",
    "25-04": "À la Saint-Marc, s'il tombe de l'eau, il n'y aura point de pommes.",
    "26-04": "À la Saint-Alida, le temps est à la joie.",
    "27-04": "À la Sainte-Zita, le printemps est déjà là.",
    "28-04": "À la Saint-Valérie, le soleil brille sur la prairie.",
    "29-04": "À la Saint-Robert, tout devient vert.",
    "30-04": "À la Saint-Eutrope, on voit souvent la pluie au galop.",

// --- MAI ---
    "01-05": "Au premier mai, fleurit le bonuguet.",
    "02-05": "Mai pluvieux marie le laboureur et sa fille.",
    "03-05": "À la Sainte-Croix, cueille tes pois.",
    "04-05": "À la Saint-Sylvain, sème ton sarrasin.",
    "05-05": "À la Saint-Ange, la pluie fait la grange.",
    "06-05": "À la Sainte-Prudence, s'il pleut, c'est de l'abondance.",
    "07-05": "À la Saint-Gisèle, le temps est souvent à la grêle.",
    "08-05": "À la Saint-Désiré, tout va de travers s'il n'a pas plu.",
    "09-05": "Brouillard de mai, chaleur de juillet.",
    "10-05": "À la Saint-Solange, on voit souvent la pluie qui s'arrange.",
    "11-05": "Attention, le premier des Saints de Glace, souvent Saint-Mamert laisse sa trace.",
    "12-05": "Saint-Pancrace apporte souvent la glace.",
    "13-05": "Avant Saint-Servais, point d'été ; après Saint-Servais, plus de gelée.",
    "14-05": "À la Saint-Matthias, la neige n'est jamais lasse.",
    "15-05": "À la Sainte-Denise, le froid n'en fait qu'à sa guise.",
    "16-05": "À la Saint-Honoré, s'il fait beau, le froment est doré.",
    "17-05": "À la Saint-Pascal, s'il fait beau, tout va mal.",
    "18-05": "À la Saint-Éric, le temps est souvent critique.",
    "19-05": "À la Saint-Yves, le beau temps arrive.",
    "20-05": "À la Saint-Bernardin, plus de gelée pour le jardin.",
    "21-05": "À la Saint-Constantin, le soleil est au chemin.",
    "22-05": "À la Sainte-Émile, le temps est fertile.",
    "23-05": "À la Saint-Didier, on voit souvent le cerisier fleurir.",
    "24-05": "À la Saint-Donatien, le temps est souvent bien.",
    "25-05": "À la Sainte-Sophie, le temps est à la folie.",
    "26-05": "À la Saint-Bérenger, tout danger est passé.",
    "27-05": "À la Saint-Augustin, le soleil est au matin.",
    "28-05": "À la Saint-Germain, sème ton grain.",
    "29-05": "À la Saint-Gérard, la pluie n'est jamais rare.",
    "30-05": "À la Saint-Ferdinand, s'il pleut, c'est pour longtemps.",
    "31-05": "S'il pleut à la Sainte-Pétronille, pendant quarante jours elle mouille sa guenille.",

// --- JUIN ---
    "01-06": "Pluie de Saint-Justin, vaut un trait de bon vin.",
    "02-06": "Beau temps à la Saint-Marcelin, promet du pain et du vin.",
    "03-06": "S'il pleut à la Sainte-Clotilde, de quoi remplir le silo de mille.",
    "04-06": "À la Sainte-Ruth, on voit souvent la pluie qui culbute.",
    "05-06": "À la Saint-Boniface, toute chaleur a sa place.",
    "06-06": "À la Saint-Norbert, on voit si le blé est vert.",
    "07-06": "À la Saint-Gilbert, s'il fait beau, tout est découvert.",
    "08-06": "S'il pleut à la Saint-Médard, il pleut quarante jours plus tard.",
    "09-06": "À la Saint-Félicien, mouche à miel ne vaut rien.",
    "10-06": "À la Saint-Landry, le temps est souvent fleuri.",
    "11-06": "À la Saint-Barnabé, fauche ton pré.",
    "12-06": "À la Saint-Guy, s'il fait beau, le paysan rit.",
    "13-06": "À la Saint-Antoine de Padoue, s'il pleut, le raisin est dans la boue.",
    "14-06": "À la Saint-Élisée, on voit souvent la pluie au fossé.",
    "15-06": "À la Saint-Guy, on voit souvent la pluie qui s'enfuit.",
    "16-06": "À la Saint-Cyr, on voit le soleil qui fait plaisir.",
    "17-06": "À la Saint-Hervé, le soleil est levé.",
    "18-06": "À la Saint-Léonce, si la pluie est là, le blé renonce.",
    "19-06": "À la Saint-Gervais, le temps n'est jamais mauvais.",
    "20-06": "Pluie de Saint-Silvère, c'est du vin pour le verre.",
    "21-06": "Été bien venu, foin bien tendu.",
    "22-06": "À la Saint-Alban, on voit souvent le temps blanc.",
    "23-06": "À la Sainte-Audrey, le foin est au pré.",
    "24-06": "Pluie de Saint-Jean, emporte la noisette et le gland.",
    "25-06": "À la Saint-Prosper, le temps est souvent vert.",
    "26-06": "À la Saint-Anthelme, le temps est souvent calme.",
    "27-06": "Temps de la Saint-Fernand, dure longtemps.",
    "28-06": "À la Saint-Irénée, on voit souvent la pluie à la journée.",
    "29-06": "Saint-Pierre et Saint-Paul, amènent la pluie dans leur col.",
    "30-06": "À la Saint-Martial, le temps est souvent royal.",

// --- JUILLET ---
    "01-07": "À la Saint-Thierry, aux champs point de répit.",
    "02-07": "S'il pleut à la Visitation, la pluie est à discrétion.",
    "03-07": "À la Saint-Anatole, l'orage souvent s'envole.",
    "04-07": "Pour la Sainte-Berthe, se moissonne à perte.",
    "05-07": "À la Saint-Antoine, le blé change de soutane.",
    "06-07": "À la Sainte-Mariette, on voit souvent la pluie à la fête.",
    "07-07": "Quand il pleut à la Saint-Raoul, le soleil n'est pas soûl.",
    "08-07": "À la Saint-Thibaut, sème tes navets s'il fait beau.",
    "09-07": "S'il pleut à la Sainte-Amandine, on verra du grain dans la farine.",
    "10-07": "À la Sainte-Félicité, c'est le milieu de l'été.",
    "11-07": "À la Saint-Benoît, le coucou se tait ou doit.",
    "12-07": "À la Saint-Olivier, fais provision de ton blé.",
    "13-07": "À la Saint-Henri, le blé est mûri.",
    "14-07": "À la Saint-Camille, on voit souvent l'éclair qui brille.",
    "15-07": "À la Saint-Donald, le temps est souvent pâle.",
    "16-07": "À la Notre-Dame du Mont-Carmel, de la pluie on n'en voit point au ciel.",
    "17-07": "À la Sainte-Charlotte, la chaleur est de la sorte.",
    "18-07": "À la Saint-Frédéric, la chaleur est classique.",
    "19-07": "À la Saint-Arsène, on moissonne dans la plaine.",
    "20-07": "À la Sainte-Marguerite, la pluie est vite maudite.",
    "21-07": "À la Saint-Victor, la pluie est un trésor.",
    "22-07": "S'il pleut à la Sainte-Madeleine, il pleut durant six semaines.",
    "23-07": "À la Sainte-Brigitte, on voit souvent la pluie qui s'excite.",
    "24-07": "À la Sainte-Christine, les blés sont de bonne mine.",
    "25-07": "Si Saint-Jacques est serein, l'hiver sera dur et plein.",
    "26-07": "À la Sainte-Anne, on voit souvent le temps qui se condamne.",
    "27-07": "À la Saint-Nathalie, on voit la fin des pluies.",
    "28-07": "À la Saint-Samson, le temps est souvent bon.",
    "29-07": "À la Sainte-Marthe, s'il pleut, le raisin s'écarte.",
    "30-07": "À la Sainte-Juliette, la chaleur nous guette.",
    "31-07": "À la Saint-Ignace, la pluie nous menace.",

// --- AOÛT ---
    "01-08": "Le temps d'août, c’est le trésor de tout.",
    "02-08": "À la Saint-Eusèbe, le soleil se lève et la chaleur s'achève.",
    "03-08": "S'il pleut à la Sainte-Lydie, l'été est bientôt fini.",
    "04-08": "À la Saint-Jean-Marie, le soleil nous sourit.",
    "05-08": "À la Saint-Abel, le temps est souvent très bel.",
    "06-08": "À la Saint-Transfiguration, l'été est à sa perfection.",
    "07-08": "À la Saint-Gaétan, on voit souvent le beau temps.",
    "08-08": "À la Saint-Dominique, la chaleur est de plus en plus unique.",
    "09-08": "À la Saint-Amour, le soleil fait son tour.",
    "10-08": "À la Saint-Laurent, le soleil est souvent très brûlant.",
    "11-08": "À la Sainte-Claire, s'il fait beau, le soleil est clair.",
    "12-08": "À la Sainte-Clarisse, le temps est souvent lisse.",
    "13-08": "À la Saint-Hippolyte, le soleil nous quitte vite.",
    "14-08": "À la Saint-Évrard, la pluie n'est jamais tard.",
    "15-08": "À la Sainte-Marie, on voit souvent la pluie qui s'en va de la prairie.",
    "16-08": "À la Saint-Roch, le temps est souvent au choc.",
    "17-08": "À la Saint-Hyacinthe, on voit souvent la pluie qui est peinte.",
    "18-08": "À la Sainte-Hélène, la chaleur est souvent pleine.",
    "19-08": "À la Saint-Jean-Eudes, on voit souvent la pluie qui s'élude.",
    "20-08": "À la Saint-Bernard, le soleil n'est jamais trop tard.",
    "21-08": "À la Saint-Christophe, l'été change d'étoffe.",
    "22-08": "Pluie de la Saint-Fabrice, rend le paysan complice.",
    "23-08": "À la Sainte-Rose, pour le jardin, point de pause.",
    "24-08": "Beau temps à la Saint-Barthélemy, promet un automne joli.",
    "25-08": "À la Saint-Louis, le soleil réjouit l'esprit.",
    "26-08": "À la Saint-Césaire, la chaleur est de bon air.",
    "27-08": "À la Sainte-Monique, le temps est souvent pacifique.",
    "28-08": "À la Saint-Augustin, le soleil est au matin.",
    "29-08": "À la Saint-Jean-Baptiste, le temps est souvent triste.",
    "30-08": "À la Saint-Fiacre, le jardinier n'est pas un diacre.",
    "31-08": "À la Saint-Aristide, le temps est souvent humide.",

// --- SEPTEMBRE ---
    "01-09": "À la Saint-Gilles, les noisettes sont pour les filles.",
    "02-09": "À la Saint-Lazare, le temps est souvent bizarre.",
    "03-09": "À la Saint-Grégoire, s'il fait beau, il faut le boire.",
    "04-09": "À la Sainte-Rosalie, souvent la pluie nous lie.",
    "05-09": "À la Saint-Bertin, le soleil est au chemin.",
    "06-09": "À la Saint-Bertrand, on voit si le blé est grand.",
    "07-09": "À la Sainte-Reine, la pluie est souvent pleine.",
    "08-09": "À la Bonne-Dame (Nativité), le beau temps est de côté.",
    "09-09": "À la Saint-Alain, tout le monde au pain.",
    "10-09": "À la Sainte-Inès, le temps est souvent en liesse.",
    "11-09": "À la Saint-Hyacinthe, on voit souvent la pluie peinte.",
    "12-09": "À la Saint-Apollinaire, l'automne est à l'aire.",
    "13-09": "À la Saint-Aimé, le point du jour est aimé.",
    "14-09": "À la Sainte-Croix, cueille tes pommes par trois.",
    "15-09": "À la Saint-Roland, le temps est souvent blanc.",
    "16-09": "À la Saint-Édith, la pluie est souvent dite.",
    "17-09": "À la Saint-Renaud, il fait souvent très beau.",
    "18-09": "À la Saint-Nadège, on voit souvent la neige (en montagne).",
    "19-09": "À la Saint-Émilie, le temps est à la folie.",
    "20-09": "À la Saint-Eustache, le temps se cache.",
    "21-09": "À la Saint-Matthieu, l'été nous dit adieu.",
    "22-09": "À la Saint-Maurice, si le soleil luit, l'hiver sera sans malice.",
    "23-09": "À la Saint-Constant, le soleil est au tournant.",
    "24-09": "À la Saint-Thècle, on voit souvent le temps de siècle.",
    "25-09": "À la Saint-Hermann, le temps est souvent de canne.",
    "26-09": "À la Saint-Côme, le temps est de baume.",
    "27-09": "À la Saint-Vincent-de-Paul, la pluie n'est pas drôle.",
    "28-09": "À la Saint-Wenceslas, le temps est souvent las.",
    "29-09": "À la Saint-Michel, la chaleur remonte au ciel.",
    "30-09": "À la Saint-Jérôme, mords dans ta pomme.",

// --- OCTOBRE ---
    "01-10": "À la Saint-Rémy, perds tes feuilles, ramasse tes fruits.",
    "02-10": "À la Saint-Léger, fais chauffer ton foyer.",
    "03-10": "À la Saint-Gérard, les noix sont à l'écart.",
    "04-10": "À la Saint-François, on voit souvent le premier froid.",
    "05-10": "À la Sainte-Fleur, tout est en couleur.",
    "06-10": "À la Saint-Bruno, le temps est souvent beau.",
    "07-10": "À la Saint-Serge, la pluie souvent submerge.",
    "08-10": "À la Sainte-Pélagie, le soleil fait de la magie.",
    "09-10": "À la Saint-Denis, le temps de l'automne est fini.",
    "10-10": "À la Saint-Ghislain, on sème son grain.",
    "11-10": "À la Saint-Firmin, le froid est au chemin.",
    "12-10": "À la Saint-Wilfrid, le temps est souvent ride.",
    "13-10": "À la Saint-Géraud, s'il fait beau, l'hiver sera chaud.",
    "14-10": "À la Saint-Juste, on voit souvent le temps robuste.",
    "15-10": "À la Sainte-Thérèse, l'automne se met à son aise.",
    "16-10": "À la Saint-Edwige, le froid souvent s'érige.",
    "17-10": "À la Saint-Baudouin, on voit souvent le temps de loin.",
    "18-10": "À la Saint-Luc, la pluie est au bec.",
    "19-10": "À la Saint-René, l'été est bien terminé.",
    "20-10": "À la Sainte-Adeline, la neige nous chagrine.",
    "21-10": "À la Sainte-Céline, le temps s'illumine.",
    "22-10": "À la Saint-Vallier, le bois est au foyer.",
    "23-10": "À la Saint-Jean-de-Capistran, le temps est souvent blanc.",
    "24-10": "À la Saint-Florentin, le soleil est au matin.",
    "25-10": "À la Saint-Crépin, les feuilles sont au chemin.",
    "26-10": "À la Saint-Dimitri, le froid est au logis.",
    "27-10": "À la Sainte-Émeline, la pluie nous domine.",
    "28-10": "À la Saint-Simon, si la pluie est là, l'hiver sera bon.",
    "29-10": "À la Saint-Narcisse, le temps est souvent lisse.",
    "30-10": "À la Saint-Bienvenu, le soleil est revenu.",
    "31-10": "À la Saint-Quentin, le froid est au jardin.",

// --- NOVEMBRE ---
    "01-11": "À la Toussaint, commence l'été de Saint-Martin ou l'hiver plein de chagrin.",
    "02-11": "Le jour des Morts mouillé, annonce un printemps ensoleillé.",
    "03-11": "À la Saint-Hubert, les oies sauvages sont au désert.",
    "04-11": "À la Saint-Charles, la gelée parle.",
    "05-11": "À la Saint-Zacharie, la pluie est souvent de la partie.",
    "06-11": "À la Saint-Léon, le temps est souvent au mouton.",
    "07-11": "À la Saint-Ernest, s'il pleut, le paysan n'est pas en reste.",
    "08-11": "À la Saint-Geoffroy, les oisons ont bien froid.",
    "09-11": "À la Saint-Théodore, le froid se fait fort.",
    "10-11": "À la Saint-Léon, sème ton blé, tu auras du bon.",
    "11-11": "À la Saint-Martin, l'hiver est au chemin.",
    "12-11": "À la Saint-Christian, on voit souvent le temps blanc.",
    "13-11": "À la Saint-Brice, le temps est souvent complice.",
    "14-11": "À la Saint-Sidoine, le froid nous éloigne.",
    "15-11": "À la Saint-Albert, tout reste découvert.",
    "16-11": "À la Sainte-Marguerite, la pluie est vite maudite.",
    "17-11": "À la Sainte-Élisabeth, tout ce qui porte des feuilles fait la fête.",
    "18-11": "À la Saint-Aude, la gelée est souvent chaude.",
    "19-11": "À la Saint-Tanguy, le temps est souvent gris.",
    "20-11": "À la Saint-Edmond, le temps est au mont.",
    "21-11": "À la Présentation, on voit souvent la pluie à foison.",
    "22-11": "À la Sainte-Cécile, si on plante des pois, ils ne viennent pas facilement.",
    "23-11": "À la Saint-Clément, le temps est souvent dément.",
    "24-11": "À la Sainte-Flora, la neige est souvent là.",
    "25-11": "À la Sainte-Catherine, tout bois prend racine.",
    "26-11": "À la Sainte-Delphine, la pluie nous domine.",
    "27-11": "À la Saint-Séverin, le soleil est au chemin.",
    "28-11": "À la Saint-Jacques, on voit souvent la pluie qui s'attaque.",
    "29-11": "À la Saint-Saturnin, la pluie est au jardin.",
    "30-11": "À la Saint-André, la neige est au fossé.",

// --- DÉCEMBRE ---
    "01-12": "À la Saint-Éloi, l'hiver est roi.",
    "02-12": "À la Sainte-Viviane, le temps est souvent de canne.",
    "03-12": "À la Saint-François-Xavier, l'hiver est au foyer.",
    "04-12": "À la Sainte-Barbe, soleil de décembre, fait fleurir la plante.",
    "05-12": "À la Saint-Gérald, le froid est au chemin.",
    "06-12": "À la Saint-Nicolas, la neige est souvent là.",
    "07-12": "À la Saint-Ambroise, le froid souvent nous toise.",
    "08-12": "À la Sainte-Immaculée, l'hiver est souvent installé.",
    "09-12": "À la Saint-Pierre-Fourier, on voit souvent le temps de janvier.",
    "10-12": "À la Saint-Romaric, le froid est souvent classique.",
    "11-12": "À la Saint-Daniel, le temps est souvent cruel.",
    "12-12": "À la Saint-Corentin, le soleil est au matin.",
    "13-12": "À la Sainte-Luce, le jour croît d'un saut de puce.",
    "14-12": "À la Saint-Odile, la neige est facile.",
    "15-12": "À la Sainte-Ninon, le temps est souvent au coton.",
    "16-12": "À la Sainte-Alice, le temps est souvent lisse.",
    "17-12": "À la Saint-Gaël, on voit souvent le ciel.",
    "18-12": "À la Saint-Gatien, le froid ne vaut rien.",
    "19-12": "À la Saint-Urbain, le soleil est au chemin.",
    "20-12": "À la Saint-Théophile, le temps est souvent fertile.",
    "21-12": "À la Saint-Thomas, les jours sont au plus bas.",
    "22-12": "En décembre, quand le jour croît, aussi fait le froid.",
    "23-12": "À la Sainte-Victoire, si le soleil luit, l'année sera de gloire.",
    "24-12": "Beau temps à Noël, beau temps à la moisson.",
    "25-12": "Noël au balcon, Pâques au tison.",
    "26-12": "À la Saint-Étienne, le temps est souvent à la peine.",
    "27-12": "À la Saint-Jean, le temps est souvent changeant.",
    "28-12": "À la Saint-Innocents, on voit souvent les vents.",
    "29-12": "À la Saint-David, le temps est souvent humide.",
    "30-12": "À la Saint-Roger, le temps est souvent léger.",
    "31-12": "Saint-Sylvestre ne vient qu'une fois l'an, c'est bien assez pour les gens.",

    // --- DEFAUT SI DATE MANQUANTE ---
    "default": "Ne remets pas au lendemain ce que tu peux faire aujourd'hui."
  };

  return dictons[cle] || dictons["default"];
};