// src/app/api/gers/route.ts
import { NextResponse } from 'next/server';

interface SiteGers {
  id: number;
  commune: string;
  description: string;
  niveau: number;
  categorie: 'incontournable' | 'remarquable' | 'suggéré';
  lat: number;
  lng: number;
}

const gersSites: SiteGers[] = [
  { id: 1, commune: "Auch", description: "Cathédrale Sainte-Marie, Escalier Monumental", niveau: 1, categorie: "incontournable", lat: 43.6465, lng: 0.5855 },
  { id: 2, commune: "L'Isle-Jourdain", description: "Château de Panat", niveau: 2, categorie: "remarquable", lat: 43.6133, lng: 1.0851 },
  { id: 3, commune: "Condom", description: "Cathédrale Saint-Pierre et Cloître", niveau: 1, categorie: "incontournable", lat: 43.9578, lng: 0.3731 },
  { id: 4, commune: "Fleurance", description: "Église Saint-Laurent et Halle", niveau: 1, categorie: "incontournable", lat: 43.8497, lng: 0.6631 },
  { id: 5, commune: "Eauze", description: "Domus de Cieutat, Cathédrale Saint-Luperc", niveau: 1, categorie: "incontournable", lat: 43.8611, lng: 0.1023 },
  { id: 6, commune: "Lectoure", description: "Cathédrale Saint-Gervais, Remparts", niveau: 1, categorie: "incontournable", lat: 43.9344, lng: 0.6247 },
  { id: 7, commune: "Vic-Fezensac", description: "Église Saint-Pierre", niveau: 2, categorie: "remarquable", lat: 43.7592, lng: 0.3031 },
  { id: 8, commune: "Mirande", description: "Église Sainte-Marie (Église-bastide)", niveau: 1, categorie: "incontournable", lat: 43.5153, lng: 0.4039 },
  { id: 9, commune: "Gimont", description: "Abbaye de Planselve, Halle", niveau: 1, categorie: "incontournable", lat: 43.6264, lng: 0.8756 },
  { id: 10, commune: "Pavie", description: "Vieux Pont sur le Gers", niveau: 1, categorie: "incontournable", lat: 43.6103, lng: 0.5908 },
  { id: 11, commune: "Samatan", description: "Halle au gras, Fontaine centrale", niveau: 2, categorie: "remarquable", lat: 43.4925, lng: 0.9300 },
  { id: 12, commune: "Mauvezin", description: "Halle médiévale, Place à arcades", niveau: 1, categorie: "incontournable", lat: 43.7314, lng: 0.8269 },
  { id: 13, commune: "Nogaro", description: "Église Saint-Nicolas (Fresques), circuit automobile", niveau: 2, categorie: "remarquable", lat: 43.7589, lng: -0.0336 },
  { id: 14, commune: "Lombez", description: "Cathédrale Sainte-Marie", niveau: 1, categorie: "incontournable", lat: 43.4744, lng: 0.9103 },
  { id: 15, commune: "Montesquiou", description: "Porte de l'Horloge", niveau: 2, categorie: "remarquable", lat: 43.5786, lng: 0.3292 },
  { id: 16, commune: "Montaut-les-Créneaux", description: "Porte de ville, Église Saint-Michel", niveau: 1, categorie: "incontournable", lat: 43.6936, lng: 0.6533 },
  { id: 17, commune: "Cologne", description: "Halle centrale du XIVe siècle", niveau: 1, categorie: "incontournable", lat: 43.7219, lng: 0.9772 },
  { id: 18, commune: "Cazaubon", description: "Quartier thermal de Barbotan, Église", niveau: 1, categorie: "incontournable", lat: 43.9347, lng: -0.0711 },
  { id: 19, commune: "Seissan", description: "Marché couvert, Enceinte fortifiée", niveau: 1, categorie: "incontournable", lat: 43.4917, lng: 0.5933 },
  { id: 20, commune: "Marciac", description: "Clocher de l'église, Place du Jazz", niveau: 1, categorie: "incontournable", lat: 43.5244, lng: 0.1611 },
  { id: 21, commune: "Saint-Clar", description: "Vieille Église, Place à cornières", niveau: 1, categorie: "incontournable", lat: 43.8922, lng: 0.7700 },
  { id: 22, commune: "Berdoues", description: "Abbaye de Berdoues", niveau: 1, categorie: "incontournable", lat: 43.4808, lng: 0.4089 },
  { id: 23, commune: "Beaumarchés", description: "Abbaye de la Case-Dieu", niveau: 1, categorie: "incontournable", lat: 43.5855, lng: 0.0900 },
  { id: 24, commune: "Boulaur", description: "Abbaye de Boulaur", niveau: 1, categorie: "incontournable", lat: 43.5411, lng: 0.7753 },
  { id: 25, commune: "Valence-sur-Baïse", description: "Abbaye de Flaran", niveau: 1, categorie: "incontournable", lat: 43.8902, lng: 0.3733 },
  { id: 26, commune: "Saint-Antoine", description: "Abbaye Saint-Antoine", niveau: 1, categorie: "incontournable", lat: 44.0361, lng: 0.8408 },
  { id: 27, commune: "Sainte-Christie-d'Armagnac", description: "Le Castet : Rempart en Terre Crue et Motte Féodale", niveau: 1, categorie: "incontournable", lat: 43.7842, lng: -0.0089 },
  { id: 28, commune: "Cassaigne", description: "Château de Cassaigne", niveau: 1, categorie: "incontournable", lat: 43.9083, lng: 0.3361 },
  { id: 29, commune: "Beaumont", description: "Chateau de Beaumont", niveau: 1, categorie: "incontournable", lat: 43.9464, lng: 0.2847 },
  { id: 30, commune: "La Sauvetat", description: "Château de Serillac", niveau: 1, categorie: "incontournable", lat: 43.8522, lng: 0.5264 },
  { id: 31, commune: "Flamarens", description: "Château de Flamarens", niveau: 1, categorie: "incontournable", lat: 44.0167, lng: 0.7917 },
  { id: 32, commune: "Sainte-Mère", description: "Village & Chateau de Sainte-mere", niveau: 1, categorie: "incontournable", lat: 44.0042, lng: 0.6678 },
  { id: 33, commune: "Plieux", description: "Château de Plieux", niveau: 1, categorie: "incontournable", lat: 43.9572, lng: 0.7333 },
  { id: 34, commune: "Lavardens", description: "Château de Lavardens", niveau: 1, categorie: "incontournable", lat: 43.7611, lng: 0.5119 },
  { id: 35, commune: "Cazaux-Savès", description: "Château de Caumont", niveau: 1, categorie: "incontournable", lat: 43.5414, lng: 0.9839 },
  { id: 36, commune: "Saint-Blancard", description: "Ville de Cap d'Astarac", niveau: 1, categorie: "incontournable", lat: 43.3444, lng: 0.6472 },
  { id: 37, commune: "L'Isle-de-Noé", description: "Château de l'Isle de Noé", niveau: 1, categorie: "incontournable", lat: 43.5833, lng: 0.4167 },
  { id: 38, commune: "Pujaudran", description: "Château de Lartus", niveau: 1, categorie: "incontournable", lat: 43.5908, lng: 1.1494 },
  { id: 39, commune: "Caussens", description: "MÉMOIRE DE LA RÉSISTANCE - PR 13 - Caussens/Castelnau-sur-l'Auvignon", niveau: 3, categorie: "suggéré", lat: 43.9442, lng: 0.4244 },
  { id: 40, commune: "Brugnens", description: "Musée des Anciens Combattants Pour la Liberté", niveau: 3, categorie: "suggéré", lat: 43.8411, lng: 0.6969 },
  { id: 41, commune: "Villefranche-d'Astarac", description: "Maquis de Meilhan", niveau: 3, categorie: "suggéré", lat: 43.4239, lng: 0.7268 },
  { id: 42, commune: "Castelnau-sur-l'Auvignon", description: "Chemin de Mémoire et de la Résistance de Castelnau-sur-l'Auvignon", niveau: 2, categorie: "remarquable", lat: 44.0154, lng: 0.6492 },
  { id: 43, commune: "Castelnau d'Auzan Labarrère", description: "Arènes de Castelnau d'Auzan", niveau: 3, categorie: "suggéré", lat: 43.9489, lng: 0.0840 },
  { id: 44, commune: "Panjas", description: "Arènes de Panjas", niveau: 2, categorie: "remarquable", lat: 43.8204, lng: -0.0916 },
  { id: 45, commune: "Estang", description: "Arènes d'Estang (Arènes Jean Bartherotte)", niveau: 3, categorie: "suggéré", lat: 43.8673, lng: -0.1065 },
  { id: 46, commune: "Manciet", description: "Arènes de Manciet", niveau: 2, categorie: "remarquable", lat: 43.8001, lng: 0.0408 },
  { id: 47, commune: "Le Houga", description: "Arènes Le Houga", niveau: 2, categorie: "remarquable", lat: 43.7747, lng: -0.1801 },
  // --- PARCS ET JARDINS ---
  { id: 48, commune: "Ayzieu", description: "Lassis Jardin Arboretum", niveau: 3, categorie: "suggéré", lat: 43.8500, lng: -0.0167 },
  { id: 49, commune: "Bétous", description: "Palmeraie du Sarthou", niveau: 3, categorie: "suggéré", lat: 43.7167, lng: 0.0333 },
  { id: 50, commune: "La Romieu", description: "Les Jardins de Coursiana", niveau: 1, categorie: "incontournable", lat: 43.9822, lng: 0.4950 },
  { id: 51, commune: "Jegun", description: "Jardin de Vassevin", niveau: 3, categorie: "suggéré", lat: 43.7500, lng: 0.4500 },
  { id: 52, commune: "Saint-Élix-d'Astarac", description: "Kazé, Land art", niveau: 3, categorie: "suggéré", lat: 43.4333, lng: 0.7667 },
  { id: 53, commune: "Simorre", description: "Potager du Bouche à Oreille", niveau: 2, categorie: "remarquable", lat: 43.4500, lng: 0.7333 },
  { id: 54, commune: "Aubiet", description: "La Nourrice, Land art", niveau: 3, categorie: "suggéré", lat: 43.6456, lng: 0.7836 },
  { id: 55, commune: "Villefranche-d'Astarac", description: "Yané, Land art", niveau: 3, categorie: "suggéré", lat: 43.4239, lng: 0.7268 },
  { id: 56, commune: "Lasseube-Propre", description: "Le Jardin d'Entêoulet", niveau: 2, categorie: "remarquable", lat: 43.5833, lng: 0.6167 },
  { id: 57, commune: "Avezan", description: "Jardin Planeso", niveau: 2, categorie: "remarquable", lat: 43.8756, lng: 0.7969 },
  { id: 58, commune: "Sarrant", description: "Village de l'Illustration, Jardin Secret et Grande Galerie", niveau: 2, categorie: "remarquable", lat: 43.7750, lng: 0.9231 },
  { id: 59, commune: "Saint-Georges", description: "Les Jardins de la Marquise", niveau: 1, categorie: "incontournable", lat: 43.7275, lng: 0.9325 },
  { id: 60, commune: "Homps", description: "Jardin de Jeanne", niveau: 2, categorie: "remarquable", lat: 43.8167, lng: 0.8500 },
  { id: 61, commune: "Castéra-Verduzan", description: "Parc Lannelongue", niveau: 2, categorie: "remarquable", lat: 43.8050, lng: 0.4200 },
  { id: 62, commune: "Saint-Ost", description: "Jardin de la Matelle", niveau: 3, categorie: "suggéré", lat: 43.3750, lng: 0.4667 },
  // --- VILLAGES ---
  { id: 63, commune: "Lussan", description: "Village de Lussan", niveau: 3, categorie: "suggéré", lat: 43.6167, lng: 0.7333 },
  { id: 64, commune: "Aubiet", description: "Village d'Aubiet", niveau: 3, categorie: "suggéré", lat: 43.6456, lng: 0.7836 },
  { id: 65, commune: "Monfort", description: "Découverte de la Bastide de Monfort en Audio", niveau: 1, categorie: "incontournable", lat: 43.7944, lng: 0.8242 },
  { id: 66, commune: "Sarrant", description: "Village de Sarrant", niveau: 2, categorie: "remarquable", lat: 43.7750, lng: 0.9231 },
  { id: 67, commune: "Panjas", description: "Village de Panjas", niveau: 3, categorie: "suggéré", lat: 43.8204, lng: -0.0916 },
  { id: 68, commune: "Gondrin", description: "Village de Gondrin", niveau: 2, categorie: "remarquable", lat: 43.8833, lng: 0.2333 },
  { id: 69, commune: "Bazian", description: "Village de Bazian", niveau: 1, categorie: "incontournable", lat: 43.6667, lng: 0.3167 },
  { id: 70, commune: "Roquebrune", description: "Village de Roquebrune", niveau: 3, categorie: "suggéré", lat: 43.6667, lng: 0.3000 },
  { id: 71, commune: "Saint-Arailles", description: "Village de Saint-Arailles", niveau: 1, categorie: "incontournable", lat: 43.6167, lng: 0.3500 },
  { id: 72, commune: "Roques", description: "Village de Roques", niveau: 3, categorie: "suggéré", lat: 43.8500, lng: 0.3000 },
  { id: 73, commune: "Cazaux-d'Anglès", description: "Village de Cazaux d'Angles", niveau: 2, categorie: "remarquable", lat: 43.6500, lng: 0.2500 },
  { id: 74, commune: "Lupiac", description: "Village de Lupiac", niveau: 1, categorie: "incontournable", lat: 43.6833, lng: 0.1833 },
  { id: 75, commune: "Riguepeu", description: "Village de Riguepeu", niveau: 3, categorie: "suggéré", lat: 43.6500, lng: 0.3333 },
  { id: 76, commune: "Préneron", description: "Village de Preneron", niveau: 3, categorie: "suggéré", lat: 43.7333, lng: 0.2833 },
  { id: 77, commune: "Rozès", description: "Village de Rozes", niveau: 3, categorie: "suggéré", lat: 43.8167, lng: 0.3667 },
  { id: 78, commune: "Saint-Paul-de-Baïse", description: "Village de Saint-paul-de-baïse", niveau: 3, categorie: "suggéré", lat: 43.7833, lng: 0.3667 },
  { id: 79, commune: "Peyrusse-Grande", description: "Village de Peyrusse-grande", niveau: 3, categorie: "suggéré", lat: 43.6333, lng: 0.2167 },
  { id: 80, commune: "Marambat", description: "Village de Marambat", niveau: 3, categorie: "suggéré", lat: 43.7667, lng: 0.3167 },
  { id: 81, commune: "Justian", description: "Village de Justian", niveau: 3, categorie: "suggéré", lat: 43.7667, lng: 0.4000 },
  // --- SECTEUR OUEST (Armagnac & Adour) ---
  { id: 82, commune: "Arblade-le-Haut", description: "Église romane Saint-Lucien et motte castrale", niveau: 3, categorie: "suggéré", lat: 43.7431, lng: -0.0697 },
  { id: 83, commune: "Lanne-Soubiran", description: "Église Saint-Christophe et paysages de vignobles", niveau: 3, categorie: "suggéré", lat: 43.7461, lng: -0.1017 },
  { id: 84, commune: "Bretagne-d'Armagnac", description: "Église Saint-Jean-Baptiste et Chapelle de Pimbat", niveau: 3, categorie: "suggéré", lat: 43.8878, lng: 0.1383 },
  { id: 85, commune: "Lannemaignan", description: "Église fortifiée Saint-Jean-Baptiste (XIIe)", niveau: 3, categorie: "suggéré", lat: 43.9006, lng: -0.1989 },
  { id: 86, commune: "Courrensan", description: "Château de Courrensan (Forteresse médiévale)", niveau: 1, categorie: "incontournable", lat: 43.8492, lng: 0.2431 },
  { id: 87, commune: "Lannepax", description: "Bastide, place à arcades et église Saint-Jacques", niveau: 1, categorie: "incontournable", lat: 43.8011, lng: 0.2272 },
  { id: 88, commune: "Dému", description: "Tour-porte médiévale fortifiée", niveau: 2, categorie: "remarquable", lat: 43.7658, lng: 0.1658 },
  { id: 89, commune: "Campagne-d'Armagnac", description: "Église Saint-André et fontaines anciennes", niveau: 3, categorie: "suggéré", lat: 43.8647, lng: -0.0014 },
  { id: 90, commune: "Castex-d'Armagnac", description: "Château de Castex et église Saint-Canne", niveau: 2, categorie: "remarquable", lat: 43.8711, lng: -0.1583 },
  { id: 91, commune: "Maupas", description: "Château de Maupas et église à clocher-mur", niveau: 2, categorie: "remarquable", lat: 43.8544, lng: -0.1469 },
  { id: 92, commune: "Mauléon-d'Armagnac", description: "Église Sainte-Madeleine et ancien prieuré", niveau: 2, categorie: "remarquable", lat: 43.9103, lng: -0.1544 },
  { id: 93, commune: "Lias-d'Armagnac", description: "Église romane Saint-Justin", niveau: 3, categorie: "suggéré", lat: 43.8631, lng: -0.0736 },
  { id: 94, commune: "Larée", description: "Église Saint-Sernin et étangs", niveau: 3, categorie: "suggéré", lat: 43.9108, lng: 0.0483 },
  { id: 95, commune: "Monlezun-d'Armagnac", description: "Panorama Pyrénées et église Saint-Orens", niveau: 3, categorie: "suggéré", lat: 43.8267, lng: -0.1439 },
  // --- SECTEUR EST (Savès & Portes de la Gascogne) ---
  { id: 96, commune: "Endoufielle", description: "Église Saint-Barthélemy et château de l'Isle", niveau: 2, categorie: "remarquable", lat: 43.5517, lng: 1.0231 },
  { id: 97, commune: "Auradé", description: "Église Saint-Benoît et maisons traditionnelles", niveau: 3, categorie: "suggéré", lat: 43.5414, lng: 1.0475 },
  { id: 98, commune: "Castillon-Savès", description: "Château de Castillon (XVIIIe) et son parc", niveau: 1, categorie: "incontournable", lat: 43.5700, lng: 0.9833 },
  { id: 99, commune: "Lias", description: "Église Saint-Martin et hameau de Goudourvielle", niveau: 3, categorie: "suggéré", lat: 43.5658, lng: 1.1272 },
  { id: 100, commune: "Ségoufielle", description: "Église Saint-Pierre et rives de la Save", niveau: 3, categorie: "suggéré", lat: 43.6308, lng: 1.1306 },
  { id: 101, commune: "Frégouville", description: "Église de l'Assomption et point de vue", niveau: 3, categorie: "suggéré", lat: 43.5886, lng: 0.9328 },
  { id: 102, commune: "Clermont-Savès", description: "Église Saint-Étienne et Château de Clermont", niveau: 2, categorie: "remarquable", lat: 43.6192, lng: 1.0294 },
  { id: 103, commune: "Razengues", description: "Église Saint-Christophe et belvédère", niveau: 2, categorie: "remarquable", lat: 43.6417, lng: 0.9986 },
  { id: 104, commune: "Beaupuy", description: "Église Saint-Pierre et vestiges du fort", niveau: 3, categorie: "suggéré", lat: 43.6453, lng: 1.0047 },
  { id: 105, commune: "L'Isle-Arné", description: "Château privé et église Saint-Brice", niveau: 3, categorie: "suggéré", lat: 43.6150, lng: 0.7719 },
  { id: 106, commune: "Saramon", description: "Ancienne abbaye Saint-Victor et tour-clocher", niveau: 2, categorie: "remarquable", lat: 43.5222, lng: 0.7653 },
  { id: 107, commune: "Tournan", description: "Église Saint-Blaise et architecture rurale", niveau: 3, categorie: "suggéré", lat: 43.4331, lng: 0.7958 },
  { id: 108, commune: "Marestaing", description: "Église Saint-Jean-Baptiste (Commanderie)", niveau: 3, categorie: "suggéré", lat: 43.5794, lng: 1.0186 },
  { id: 109, commune: "Garravet", description: "Église de campagne et anciens moulins", niveau: 1, categorie: "incontournable", lat: 43.4147, lng: 0.9147 },
  { id: 110, commune: "Savignac-Mona", description: "Architecture rurale et moulin", niveau: 1, categorie: "incontournable", lat: 43.4883, lng: 1.0069 },
  { id: 111, commune: "Nizas", description: "Patrimoine rural et église de village", niveau: 1, categorie: "incontournable", lat: 43.5119, lng: 1.0017 },
  { id: 112, commune: "Montégut-Savès", description: "Église Saint-Sébastien et château", niveau: 3, categorie: "suggéré", lat: 43.4411, lng: 0.9583 },
  { id: 113, commune: "Montpezat", description: "Église de l'Assomption et murs d'enceinte", niveau: 2, categorie: "remarquable", lat: 43.3869, lng: 0.9744 },
  { id: 114, commune: "Labastide-Savès", description: "Bastide et église Saint-Jacques", niveau: 3, categorie: "suggéré", lat: 43.4689, lng: 0.9858 },
  // --- SECTEUR NORD (Lomagne & Ténarèze) ---
  { id: 115, commune: "Fourcés", description: "Bastide ronde unique, Place ombragée de platanes", niveau: 1, categorie: "incontournable", lat: 43.9928, lng: 0.2311 },
  { id: 116, commune: "Bascous", description: "Église Saint-Amand et bois de chênes", niveau: 2, categorie: "remarquable", lat: 43.8208, lng: 0.1469 },
  { id: 117, commune: "Blaziert", description: "Village fleuri (4 fleurs) et Église Saint-Barthélemy", niveau: 3, categorie: "suggéré", lat: 43.9333, lng: 0.4833 },
  { id: 118, commune: "Tourrenquets", description: "Église Saint-Barthélemy (située sur une crête)", niveau: 3, categorie: "suggéré", lat: 43.7544, lng: 0.6939 },
  { id: 119, commune: "Mouchan", description: "Église romane Saint-Austrégésile (Chemin de Compostelle)", niveau: 1, categorie: "incontournable", lat: 43.9039, lng: 0.2975 },
  { id: 120, commune: "Perchède", description: "Église Saint-Martin et Étang de la Pesqué", niveau: 2, categorie: "remarquable", lat: 43.7781, lng: -0.1336 },
  { id: 121, commune: "Larroque-sur-l'Osse", description: "Église Saint-Pierre et Pont d'Artigues (UNESCO)", niveau: 2, categorie: "remarquable", lat: 43.9714, lng: 0.2764 },
  { id: 122, commune: "Ligardes", description: "Église Saint-Jean-Baptiste et ses jardins", niveau: 2, categorie: "remarquable", lat: 44.0406, lng: 0.4739 },
  { id: 123, commune: "Lagraulet-du-Gers", description: "Château d'eau peint et Église Sainte-Marie", niveau: 2, categorie: "remarquable", lat: 43.9031, lng: 0.2117 },
  { id: 124, commune: "Béraut", description: "Église Saint-Côme et Saint-Damien", niveau: 1, categorie: "incontournable", lat: 43.9189, lng: 0.4014 },
  { id: 125, commune: "Montréal-du-Gers", description: "Collégiale Saint-Philippe et Villa de Séviac", niveau: 1, categorie: "incontournable", lat: 43.9511, lng: 0.2031 },
  { id: 126, commune: "Gimbrède", description: "Ancienne Commanderie des Templiers", niveau: 2, categorie: "remarquable", lat: 44.0406, lng: 0.7111 },
  { id: 127, commune: "Marsolan", description: "Église de l'Assomption et vue dominante", niveau: 3, categorie: "suggéré", lat: 43.9436, lng: 0.5375 },
  { id: 128, commune: "Terraube", description: "Château de Terraube (Famille de Galard)", niveau: 1, categorie: "incontournable", lat: 43.9056, lng: 0.5517 },
  { id: 129, commune: "Miradoux", description: "Église fortifiée Saint-Orens (Gothique)", niveau: 1, categorie: "incontournable", lat: 43.9989, lng: 0.7533 },
  // --- SECTEUR CENTRE (Autour d'Auch) ---
  { id: 130, commune: "Montaut-les-Créneaux", description: "Porte de ville et Église Saint-Michel", niveau: 1, categorie: "incontournable", lat: 43.6936, lng: 0.6533 },
  { id: 131, commune: "Roquelaure", description: "Église Saint-Loup et Chapelle Saint-Blaise", niveau: 3, categorie: "suggéré", lat: 43.7175, lng: 0.5814 },
  { id: 132, commune: "Pessan", description: "Abbatiale Saint-Michel et tours-portes", niveau: 1, categorie: "incontournable", lat: 43.6214, lng: 0.6489 },
  { id: 133, commune: "Castelnau-Barbarens", description: "Village en terrasses et Église Sainte-Quitterie", niveau: 2, categorie: "remarquable", lat: 43.5761, lng: 0.7236 },
  { id: 134, commune: "Jegun", description: "Bastide et Collégiale Sainte-Candide", niveau: 3, categorie: "suggéré", lat: 43.7544, lng: 0.4594 },
  { id: 135, commune: "Biran", description: "Pile gallo-romaine (Monument funéraire antique)", niveau: 1, categorie: "incontournable", lat: 43.6947, lng: 0.4194 },
  { id: 136, commune: "Antras", description: "Église Saint-Côme et panorama circulaire", niveau: 3, categorie: "suggéré", lat: 43.7153, lng: 0.4619 },
  // --- NOUVEAUX SITES NIVEAU 1 ---
  { id: 137, commune: "Cazeaux-Savès", description: "Château de Caumont (Chef-d'œuvre de la Renaissance)", niveau: 1, categorie: "incontournable", lat: 43.5414, lng: 0.9839 },
  { id: 138, commune: "Tillac", description: "Village-rue médiéval, Tours de l'Horloge et de l'Église", niveau: 1, categorie: "incontournable", lat: 43.4753, lng: 0.2736 },
  { id: 139, commune: "Larressingle", description: "Plus petite cité fortifiée de France (La petite Carcassonne)", niveau: 1, categorie: "incontournable", lat: 43.9439, lng: 0.3139 },
  { id: 140, commune: "Pardailhan", description: "Château de Pardailhan et son parc historique", niveau: 1, categorie: "incontournable", lat: 43.7167, lng: 0.0500 },
  { id: 141, commune: "Termes d'Armagnac", description: "Tour de Termes (Donjon médiéval de 36m de haut)", niveau: 1, categorie: "incontournable", lat: 43.6708, lng: -0.0133 },
  { id: 142, commune: "Riscle", description: "Arènes Jean-Pierre Longepée et église Saint-Pierre", niveau: 1, categorie: "incontournable", lat: 43.6617, lng: -0.0858 },
  { id: 143, commune: "Belmont", description: "Château-Neuf des Peuples et église Saint-Cassin", niveau: 2, categorie: "remarquable", lat: 43.6763, lng: 0.2372 }, 
  { id: 144, commune: "Plaisance", description: "Bastide, église Notre-Dame et ses Arènes", niveau: 1, categorie: "incontournable", lat: 43.6048, lng: 0.0464 },
];

export async function GET() {
  return NextResponse.json(gersSites);
}