import { NextResponse } from 'next/server';

interface SiteLot {
  id: number;
  commune: string;
  description: string;
  niveau: number;
  categorie: 'incontournable' | 'remarquable' | 'suggéré';
  lat: number;
  lng: number;
}

const lotSites: SiteLot[] = [
  { id: 1, commune: 'Albas', description: 'Village perché et vallée du Lot', niveau: 1, categorie: 'incontournable', lat: 44.463, lng: 1.201 },
  { id: 2, commune: 'Autoire', description: 'Cirque naturel, cascade, falaises, Château des Anglais et demeures de caractère (Le plus "Renaissance" des Plus Beaux Villages)', niveau: 1, categorie: 'incontournable', lat: 44.855, lng: 1.763 },
  { id: 3, commune: 'Bélaye', description: 'Village et panorama remarquable sur la vallée du Lot', niveau: 1, categorie: 'incontournable', lat: 44.505, lng: 1.204 },
  { id: 4, commune: 'Cahors', description: 'Pont Valentré, centre historique, Cathédrale Saint-Étienne et patrimoine de la Vallée du Lot', niveau: 1, categorie: 'incontournable', lat: 44.449, lng: 1.436 },
  { id: 5, commune: 'Calvignac', description: 'Village perché dominant la vallée du Lot', niveau: 1, categorie: 'incontournable', lat: 44.483, lng: 1.781 },
  { id: 6, commune: 'Capdenac-le-Haut', description: 'Îlot de pierre médiéval suspendu au-dessus du Lot, remparts et site archéologique', niveau: 1, categorie: 'incontournable', lat: 44.575, lng: 1.989 },
  { id: 7, commune: 'Cardaillac', description: 'Village médiéval, tours de Sagnes, église romane et bourg castral', niveau: 1, categorie: 'incontournable', lat: 44.665, lng: 1.931 },
  { id: 8, commune: 'Carennac', description: 'Prieuré clunisien, cloître roman et abbaye bénédictine au bord de la Dordogne', niveau: 1, categorie: 'incontournable', lat: 44.839, lng: 1.703 },
  { id: 9, commune: 'Carlucet', description: 'Village rural et patrimoine bâti du causse', niveau: 1, categorie: 'incontournable', lat: 44.689, lng: 1.527 },
  { id: 10, commune: 'Castelnau-Montratier', description: 'Bastide du Quercy Blanc et place centrale à arcades', niveau: 1, categorie: 'incontournable', lat: 44.273, lng: 1.353 },
  { id: 11, commune: 'Creysse', description: 'Écrin de pierre au bord de la Dordogne', niveau: 1, categorie: 'incontournable', lat: 44.828, lng: 1.673 },
  { id: 12, commune: 'Espagnac-Sainte-Eulalie', description: 'Trésor caché de la vallée du Célé, abbaye et maisons troglodytes', niveau: 1, categorie: 'incontournable', lat: 44.592, lng: 1.854 },
  { id: 13, commune: 'Espédaillac', description: 'Village emblématique du causse, murets de pierre sèche et Sentier de la Brebis', niveau: 1, categorie: 'incontournable', lat: 44.671, lng: 1.681 },
  { id: 14, commune: 'Figeac', description: 'Ville d’art et d’histoire entre Lot et Célé, Musée Champollion et centre médiéval', niveau: 1, categorie: 'incontournable', lat: 44.608, lng: 2.031 },
  { id: 15, commune: 'Flaugnac', description: 'Village et panorama sur le Quercy Blanc', niveau: 2, categorie: 'remarquable', lat: 44.356, lng: 1.337 },
  { id: 16, commune: 'Gigouzac', description: 'Village médiéval et église romane', niveau: 1, categorie: 'incontournable', lat: 44.567, lng: 1.445 },
  { id: 17, commune: 'Gluges', description: 'Falaises et vallée de la Dordogne', niveau: 1, categorie: 'incontournable', lat: 44.882, lng: 1.642 },
  { id: 18, commune: 'Goujounac', description: 'Village du Quercy et patrimoine rural', niveau: 2, categorie: 'remarquable', lat: 44.643, lng: 1.163 },
  { id: 19, commune: 'Gourdon', description: 'Cité médiévale perchée, remparts et accents du Moyen Âge', niveau: 1, categorie: 'incontournable', lat: 44.739, lng: 1.386 },
  { id: 20, commune: 'Lacapelle-Marival', description: 'Château MH (famille Cardaillac) et bourg médiéval de caractère', niveau: 1, categorie: 'incontournable', lat: 44.726, lng: 1.923 },
  { id: 21, commune: 'Larroque-Toirac', description: 'Château accroché à la falaise, grottes et patrimoine troglodytique', niveau: 1, categorie: 'incontournable', lat: 44.498, lng: 1.828 },
  { id: 22, commune: 'Lavercantière', description: 'Village rural du Quercy', niveau: 1, categorie: 'incontournable', lat: 44.688, lng: 1.284 },
  { id: 23, commune: 'Les Arques', description: 'Village d’artistes et Musée Ossip Zadkine', niveau: 1, categorie: 'incontournable', lat: 44.636, lng: 1.164 },
  { id: 24, commune: 'Lherm', description: 'Village et patrimoine rural du causse', niveau: 1, categorie: 'incontournable', lat: 44.558, lng: 1.364 },
  { id: 25, commune: 'Loubressac', description: 'Village classé, panorama sur la Dordogne et château du XVe', niveau: 1, categorie: 'incontournable', lat: 44.873, lng: 1.784 },
  { id: 26, commune: 'Marcilhac-sur-Célé', description: 'Abbaye Saint-Pierre, perle de la vallée du Célé et patrimoine en pierre sèche', niveau: 1, categorie: 'incontournable', lat: 44.642, lng: 1.807 },
  { id: 27, commune: 'Martel', description: 'Ville aux 7 tours, Palais de la Raymondie et cité de la truffe et de la noix', niveau: 1, categorie: 'incontournable', lat: 44.936, lng: 1.608 },
  { id: 28, commune: 'Montcuq', description: 'Village emblématique perché du Quercy Blanc et tour médiévale sur éperon', niveau: 1, categorie: 'incontournable', lat: 44.339, lng: 1.209 },
  { id: 29, commune: 'Montvalent', description: 'Falaises calcaires et belvédères du causse', niveau: 1, categorie: 'incontournable', lat: 44.872, lng: 1.680 },
  { id: 30, commune: 'Prudhomat', description: 'Forteresse de Castelnau-Bretenoux sur éperon rocheux dominant les quatre rivières', niveau: 1, categorie: 'incontournable', lat: 44.873, lng: 1.836 },
  { id: 31, commune: 'Puy-l’Évêque', description: 'Cité médiévale en gradins dominant le Lot et son port ancien', niveau: 1, categorie: 'incontournable', lat: 44.504, lng: 1.135 },
  { id: 32, commune: 'Rocamadour', description: 'Cité sacrée vertigineuse, Basilique Saint-Sauveur, Sanctuaire et Grotte des Merveilles', niveau: 1, categorie: 'incontournable', lat: 44.799, lng: 1.618 },
  { id: 33, commune: 'Séniergues', description: 'Village du causse et paysages karstiques', niveau: 2, categorie: 'remarquable', lat: 44.693, lng: 1.655 },
  { id: 34, commune: 'Souillac', description: 'Abbaye Sainte-Marie et centre ancien au bord de la Dordogne', niveau: 1, categorie: 'incontournable', lat: 44.898, lng: 1.472 },
  { id: 35, commune: 'Saint-Cirq-Lapopie', description: 'Village d’artistes sur falaise, ruines du Château des Cardaillac et maisons médiévales', niveau: 1, categorie: 'incontournable', lat: 44.467, lng: 1.671 },
  { id: 36, commune: 'Saint-Martin-le-Redon', description: 'Village et vallée préservée', niveau: 2, categorie: 'remarquable', lat: 44.613, lng: 1.044 },
  { id: 37, commune: 'Les Pechs du Vers', description: 'Causse du Quercy et patrimoine karstique', niveau: 2, categorie: 'remarquable', lat: 44.576, lng: 1.552 },
  { id: 38, commune: 'Saint-Vincent-Rive-d’Olt', description: 'Village et berges du Lot', niveau: 1, categorie: 'incontournable', lat: 44.464, lng: 1.286 },
  { id: 39, commune: 'Thégra', description: 'Village et patrimoine bâti traditionnel', niveau: 1, categorie: 'incontournable', lat: 44.735, lng: 1.625 },
  { id: 40, commune: 'Saint-Céré', description: 'Ville historique entre Causse et Ségala, proche du Château de Montal', niveau: 1, categorie: 'incontournable', lat: 44.858, lng: 1.924 },
  { id: 41, commune: 'Gramat', description: 'Escale au cœur du causse lotois et parc animalier', niveau: 1, categorie: 'incontournable', lat: 44.780, lng: 1.607 },
  { id: 42, commune: 'Prayssac', description: 'Bastide et vignoble de Cahors', niveau: 1, categorie: 'incontournable', lat: 44.504, lng: 1.187 },
  { id: 43, commune: 'Biars-sur-Cère', description: 'Bords de Cère et patrimoine industriel', niveau: 2, categorie: 'remarquable', lat: 44.926, lng: 1.848 },
  { id: 44, commune: 'Luzech', description: 'Méandre du Lot et tour médiévale', niveau: 1, categorie: 'incontournable', lat: 44.480, lng: 1.287 },
  { id: 45, commune: 'Bagnac-sur-Célé', description: 'Village et vallée du Célé', niveau: 1, categorie: 'incontournable', lat: 44.666, lng: 2.164 },
  { id: 46, commune: 'Lalbenque', description: 'Capitale de la truffe noire et cœur du Quercy Blanc', niveau: 2, categorie: 'remarquable', lat: 44.339, lng: 1.546 },
  { id: 47, commune: 'Padirac', description: 'Gouffre de Padirac (visite à 103m sous terre, effet "Waouh" garanti)', niveau: 1, categorie: 'incontournable', lat: 44.858, lng: 1.759 },
  { id: 48, commune: 'Cabrerets', description: 'Grotte ornée du Pech Merle, Château du XVe et Château du Diable (repaire troglodyte)', niveau: 1, categorie: 'incontournable', lat: 44.504, lng: 1.651 },
  { id: 49, commune: 'Miers', description: 'Archéosite des Fieux', niveau: 1, categorie: 'incontournable', lat: 44.848, lng: 1.748 },
  { id: 50, commune: 'Payrignac', description: 'Grottes de Cougnac (art préhistorique)', niveau: 1, categorie: 'incontournable', lat: 44.743, lng: 1.386 },
  { id: 51, commune: 'Gréalou', description: 'Dolmen de Pech Laglaire sur le GR 65', niveau: 2, categorie: 'remarquable', lat: 44.610, lng: 1.848 },
  { id: 52, commune: 'Bach', description: 'Phosphatières du Cloup d’Aural, Réserve Naturelle Géologique et voie romaine', niveau: 1, categorie: 'incontournable', lat: 44.516, lng: 1.545 },
  { id: 53, commune: 'Lacave', description: 'Grottes de Lacave et Grotte des Carbonnières (trésor caché du Causse)', niveau: 1, categorie: 'incontournable', lat: 44.875, lng: 1.584 },
  { id: 54, commune: 'Saint-Sozy', description: 'Grottes de Presque', niveau: 1, categorie: 'incontournable', lat: 44.900, lng: 1.780 },
  { id: 55, commune: 'Crégols', description: 'Igue de Crégols (curiosité géologique karstique)', niveau: 1, categorie: 'incontournable', lat: 44.456, lng: 1.696 },
  { id: 56, commune: 'Latouille-Lentillac', description: 'Ruisseaux du Cayla et du Tolerme', niveau: 3, categorie: 'suggéré', lat: 44.860, lng: 1.964 },
  { id: 57, commune: 'Lamativie', description: 'Gorges sauvages et ruisseaux du Cayla et d’Escalmels', niveau: 3, categorie: 'suggéré', lat: 44.928, lng: 2.040 },
  { id: 58, commune: 'Sabadel-Latronquière', description: 'Cascade du ruisseau du Bervezou (Gouffre des Cloches)', niveau: 3, categorie: 'suggéré', lat: 44.736, lng: 2.060 },
  { id: 59, commune: 'Cénevières', description: 'Château de Cénevières, joyau Renaissance accroché aux falaises du Lot', niveau: 1, categorie: 'incontournable', lat: 44.463, lng: 1.751 },
  { id: 60, commune: 'Saint-Jean-Lespinasse', description: 'Château de Montal, chef-d’œuvre de la Renaissance de Jeanne de Balsac', niveau: 1, categorie: 'incontournable', lat: 44.861, lng: 1.919 },
  { id: 61, commune: 'Cœur de Causse', description: 'Château de Vaillac (XV-XVIIe siècle)', niveau: 1, categorie: 'incontournable', lat: 44.675, lng: 1.530 },
  { id: 62, commune: 'Saint-Front-sur-Lémance', description: 'Château de Bonaguil, architecture militaire parfaite (1480-1520)', niveau: 1, categorie: 'incontournable', lat: 44.538, lng: 0.992 },
  { id: 63, commune: 'Saignes', description: 'Château de Saignes, monument historique majeur du Quercy', niveau: 1, categorie: 'incontournable', lat: 44.786, lng: 1.815 },
  { id: 64, commune: 'Couzou', description: 'Château de la Pannonie (XV-XVIIIe), à proximité de Rocamadour', niveau: 1, categorie: 'incontournable', lat: 44.767, lng: 1.587 },
  { id: 65, commune: 'Bessonies', description: 'Château de Bessonies, lieu d’arrestation du Maréchal Ney', niveau: 1, categorie: 'incontournable', lat: 44.811, lng: 2.148 },
  { id: 66, commune: 'Larnagol', description: 'Château de Larnagol, place forte du XIIe et jardins remarquables', niveau: 1, categorie: 'incontournable', lat: 44.475, lng: 1.777 },
  { id: 67, commune: 'Assier', description: 'Château d’Assier, témoignage exceptionnel de l’art de la Renaissance', niveau: 1, categorie: 'incontournable', lat: 44.675, lng: 1.878 },
  { id: 68, commune: 'Dégagnac', description: 'Château de Lantis (XV-XVIIIe)', niveau: 1, categorie: 'incontournable', lat: 44.665, lng: 1.314 },
  { id: 69, commune: 'Saint Géry-Vers', description: 'Château des Anglais de Vers (fortification de falaise)', niveau: 1, categorie: 'incontournable', lat: 44.484, lng: 1.587 },
  { id: 70, commune: 'Bouziès', description: 'Château des Anglais (XI-XIIe) ancré dans la falaise', niveau: 1, categorie: 'incontournable', lat: 44.484, lng: 1.642 },
  { id: 71, commune: 'Aujols', description: 'Igues d’Aujols, dont la Ramade, curiosités karstiques majeures', niveau: 1, categorie: 'incontournable', lat: 44.382, lng: 1.554 },
  { id: 72, commune: 'Cazals', description: 'Écrin de pierre au cœur de la Bouriane', niveau: 1, categorie: 'incontournable', lat: 44.644, lng: 1.226 },
  { id: 73, commune: 'Salviac', description: 'Charme de la Bouriane entre nature et patrimoine médiéval', niveau: 1, categorie: 'incontournable', lat: 44.681, lng: 1.266 },
  { id: 74, commune: 'Cajarc', description: 'Petite ville du Lot au pied des falaises, proche de l’Aveyron', niveau: 1, categorie: 'incontournable', lat: 44.486, lng: 1.843 },
  { id: 75, commune: 'Caniac-du-Causse', description: 'Sur les pas de l’ermite St Namphaise, église avec crypte et Igue de Planagrèze', niveau: 2, categorie: 'remarquable', lat: 44.622, lng: 1.643 },
  { id: 76, commune: 'Reilhac', description: 'Village fleuri du Triangle Noir, église romane et Chemin de l’Eau', niveau: 2, categorie: 'remarquable', lat: 44.700, lng: 1.719 },
  { id: 77, commune: 'Lunegarde', description: 'Village rural préservé, église Saint-Julien et illuminations de Noël', niveau: 2, categorie: 'remarquable', lat: 44.690, lng: 1.688 },
  { id: 78, commune: 'Quissac', description: 'Structure parcellaire rayonnante du XVe siècle et Lac des Places', niveau: 2, categorie: 'remarquable', lat: 44.646, lng: 1.616 },
  { id: 79, commune: 'Escamps', description: 'Village de l’eau et des pierres, cinquante fontaines et Phosphatières des Tempories', niveau: 2, categorie: 'remarquable', lat: 44.368, lng: 1.585 },
  { id: 80, commune: 'Beauregard', description: 'Bastide typique du XIIIe siècle et labellisé Village Étoilé', niveau: 2, categorie: 'remarquable', lat: 44.346, lng: 1.733 },
  { id: 81, commune: 'Concots', description: 'Ancien carrefour commercial, tour du XIIIe et cuisine bistronomique', niveau: 2, categorie: 'remarquable', lat: 44.428, lng: 1.644 },
  { id: 82, commune: 'Varaire', description: 'Passage du GR 65, Lavoir Papillon et Château de Couanac', niveau: 2, categorie: 'remarquable', lat: 44.357, lng: 1.723 },
  { id: 83, commune: 'Grèzes', description: 'Église Saint-Jacques-le-Majeur, Chapelle Notre-Dame, Dolmens (Custalou, Champ de Ligoussou, Cloup-de-Périès, lac de Lapeyre)', niveau: 2, categorie: 'remarquable', lat: 44.627, lng: 1.821 },
  { id: 84, commune: 'Meyronne', description: 'Église Saint-Sulpice, gouffres du Limon, Dolmen des Devinaudes, Notre-Dame du Rocher, ancienne résidence des évêques de Tulle', niveau: 1, categorie: 'incontournable', lat: 44.876, lng: 1.577 },
  { id: 85, commune: 'Sousceyrac-en-Quercy', description: 'Église Saint-Martin, cité médiévale, châteaux (Grugnac, Sousceyrac, La Bessonie, Fraysse, Alzac), bois de la Luzette, pont Roumieu', niveau: 1, categorie: 'incontournable', lat: 44.873, lng: 2.035 },
  { id: 86, commune: 'Bretenoux', description: 'Bastide, église Sainte-Catherine, place des Consuls, maison de l’oncle de Pierre Loti, château de Castelnau-Bretenoux, arcades', niveau: 1, categorie: 'incontournable', lat: 44.914, lng: 1.838 },
];

export async function GET() {
  return NextResponse.json(lotSites);
}
