// src/app/api/randoariege/route.ts
import { NextResponse } from 'next/server';

// Définition du type pour les activités/randonnées
interface ActiviteAriege {
  id: number;
  commune: string;
  type: string;
  details: string;
}

// Données complètes des activités/randonnées en Ariège
const activitesAriege: ActiviteAriege[] = [
  { id: 1, commune: 'Albiès', type: 'Randonnée', details: 'Chemin de la Transhumance Plateau de Beille – Val d’Incles' },
  { id: 2, commune: 'Alliat', type: 'Sites Préhistoriques / Grottes', details: 'Grotte de La Vache' },
  { id: 3, commune: 'Appy', type: 'Randonnée', details: 'Étang d’Appy – depuis Appy' },
  { id: 4, commune: 'Arnave', type: 'Randonnée', details: 'La chapelle St-Paul d’Arnave' },
  { id: 5, commune: 'Artigues', type: 'Site Naturel', details: 'Les mouillères, faune et flore associées dans le Donezan' },
  { id: 6, commune: 'Ascou', type: 'Randonnée', details: 'La dent d’Orlu, Pic de Tarbésou' },
  { id: 7, commune: 'Aston', type: 'Site Naturel', details: 'Natura 2000 – Vallée de l’Aston, Massif de l’Aston et de l’Hospitalet' },
  { id: 8, commune: 'Aston', type: 'Randonnée', details: 'Refuge du Rulhe par Le Rieutort' },
  { id: 9, commune: 'Aston', type: 'Professionnel', details: 'Pyren’Equiâme' },
  { id: 10, commune: 'Auzat', type: 'Site Naturel', details: 'Parc Naturel Régional des Pyrénées Ariégeoises, Vallée de Soulcem' },
  { id: 11, commune: 'Auzat', type: 'Sites Industriels', details: "LE chemin de l'aluminium" },
  { id: 12, commune: 'Auzat', type: 'Lieux de Visite', details: 'Maison des patrimoines' },
  { id: 13, commune: 'Auzat', type: 'Patrimoine Culturel', details: 'Château de Montréal-de-Sos, Orris du Carla' },
  { id: 14, commune: 'Auzat', type: 'Randonnée', details: 'De Marc à l’Artigue, Circuit des Orris, Étangs du Fourcat et refuge, Refuge du Pinet, Pic de la Rouge' },
  { id: 15, commune: 'Auzat', type: 'Professionnel', details: 'Vertikarst, CAP Montcalm (2 mentions)' },
  { id: 16, commune: 'Auzat', type: 'Activité (Insolite/Hiver)', details: 'Escalade (Caverne & Canyon), Challenge Alain Leplus, Stage trail (Luca Papi)' },
  { id: 17, commune: 'Ax-les-Thermes', type: 'Sites Industriels', details: "Sentier d’interprétation de l’usine hydroélectrique du Teich" },
  { id: 18, commune: 'Ax-les-Thermes', type: 'Patrimoine Culturel', details: "Bassin du Couloubret, Église Saint-Vincent, Bassin de l’Axéenne, Bassin des Ladres, Église Saint-Jérôme, Bassin de la Basse" },
  { id: 19, commune: 'Ax-les-Thermes', type: 'Spéléologie', details: 'Bureau des Guides des Pyrénées Ariégeoises' },
  { id: 20, commune: 'Ax-les-Thermes', type: 'Activité (Animaux)', details: 'Adadane' },
  { id: 21, commune: 'Ax-les-Thermes', type: 'Randonnée', details: 'Boucle bleue – Ax au barrage de Campauleil' },
  { id: 22, commune: 'Ax-les-Thermes', type: 'Professionnel', details: 'Adadane, Bureau des Guides, ESI, Ski Club Ax, Le Dahu Ariégeois, Jean Demary, Guide Montagne (Baptiste Sicre)' },
  { id: 23, commune: 'Ax-les-Thermes', type: 'Activité (Insolite/Hiver)', details: 'Alpinisme/cascades de glace, Ski hors piste/randonnée, Escalade (grande voie), Ma famille trappeur, Patinoire, VTT fatbike, Spéléologie, Escalade, Ski' },
  { id: 24, commune: 'Bédeilhac-et-Aynat', type: 'Patrimoine Culturel', details: 'Tour de Montorgueil' },
  { id: 25, commune: 'Bédeilhac-et-Aynat', type: 'Sites Préhistoriques / Grottes', details: 'Grotte de Bédeilhac' },
  { id: 26, commune: 'Bédeilhac-et-Aynat', type: 'Randonnée', details: 'Tour de Montorgueil' },
  { id: 27, commune: 'Camurac', type: 'Activité (Insolite/Hiver)', details: 'Astronomie – Le Ciel et Vous' },
  { id: 28, commune: 'Carcanières', type: 'Patrimoine Culturel', details: 'Abbaye Notre-Dame du Donezan' },
  { id: 29, commune: 'Cazenave-Serres-et-Allens', type: 'Professionnel', details: 'Adret Canyon' },
  { id: 30, commune: 'Comus', type: 'Site Naturel', details: 'Natura 2000 – Gorge de la Frau et Bélesta' },
  { id: 31, commune: 'Fontrabiouse', type: 'Sites Préhistoriques / Grottes', details: 'Grotte de Fontrabiouse' },
  { id: 32, commune: 'Foix', type: 'Randonnée', details: 'Le Chemin des Bonshommes GR®107, Sentier Cathare GR®367' },
  { id: 33, commune: 'Ignaux', type: 'Randonnée', details: 'Signal du Chioula' },
  { id: 34, commune: 'Ignaux', type: 'Activité (Insolite/Hiver)', details: 'VTT AE “Vélo Apéro”' },
  { id: 35, commune: 'Larcat', type: 'Randonnée', details: 'Chapelle St-Barthélémy' },
  { id: 36, commune: 'Le Pla', type: 'Randonnée', details: 'Roc Blanc' },
  { id: 37, commune: 'Les Cabannes', type: 'Patrimoine Culturel', details: 'Église Saint-Martial' },
  { id: 38, commune: 'Les Cabannes', type: 'Randonnée', details: 'La Camina – itinéraire mobilités douces' },
  { id: 39, commune: 'Les Cabannes', type: 'Professionnel', details: 'ESF – École du Ski Français Beille & Chioula' },
  { id: 40, commune: 'Les Cabannes', type: 'Activité (Insolite/Hiver)', details: 'Atelier construction d’igloo, VTT à assistance électrique' },
{ id: 41, commune: 'Lordat', type: 'Lieux de Visite', details: 'Aire d’observation' },
{ id: 42, commune: 'Luzenac', type: 'Sites Industriels', details: 'Talcaneô – Carrière de talc et musée' },
{ id: 43, commune: 'Luzenac', type: 'Patrimoine Culturel', details: 'Église de Saint-Martin' },
{ id: 44, commune: 'Luzenac', type: 'Randonnée', details: 'Pics de Soularac et St-Barthélémy' },
{ id: 45, commune: 'Mercus-Garrabet', type: 'Professionnel', details: 'Kymaya Parapente' },
{ id: 46, commune: 'Mérens-les-Vals', type: 'Patrimoine Culturel', details: 'Église Saint-Pierre' },
{ id: 47, commune: 'Mérens-les-Vals', type: 'Randonnée', details: 'GR®10 – La grande traversée des Pyrénées, Étang de Comte' },
{ id: 48, commune: 'Mérens-les-Vals', type: 'Professionnel', details: 'Montagne Passion, Zen Aventure' },
{ id: 49, commune: 'Mijanès', type: 'Randonnée', details: 'Col de Sira, Plaine d’Artigues par Noubals, Étangs de Rabassoles, Étang de Balbonne' },
{ id: 50, commune: 'Mijanès', type: 'Professionnel', details: 'Husky Évasion' },
{ id: 51, commune: 'Mijanès', type: 'Activité (Insolite/Hiver)', details: 'Luge Snake-gliss' },
{ id: 52, commune: 'Miglos', type: 'Patrimoine Culturel', details: 'Église Saint-Hilaire' },
{ id: 53, commune: 'Miglos', type: 'Randonnée', details: 'Château de Miglos' },
{ id: 54, commune: 'Montaillou', type: 'Lieux de Visite', details: 'Centre historique Jean Duvernoy' },
{ id: 55, commune: 'Montaillou', type: 'Patrimoine Culturel', details: 'Château de Montaillou' },
{ id: 56, commune: 'Montaillou', type: 'Randonnée', details: 'Autour du château de Montaillou' },
{ id: 57, commune: 'Niaux', type: 'Spéléologie', details: 'Spéléologie avec Spéléo Canyon Ariège' },
{ id: 58, commune: 'Niaux', type: 'Sites Préhistoriques / Grottes', details: 'Grotte de Niaux' },
{ id: 59, commune: 'Niaux', type: 'Professionnel', details: 'Spéléo Canyon Ariège' },
{ id: 60, commune: 'Niaux', type: 'Activité (Insolite/Hiver)', details: 'Spéléo – Spéléo Canyon Ariège' },
{ id: 61, commune: 'Orgeix', type: 'Sites Industriels', details: "Sentier d’interprétation de l’usine hydroélectrique" },
{ id: 62, commune: 'Orgeix', type: 'Patrimoine Culturel', details: 'Jardin botanique de la Galinière' },
{ id: 63, commune: 'Orgeix', type: 'Professionnel', details: 'Le sens Outdoor' },
{ id: 64, commune: 'Orlu', type: 'Site Naturel', details: 'Réserve nationale d’Orlu, Natura 2000' },
{ id: 65, commune: 'Orlu', type: 'Lieux de Visite', details: 'Mountanéô – espace muséographique' },
{ id: 66, commune: 'Orlu', type: 'Activité (Animaux)', details: 'La Maison des Loups' },
{ id: 67, commune: 'Orlu', type: 'Randonnée', details: 'Étang d’En Beys et son refuge, La prairie des marmottes, La fraîcheur des cascades' },
{ id: 68, commune: 'Ornolac-Ussat-les-Bains', type: 'Site Naturel', details: 'Natura 2000 – Quiès calcaires et grotte de la Caougno' },
{ id: 69, commune: 'Ornolac-Ussat-les-Bains', type: 'Spéléologie', details: 'Initiation gouffre des eaux chaudes' },
{ id: 70, commune: 'Ornolac-Ussat-les-Bains', type: 'Activité (Insolite/Hiver)', details: 'Stage initiation trail' },
{ id: 71, commune: 'Prades', type: 'Patrimoine Culturel', details: 'Fort de Prades' },
{ id: 72, commune: 'Quérigut', type: 'Randonnée', details: 'Col des Ares, Étang de Quérigut' },
{ id: 73, commune: 'Rabat-les-Trois-Seigneurs', type: 'Spéléologie', details: 'Sibelle Escapade' },
{ id: 74, commune: 'Rabat-les-Trois-Seigneurs', type: 'Randonnée', details: 'Étang Bleu' },
{ id: 75, commune: 'Rabat-les-Trois-Seigneurs', type: 'Professionnel', details: 'Sibelle Escapade' },
{ id: 76, commune: 'Rouze', type: 'Patrimoine Culturel', details: 'Château d’Usson, Ponts Vauban' },
{ id: 77, commune: 'Saurat', type: 'Sites Industriels', details: 'Atelier de la pierre à aiguiser' },
{ id: 78, commune: 'Saurat', type: 'Spéléologie', details: 'Randonnée souterraine – Grotte de Saurat' },
{ id: 79, commune: 'Saurat', type: 'Professionnel', details: 'Escalade-Canyon Maël Loizance' },
{ id: 80, commune: 'Saurat', type: 'Activité (Insolite/Hiver)', details: 'Escalade – Maël Loizance' },
{ id: 81, commune: 'Savignac-les-Ormeaux', type: 'Professionnel', details: 'Planet Rando Yoga' },
{ id: 82, commune: 'Tarascon-sur-Ariège', type: 'Lieux de Visite', details: 'Rêve et magie du rail' },
{ id: 83, commune: 'Tarascon-sur-Ariège', type: 'Patrimoine Culturel', details: 'Église Notre-Dame de la Daurade, découverte vieille ville' },
{ id: 84, commune: 'Tarascon-sur-Ariège', type: 'Spéléologie', details: 'Ici et Ailleurs, Objectif Spéléo' },
{ id: 85, commune: 'Tarascon-sur-Ariège', type: 'Sites Préhistoriques / Grottes', details: 'Parc de la Préhistoire' },
{ id: 86, commune: 'Tarascon-sur-Ariège', type: 'Professionnel', details: 'Maison de la Montagne, L’Ariégeoise, Marie Escalade Canyon, Les Sentiers de Babeth' },
{ id: 87, commune: 'Tarascon-sur-Ariège', type: 'Activité (Insolite/Hiver)', details: 'Raquettes, igloo, trail, spéléo, escalade' },
{ id: 88, commune: 'Unac', type: 'Activité (Animaux)', details: 'La Ferme aux Ânes' },
{ id: 89, commune: 'Unac', type: 'Patrimoine Culturel', details: 'Église Saint-Martin' },
{ id: 90, commune: 'Unac', type: 'Professionnel', details: 'La Ferme aux Ânes, Pyrénées Excursions' },
{ id: 91, commune: 'Unac', type: 'Activité (Insolite/Hiver)', details: 'Escalade – Ariège Canyon Aventure' },
{ id: 92, commune: 'Val-de-Sos', type: 'Site Naturel', details: 'Natura 2000 – Mont Ceint, Mont Béas, tourbière de Bernadouze' },
{ id: 93, commune: 'Val-de-Sos', type: 'Sites Industriels', details: 'La mine de Rancié' },
{ id: 94, commune: 'Val-de-Sos', type: 'Lieux de Visite', details: 'Exposition mine de fer, Le chemin de l’aluminium' },
{ id: 95, commune: 'Val-de-Sos', type: 'Spéléologie', details: 'Montcalm Aventure' },
{ id: 96, commune: 'Val-de-Sos', type: 'Randonnée', details: 'Montréal-de-Sos' },
{ id: 97, commune: 'Val-de-Sos', type: 'Professionnel', details: 'Montcalm Aventure – Multiactivités' },
{ id: 98, commune: 'Val-de-Sos', type: 'Activité (Insolite/Hiver)', details: 'Escalade – Montcalm Aventure' },
{ id: 99, commune: 'Vaychis', type: 'Activité (Animaux)', details: 'Chioula Activités Nature' },
{ id: 100, commune: 'Vaychis', type: 'Professionnel', details: 'Chioula Activités Nature' },
{ id: 101, commune: 'Verdun', type: 'Patrimoine Culturel', details: 'Église Saint-Blaise' },
{ id: 102, commune: 'Verdun', type: 'Professionnel', details: 'O’calm Canyon' },
{ id: 103, commune: 'Vernaux', type: 'Patrimoine Culturel', details: 'Église Sainte-Marthe' },
];

export async function GET() {
  return NextResponse.json(activitesAriege);
}
