import { NextResponse } from "next/server";

const establishments = [
  { num: "0", voie: "avenue", adresse: "Flammarion", bâtiment: "obélisque", quartier: "Colonne", "équivalent à Paris": "type égyptien, parisien", ressemble: "Paris", localisation: "hypercentre" },
  { num: "1", voie: "avenue", adresse: "Flammarion", bâtiment: "observatoire", quartier: "Colonne", "équivalent à Paris": "type Meudon, parisien", ressemble: "Paris", localisation: "hypercentre" },
  { num: "0", voie: "cim", adresse: "Terre Cabade", bâtiment: "cimetière Terre Cabade", quartier: "Colonne", "équivalent à Paris": "cimetière Père Lachaise", ressemble: "Paris", localisation: "hypercentre" },
  { num: "0", voie: "cim", adresse: "Terre Cabade", bâtiment: "monument aux Morts", quartier: "Colonne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "25", voie: "avenue", adresse: "Colonne", bâtiment: "immeuble", quartier: "Colonne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "24", voie: "rue", adresse: "Cimetière", bâtiment: "immeuble", quartier: "Colonne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "0", voie: "place", adresse: "Légion Honneur", bâtiment: "fontaine cascade", quartier: "Matabiau", "équivalent à Paris": "fontaine Trocadéro", ressemble: "Paris", localisation: "hypercentre" },
  { num: "1", voie: "all", adresse: "Chaband-Delmas", bâtiment: "Arche Marengo", quartier: "Matabiau", "équivalent à Paris": "Arche de la Défense", ressemble: "Paris", localisation: "hypercentre" },
  { num: "0", voie: "all", adresse: "Jean Jaurès", bâtiment: "statue Riquet", quartier: "Matabiau", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "0", voie: "all", adresse: "Jean Jaurès", bâtiment: "allées Jean Jaurès", quartier: "Jean Jaurès", "équivalent à Paris": "Champs-Elysées, rue et pharmacie", ressemble: "Paris", localisation: "hypercentre" },
  { num: "14", voie: "bd", adresse: "Bonrepos", bâtiment: "gare Matabiau", quartier: "Matabiau", "équivalent à Paris": "mansarde avec ardoise, gare parisienne", ressemble: "Paris", localisation: "hypercentre" },
  { num: "0", voie: "place", adresse: "Roquelaine", bâtiment: "monument morts", quartier: "Matabiau", "équivalent à Paris": "statue style parisien", ressemble: "Paris", localisation: "hypercentre" },
  { num: "0", voie: "place", adresse: "Concorde", bâtiment: "fontaine Romane", quartier: "Matabiau", "équivalent à Paris": "fontaine", ressemble: "Paris", localisation: "hypercentre" },
  { num: "5", voie: "rue", adresse: "Orient", bâtiment: "Grand Orient", quartier: "Bayard", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "1", voie: "rue", adresse: "Belfort", bâtiment: "Dame des Victoires", quartier: "Jean Jaurès", "équivalent à Paris": "chapelle parisienne baroque", ressemble: "Paris", localisation: "hypercentre" },
  { num: "0", voie: "all", adresse: "Jean Jaurès", bâtiment: "immeuble", quartier: "Jean Jaurès", "équivalent à Paris": "immeuble parisien Hausmann", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "0", voie: "all", adresse: "Jean Jaurès", bâtiment: "Hausmanien", quartier: "Jean Jaurès", "équivalent à Paris": "Hausmanien", ressemble: "Paris", localisation: "hypercentre" },
  { num: "27", voie: "all", adresse: "Jean Jaurès", bâtiment: "fontaine Victoire", quartier: "Jean Jaurès", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "27", voie: "all", adresse: "Jean Jaurès", bâtiment: "Dame des Graces", quartier: "Jean Jaurès", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
  { num: "0", voie: "place", adresse: "Toulouse", bâtiment: "fontaine Wallace", quartier: "Toulouse", "équivalent à Paris": "fontaine Wallace", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "bd", adresse: "boulevards", bâtiment: "Hausmanien", quartier: "boulevards", "équivalent à Paris": "Hausmanien", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Baudis", bâtiment: "théâtre Cité", quartier: "Wilson", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Wilson", bâtiment: "immeuble", quartier: "Wilson", "équivalent à Paris": "série d'arcades", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "square", adresse: "Goudouli", bâtiment: "fontaine Goudouli", quartier: "Wilson", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "all", adresse: "Roosevelt", bâtiment: "immeuble", quartier: "Wilson", "équivalent à Paris": "série d'arcades", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "rue", adresse: "Victor Hugo", bâtiment: "halles Victor Hugo", quartier: "Wilson", "équivalent à Paris": "halles Baltard", ressemble: "Paris", localisation: "centre" },
{ num: "42", voie: "rue", adresse: "Alsace Lorraine", bâtiment: "la Dépêche", quartier: "Jeanne d'Arc", "équivalent à Paris": "art déco Sud-Ouest", ressemble: "Toulouse", localisation: "centre" },
{ num: "15", voie: "rue", adresse: "Bellegarde", bâtiment: "immeuble", quartier: "Jeanne d'Arc", "équivalent à Paris": "immeuble parisien Hausmann", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Périgord", bâtiment: "Bibliothèque", quartier: "Saint-Sernin", "équivalent à Paris": "art déco Sud-Ouest", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Périgord", bâtiment: "chapelle Carmélites", quartier: "Saint-Sernin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "2", voie: "rue", adresse: "Périgord", bâtiment: "chapelle Ste Marie Nevers", quartier: "Saint-Sernin", "équivalent à Paris": "toit en ardoise", ressemble: "Paris", localisation: "centre" },
{ num: "69", voie: "rue", adresse: "Taur", bâtiment: "collège Esquile", quartier: "Saint-Sernin", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "54", voie: "rue", adresse: "Taur", bâtiment: "collège Périgord", quartier: "Saint-Sernin", "équivalent à Paris": "arcades et chapitau cours centrale", ressemble: "Paris", localisation: "centre" },
{ num: "38", voie: "rue", adresse: "Taur", bâtiment: "collège Maguelone", quartier: "Saint-Sernin", "équivalent à Paris": "façade", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Esquile", bâtiment: "collège Esquile", quartier: "Saint-Sernin", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Saint-Sernin", bâtiment: "basilique Saint-Sernin", quartier: "Saint-Sernin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Saint-Sernin", bâtiment: "collège Saint-Raymond", quartier: "Saint-Sernin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "3", voie: "place", adresse: "Saint-Sernin", bâtiment: "hôtel", quartier: "Saint-Sernin", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Saint-Pierre", bâtiment: "Saint-Pierre des Cuisines", quartier: "Saint-Pierre", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "pont", adresse: "Saint-Pierre", bâtiment: "pont", quartier: "Saint-Pierre", "équivalent à Paris": "pont parisien en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "21", voie: "all", adresse: "Brienne", bâtiment: "manufacture Tabacs", quartier: "Saint-Pierre", "équivalent à Paris": "usine", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "quai", adresse: "Saint-Pierre", bâtiment: "moulin Bazacle", quartier: "Saint-Pierre", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "7", voie: "place", adresse: "Lange", bâtiment: "Dome de la Grave", quartier: "Saint-Cyprien", "équivalent à Paris": "dome parisien", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "1", voie: "imp", adresse: "Dame Porte", bâtiment: "couvent Dame Porte", quartier: "Saint-Cyprien", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "25", voie: "grde rue", adresse: "Saint-Nicolas", bâtiment: "église Saint-Nicolas", quartier: "Saint-Cyprien", "équivalent à Paris": "méridional, clocher sans toit, ajout toit ardoise", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "76", voie: "all", adresse: "Charles de Fitte", bâtiment: "remparts", quartier: "Saint-Cyprien", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "Rive Gauche" },
{ num: "76", voie: "all", adresse: "Charles de Fitte", bâtiment: "musée Abattoirs", quartier: "Saint-Cyprien", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "Rive Gauche" },
{ num: "1", voie: "avenue", adresse: "château d'eau", bâtiment: "nouveau château d'eau", quartier: "Saint-Cyprien", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "0", voie: "place", adresse: "Lagane", bâtiment: "arc de triomphe", quartier: "Saint-Cyprien", "équivalent à Paris": "arc de triomphe", ressemble: "Aquitaine", localisation: "Rive Gauche" },
{ num: "0", voie: "place", adresse: "Lagane", bâtiment: "château d'eau", quartier: "Saint-Cyprien", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "Rive Gauche" },
{ num: "0", voie: "place", adresse: "Roguet", bâtiment: "halles Saint-Cyprien", quartier: "Saint-Cyprien", "équivalent à Paris": "halles Baltard", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "0", voie: "place", adresse: "Saint-Cyprien", bâtiment: "Toulouse et Langedoc", quartier: "Saint-Cyprien", "équivalent à Paris": "statues place Concorde", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "0", voie: "place", adresse: "Olivier", bâtiment: "fontaine des Oliviers", quartier: "Saint-Cyprien", "équivalent à Paris": "fontaine Concorde", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "9", voie: "rue", adresse: "Teinturiers", bâtiment: "cloître Feuillants", quartier: "Saint-Cyprien", "équivalent à Paris": "méridional, clocher sans toit, ajout toit ardoise", ressemble: "Paris", localisation: "Rive Gauche" },
{ num: "2", voie: "rue", adresse: "Viguier", bâtiment: "hôpital Saint-Jacques", quartier: "Saint-Cyprien", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "Rive Gauche" },
{ num: "3", voie: "rue", adresse: "Peyrolières", bâtiment: "hôtel", quartier: "Peyrolières", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "5", voie: "quai", adresse: "Daurade", bâtiment: "école Beaux Arts", quartier: "Daurade", "équivalent à Paris": "pierres blanches", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Daurade", bâtiment: "basilique Daurade", quartier: "Daurade", "équivalent à Paris": "pierres blanches et temple grec", ressemble: "Paris", localisation: "centre" },
{ num: "2", voie: "place", adresse: "Daurade", bâtiment: "Noviciat Jésuites", quartier: "Daurade", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "17", voie: "rue", adresse: "Larrey", bâtiment: "conservatoire musique", quartier: "Daurade", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Bourse", bâtiment: "fontaine feuille", quartier: "Bourse", "équivalent à Paris": "feuille jardin James Joyce", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Bourse", bâtiment: "palais Bourse", quartier: "Bourse", "équivalent à Paris": "carré avec colonnades", ressemble: "Paris", localisation: "centre" },
{ num: "15", voie: "rue", adresse: "Bourse", bâtiment: "hôtel", quartier: "Bourse", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "20", voie: "rue", adresse: "Bourse", bâtiment: "hôtel", quartier: "Bourse", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "13", voie: "rue", adresse: "Sainte-Ursule", bâtiment: "hôtel", quartier: "Bourse", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "13", voie: "rue", adresse: "Sainte-Ursule", bâtiment: "pavillon Mazar", quartier: "Bourse", "équivalent à Paris": "parisien", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Gambetta", bâtiment: "hôtel", quartier: "Gambetta", "équivalent à Paris": "florentin, mais de Paris", ressemble: "Paris", localisation: "centre" },
{ num: "25", voie: "rue", adresse: "Gambetta", bâtiment: "hôtel", quartier: "Gambetta", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Jacobins", bâtiment: "cloître Jacobins", quartier: "Jacobins", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Mirepoix", bâtiment: "collège Mirepoix", quartier: "Jacobins", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "69", voie: "rue", adresse: "Pargaminières", bâtiment: "immeuble", quartier: "Capitole", "équivalent à Paris": "immeuble parisien Hausmann", ressemble: "Toulouse", localisation: "centre" },
{ num: "71", voie: "rue", adresse: "Pargaminières", bâtiment: "Temple réformé", quartier: "Capitole", "équivalent à Paris": "temple type parisien avec chapiteau", ressemble: "Paris", localisation: "centre" },
{ num: "8", voie: "rue", adresse: "Romiguières", bâtiment: "grand hôtel Balcon", quartier: "Capitole", "équivalent à Paris": "immeuble parisien Hausmann", ressemble: "Paris", localisation: "centre" },
{ num: "6", voie: "rue", adresse: "Taur", bâtiment: "cloître Cisterciens", quartier: "Capitole", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "4", voie: "rue", adresse: "Taur", bâtiment: "église Taur", quartier: "Capitole", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Capitole", bâtiment: "Arcades du Capitole", quartier: "Capitole", "équivalent à Paris": "arcades rue de Rivoli", ressemble: "Paris", localisation: "centre" },
{ num: "7", voie: "place", adresse: "Capitole", bâtiment: "Grand hôtel Plaza", quartier: "Capitole", "équivalent à Paris": "ancien collège, immeuble parisien", ressemble: "Paris", localisation: "centre" },
{ num: "5", voie: "place", adresse: "Capitole", bâtiment: "café Bibent", quartier: "Capitole", "équivalent à Paris": "café parisien XIXème siècle", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Capitole", bâtiment: "Grand hôtel Opéra", quartier: "Capitole", "équivalent à Paris": "ancien collège, immeuble parisien", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Capitole", bâtiment: "collège Saint-Martin", quartier: "Capitole", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "17", voie: "rue", adresse: "Rémusat", bâtiment: "maison du Sénéchal", quartier: "Capitole", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Capitole", bâtiment: "place Capitole en blanc", quartier: "Capitole", "équivalent à Paris": "peinture blanche, immite pierre", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Capitole", bâtiment: "mairie Capitole", quartier: "Capitole", "équivalent à Paris": "ministère Marine", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Capitole", bâtiment: "Salle des Illustres", quartier: "Capitole", "équivalent à Paris": "Galerie des Glaces de Versailles", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "square", adresse: "de Gaulle", bâtiment: "donjon", quartier: "Capitole", "équivalent à Paris": "donjon sans toit, ajout toit en ardoise", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Salengro", bâtiment: "fontaine Salengro", quartier: "Capitole", "équivalent à Paris": "fontaine Concorde", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "rue", adresse: "Alsace Lorraine", bâtiment: "Hausmanien", quartier: "Capitole", "équivalent à Paris": "Hausmanien", ressemble: "Paris", localisation: "centre" },
{ num: "77", voie: "rue", adresse: "Alsace Lorraine", bâtiment: "Galeries Lafayette", quartier: "Capitole", "équivalent à Paris": "Galeries Lafayette", ressemble: "Paris", localisation: "centre" },
{ num: "43", voie: "rue", adresse: "Saint-Jérôme", bâtiment: "chapelle Saint-Jérôme", quartier: "Capitole", "équivalent à Paris": "méridional, clocher sans toit, ajout toit ardoise", ressemble: "semi-Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Lt Pélissier", bâtiment: "hôtel", quartier: "Capitole", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "8", voie: "rue", adresse: "Lt Pélissier", bâtiment: "commanderie st-Antoine T", quartier: "Capitole", "équivalent à Paris": "parisien", ressemble: "Paris", localisation: "centre" },
{ num: "10", voie: "rue", adresse: "Lt Pélissier", bâtiment: "Saint-Antoine de Vienne", quartier: "Capitole", "équivalent à Paris": "chapelle parisienne baroque", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Saint-Rome", bâtiment: "hôtel", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "7", voie: "rue", adresse: "Dumay", bâtiment: "hôtel", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Puits Clos", bâtiment: "fontaine Electricité Garonne", quartier: "Saint-Rome", "équivalent à Paris": "fontaine Gaillon", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Genty-Mengre", bâtiment: "hôtel", quartier: "Filatiers", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "46", voie: "rue", adresse: "Tourneurs", bâtiment: "poivrière", quartier: "Filatiers", "équivalent à Paris": "Hausmanien", ressemble: "Paris", localisation: "centre" },
{ num: "14", voie: "rue", adresse: "Tripière", bâtiment: "maison Compagnons", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Chalande", bâtiment: "collège Saint-Rome", quartier: "Saint-Rome", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "10", voie: "rue", adresse: "Changes", bâtiment: "hôtel", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "16", voie: "rue", adresse: "Changes", bâtiment: "hôtel", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "4", voie: "rue", adresse: "Malcousinat", bâtiment: "hôtel", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "11", voie: "rue", adresse: "Malcousinat", bâtiment: "hôtel", quartier: "Saint-Rome", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "3", voie: "place", adresse: "Assézat", bâtiment: "hôtel", quartier: "Esquirol", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Echarpe", bâtiment: "hôtel", quartier: "Esquirol", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "pont", adresse: "Neuf", bâtiment: "pont", quartier: "Esquirol", "équivalent à Paris": "pont parisien en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "45", voie: "rue", adresse: "Tourneurs", bâtiment: "hôtel", quartier: "Esquirol", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "21", voie: "rue", adresse: "Metz", bâtiment: "cloître Augustins", quartier: "Esquirol", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Paul Mercier", bâtiment: "chapelle St-Jean baptiste", quartier: "Esquirol", "équivalent à Paris": "chapelle parisienne baroque", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "rue", adresse: "Metz", bâtiment: "Hausmanien", quartier: "Metz", "équivalent à Paris": "Hausmanien", ressemble: "Paris", localisation: "centre" },
{ num: "5", voie: "rue", adresse: "Pomme", bâtiment: "hôtel", quartier: "Pomme", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "19", voie: "place", adresse: "Saint-Georges", bâtiment: "hôtel", quartier: "Saint-Georges", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Roland", bâtiment: "fontaine Pas de Roland", quartier: "Saint-Georges", "équivalent à Paris": "fontaine parisienne", ressemble: "Paris", localisation: "centre" },
{ num: "25", voie: "rue", adresse: "Malaret", bâtiment: "hôtel", quartier: "Saint-Etienne", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Saint-Etienne", bâtiment: "cathédrale", quartier: "Saint-Etienne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Saint-Etienne", bâtiment: "fontaine Grifoul", quartier: "Saint-Etienne", "équivalent à Paris": "fontaine Manneken-Pis Bruxelles", ressemble: "Etranger", localisation: "centre" },
{ num: "8", voie: "place", adresse: "Saint-Etienne", bâtiment: "Palais National", quartier: "Saint-Etienne", "équivalent à Paris": "parisien", ressemble: "Paris", localisation: "centre" },
{ num: "9", voie: "rue", adresse: "Croix-Baragnon", bâtiment: "ancien Jeu de Paume", quartier: "Saint-Etienne", "équivalent à Paris": "immeuble parisien Hausmann", ressemble: "Paris", localisation: "centre" },
{ num: "10", voie: "rue", adresse: "Croix-Baragnon", bâtiment: "hôtel", quartier: "Saint-Etienne", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "10", voie: "rue", adresse: "Croix-Baragnon", bâtiment: "hôtel", quartier: "Saint-Etienne", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "15", voie: "rue", adresse: "Croix-Baragnon", bâtiment: "maison gothique", quartier: "Saint-Etienne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Dupuy", bâtiment: "obélisque", quartier: "Dupuy", "équivalent à Paris": "fontaine Châtelet, type égyptien, parisien", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Dupuy", bâtiment: "Halle aux Grains", quartier: "Dupuy", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "all", adresse: "François Verdier", bâtiment: "monument aux Morts", quartier: "Dupuy", "équivalent à Paris": "Arc de Triomphe", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Saint-Aubin", bâtiment: "église Saint-Aubin", quartier: "Saint-Aubin", "équivalent à Paris": "basilique du Sacré-Cœur Montmartre", ressemble: "Paris", localisation: "hypercentre" },
{ num: "15", voie: "rue", adresse: "Sainte-Anne", bâtiment: "chapelle Sainte-Anne", quartier: "Saint-Etienne", "équivalent à Paris": "toulousain, midi", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Bida", bâtiment: "remparts", quartier: "Palais Niel", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Montoulieu", bâtiment: "Palais Niel", quartier: "Palais Niel", "équivalent à Paris": "Palais du Luxembourg", ressemble: "Paris", localisation: "centre" },
{ num: "20", voie: "rue", adresse: "Saint-Jacques", bâtiment: "palais Académique", quartier: "Palais Niel", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "12", voie: "rue", adresse: "Ninau", bâtiment: "hôtel", quartier: "Grand-Rond", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "15", voie: "rue", adresse: "Ninau", bâtiment: "hôtel", quartier: "Grand-Rond", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "19", voie: "rue", adresse: "Ninau", bâtiment: "hôtel", quartier: "Grand-Rond", "équivalent à Paris": "châpiteau, parisien", ressemble: "Paris", localisation: "centre" },
{ num: "4", voie: "rue", adresse: "Fermat", bâtiment: "hôtel", quartier: "Saint-Etienne", "équivalent à Paris": "tour ronde", ressemble: "Paris", localisation: "centre" },
{ num: "11", voie: "rue", adresse: "Trois Banquets", bâtiment: "hôtel", quartier: "Saint-Etienne", "équivalent à Paris": "tour ronde", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "pl", adresse: "Sainte-Scrabes", bâtiment: "fontaine", quartier: "Sainte-Scrabes", "équivalent à Paris": "fontaine parisienne", ressemble: "Paris", localisation: "centre" },
{ num: "4", voie: "rue", adresse: "Tolosane", bâtiment: "hôtel", quartier: "Grand-Rond", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "8", voie: "rue", adresse: "Bouquières", bâtiment: "hôtel", quartier: "Sainte-Scrabes", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "20", voie: "rue", adresse: "Mage", bâtiment: "hôtel", quartier: "Sainte-Scrabes", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Mage", bâtiment: "hôtel", quartier: "Ozenne", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "13", voie: "rue", adresse: "Vélane", bâtiment: "hôtel", quartier: "Grand-Rond", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "16", voie: "rue", adresse: "Vélane", bâtiment: "hôtel", quartier: "Grand-Rond", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Trinité", bâtiment: "fontaine", quartier: "Esquirol", "équivalent à Paris": "place Concorde", ressemble: "Paris", localisation: "centre" },
{ num: "15", voie: "rue", adresse: "Dalbade", bâtiment: "couvent Visitation", quartier: "Dalbade", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "9", voie: "rue", adresse: "Saint-Rémésy", bâtiment: "hôtel", quartier: "Dalbade", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "25", voie: "rue", adresse: "Dalbade", bâtiment: "hôtel", quartier: "Dalbade", "équivalent à Paris": "pierres, hôtel", ressemble: "Paris", localisation: "centre" },
{ num: "31", voie: "rue", adresse: "Dalbade", bâtiment: "hôtel", quartier: "Dalbade", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "32", voie: "rue", adresse: "Dalbade", bâtiment: "église Dalbade", quartier: "Dalbade", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "32", voie: "rue", adresse: "Dalbade", bâtiment: "hôtel", quartier: "Dalbade", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "22", voie: "rue", adresse: "Dalbade", bâtiment: "hôtel", quartier: "Dalbade", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "53", voie: "rue", adresse: "Filatiers", bâtiment: "maison Calas", quartier: "Filatiers", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "57", voie: "rue", adresse: "Filatiers", bâtiment: "immeuble", quartier: "Filatiers", "équivalent à Paris": "florentin, mais de Paris", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Madeleine", bâtiment: "hôtel", quartier: "Filatiers", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Maletache", bâtiment: "hôtel", quartier: "Filatiers", "équivalent à Paris": "hôtel parisien", ressemble: "Paris", localisation: "centre" },
{ num: "2", voie: "rue", adresse: "Alsace Lorraine", bâtiment: "palais consulaire", quartier: "Languedoc", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "8", voie: "rue", adresse: "Régan", bâtiment: "hôtel", quartier: "Languedoc", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "10", voie: "rue", adresse: "Languedoc", bâtiment: "hôtel", quartier: "Languedoc", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" }
{ num: "16", voie: "rue", adresse: "Languedoc", bâtiment: "hôtel", quartier: "Languedoc", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "34", voie: "rue", adresse: "Languedoc", bâtiment: "hôtel", quartier: "Languedoc", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "36", voie: "rue", adresse: "Languedoc", bâtiment: "hôtel", quartier: "Languedoc", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "46", voie: "rue", adresse: "Languedoc", bâtiment: "hôtel", quartier: "Languedoc", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "3", voie: "rue", adresse: "Ozenne", bâtiment: "pharmacie", quartier: "Ozenne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "9", voie: "rue", adresse: "Ozenne", bâtiment: "hôtel", quartier: "Ozenne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "13", voie: "rue", adresse: "Pleau", bâtiment: "hôtel", quartier: "Ozenne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "rue", adresse: "Espinasse", bâtiment: "hôtel", quartier: "Ozenne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "4", voie: "rue", adresse: "Féral", bâtiment: "chapelle Nazareth", quartier: "Ozenne", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "40", voie: "grde rue", adresse: "Nazareth", bâtiment: "école Saint-Thomas d'Aquin", quartier: "Ozenne", "équivalent à Paris": "immeuble parisien Hausmann", ressemble: "Paris", localisation: "centre" },
{ num: "33", voie: "all", adresse: "Jules Guesdes", bâtiment: "église Saint-Exupère", quartier: "Jules Guesdes", "équivalent à Paris": "église Saint-Michel", ressemble: "Paris", localisation: "centre" },
{ num: "33", voie: "all", adresse: "Jules Guesdes", bâtiment: "jardin des Plantes", quartier: "Jules Guesdes", "équivalent à Paris": "jardin des Plantes", ressemble: "Paris", localisation: "centre" },
{ num: "35", voie: "all", adresse: "Jules Guesdes", bâtiment: "théâtre Sorano", quartier: "Jules Guesdes", "équivalent à Paris": "colonnade et chapitaux type grec", ressemble: "Paris", localisation: "centre" },
{ num: "35", voie: "all", adresse: "Jules Guesdes", bâtiment: "muséum", quartier: "Jules Guesdes", "équivalent à Paris": "muséum", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "square", adresse: "Boulingrin", bâtiment: "fontaine Boulingrin", quartier: "Grand-Rond", "équivalent à Paris": "jet d'eau type parisien", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "all", adresse: "Mistral", bâtiment: "porte Arsenal du Capitole", quartier: "Grand-Rond", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "all", adresse: "Mistral", bâtiment: "porte jardin des Plantes", quartier: "Grand-Rond", "équivalent à Paris": "arc triomphe", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "all", adresse: "Demoiselles", bâtiment: "série hôtels particulier", quartier: "Demoiselles", "équivalent à Paris": "toit en ardoise", ressemble: "Paris", localisation: "hypercentre" },
{ num: "17", voie: "rue", adresse: "Japon", bâtiment: "villa mauresque", quartier: "Demoiselles", "équivalent à Paris": "style mauresque", ressemble: "Etranger", localisation: "hypercentre" },
{ num: "19", voie: "bd", adresse: "Marne", bâtiment: "serres municipales", quartier: "Demoiselles", "équivalent à Paris": "type parisien", ressemble: "Paris", localisation: "hypercentre" },
{ num: "22", voie: "rue", adresse: "Fleurs", bâtiment: "église Gésu", quartier: "Salin", "équivalent à Paris": "méridional, clocher sans toit, ajout toit ardoise", ressemble: "Paris", localisation: "centre" },
{ num: "22", voie: "rue", adresse: "Fleurs", bâtiment: "école Saint-Stanislas", quartier: "Salin", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Hauts Murats", bâtiment: "remparts", quartier: "Salin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Parlement", bâtiment: "chapelle st-Dominique", quartier: "Salin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "12", voie: "place", adresse: "Parlement", bâtiment: "hôtel", quartier: "Salin", "équivalent à Paris": "porche en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "place", adresse: "Salin", bâtiment: "Palais de Justice", quartier: "Salin", "équivalent à Paris": "parisien", ressemble: "Paris", localisation: "centre" },
{ num: "3", voie: "place", adresse: "Salin", bâtiment: "ancien hôtel de la Monnaie", quartier: "Salin", "équivalent à Paris": "parisien", ressemble: "Paris", localisation: "centre" },
{ num: "4", voie: "imp", adresse: "Trésorerie", bâtiment: "Temple du Salin", quartier: "Salin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "18", voie: "rue", adresse: "Pharaon", bâtiment: "Saint-Antoine du Salin", quartier: "Salin", "équivalent à Paris": "façade", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "all", adresse: "Paul Feuga", bâtiment: "maison du boureau", quartier: "Salin", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "all", adresse: "Jules Guesdes", bâtiment: "monument morts 1871", quartier: "Saint-Michel", "équivalent à Paris": "monument République", ressemble: "Paris", localisation: "centre" },
{ num: "2", voie: "all", adresse: "Jules Guesdes", bâtiment: "château narbonnais", quartier: "Saint-Michel", "équivalent à Paris": "Conciergerie", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Lafourcade", bâtiment: "fontaine Garonne et Ariège", quartier: "Saint-Michel", "équivalent à Paris": "fontaine Saint-Michel, Paris", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "pont", adresse: "Saint-Michel", bâtiment: "pont", quartier: "Saint-Michel", "équivalent à Paris": "pont parisien en pierre", ressemble: "Paris", localisation: "centre" },
{ num: "1", voie: "avenue", adresse: "Gabriel Biénès", bâtiment: "piscine municipale", quartier: "Ramier", "équivalent à Paris": "art déco Sud-Ouest", ressemble: "Toulouse", localisation: "hypercentre" },
{ num: "13", voie: "all", adresse: "pr Soula", bâtiment: "soufflerie Banlève", quartier: "Ramier", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "hypercentre" },
{ num: "31", voie: "rue", adresse: "Fonderie", bâtiment: "monastère Saint-Claire", quartier: "Dalbade", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "centre" },
{ num: "0", voie: "avenue", adresse: "Arène Romaine", bâtiment: "arènes romaines", quartier: "Ancely", "équivalent à Paris": "gallo-romain", ressemble: "Antique", localisation: "yextérieur" }
{ num: "7", voie: "all", adresse: "Causses", bâtiment: "thermes romains", quartier: "Ancely", "équivalent à Paris": "gallo-romain", ressemble: "Antique", localisation: "yextérieur" },
{ num: "4", voie: "place", adresse: "Busca", bâtiment: "maison", quartier: "Busca", "équivalent à Paris": "toit en ardoise", ressemble: "Paris", localisation: "yextérieur" },
{ num: "147", voie: "route", adresse: "Albi", bâtiment: "castelet Ozenne", quartier: "Croix-Daurade", "équivalent à Paris": "poivrière", ressemble: "Paris", localisation: "y'extérieur" },
{ num: "21", voie: "chem", adresse: "Calquet", bâtiment: "château Calquet", quartier: "Lardenne", "équivalent à Paris": "des mansardes, château avec ardoise", ressemble: "Paris", localisation: "yextérieur" },
{ num: "4", voie: "all", adresse: "Machado", bâtiment: "Arche Mirail", quartier: "Mirail", "équivalent à Paris": "Arche de la Défense", ressemble: "Paris", localisation: "yextérieur" },
{ num: "1", voie: "avenue", adresse: "Jean Gonord", bâtiment: "cité de l'Espace", quartier: "Montaudran", "équivalent à Paris": "cité de la Vilette", ressemble: "Paris", localisation: "y’extérieur" },
{ num: "0", voie: "pont", adresse: "Jumeaux", bâtiment: "pont", quartier: "Ponts Jumeaux", "équivalent à Paris": "pont parisien en pierre", ressemble: "Paris", localisation: "yextérieur" },
{ num: "75", voie: "voie", adresse: "TOEC", bâtiment: "château Purpan", quartier: "Purpan", "équivalent à Paris": "portes-fenêtres, arcades", ressemble: "Paris", localisation: "yextérieur" },
{ num: "1", voie: "avenue", adresse: "Edouard Belin", bâtiment: "château Lespinet-Raynal", quartier: "Rangueil", "équivalent à Paris": "avec poivrières et ardoise", ressemble: "Paris", localisation: "yextérieur" },
{ num: "1", voie: "imp", adresse: "Lacordaire", bâtiment: "studium Dominicains", quartier: "Rangueil", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "yextérieur" },
{ num: "0", voie: "parc", adresse: "Reynerie", bâtiment: "château Reynerie", quartier: "Reynerie", "équivalent à Paris": "petit Trianon", ressemble: "Paris", localisation: "yextérieur" },
{ num: "4", voie: "grde rue", adresse: "Saint-Michel", bâtiment: "villa Gabès", quartier: "Saint-Michel", "équivalent à Paris": "style colonial", ressemble: "Etranger", localisation: "yextérieur" },
{ num: "18", voie: "grde rue", adresse: "Saint-Michel", bâtiment: "chapelle Lazaristes", quartier: "Saint-Michel", "équivalent à Paris": "toulousain, midi", ressemble: "Toulouse", localisation: "yextérieur" },
{ num: "18", voie: "grde rue", adresse: "Saint-Michel", bâtiment: "prison Saint-Michel", quartier: "Saint-Michel", "équivalent à Paris": "Castelet", ressemble: "Paris", localisation: "yextérieur" },
{ num: "0", voie: "all", adresse: "André Turcat", bâtiment: "futur parc des expos", quartier: "Beauzelle", "équivalent à Paris": "cité de la Vilette", ressemble: "Paris", localisation: "zbanlieue" },
{ num: "1", voie: "all", adresse: "André Turcat", bâtiment: "Aeroscopia", quartier: "Beauzelle", "équivalent à Paris": "cité de la Vilette", ressemble: "Paris", localisation: "zbanlieue" },
{ num: "33", voie: "all", adresse: "Jules Guesdes", bâtiment: "faculté de Médecine", quartier: "Jules Guesdes", "équivalent à Paris": "muséum", ressemble: "Paris", localisation: "centre" },
{ num: "0", voie: "place", adresse: "Jeanne d'Arc", bâtiment: "statue Jeanne d'Arc", quartier: "Jeanne d'Arc", "équivalent à Paris": "statue Jeanne d'Arc Paris", ressemble: "Paris", localisation: "centre" }
];

export async function GET() {
  return NextResponse.json(establishments);
}
