// app/api/ecrivainsaude/route.ts

import { NextResponse } from 'next/server';

const ecrivains = [
  { "nom": "Louis Bousquet", "commune": "Armissan", "dates": null, "description": null },
  { "nom": "Gaston Bonheur", "commune": "Belvianes", "dates": "1913-1980", "description": "journaliste et romancier" },
  { "nom": "Leon de belvis", "commune": "Belvis", "dates": null, "description": null },
  { "nom": "Jean-Frédéric Sarda", "commune": "Blomac", "dates": null, "description": "romancier" },
  { "nom": "Jean Cau", "commune": "Bram", "dates": "1925-1993", "description": "écrivain, éditorialiste, journaliste, secrétaire de Jean Paul Sartre" },
  { "nom": "Loïs Alibert", "commune": "Bram", "dates": "1884-1959", "description": "linguiste occitan" },
  { "nom": "Achille Astre", "commune": "Carcassonne", "dates": null, "description": "Critique d'art" },
  { "nom": "Albert Sarraut", "commune": "Carcassonne", "dates": null, "description": "essayiste, critique d'art" },
  { "nom": "Alphonse Alègre de Lasoujeole", "commune": "Carcassonne", "dates": null, "description": "essayiste" },
  { "nom": "Denis Amiel", "commune": "Carcassonne", "dates": null, "description": "auteur dramatique" },
  { "nom": "Fortunat Strowski", "commune": "Carcassonne", "dates": null, "description": "Prof. De lettres, essayiste, critique littéraire et dramatique" },
  { "nom": "François Brousse", "commune": "Carcassonne", "dates": null, "description": "poète" },
  { "nom": "Georges Soum", "commune": "Carcassonne", "dates": null, "description": "Publiciste, essayiste" },
  { "nom": "Jean Amiel", "commune": "Carcassonne", "dates": null, "description": "essayiste, historien local" },
  { "nom": "Jean Azais", "commune": "Carcassonne", "dates": null, "description": "Poète, écrivain" },
  { "nom": "Julien Astruc", "commune": "Carcassonne", "dates": null, "description": "Curé de st Vincent" },
  { "nom": "Osmin Nogue", "commune": "Carcassonne", "dates": null, "description": "poète, chansonnier, avocat" },
  { "nom": "Pierre et Maria Sire", "commune": "Carcassonne", "dates": null, "description": "romanciers" },
  { "nom": "Pierre Malacamp", "commune": "Carcassonne", "dates": null, "description": "poète" },
  { "nom": "Pierre Valmigère", "commune": "Carcassonne", "dates": null, "description": "romancier, essayiste, auteur dramatique" },
  { "nom": "Prosper Montagné", "commune": "Carcassonne", "dates": "1865-1948", "description": "chef cuisinier, auteur de nombreux ouvrages sur la gastronomie" },
  { "nom": "René Nelli", "commune": "Carcassonne", "dates": null, "description": "poète, essayiste, romaniste" },
  { "nom": "Jacques Vergues", "commune": "Castelnau d'Aude", "dates": null, "description": "Ecrivain, spécialiste des questions agricoles" },
  { "nom": "Auguste Foures", "commune": "Castelnaudary", "dates": "1848-1891", "description": "Ecrivain" },
  { "nom": "Xavier Riviere-Cros", "commune": "Castelnaudary", "dates": "1849-1926", "description": null },
  { "nom": "Roger Peyrefitte", "commune": "Castres", "dates": "1907-2000", "description": "écrivain" },
  { "nom": "Déodat Roche", "commune": "d'Arques", "dates": null, "description": "essayiste, théosophe" },
  { "nom": "Mlle A.Daguet", "commune": "Douzens", "dates": null, "description": "poète" },
  { "nom": "Achille Mir", "commune": "Escales", "dates": "1822-1901", "description": "Ecrivain" },
  { "nom": "Charles Cros", "commune": "Fabrezan", "dates": "1842-1888", "description": "poète et scientifique, il est à l'origine du procédé de la photographie couleur et du phonographe" },
  { "nom": "Prosper Estieu", "commune": "Fendeille", "dates": "né en 1860", "description": "Ecrivain" },
  { "nom": "Gaston Bonheur", "commune": "Flourès", "dates": null, "description": null },
  { "nom": "Albert Maissonnier", "commune": "Grèzes", "dates": null, "description": "poète" },
  { "nom": "François-Paul Alibert", "commune": "Grèzes", "dates": null, "description": "poète, critique, essaiste, auteur dramatique, prosateur" },
  { "nom": "Henri de Monfreid", "commune": "La Franqui", "dates": null, "description": "romancier d'aventures" },
  { "nom": "Henry de Monfreid", "commune": "La Franqui", "dates": "1879-1974", "description": "aventurier et écrivain" },
  { "nom": "Guilhem de Nauroza", "commune": "Labastide d'Anjou", "dates": null, "description": "Poète" },
  { "nom": "Léon Soulié", "commune": "Lagrasse", "dates": null, "description": "Poète" },
  { "nom": "Dr Charles Pelissier", "commune": "Lapalme", "dates": null, "description": null },
  { "nom": "Jan-Pierre (Joseph Anglade)", "commune": "Lézignan-Corbières", "dates": null, "description": null },
  { "nom": "Joseph Anglade", "commune": "Lézignan-Corbières", "dates": null, "description": null },
  { "nom": "Joseph Euzet", "commune": "Lézignan-Corbières", "dates": null, "description": null },
  { "nom": "Henri Duclos", "commune": "Limoux", "dates": null, "description": "poète, romancier" },
  { "nom": "Jacques Cestre", "commune": "Limoux", "dates": null, "description": "poète" },
  { "nom": "Magali", "commune": "Limoux", "dates": null, "description": "romancière" },
  { "nom": "Marcel Barrière", "commune": "Limoux", "dates": null, "description": "Romancier, essayiste" },
  { "nom": "Paul Gourdou", "commune": "Limoux", "dates": "1846-1937", "description": null },
  { "nom": "Jean Girou", "commune": "Montpellier", "dates": null, "description": "essayiste, critique d'art" },
  { "nom": "Francis la Tour", "commune": "Montréal", "dates": null, "description": "romancier" },
  { "nom": "Louis Alibert", "commune": "Montréal de l'A.", "dates": null, "description": null },
  { "nom": "Henri Bataille", "commune": "Moux", "dates": null, "description": null },
  { "nom": "Jean Lebrau", "commune": "Moux", "dates": null, "description": "poète, écrivain" },
  { "nom": "Benjamin Crémieux", "commune": "Narbonne", "dates": "1888-1944", "description": "écrivain, docteur ès lettres, mort en déportation à Buchenwald" },
  { "nom": "Bichambis", "commune": "Narbonne", "dates": null, "description": "essayiste, historien local" },
  { "nom": "Charles Trenet", "commune": "Narbonne", "dates": "1913-2001", "description": "chanteur et poète" },
  { "nom": "Dr. Duplessis de Pouzilhac", "commune": "Narbonne", "dates": null, "description": "directeur littéraire et artistique de \"Septimanie\"" },
  { "nom": "Georges Romieu", "commune": "Narbonne", "dates": null, "description": "romancier" },
  { "nom": "Joê Bousquet", "commune": "Narbonne", "dates": "1897-1950", "description": "poète et écrivain surréaliste" },
  { "nom": "Louis Arraou", "commune": "Narbonne", "dates": null, "description": "Romancier" },
  { "nom": "Luc Alberny", "commune": "Narbonne", "dates": null, "description": "romancier" },
  { "nom": "Marguerite Sol", "commune": "Narbonne", "dates": "1867", "description": null },
  { "nom": "Paul Raynal", "commune": "Narbonne", "dates": null, "description": "auteur dramatique" },
  { "nom": "Pierre Reverdy", "commune": "Narbonne", "dates": "1889-1960", "description": "écrivain précurseur du surréalisme" },
  { "nom": "Publius Terentius Varro Atacinus (Varron)", "commune": "Narbonne", "dates": "82-37 av J.C", "description": "poète épique romain" },
  { "nom": "Suzanne Lainé", "commune": "Narbonne", "dates": null, "description": "poète lyrique sacré" },
  { "nom": "Adam Peyrusse", "commune": "Ornaisons", "dates": null, "description": null },
  { "nom": "François Bousgarbies", "commune": "Pamiers", "dates": null, "description": "poète" },
  { "nom": "E.Mourgues", "commune": "Paulhan", "dates": null, "description": "poète" },
  { "nom": "Ernest Vieu", "commune": "Puichérie", "dates": null, "description": null },
  { "nom": "Casimir Clotos", "commune": "Raissac sur Lampy", "dates": null, "description": null },
  { "nom": "Jean l'Atacien", "commune": "Ribaute", "dates": null, "description": "journaliste, écrivain, poète, musicien, inventeur" },
  { "nom": "Abat Jozèp Salvat", "commune": "Rivel", "dates": null, "description": null },
  { "nom": "Maffre", "commune": "Rouffiac d'Aude", "dates": null, "description": null },
  { "nom": "Michel Maurette", "commune": "Serralongue", "dates": null, "description": "écrivain, conteur" },
  { "nom": "Jean Mistler", "commune": "Sorèze", "dates": null, "description": "romancier, historien, essayiste" },
  { "nom": "Paul Albarel", "commune": "St André de Roqu", "dates": "1873-1929", "description": "Ecrivain" },
  { "nom": "Paul Rives", "commune": "St-Papoul", "dates": null, "description": "essayiste, philosophe" },
  { "nom": "Gaston Icart", "commune": "Toulouse", "dates": null, "description": "poète" },
  { "nom": "Paul Sentenac", "commune": "Toulouse", "dates": null, "description": "poète, romancier, essayiste, critique d'art" },
  { "nom": "Joseph Delteil", "commune": "Villar-en-Val", "dates": "1889-1960", "description": "écrivain" },
  { "nom": "Rodolphe Darzens", "commune": "Villedubert-Carc", "dates": null, "description": "poète, auteur, essayiste" },
  { "nom": "Auguste Amiel-Lapeyre", "commune": "Villegailhenc", "dates": null, "description": "écrivain" }
];

export async function GET() {
  return NextResponse.json(ecrivains);
}
