import { NextResponse } from 'next/server';

// Liste exportée pour l'importation directe dans page.tsx (résoud l'erreur ECONNREFUSED)
export interface Ecrivain {
  nom: string;
  commune: string;
  dates?: string;
  description?: string;
}

export const ecrivainsData: Ecrivain[] = [
{ "nom": "Louis Bousquet", "commune": "Armissan, Aude", "dates": null, "description": null, "lat": 43.1865, "lng": 3.0958 },
  { "nom": "Gaston Bonheur", "commune": "Belvianes, Aude", "dates": "1913-1980", "description": "journaliste et romancier", "lat": 42.8512, "lng": 2.2001 },
  { "nom": "Leon de belvis", "commune": "Belvis, Aude", "dates": null, "description": null, "lat": 42.8495, "lng": 2.0766 },
  { "nom": "Jean-Frédéric Sarda", "commune": "Blomac, Aude", "dates": null, "description": "romancier", "lat": 43.2048, "lng": 2.5969 },
  { "nom": "Jean Cau", "commune": "Bram, Aude", "dates": "1925-1993", "description": "écrivain, éditorialiste, journaliste, secrétaire de Jean Paul Sartre", "lat": 43.2443, "lng": 2.1151 },
  { "nom": "Loïs Alibert", "commune": "Bram, Aude", "dates": "1884-1959", "description": "linguiste occitan", "lat": 43.2443, "lng": 2.1151 },
  { "nom": "Achille Astre", "commune": "Carcassonne, Aude", "dates": null, "description": "Critique d'art", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Albert Sarraut", "commune": "Carcassonne, Aude", "dates": null, "description": "essayiste, critique d'art", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Alphonse Alègre de Lasoujeole", "commune": "Carcassonne, Aude", "dates": null, "description": "essayiste", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Denis Amiel", "commune": "Carcassonne, Aude", "dates": null, "description": "auteur dramatique", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Fortunat Strowski", "commune": "Carcassonne, Aude", "dates": null, "description": "Prof. De lettres, essayiste, critique littéraire et dramatique", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "François Brousse", "commune": "Carcassonne, Aude", "dates": null, "description": "poète", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Georges Soum", "commune": "Carcassonne, Aude", "dates": null, "description": "Publiciste, essayiste", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Jean Amiel", "commune": "Carcassonne, Aude", "dates": null, "description": "essayiste, historien local", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Jean Azais", "commune": "Carcassonne, Aude", "dates": null, "description": "Poète, écrivain", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Julien Astruc", "commune": "Carcassonne, Aude", "dates": null, "description": "Curé de st Vincent", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Osmin Nogue", "commune": "Carcassonne, Aude", "dates": null, "description": "poète, chansonnier, avocat", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Pierre et Maria Sire", "commune": "Carcassonne, Aude", "dates": null, "description": "romanciers", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Pierre Malacamp", "commune": "Carcassonne, Aude", "dates": null, "description": "poète", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Pierre Valmigère", "commune": "Carcassonne, Aude", "dates": null, "description": "romancier, essayiste, auteur dramatique", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Prosper Montagné", "commune": "Carcassonne, Aude", "dates": "1865-1948", "description": "chef cuisinier, auteur de nombreux ouvrages sur la gastronomie", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "René Nelli", "commune": "Carcassonne, Aude", "dates": null, "description": "poète, essayiste, romaniste", "lat": 43.2163, "lng": 2.3539 },
  { "nom": "Jacques Vergues", "commune": "Castelnau d'Aude, Aude", "dates": null, "description": "Ecrivain, spécialiste des questions agricoles", "lat": 43.2302, "lng": 2.6756 },
  { "nom": "Auguste Foures", "commune": "Castelnaudary, Aude", "dates": "1848-1891", "description": "Ecrivain", "lat": 43.3183, "lng": 1.9531 },
  { "nom": "Xavier Riviere-Cros", "commune": "Castelnaudary, Aude", "dates": "1849-1926", "description": null, "lat": 43.3183, "lng": 1.9531 },
  { "nom": "Roger Peyrefitte", "commune": "Castres, Tarn", "dates": "1907-2000", "description": "écrivain", "lat": 43.6069, "lng": 2.2411 },
  { "nom": "Déodat Roche", "commune": "Arques, Aude", "dates": null, "description": "essayiste, théosophe", "lat": 42.9533, "lng": 2.3756 },
  { "nom": "Mlle A.Daguet", "commune": "Douzens, Aude", "dates": null, "description": "poète", "lat": 43.1873, "lng": 2.5986 },
  { "nom": "Achille Mir", "commune": "Escales, Aude", "dates": "1822-1901", "description": "Ecrivain", "lat": 43.2233, "lng": 2.6953 },
  { "nom": "Charles Cros", "commune": "Fabrezan, Aude", "dates": "1842-1888", "description": "poète et scientifique, à l'origine du procédé de la photographie couleur et du phonographe", "lat": 43.1360, "lng": 2.6974 },
  { "nom": "Prosper Estieu", "commune": "Fendeille, Aude", "dates": "né en 1860", "description": "Ecrivain", "lat": 43.2694, "lng": 1.9392 },
  { "nom": "Gaston Bonheur", "commune": "Flourès, Aude", "dates": null, "description": null, "lat": 43.1833, "lng": 2.4833 },
  { "nom": "Albert Maissonnier", "commune": "Grèzes, Aude", "dates": null, "description": "poète", "lat": 43.2044, "lng": 2.2982 },
  { "nom": "François-Paul Alibert", "commune": "Grèzes, Aude", "dates": null, "description": "poète, critique, essaiste, auteur dramatique, prosateur", "lat": 43.2044, "lng": 2.2982 },
  { "nom": "Henri de Monfreid", "commune": "La Franqui, Aude", "dates": null, "description": "romancier d'aventures", "lat": 42.9261, "lng": 3.0361 },
  { "nom": "Henry de Monfreid", "commune": "La Franqui, Aude", "dates": "1879-1974", "description": "aventurier et écrivain", "lat": 42.9261, "lng": 3.0361 },
  { "nom": "Guilhem de Nauroza", "commune": "Labastide d'Anjou, Aude", "dates": null, "description": "Poète", "lat": 43.3464, "lng": 1.8519 },
  { "nom": "Léon Soulié", "commune": "Lagrasse, Aude", "dates": null, "description": "Poète", "lat": 43.0906, "lng": 2.6192 },
  { "nom": "Dr Charles Pelissier", "commune": "Lapalme, Aude", "dates": null, "description": null, "lat": 42.9748, "lng": 2.9934 },
  { "nom": "Jan-Pierre (Joseph Anglade)", "commune": "Lézignan-Corbières, Aude", "dates": null, "description": null, "lat": 43.2003, "lng": 2.7586 },
  { "nom": "Joseph Anglade", "commune": "Lézignan-Corbières, Aude", "dates": null, "description": null, "lat": 43.2003, "lng": 2.7586 },
  { "nom": "Joseph Euzet", "commune": "Lézignan-Corbières, Aude", "dates": null, "description": null, "lat": 43.2003, "lng": 2.7586 },
  { "nom": "Henri Duclos", "commune": "Limoux, Aude", "dates": null, "description": "poète, romancier", "lat": 43.0539, "lng": 2.2178 },
  { "nom": "Jacques Cestre", "commune": "Limoux, Aude", "dates": null, "description": "poète", "lat": 43.0539, "lng": 2.2178 },
  { "nom": "Magali", "commune": "Limoux, Aude", "dates": null, "description": "romancière", "lat": 43.0539, "lng": 2.2178 },
  { "nom": "Marcel Barrière", "commune": "Limoux, Aude", "dates": null, "description": "Romancier, essayiste", "lat": 43.0539, "lng": 2.2178 },
  { "nom": "Paul Gourdou", "commune": "Limoux, Aude", "dates": "1846-1937", "description": null, "lat": 43.0539, "lng": 2.2178 },
  { "nom": "Jean Girou", "commune": "Montpellier, Hérault", "dates": null, "description": "essayiste, critique d'art", "lat": 43.6107, "lng": 3.8767 },
  { "nom": "Francis la Tour", "commune": "Montréal, Aude", "dates": null, "description": "romancier", "lat": 43.2003, "lng": 2.1408 },
  { "nom": "Louis Alibert", "commune": "Montréal de l'A., Aude", "dates": null, "description": null, "lat": 43.2003, "lng": 2.1408 },
  { "nom": "Henri Bataille", "commune": "Moux, Aude", "dates": null, "description": null, "lat": 43.1814, "lng": 2.6517 },
  { "nom": "Jean Lebrau", "commune": "Moux, Aude", "dates": null, "description": "poète, écrivain", "lat": 43.1814, "lng": 2.6517 },
  { "nom": "Benjamin Crémieux", "commune": "Narbonne, Aude", "dates": "1888-1944", "description": "écrivain, docteur ès lettres, mort en déportation à Buchenwald", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Bichambis", "commune": "Narbonne, Aude", "dates": null, "description": "essayiste, historien local", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Charles Trenet", "commune": "Narbonne, Aude", "dates": "1913-2001", "description": "chanteur et poète", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Dr. Duplessis de Pouzilhac", "commune": "Narbonne, Aude", "dates": null, "description": "directeur littéraire et artistique de \"Septimanie\"", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Georges Romieu", "commune": "Narbonne, Aude", "dates": null, "description": "romancier", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Joê Bousquet", "commune": "Narbonne, Aude", "dates": "1897-1950", "description": "poète et écrivain surréaliste", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Louis Arraou", "commune": "Narbonne, Aude", "dates": null, "description": "Romancier", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Luc Alberny", "commune": "Narbonne, Aude", "dates": null, "description": "romancier", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Marguerite Sol", "commune": "Narbonne, Aude", "dates": "1867", "description": null, "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Paul Raynal", "commune": "Narbonne, Aude", "dates": null, "description": "auteur dramatique", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Pierre Reverdy", "commune": "Narbonne, Aude", "dates": "1889-1960", "description": "écrivain précurseur du surréalisme", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Publius Terentius Varro Atacinus (Varron)", "commune": "Narbonne, Aude", "dates": "82-37 av J.C", "description": "poète épique romain", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Suzanne Lainé", "commune": "Narbonne, Aude", "dates": null, "description": "poète lyrique sacré", "lat": 43.1843, "lng": 3.0031 },
  { "nom": "Adam Peyrusse", "commune": "Ornaisons, Aude", "dates": null, "description": null, "lat": 43.1811, "lng": 2.8354 },
  { "nom": "François Bousgarbies", "commune": "Pamiers, Ariège", "dates": null, "description": "poète", "lat": 43.1167, "lng": 1.6112 },
  { "nom": "E.Mourgues", "commune": "Paulhan, Hérault", "dates": null, "description": "poète", "lat": 43.5411, "lng": 3.4593 },
  { "nom": "Ernest Vieu", "commune": "Puichérie, Aude", "dates": null, "description": null, "lat": 43.2667, "lng": 2.6167 },
  { "nom": "Casimir Clotos", "commune": "Raissac sur Lampy, Aude", "dates": null, "description": null, "lat": 43.2669, "lng": 2.1611 },
  { "nom": "Jean l'Atacien", "commune": "Ribaute, Aude", "dates": null, "description": "journaliste, écrivain, poète, musicien, inventeur", "lat": 43.1075, "lng": 2.6322 },
  { "nom": "Abat Jozèp Salvat", "commune": "Rivel, Aude", "dates": null, "description": null, "lat": 42.9292, "lng": 2.0006 },
  { "nom": "Maffre", "commune": "Rouffiac d'Aude, Aude", "dates": null, "description": null, "lat": 43.1286, "lng": 2.2981 },
  { "nom": "Michel Maurette", "commune": "Serralongue, Pyrénées-Orientales", "dates": null, "description": "écrivain, conteur", "lat": 42.3975, "lng": 2.5564 },
  { "nom": "Jean Mistler", "commune": "Sorèze, Tarn", "dates": null, "description": "romancier, historien, essayiste", "lat": 43.4528, "lng": 2.0667 },
  { "nom": "Paul Albarel", "commune": "St-André-de-Roquelongue, Aude", "dates": "1873-1929", "description": "Ecrivain", "lat": 43.1119, "lng": 2.8378 },
  { "nom": "Paul Rives", "commune": "St-Papoul, Aude", "dates": null, "description": "essayiste, philosophe", "lat": 43.3322, "lng": 2.0353 },
  { "nom": "Gaston Icart", "commune": "Toulouse, Haute-Garonne", "dates": null, "description": "poète", "lat": 43.6047, "lng": 1.4442 },
  { "nom": "Paul Sentenac", "commune": "Toulouse, Haute-Garonne", "dates": null, "description": "poète, romancier, essayiste, critique d'art", "lat": 43.6047, "lng": 1.4442 },
  { "nom": "Joseph Delteil", "commune": "Villar-en-Val, Aude", "dates": "1889-1960", "description": "écrivain", "lat": 43.0831, "lng": 2.4536 },
  { "nom": "Rodolphe Darzens", "commune": "Villedubert, Aude", "dates": null, "description": "poète, auteur, essayiste", "lat": 43.2311, "lng": 2.4158 },
  { "nom": "Auguste Amiel-Lapeyre", "commune": "Villegailhenc, Aude", "dates": null, "description": "écrivain", "lat": 43.2694, "lng": 2.3522 }
];

export async function GET() {
  return NextResponse.json(ecrivainsData);
}
