import { NextResponse } from 'next/server';

// Liste exportée pour l'importation directe dans page.tsx (résoud l'erreur ECONNREFUSED)
export interface Ecrivain {
  nom: string;
  commune: string;
  dates?: string;
  description?: string;
}

export const ecrivainsData: Ecrivain[] = [
  { "nom": "Louis Bousquet", "commune": "Armissan, Aude", "dates": null, "description": null },
  { "nom": "Gaston Bonheur", "commune": "Belvianes, Aude", "dates": "1913-1980", "description": "journaliste et romancier" },
  { "nom": "Leon de belvis", "commune": "Belvis, Aude", "dates": null, "description": null },
  { "nom": "Jean-Frédéric Sarda", "commune": "Blomac, Aude", "dates": null, "description": "romancier" },
  { "nom": "Jean Cau", "commune": "Bram, Aude", "dates": "1925-1993", "description": "écrivain, éditorialiste, journaliste, secrétaire de Jean Paul Sartre" },
  { "nom": "Loïs Alibert", "commune": "Bram, Aude", "dates": "1884-1959", "description": "linguiste occitan" },
  { "nom": "Achille Astre", "commune": "Carcassonne, Aude", "dates": null, "description": "Critique d'art" },
  { "nom": "Albert Sarraut", "commune": "Carcassonne, Aude", "dates": null, "description": "essayiste, critique d'art" },
  { "nom": "Alphonse Alègre de Lasoujeole", "commune": "Carcassonne, Aude", "dates": null, "description": "essayiste" },
  { "nom": "Denis Amiel", "commune": "Carcassonne, Aude", "dates": null, "description": "auteur dramatique" },
  { "nom": "Fortunat Strowski", "commune": "Carcassonne, Aude", "dates": null, "description": "Prof. De lettres, essayiste, critique littéraire et dramatique" },
  { "nom": "François Brousse", "commune": "Carcassonne, Aude", "dates": null, "description": "poète" },
  { "nom": "Georges Soum", "commune": "Carcassonne, Aude", "dates": null, "description": "Publiciste, essayiste" },
  { "nom": "Jean Amiel", "commune": "Carcassonne, Aude", "dates": null, "description": "essayiste, historien local" },
  { "nom": "Jean Azais", "commune": "Carcassonne, Aude", "dates": null, "description": "Poète, écrivain" },
  { "nom": "Julien Astruc", "commune": "Carcassonne, Aude", "dates": null, "description": "Curé de st Vincent" },
  { "nom": "Osmin Nogue", "commune": "Carcassonne, Aude", "dates": null, "description": "poète, chansonnier, avocat" },
  { "nom": "Pierre et Maria Sire", "commune": "Carcassonne, Aude", "dates": null, "description": "romanciers" },
  { "nom": "Pierre Malacamp", "commune": "Carcassonne, Aude", "dates": null, "description": "poète" },
  { "nom": "Pierre Valmigère", "commune": "Carcassonne, Aude", "dates": null, "description": "romancier, essayiste, auteur dramatique" },
  { "nom": "Prosper Montagné", "commune": "Carcassonne, Aude", "dates": "1865-1948", "description": "chef cuisinier, auteur de nombreux ouvrages sur la gastronomie" },
  { "nom": "René Nelli", "commune": "Carcassonne, Aude", "dates": null, "description": "poète, essayiste, romaniste" },
  { "nom": "Jacques Vergues", "commune": "Castelnau d'Aude, Aude", "dates": null, "description": "Ecrivain, spécialiste des questions agricoles" },
  { "nom": "Auguste Foures", "commune": "Castelnaudary, Aude", "dates": "1848-1891", "description": "Ecrivain" },
  { "nom": "Xavier Riviere-Cros", "commune": "Castelnaudary, Aude", "dates": "1849-1926", "description": null },
  { "nom": "Roger Peyrefitte", "commune": "Castres, Tarn", "dates": "1907-2000", "description": "écrivain" },
  { "nom": "Déodat Roche", "commune": "Arques, Aude", "dates": null, "description": "essayiste, théosophe" },
  { "nom": "Mlle A.Daguet", "commune": "Douzens, Aude", "dates": null, "description": "poète" },
  { "nom": "Achille Mir", "commune": "Escales, Aude", "dates": "1822-1901", "description": "Ecrivain" },
  { "nom": "Charles Cros", "commune": "Fabrezan, Aude", "dates": "1842-1888", "description": "poète et scientifique, à l'origine du procédé de la photographie couleur et du phonographe" },
  { "nom": "Prosper Estieu", "commune": "Fendeille, Aude", "dates": "né en 1860", "description": "Ecrivain" },
  { "nom": "Gaston Bonheur", "commune": "Flourès, Aude", "dates": null, "description": null },
  { "nom": "Albert Maissonnier", "commune": "Grèzes, Aude", "dates": null, "description": "poète" },
  { "nom": "François-Paul Alibert", "commune": "Grèzes, Aude", "dates": null, "description": "poète, critique, essaiste, auteur dramatique, prosateur" },
  { "nom": "Henri de Monfreid", "commune": "La Franqui, Aude", "dates": null, "description": "romancier d'aventures" },
  { "nom": "Henry de Monfreid", "commune": "La Franqui, Aude", "dates": "1879-1974", "description": "aventurier et écrivain" },
  { "nom": "Guilhem de Nauroza", "commune": "Labastide d'Anjou, Aude", "dates": null, "description": "Poète" },
  { "nom": "Léon Soulié", "commune": "Lagrasse, Aude", "dates": null, "description": "Poète" },
  { "nom": "Dr Charles Pelissier", "commune": "Lapalme, Aude", "dates": null, "description": null },
  { "nom": "Jan-Pierre (Joseph Anglade)", "commune": "Lézignan-Corbières, Aude", "dates": null, "description": null },
  { "nom": "Joseph Anglade", "commune": "Lézignan-Corbières, Aude", "dates": null, "description": null },
  { "nom": "Joseph Euzet", "commune": "Lézignan-Corbières, Aude", "dates": null, "description": null },
  { "nom": "Henri Duclos", "commune": "Limoux, Aude", "dates": null, "description": "poète, romancier" },
  { "nom": "Jacques Cestre", "commune": "Limoux, Aude", "dates": null, "description": "poète" },
  { "nom": "Magali", "commune": "Limoux, Aude", "dates": null, "description": "romancière" },
  { "nom": "Marcel Barrière", "commune": "Limoux, Aude", "dates": null, "description": "Romancier, essayiste" },
  { "nom": "Paul Gourdou", "commune": "Limoux, Aude", "dates": "1846-1937", "description": null },
  { "nom": "Jean Girou", "commune": "Montpellier, Hérault", "dates": null, "description": "essayiste, critique d'art" },
  { "nom": "Francis la Tour", "commune": "Montréal, Aude", "dates": null, "description": "romancier" },
  { "nom": "Louis Alibert", "commune": "Montréal de l'A., Aude", "dates": null, "description": null },
  { "nom": "Henri Bataille", "commune": "Moux, Aude", "dates": null, "description": null },
  { "nom": "Jean Lebrau", "commune": "Moux, Aude", "dates": null, "description": "poète, écrivain" },
  { "nom": "Benjamin Crémieux", "commune": "Narbonne, Aude", "dates": "1888-1944", "description": "écrivain, docteur ès lettres, mort en déportation à Buchenwald" },
  { "nom": "Bichambis", "commune": "Narbonne, Aude", "dates": null, "description": "essayiste, historien local" },
  { "nom": "Charles Trenet", "commune": "Narbonne, Aude", "dates": "1913-2001", "description": "chanteur et poète" },
  { "nom": "Dr. Duplessis de Pouzilhac", "commune": "Narbonne, Aude", "dates": null, "description": "directeur littéraire et artistique de \"Septimanie\"" },
  { "nom": "Georges Romieu", "commune": "Narbonne, Aude", "dates": null, "description": "romancier" },
  { "nom": "Joê Bousquet", "commune": "Narbonne, Aude", "dates": "1897-1950", "description": "poète et écrivain surréaliste" },
  { "nom": "Louis Arraou", "commune": "Narbonne, Aude", "dates": null, "description": "Romancier" },
  { "nom": "Luc Alberny", "commune": "Narbonne, Aude", "dates": null, "description": "romancier" },
  { "nom": "Marguerite Sol", "commune": "Narbonne, Aude", "dates": "1867", "description": null },
  { "nom": "Paul Raynal", "commune": "Narbonne, Aude", "dates": null, "description": "auteur dramatique" },
  { "nom": "Pierre Reverdy", "commune": "Narbonne, Aude", "dates": "1889-1960", "description": "écrivain précurseur du surréalisme" },
  { "nom": "Publius Terentius Varro Atacinus (Varron)", "commune": "Narbonne, Aude", "dates": "82-37 av J.C", "description": "poète épique romain" },
  { "nom": "Suzanne Lainé", "commune": "Narbonne, Aude", "dates": null, "description": "poète lyrique sacré" },
  { "nom": "Adam Peyrusse", "commune": "Ornaisons, Aude", "dates": null, "description": null },
  { "nom": "François Bousgarbies", "commune": "Pamiers, Ariège", "dates": null, "description": "poète" },
  { "nom": "E.Mourgues", "commune": "Paulhan, Hérault", "dates": null, "description": "poète" },
  { "nom": "Ernest Vieu", "commune": "Puichérie, Aude", "dates": null, "description": null },
  { "nom": "Casimir Clotos", "commune": "Raissac sur Lampy, Aude", "dates": null, "description": null },
  { "nom": "Jean l'Atacien", "commune": "Ribaute, Aude", "dates": null, "description": "journaliste, écrivain, poète, musicien, inventeur" },
  { "nom": "Abat Jozèp Salvat", "commune": "Rivel, Aude", "dates": null, "description": null },
  { "nom": "Maffre", "commune": "Rouffiac d'Aude, Aude", "dates": null, "description": null },
  { "nom": "Michel Maurette", "commune": "Serralongue, Pyrénées-Orientales", "dates": null, "description": "écrivain, conteur" },
  { "nom": "Jean Mistler", "commune": "Sorèze, Tarn", "dates": null, "description": "romancier, historien, essayiste" },
  { "nom": "Paul Albarel", "commune": "St-André-de-Roquelongue, Aude", "dates": "1873-1929", "description": "Ecrivain" },
  { "nom": "Paul Rives", "commune": "St-Papoul, Aude", "dates": null, "description": "essayiste, philosophe" },
  { "nom": "Gaston Icart", "commune": "Toulouse, Haute-Garonne", "dates": null, "description": "poète" },
  { "nom": "Paul Sentenac", "commune": "Toulouse, Haute-Garonne", "dates": null, "description": "poète, romancier, essayiste, critique d'art" },
  { "nom": "Joseph Delteil", "commune": "Villar-en-Val, Aude", "dates": "1889-1960", "description": "écrivain" },
  { "nom": "Rodolphe Darzens", "commune": "Villedubert, Aude", "dates": null, "description": "poète, auteur, essayiste" },
  { "nom": "Auguste Amiel-Lapeyre", "commune": "Villegailhenc, Aude", "dates": null, "description": "écrivain" }
];

export async function GET() {
  return NextResponse.json(ecrivainsData);
}
