// src/app/api/visitemonument/route.ts
import { NextResponse } from "next/server";

const data = [
  { nom: 'Bordeblanche', numero: 0, voie: 'quartier', rue: 'Bordeblanche', type: 'borde', note: 'verif' },
  { nom: 'Bordelongue', numero: 0, voie: 'quartier', rue: 'Bordelongue', type: 'borde', note: 'verif' },
  { nom: 'Borderouge', numero: 0, voie: 'quartier', rue: 'Borderouge', type: 'borde', note: '' },
  { nom: 'caserne Compans et Cafarelli', numero: '', voie: 'esp', rue: 'Compans', type: 'caserne', note: '' },
  { nom: 'caserne Dupuy', numero: 32, voie: 'rue', rue: 'Dalbade', type: 'caserne', note: '' },
  { nom: 'caserne de la Mission', numero: 17, voie: 'place', rue: 'Daurade', type: 'caserne', note: '' },
  { nom: 'caserne Saint-Charles', numero: 8, voie: 'rue', rue: 'Merly', type: 'caserne', note: '' },
  { nom: 'palais Niel', numero: '', voie: 'rue', rue: 'Montoulieu St-Jqes', type: 'caserne', note: '' },
  { nom: 'caserne Pérignon', numero: 2, voie: 'rue', rue: 'Pérignon', type: 'caserne', note: '' },
  { nom: 'monument aux morts', numero: 2, voie: 'rue', rue: 'Pérignon', type: 'caserne', note: 'Pérignon' },
  { nom: 'caserne Lignières', numero: 24, voie: 'rue', rue: 'Riquet', type: 'caserne', note: '' },
  { nom: 'caserne Niel', numero: 81, voie: 'rue', rue: 'Saint-Roch', type: 'caserne', note: '' },
  { nom: 'caserne Robert', numero: 1, voie: 'rue', rue: 'Salenques', type: 'caserne', note: '' },
  { nom: 'ancienne caserne Carmélites', numero: 56, voie: 'rue', rue: 'Taur', type: 'caserne', note: '' },
  { nom: 'Croix-Daurade', numero: 147, voie: 'rte', rue: 'Albi', type: 'château', note: 'mairie' },
  { nom: 'Ozenne', numero: 147, voie: 'rte', rue: 'Albi', type: 'château', note: 'mairie' },
  { "nom": "Sage", "numero": 13, "voie": "rue", "rue": "Antoine Bayes", "type": "château", "note": "adolescents" },
  { "nom": "Le Mirail", "numero": 5, "voie": "allées", "rue": "Antonio Machado", "type": "château", "note": "université" },
  { "nom": "Bagatelle", "numero": 13, "voie": "imp", "rue": "Bachaga Boualam", "type": "château", "note": "disparu" },
  { "nom": "la Barigoude", "numero": 24, "voie": "chem", "rue": "Barigoude", "type": "château", "note": "résidence" },
  { "nom": "Bellefontaine", "numero": 64, "voie": "allées", "rue": "Bellefontaine", "type": "château", "note": "escalier" },
  { "nom": "Bellefontaine", "numero": 64, "voie": "allées", "rue": "Bellefontaine", "type": "château", "note": "pigeonnier" },
  { "nom": "palais des rois Wisigoths", "numero": 0, "voie": "place", "rue": "Bologne", "type": "château", "note": "" },
  { "nom": "Bourrasol", "numero": 0, "voie": "place", "rue": "Bourrasol", "type": "château", "note": "disparu" },
  { "nom": "Busca", "numero": 0, "voie": "place", "rue": "Busca", "type": "château", "note": "disparu" },
  { "nom": "Griffoulet", "numero": 23, "voie": "chem", "rue": "Capelles", "type": "château", "note": "disparu" },
  { "nom": "Marmande", "numero": 71, "voie": "chem", "rue": "Capelles", "type": "château", "note": "école" },
  { "nom": "Casselardit", "numero": 92, "voie": "avenue", "rue": "Casselardit", "type": "château", "note": "Ehpad" },
  { "nom": "Ancely", "numero": 224, "voie": "avenue", "rue": "Casselardit", "type": "château", "note": "dépendances" },
  { "nom": "L'Hers", "numero": 21, "voie": "rue", "rue": "Claudius Rougenet", "type": "château", "note": "pigeonnier" },
  { "nom": "la Flambelle", "numero": 29, "voie": "rue", "rue": "de Ventadour", "type": "château", "note": "abandonné" },
  { "nom": "Lespinet-Ramel", "numero": 1, "voie": "avenue", "rue": "Edourard Belin", "type": "château", "note": "CREPS" },
  { "nom": "Gounon", "numero": 1, "voie": "rte", "rue": "Espagne", "type": "château", "note": "résidence" },
  { "nom": "Fondeyre", "numero": 185, "voie": "avenue", "rue": "États-Unis", "type": "château", "note": "parc" },
  { "nom": "Lalanne", "numero": 0, "voie": "allées", "rue": "Foulques", "type": "château", "note": "château" },
  { "nom": "Sesquières", "numero": 0, "voie": "allées", "rue": "Foulques", "type": "château", "note": "" },
  { "nom": "Paléficat", "numero": 23, "voie": "rue", "rue": "Frédéric Chopin", "type": "château", "note": "Virebent" },
  { "nom": "Gramont", "numero": 107, "voie": "chem", "rue": "Gabardie", "type": "château", "note": "résidence" },
  { "nom": "Comigères", "numero": 6, "voie": "rue", "rue": "Général Giraud", "type": "château", "note": "château" },
  { "nom": "Leblanc", "numero": 4, "voie": "chem", "rue": "Glacière", "type": "château", "note": "Emmaüs" },
  { "nom": "Les Verrrières", "numero": 8, "voie": "rue", "rue": "Godolin", "type": "château", "note": "résidence" },
  { "nom": "Grandselve", "numero": 37, "voie": "allées", "rue": "Grand-Selve", "type": "château", "note": "résidence" },
  { "nom": "Guilhermy", "numero": 0, "voie": "imp", "rue": "Guilhermy", "type": "château", "note": "résidence" },
  { "nom": "Lespinet-Raynal", "numero": 6, "voie": "rue", "rue": "Jacqueline Auriol", "type": "château", "note": "musée" },
  { "nom": "Fontaine-Lestang", "numero": 8, "voie": "rue", "rue": "Jacques Gamelin", "type": "château", "note": "pont" },
  { "nom": "Aïgua", "numero": 158, "voie": "avenue", "rue": "Jean Chaubet", "type": "château", "note": "disparu" },
  { "nom": "Madron", "numero": 1, "voie": "allées", "rue": "Jean Griffon", "type": "château", "note": "Ehpad" },
  { "nom": "Saint-Raymond Sacarin", "numero": 18, "voie": "rue", "rue": "Jean Micoud", "type": "château", "note": "parc" },
  { "nom": "Narbonais", "numero": 2, "voie": "allées", "rue": "Jules Guesde", "type": "château", "note": "disparu" },
  { "nom": "Lanusse", "numero": 102, "voie": "chem", "rue": "Lanusse", "type": "château", "note": "résidence" },
  { "nom": "Lapujade", "numero": 129, "voie": "chem", "rue": "Lapujade", "type": "château", "note": "résidence" },
  { "nomLieu": "Petit Capitole", "num": 153, "typeRue": "avenue", "nomRue": "Lardenne", "quartier": "", "établissement": "château", "commentaire": "colonie" },
  { "nom": "Corail", "numero": 425, "voie": "rte", "rue": "Launaguet", "type": "château", "note": "disparu" },
  { "nom": "Le Calquet", "numero": 100, "voie": "chem", "rue": "le Goff", "type": "château", "note": "cadastres" },
  { "nom": "Monlon", "numero": 25, "voie": "chem", "rue": "Lestang", "type": "château", "note": "pépinière" },
  { "nom": "Reynerie", "numero": 160, "voie": "chem", "rue": "Lestang", "type": "château", "note": "municipal" },
  { "nom": "Saint-Michel du Touch", "numero": 19, "voie": "allées", "rue": "Limagne", "type": "château", "note": "ruines" },
  { "nom": "palais Saint-Michel du Touch", "numero": 19, "voie": "allées", "rue": "Limagne", "type": "château", "note": "" },
  { "nom": "Limayrac", "numero": 50, "voie": "rue", "rue": "Limayrac", "type": "château", "note": "lycée" },
  { "nom": "Clerfont", "numero": 2, "voie": "rue", "rue": "Lizop", "type": "château", "note": "résidence" },
  { "nom": "Tabard", "numero": 1, "voie": "imp", "rue": "Londres", "type": "château", "note": "mosquée" },
  { "nom": "Lespinet-Lasvignes", "numero": 3, "voie": "allées", "rue": "Lucien Lafay", "type": "château", "note": "CRS" },
  { "nom": "Desazars", "numero": 3, "voie": "chem", "rue": "Maraîchers", "type": "château", "note": "puits" },
  { "nom": "Chantelle", "numero": 6, "voie": "imp", "rue": "Marie Laurencin", "type": "château", "note": "disparu" },
  { "nom": "Larade", "numero": 35, "voie": "rue", "rue": "Mathaly", "type": "château", "note": "école" },
  { "nom": "château du Balufet", "numero": 0, "voie": "rue", "rue": "Maubec", "type": "château", "note": "" },
  { "nom": "Comminges", "numero": 0, "voie": "rd pt", "rue": "Maurice Hauriou", "type": "château", "note": "disparu" },
  { "nom": "Mazades", "numero": 18, "voie": "avenue", "rue": "Mazades", "type": "château", "note": "disparu" },
  { "nom": "Bellevue", "numero": 135, "voie": "rte", "rue": "Narbonne", "type": "château", "note": "lycée" },
  { "nom": "Nicol", "numero": 98, "voie": "chem", "rue": "Nicol", "type": "château", "note": "disparu" },
  { "nom": "Braqueville", "numero": 0, "voie": "imp", "rue": "Palayre", "type": "château", "note": "façade" },
  { "nom": "Palays", "numero": 1, "voie": "chem", "rue": "Palays", "type": "château", "note": "institut" },
  { "nom": "château Papus", "numero": 1, "voie": "chem", "rue": "Papus", "type": "château", "note": "" },
  { "nom": "Caumont", "numero": 5, "voie": "avenue", "rue": "Parc", "type": "château", "note": "disparu" },
  { "nom": "Lansac", "numero": 4, "voie": "rue", "rue": "Paul Farrando", "type": "château", "note": "château" },
  { "nom": "La Mounède", "numero": 1, "voie": "rue", "rue": "Perroud", "type": "château", "note": "spectacle" },
  { "nom": "La Cépière", "numero": 5, "voie": "chem", "rue": "Pigeonnier Cépière", "type": "château", "note": "résidence" },
  { "nom": "Montredon", "numero": 0, "voie": "imp", "rue": "Pyrénées", "type": "château", "note": "château" },
  { "nom": "Rangueil", "numero": 68, "voie": "avenue", "rue": "Rangueil", "type": "château", "note": "disparu" },
  { "nom": "Bazacle", "numero": 11, "voie": "quai", "rue": "Saint-Pierre", "type": "château", "note": "disparu" },
  { "nom": "Les Ormes", "numero": 128, "voie": "rte", "rue": "Saint-Simon", "type": "château", "note": "institut" },
  { "nom": "Candie", "numero": 17, "voie": "chem", "rue": "Saudrune", "type": "château", "note": "coopérative" },
  { "nom": "Cazal Lapujade", "numero": 5, "voie": "rue", "rue": "Simone Boudet", "type": "château", "note": "résidence" },
  { "nom": "Petit Gragnague", "numero": 9, "voie": "rue", "rue": "Sports", "type": "château", "note": "école" },
  { "nom": "Teynier", "numero": 1, "voie": "imp", "rue": "Teynier", "type": "château", "note": "usine" },
  { "nom": "Purpan", "numero": 75, "voie": "voir", "rue": "TOEC", "type": "château", "note": "école" },
  { "nom": "Petit Niquet", "numero": 49, "voie": "chem", "rue": "Vallon", "type": "château", "note": "résidence" },
  { "nom": "château des Potiers", "numero": 14, "voie": "rue", "rue": "Vases", "type": "château", "note": "école" },
  { "nom": "Doujat", "numero": 35, "voie": "rue", "rue": "Velasquez", "type": "château", "note": "résidence" }
];

export function GET() {
  return NextResponse.json(data);
}
