// src/app/api/visitemonument/route.ts
import { NextResponse } from "next/server";

const data = [
  { nom: 'Bordeblanche', numero: 0, voie: 'quartier', rue: 'Bordeblanche', type: 'borde', note: 'verif' },
  { nom: 'Bordelongue', numero: 0, voie: 'quartier', rue: 'Bordelongue', type: 'borde', note: 'verif' },
  { nom: 'Borderouge', numero: 0, voie: 'quartier', rue: 'Borderouge', type: 'borde', note: '' },
  { nom: 'caserne Compans et Cafarelli', numero: '', voie: 'esp', rue: 'Compans', type: 'caserne', note: '' },
  { nom: 'caserne Dupuy', numero: 32, voie: 'rue', rue: 'Dalbade', type: 'caserne', note: '' },
  { nom: 'caserne de la Mission', numero: 17, voie: 'place', rue: 'Daurade', type: 'caserne', note: '' },
  { nom: 'caserne Saint-Charles', numero: 8, voie: 'rue', rue: 'Merly', type: 'caserne', note: '' },
  { nom: 'palais Niel', numero: '', voie: 'rue', rue: 'Montoulieu St-Jqes', type: 'caserne', note: '' },
  { nom: 'caserne Pérignon', numero: 2, voie: 'rue', rue: 'Pérignon', type: 'caserne', note: '' },
  { nom: 'monument aux morts', numero: 2, voie: 'rue', rue: 'Pérignon', type: 'caserne', note: 'Pérignon' },
  { nom: 'caserne Lignières', numero: 24, voie: 'rue', rue: 'Riquet', type: 'caserne', note: '' },
  { nom: 'caserne Niel', numero: 81, voie: 'rue', rue: 'Saint-Roch', type: 'caserne', note: '' },
  { nom: 'caserne Robert', numero: 1, voie: 'rue', rue: 'Salenques', type: 'caserne', note: '' },
  { nom: 'ancienne caserne Carmélites', numero: 56, voie: 'rue', rue: 'Taur', type: 'caserne', note: '' },
  { nom: 'Croix-Daurade', numero: 147, voie: 'rte', rue: 'Albi', type: 'château', note: 'mairie' },
  { nom: 'Ozenne', numero: 147, voie: 'rte', rue: 'Albi', type: 'château', note: 'mairie' },
  { "nom": "Sage", "numero": 13, "voie": "rue", "rue": "Antoine Bayes", "type": "château", "note": "adolescents" },
  { "nom": "Le Mirail", "numero": 5, "voie": "allées", "rue": "Antonio Machado", "type": "château", "note": "université" },
  { "nom": "Bagatelle", "numero": 13, "voie": "imp", "rue": "Bachaga Boualam", "type": "château", "note": "disparu" },
  { "nom": "la Barigoude", "numero": 24, "voie": "chem", "rue": "Barigoude", "type": "château", "note": "résidence" },
  { "nom": "Bellefontaine", "numero": 64, "voie": "allées", "rue": "Bellefontaine", "type": "château", "note": "escalier" },
  { "nom": "Bellefontaine", "numero": 64, "voie": "allées", "rue": "Bellefontaine", "type": "château", "note": "pigeonnier" },
  { "nom": "palais des rois Wisigoths", "numero": 0, "voie": "place", "rue": "Bologne", "type": "château", "note": "" },
  { "nom": "Bourrasol", "numero": 0, "voie": "place", "rue": "Bourrasol", "type": "château", "note": "disparu" },
  { "nom": "Busca", "numero": 0, "voie": "place", "rue": "Busca", "type": "château", "note": "disparu" },
  { "nom": "Griffoulet", "numero": 23, "voie": "chem", "rue": "Capelles", "type": "château", "note": "disparu" },
  { "nom": "Marmande", "numero": 71, "voie": "chem", "rue": "Capelles", "type": "château", "note": "école" },
  { "nom": "Casselardit", "numero": 92, "voie": "avenue", "rue": "Casselardit", "type": "château", "note": "Ehpad" },
  { "nom": "Ancely", "numero": 224, "voie": "avenue", "rue": "Casselardit", "type": "château", "note": "dépendances" },
  { "nom": "L'Hers", "numero": 21, "voie": "rue", "rue": "Claudius Rougenet", "type": "château", "note": "pigeonnier" },
  { "nom": "la Flambelle", "numero": 29, "voie": "rue", "rue": "de Ventadour", "type": "château", "note": "abandonné" },
  { "nom": "Lespinet-Ramel", "numero": 1, "voie": "avenue", "rue": "Edourard Belin", "type": "château", "note": "CREPS" },
  { "nom": "Gounon", "numero": 1, "voie": "rte", "rue": "Espagne", "type": "château", "note": "résidence" },
  { "nom": "Fondeyre", "numero": 185, "voie": "avenue", "rue": "États-Unis", "type": "château", "note": "parc" },
  { "nom": "Lalanne", "numero": 0, "voie": "allées", "rue": "Foulques", "type": "château", "note": "château" },
  { "nom": "Sesquières", "numero": 0, "voie": "allées", "rue": "Foulques", "type": "château", "note": "" },
  { "nom": "Paléficat", "numero": 23, "voie": "rue", "rue": "Frédéric Chopin", "type": "château", "note": "Virebent" },
  { "nom": "Gramont", "numero": 107, "voie": "chem", "rue": "Gabardie", "type": "château", "note": "résidence" },
  { "nom": "Comigères", "numero": 6, "voie": "rue", "rue": "Général Giraud", "type": "château", "note": "château" },
  { "nom": "Leblanc", "numero": 4, "voie": "chem", "rue": "Glacière", "type": "château", "note": "Emmaüs" },
  { "nom": "Les Verrrières", "numero": 8, "voie": "rue", "rue": "Godolin", "type": "château", "note": "résidence" },
  { "nom": "Grandselve", "numero": 37, "voie": "allées", "rue": "Grand-Selve", "type": "château", "note": "résidence" },
  { "nom": "Guilhermy", "numero": 0, "voie": "imp", "rue": "Guilhermy", "type": "château", "note": "résidence" },
  { "nom": "Lespinet-Raynal", "numero": 6, "voie": "rue", "rue": "Jacqueline Auriol", "type": "château", "note": "musée" },
  { "nom": "Fontaine-Lestang", "numero": 8, "voie": "rue", "rue": "Jacques Gamelin", "type": "château", "note": "pont" },
  { "nom": "Aïgua", "numero": 158, "voie": "avenue", "rue": "Jean Chaubet", "type": "château", "note": "disparu" },
  { "nom": "Madron", "numero": 1, "voie": "allées", "rue": "Jean Griffon", "type": "château", "note": "Ehpad" },
  { "nom": "Saint-Raymond Sacarin", "numero": 18, "voie": "rue", "rue": "Jean Micoud", "type": "château", "note": "parc" },
  { "nom": "Narbonais", "numero": 2, "voie": "allées", "rue": "Jules Guesde", "type": "château", "note": "disparu" },
  { "nom": "Lanusse", "numero": 102, "voie": "chem", "rue": "Lanusse", "type": "château", "note": "résidence" },
  { "nom": "Lapujade", "numero": 129, "voie": "chem", "rue": "Lapujade", "type": "château", "note": "résidence" },
  { nom: "Petit Capitole", numero: 153, voie: "avenue", rue: "Lardenne", type: "château", note: "colonie" },
  { "nom": "Corail", "numero": 425, "voie": "rte", "rue": "Launaguet", "type": "château", "note": "disparu" },
  { "nom": "Le Calquet", "numero": 100, "voie": "chem", "rue": "le Goff", "type": "château", "note": "cadastres" },
  { "nom": "Monlon", "numero": 25, "voie": "chem", "rue": "Lestang", "type": "château", "note": "pépinière" },
  { "nom": "Reynerie", "numero": 160, "voie": "chem", "rue": "Lestang", "type": "château", "note": "municipal" },
  { "nom": "Saint-Michel du Touch", "numero": 19, "voie": "allées", "rue": "Limagne", "type": "château", "note": "ruines" },
  { "nom": "palais Saint-Michel du Touch", "numero": 19, "voie": "allées", "rue": "Limagne", "type": "château", "note": "" },
  { "nom": "Limayrac", "numero": 50, "voie": "rue", "rue": "Limayrac", "type": "château", "note": "lycée" },
  { "nom": "Clerfont", "numero": 2, "voie": "rue", "rue": "Lizop", "type": "château", "note": "résidence" },
  { "nom": "Tabard", "numero": 1, "voie": "imp", "rue": "Londres", "type": "château", "note": "mosquée" },
  { "nom": "Lespinet-Lasvignes", "numero": 3, "voie": "allées", "rue": "Lucien Lafay", "type": "château", "note": "CRS" },
  { "nom": "Desazars", "numero": 3, "voie": "chem", "rue": "Maraîchers", "type": "château", "note": "puits" },
  { "nom": "Chantelle", "numero": 6, "voie": "imp", "rue": "Marie Laurencin", "type": "château", "note": "disparu" },
  { "nom": "Larade", "numero": 35, "voie": "rue", "rue": "Mathaly", "type": "château", "note": "école" },
  { "nom": "château du Balufet", "numero": 0, "voie": "rue", "rue": "Maubec", "type": "château", "note": "" },
  { "nom": "Comminges", "numero": 0, "voie": "rd pt", "rue": "Maurice Hauriou", "type": "château", "note": "disparu" },
  { "nom": "Mazades", "numero": 18, "voie": "avenue", "rue": "Mazades", "type": "château", "note": "disparu" },
  { "nom": "Bellevue", "numero": 135, "voie": "rte", "rue": "Narbonne", "type": "château", "note": "lycée" },
  { "nom": "Nicol", "numero": 98, "voie": "chem", "rue": "Nicol", "type": "château", "note": "disparu" },
  { "nom": "Braqueville", "numero": 0, "voie": "imp", "rue": "Palayre", "type": "château", "note": "façade" },
  { "nom": "Palays", "numero": 1, "voie": "chem", "rue": "Palays", "type": "château", "note": "institut" },
  { "nom": "château Papus", "numero": 1, "voie": "chem", "rue": "Papus", "type": "château", "note": "" },
  { "nom": "Caumont", "numero": 5, "voie": "avenue", "rue": "Parc", "type": "château", "note": "disparu" },
  { "nom": "Lansac", "numero": 4, "voie": "rue", "rue": "Paul Farrando", "type": "château", "note": "château" },
  { "nom": "La Mounède", "numero": 1, "voie": "rue", "rue": "Perroud", "type": "château", "note": "spectacle" },
  { "nom": "La Cépière", "numero": 5, "voie": "chem", "rue": "Pigeonnier Cépière", "type": "château", "note": "résidence" },
  { "nom": "Montredon", "numero": 0, "voie": "imp", "rue": "Pyrénées", "type": "château", "note": "château" },
  { "nom": "Rangueil", "numero": 68, "voie": "avenue", "rue": "Rangueil", "type": "château", "note": "disparu" },
  { "nom": "Bazacle", "numero": 11, "voie": "quai", "rue": "Saint-Pierre", "type": "château", "note": "disparu" },
  { "nom": "Les Ormes", "numero": 128, "voie": "rte", "rue": "Saint-Simon", "type": "château", "note": "institut" },
  { "nom": "Candie", "numero": 17, "voie": "chem", "rue": "Saudrune", "type": "château", "note": "coopérative" },
  { "nom": "Cazal Lapujade", "numero": 5, "voie": "rue", "rue": "Simone Boudet", "type": "château", "note": "résidence" },
  { "nom": "Petit Gragnague", "numero": 9, "voie": "rue", "rue": "Sports", "type": "château", "note": "école" },
  { "nom": "Teynier", "numero": 1, "voie": "imp", "rue": "Teynier", "type": "château", "note": "usine" },
  { "nom": "Purpan", "numero": 75, "voie": "voir", "rue": "TOEC", "type": "château", "note": "école" },
  { "nom": "Petit Niquet", "numero": 49, "voie": "chem", "rue": "Vallon", "type": "château", "note": "résidence" },
  { "nom": "château des Potiers", "numero": 14, "voie": "rue", "rue": "Vases", "type": "château", "note": "école" },
  { "nom": "Doujat", "numero": 35, "voie": "rue", "rue": "Velasquez", "type": "château", "note": "résidence" },
  { "nom": "Ecole Privée Notre Dame", "numero": 42, "voie": "rue", "rue": "36 Ponts", "type": "église", "note": "école" },
  { "nom": "Sainte-Famille des Minimes", "numero": 1, "voie": "rue", "rue": "Abbé Sicard", "type": "église", "note": "collège" },
  { "nom": "Patte D'oie", "numero": 57, "voie": "rue", "rue": "Adolphe Coll", "type": "église", "note": "" },
  { "nom": "Croix-Daurade", "numero": 122, "voie": "rte", "rue": "Albi", "type": "église", "note": "" },
  { "nom": "Saint-Caprais", "numero": null, "voie": "rte", "rue": "Albi", "type": "église", "note": "" },
  { "nom": "Saint-Paul", "numero": 37, "voie": "rue", "rue": "Amidonniers", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 37, "voie": "rue", "rue": "Amidonniers", "type": "église", "note": "Saint-Paul" },
  { "nom": "Église St-Nicolas", "numero": 1, "voie": "rue", "rue": "Antoine Bourdelle", "type": "église", "note": "" },
  { "nom": "Saint-Jean-Baptiste", "numero": 7, "voie": "rue", "rue": "Antonin Mercié", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 7, "voie": "rue", "rue": "Antonin Mercié", "type": "église", "note": "St-Jn-Baptiste" },
  { "nom": "chapelle du Raisin", "numero": null, "voie": "rue", "rue": "Aquitaine", "type": "église", "note": "" },
  { "nom": "Sainte-Marguerite", "numero": 105, "voie": "avenue", "rue": "Arènes Romaines", "type": "église", "note": "" },
  { "nom": "Sainte Marie de Saint Sernin", "numero": 19, "voie": "bd", "rue": "Armand Duportal", "type": "église", "note": "lycée" },
  { "nom": "Église du Christ Roi", "numero": 26, "voie": "rue", "rue": "Aude", "type": "église", "note": "" },
  { "nom": "Christ-Roi", "numero": 28, "voie": "rue", "rue": "Aude", "type": "église", "note": "" },
  { "nom": "Sainte-Colline", "numero": 28, "voie": "rue", "rue": "Aude", "type": "église", "note": "" },
  { "nom": "chapelle de la cité", "numero": null, "voie": "rue", "rue": "Baudelaire", "type": "église", "note": "" },
  { "nom": "église christ st gabriel", "numero": 270, "voie": "rte", "rue": "Bayonne", "type": "église", "note": "" },
  { "nom": "Chapelle du Castelet", "numero": 7, "voie": "rue", "rue": "Belfort", "type": "église", "note": "" },
  { "nom": "Notre-Dame des Victoires", "numero": 7, "voie": "rue", "rue": "Belfort", "type": "église", "note": "" },
  { "nom": "Sainte-Thérèse", "numero": 13, "voie": "rue", "rue": "Belle Paule", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 13, "voie": "rue", "rue": "Belle Paule", "type": "église", "note": "Ste-Thérèse" },
  { "nom": "Sainte-Thérèse", "numero": null, "voie": "rue", "rue": "Belle-Paule", "type": "église", "note": "" },
  { "nom": "Saint-François d'Assise", "numero": 0, "voie": "parvis", "rue": "Bertrand Delpy", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "parvis", "rue": "Bertrand Delpy", "type": "église", "note": "St-Frs d'Assise" },
  { "nom": "Montaudran", "numero": 45, "voie": "chem", "rue": "Bitet", "type": "église", "note": "" },
  { "nom": "chapelle maison Ramel", "numero": null, "voie": "rue", "rue": "Bitet", "type": "église", "note": "" },
  { "nom": "Nuestra señora de la compasión", "numero": 62, "voie": "rte", "rue": "Blagnac", "type": "église", "note": "espagnol" },
  { "nom": "Saint Jean-Baptiste", "numero": 62, "voie": "rte", "rue": "Blagnac", "type": "église", "note": "" },
  { "nom": "Notre-Dame D'espérance", "numero": 113, "voie": "rue", "rue": "Bonnat", "type": "église", "note": "" },
  { "nom": "Notre Dame de l'Espérance", "numero": null, "voie": "rue", "rue": "Bonnat", "type": "église", "note": "" },
  { "nom": "Salle paroissiale de Borderouge", "numero": 13, "voie": "chem", "rue": "Borderouge", "type": "église", "note": "" },
  { "nom": "chapelle ancien lycée St-Joseph", "numero": 2, "voie": "rue", "rue": "Camichel", "type": "église", "note": "" },
  { "nom": "chapelle Le Caousou", "numero": 42, "voie": "avenue", "rue": "Camille Pujol", "type": "église", "note": "lycée" },
  { "nom": "Saint-François d'Assise", "numero": null, "voie": "avenue", "rue": "Camille Pujol", "type": "église", "note": "" },
  { "nom": "église Saint-Romain", "numero": 0, "voie": "place", "rue": "Capitole", "type": "église", "note": "" },
  { "nom": "Chapelle Casselardit", "numero": 31, "voie": "avenue", "rue": "Casselardit", "type": "église", "note": "" },
  { "nom": "chapelle Casselardit", "numero": 31, "voie": "avenue", "rue": "casselardit", "type": "église", "note": "" },
  { "nom": "église Immaculée Conception", "numero": 1, "voie": "place", "rue": "ch. Philippe Ravary", "type": "église", "note": "" },
  { "nom": "Saint-Jean Marie Vianney", "numero": 15, "voie": "rue", "rue": "Chamois", "type": "église", "note": "" },
  { "nom": "Saint-Simon", "numero": 30, "voie": "rue", "rue": "Cimetière St-Simon", "type": "église", "note": "" },
  { "nom": "chapelle collège Foix", "numero": 1, "voie": "rue", "rue": "Collège de Foix", "type": "église", "note": "" },
  { "nom": "Sainte-Marie-des-Ursulines", "numero": 34, "voie": "avenue", "rue": "Colonne", "type": "église", "note": "collège" },
  { "nom": "APMA", "numero": 25, "voie": "rue", "rue": "Concorde", "type": "église", "note": "" },
  { "nom": "presbytère Saint-Sernin", "numero": 13, "voie": "rue", "rue": "Cuves Saint-Sernin", "type": "église", "note": "" },
  { "nom": "Notre-Dame de la Dalbade", "numero": 30, "voie": "rue", "rue": "Dalbade", "type": "église", "note": "" },
  { "nom": "chapelle Sainte-Jeanne d'Arc", "numero": null, "voie": "rue", "rue": "Danièle Casanova", "type": "église", "note": "" },
  { "nom": "Sainte-Jeanne d'Arc", "numero": 36, "voie": "rue", "rue": "Danielle Casanova", "type": "église", "note": "" },
  { "nom": "basilique de la Daurade", "numero": 1, "voie": "place", "rue": "Daurade", "type": "église", "note": "" },
  { "nom": "Saint-Martin du Touch", "numero": 2, "voie": "imp", "rue": "Dr Joseph Laurent", "type": "église", "note": "" },
  { "nom": "Lafourguette", "numero": 0, "voie": "place", "rue": "du 8 Mai 1945", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "du 8 Mai 1945", "type": "église", "note": "Lafourguette" },
  { "nom": "Communauté FEC", "numero": 12, "voie": "chem", "rue": "Duroux", "type": "église", "note": "" },
  { "nom": "Sainte-Madeleine de Lalande", "numero": 2, "voie": "rue", "rue": "Église de Lalande", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rue", "rue": "Église de Lalande", "type": "église", "note": "Lalande" },
  { "nom": "chapelle", "numero": null, "voie": "rue", "rue": "Fages", "type": "église", "note": "" },
  { "nom": "Notre-Dame du Férétra", "numero": 98, "voie": "rue", "rue": "Feretra", "type": "église", "note": "" },
  { "nom": "Gésu", "numero": 22, "voie": "rue", "rue": "Fleurs", "type": "église", "note": "" },
  { "nom": "Sainte-Claire du Salin", "numero": 31, "voie": "rue", "rue": "Fonderie", "type": "église", "note": "" },
  { "nom": "Sainte-Madeleine", "numero": 38, "voie": "rue", "rue": "Fondeville", "type": "église", "note": "" },
  { "nom": "Notre-Dame des Anges", "numero": null, "voie": "rue", "rue": "Fondeville", "type": "église", "note": "" },
  { "nom": "Notre Dame de Bellefontaine", "numero": 1, "voie": "imp", "rue": "François Foulquier", "type": "église", "note": "" },
  { "nom": "Notre-Dame de Lourdes", "numero": 1, "voie": "rue", "rue": "Frédéric Mistral", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 1, "voie": "rue", "rue": "Frédéric Mistral", "type": "église", "note": "Lourdes" },
  { "nom": "Saint-François de Paule", "numero": 22, "voie": "rue", "rue": "Général Bourbaki", "type": "église", "note": "" },
  { "nom": "Eglise Minimes", "numero": 22, "voie": "rue", "rue": "Général Bourbaki", "type": "église", "note": "" },
  { "nom": "chapelle château Grand Selve", "numero": null, "voie": "allées", "rue": "Grand Selves", "type": "église", "note": "" },
  { "nom": "Assomptionnistes Courbet", "numero": 17, "voie": "rue", "rue": "Gustave Courbet", "type": "église", "note": "" },
  { "nom": "Saint-Vincent de Paul", "numero": 56, "voie": "chem", "rue": "Heredia", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 56, "voie": "chem", "rue": "Heredia", "type": "église", "note": "St-Vt de Paul" },
  { "nom": "Saint Vincent de Paul", "numero": 56, "voie": "rue", "rue": "Heredia", "type": "église", "note": "" },
  { "nom": "chapelle château des veyrières", "numero": 28, "voie": "avenue", "rue": "Honoré Serres", "type": "église", "note": "" },
  { "nom": "Eglise jacobins", "numero": 10, "voie": "place", "rue": "Jacobins", "type": "église", "note": "" },
  { "nom": "Notre-Dame des Grâces", "numero": 27, "voie": "allées", "rue": "Jean Jaurès", "type": "église", "note": "" },
  { "nom": "Couvent des Carmes", "numero": 33, "voie": "avenue", "rue": "Jean Rieux", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 33, "voie": "avenue", "rue": "Jean Rieux", "type": "église", "note": "Carmes" },
  { "nom": "chappelle av Jean Rieux", "numero": null, "voie": "avenue", "rue": "Jean Rieux", "type": "église", "note": "" },
  { "nom": "chappelle du palais de justice", "numero": 2, "voie": "allées", "rue": "Jules Guesde", "type": "église", "note": "" },
  { "nom": "Sainte-Rita", "numero": 17, "voie": "avenue", "rue": "Jules Julien", "type": "église", "note": "" },
  { "nom": "Saint-Paul des Nations", "numero": 3, "voie": "rue", "rue": "Kiev", "type": "église", "note": "" },
  { "nom": "église de la Reynerie", "numero": null, "voie": "rue", "rue": "Kiev", "type": "église", "note": "" },
  { "nom": "chappelle école Calvinhac", "numero": 8, "voie": "rue", "rue": "Labatut", "type": "église", "note": "" },
  { "nom": "Communauté Assomptionniste", "numero": 4, "voie": "rue", "rue": "Lamarck", "type": "église", "note": "" },
  { "nom": "Saint-Exupère", "numero": 6, "voie": "rue", "rue": "Lamarck", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 6, "voie": "rue", "rue": "Lamarck", "type": "église", "note": "Saint-Exupère" },
  { "nom": "Notre-Dame de l'Assomption", "numero": 23, "voie": "rue", "rue": "Larade", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 23, "voie": "rue", "rue": "Larade", "type": "église", "note": "Assomption" },
  { "nom": "Saint-Michel", "numero": 207, "voie": "avenue", "rue": "Lardenne", "type": "église", "note": "" },
  { "nom": "église Sainte-Geneviève", "numero": null, "voie": "avenue", "rue": "Lardenne", "type": "église", "note": "" },
  { "nom": "Saint-Michel", "numero": 207, "voie": "rue", "rue": "Lardenne", "type": "église", "note": "" },
  { "nom": "Collège Lycée Les Maristes", "numero": 134, "voie": "avenue", "rue": "Lespinet", "type": "église", "note": "lycée" },
  { "nom": "monument aux morts", "numero": 3, "voie": "psge", "rue": "Lieberknecht", "type": "église", "note": "Saint-Caprais" },
  { "nom": "Ensemble Scolaire Saint Joseph", "numero": 85, "voie": "rue", "rue": "Limayrac", "type": "église", "note": "lycée" },
  { "nom": "chapelle Saint Vincent de Paul", "numero": 80, "voie": "rue", "rue": "Louis Plana", "type": "église", "note": "" },
  { "nom": "Sainte-Thérèse de l'Enfant Jésus", "numero": 5, "voie": "rue", "rue": "Lucien Cassagne", "type": "église", "note": "" },
  { "nom": "Église Saint-Jean", "numero": 9, "voie": "place", "rue": "Marnac", "type": "église", "note": "Ramonville" },
  { "nom": "Saint-André", "numero": 68, "voie": "chem", "rue": "Michoun", "type": "église", "note": "" },
  { "nom": "Saint-André", "numero": null, "voie": "chem", "rue": "Michoun", "type": "église", "note": "" },
  { "nom": "chapelle collège Mirepoix", "numero": "3, 5", "voie": "rue", "rue": "Mirepoix", "type": "église", "note": "" },
  { "nom": "Communauté jésuite", "numero": 9, "voie": "rue", "rue": "Monplaisir", "type": "église", "note": "" },
  { "nom": "Saint-François-Xavier", "numero": 157, "voie": "avenue", "rue": "Muret", "type": "église", "note": "" },
  { "nom": "Collège Saint-Thomas d'Aquin", "numero": 40, "voie": "gde rue", "rue": "Nazareth", "type": "église", "note": "collège" },
  { "nom": "Saint-Luc", "numero": 118, "voie": "rue", "rue": "Negreneys", "type": "église", "note": "" },
  { "nom": "Notre-Dame de la Dalbade", "numero": 2, "voie": "rue", "rue": "Paradoux", "type": "église", "note": "" },
  { "nom": "Sacré Coeur", "numero": 2, "voie": "place", "rue": "Patte d'Oie", "type": "église", "note": "" },
  { "nom": "chapelle Carmélites", "numero": 1, "voie": "rue", "rue": "Périgord", "type": "église", "note": "" },
  { "nom": "Sainte-Marie de Nevers", "numero": 10, "voie": "rue", "rue": "Périgord", "type": "église", "note": "lycée" },
  { "nom": "Notre-Dame du Calvaire", "numero": 7, "voie": "rue", "rue": "Peyrolade", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 7, "voie": "rue", "rue": "Peyrolade", "type": "église", "note": "Calvaire" },
  { "nom": "Saint-Antoine du Salin", "numero": 18, "voie": "rue", "rue": "Pharaon", "type": "église", "note": "" },
  { "nom": "Porte du Lauragais", "numero": 3, "voie": "avenue", "rue": "Pierre Coupeau", "type": "église", "note": "Balma" },
  { "nom": "Sainte-Germaine des Pradettes", "numero": 4, "voie": "chem", "rue": "Pradettes", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 4, "voie": "chem", "rue": "Pradettes", "type": "église", "note": "Pradettes" },
  { "nom": "chapelle des Pradettes", "numero": null, "voie": "chem", "rue": "Pradettes", "type": "église", "note": "" },
  { "nom": "cathédrale Saint-Etienne", "numero": 1, "voie": "imp", "rue": "Préfecture", "type": "église", "note": "" },
  { "nom": "Saint-Etienne", "numero": 1, "voie": "imp", "rue": "Préfecture", "type": "église", "note": "" },
  { "nom": "CCU Rangueil", "numero": 66, "voie": "avenue", "rue": "Rangueil", "type": "église", "note": "" },
  { "nom": "Saint-Marc", "numero": 68, "voie": "avenue", "rue": "Rangueil", "type": "église", "note": "" },
  { "nom": "Saint-François d'Assise", "numero": 37, "voie": "avenue", "rue": "Raymond Naves", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 37, "voie": "avenue", "rue": "Raymond Naves", "type": "église", "note": "St-Fs d'Assise" },
  { "nom": "Sainte-Claire", "numero": 206, "voie": "avenue", "rue": "Raymond Naves", "type": "église", "note": "" },
  { "nom": "Sainte-Claire", "numero": null, "voie": "avenue", "rue": "Raymond Naves", "type": "église", "note": "" },
  { "nom": "Sainte-Marie-des-Anges", "numero": 36, "voie": "bd", "rue": "Récollets", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 36, "voie": "bd", "rue": "Récollets", "type": "église", "note": "Ste-Me-Anges" },
  { "nom": "Saint-Sylve", "numero": 6, "voie": "rue", "rue": "Reille", "type": "église", "note": "" },
  { "nom": "Pères Blancs", "numero": 3, "voie": "rue", "rue": "Ringaud", "type": "église", "note": "" },
  { "nom": "Saint-Aubin", "numero": 45, "voie": "rue", "rue": "Riquet", "type": "église", "note": "" },
  { "nom": "Saint-Caprais", "numero": 0, "voie": "place", "rue": "Saint-Caprais", "type": "église", "note": "" },
  { "nom": "Sainte-Anne", "numero": 15, "voie": "rue", "rue": "Sainte-Anne", "type": "église", "note": "" },
  { "nom": "Notre Dame de l'Assomption", "numero": null, "voie": "rue", "rue": "Sainte-Mélanie", "type": "église", "note": "" },
  { "nom": "chapelle Archives Canal Midi", "numero": 2, "voie": "port", "rue": "Saint-Etienne", "type": "église", "note": "" },
  { "nom": "Cathédrale Saint-Étienne", "numero": 0, "voie": "place", "rue": "Saint-Étienne", "type": "église", "note": "" },
  { "nom": "Saint-Joseph", "numero": 40, "voie": "avenue", "rue": "Saint-Exupéry", "type": "église", "note": "" },
  { "nom": "Saint-Hilaire", "numero": 19, "voie": "rue", "rue": "Saint-Hilaire", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 19, "voie": "rue", "rue": "Saint-Hilaire", "type": "église", "note": "Saint-Hilaire" },
  { "nom": "chapelle Saint-Hilaire", "numero": null, "voie": "rue", "rue": "Saint-Hilaire", "type": "église", "note": "" },
  { "nom": "Saint-Esprit", "numero": 2, "voie": "rue", "rue": "Saintonge", "type": "église", "note": "" },
  { "nom": "Soeurs de la Bonne Nouvelle", "numero": 2, "voie": "rue", "rue": "Saintonge", "type": "église", "note": "" },
  { "nom": "Saint-Esprit", "numero": null, "voie": "rue", "rue": "Saintonge", "type": "église", "note": "" },
  { "nom": "monument aux morts", "numero": 12, "voie": "place", "rue": "Saint-Pierre", "type": "église", "note": "Saint-Pierre des Cuisines" },
  { "nom": "Saint-Roch-du-Férétra", "numero": 1, "voie": "place", "rue": "Saint-Roch", "type": "église", "note": "" },
  { "nom": "chapelle des Bateliers", "numero": 10, "voie": "port", "rue": "Saint-Sauveur", "type": "église", "note": "" },
  { "nom": "basilique Saint-Sernin", "numero": 0, "voie": "place", "rue": "Saint-Sernin", "type": "église", "note": "" },
  { "nom": "Saint-Sernin", "numero": 13, "voie": "place", "rue": "Saint-Sernin", "type": "église", "note": "" },
  { "nom": "église Saint-Simon", "numero": null, "voie": "place", "rue": "Saint-Simon", "type": "église", "note": "" },
  { "nom": "Saint-Nicolas", "numero": 1, "voie": "rue", "rue": "San Subra", "type": "église", "note": "" },
  { "nom": "chapelle château de Candie", "numero": 17, "voie": "chem", "rue": "Saudrune", "type": "église", "note": "" },
  { "nom": "MCR", "numero": 14, "voie": "rue", "rue": "Sénéchal", "type": "église", "note": "" },
  { "nom": "Trinité", "numero": 290, "voie": "rte", "rue": "Seysses", "type": "église", "note": "" },
  { "nom": "église de la Trinité", "numero": null, "voie": "rte", "rue": "Seysses", "type": "église", "note": "" },
  { "nom": "chapelle lycée Saint-Joseph", "numero": null, "voie": "rue", "rue": "Sylvain Dauriac", "type": "église", "note": "" },
  { "nom": "Notre-Dame-du-Taur", "numero": 12, "voie": "rue", "rue": "Taur", "type": "église", "note": "" },
  { "nom": "Sainte-Germaine", "numero": 59, "voie": "avenue", "rue": "U.R.S.S.", "type": "église", "note": "" },
  { "nom": "Saint-Pierre des Chartreux", "numero": 21, "voie": "rue", "rue": "Valade", "type": "église", "note": "" },
  { "nom": "Saint-Jean Vianey", "numero": null, "voie": "rue", "rue": "Van Dyck", "type": "église", "note": "" },
  { "nom": "métairie et tour Michel de Pira", "numero": null, "voie": null, "rue": "à voir", "type": "ferme", "note": "" },
  { "nom": "ferme de Thibaut", "numero": null, "voie": null, "rue": "à voir", "type": "ferme", "note": "" },
  { "nom": "ferme du Chapitre", "numero": null, "voie": null, "rue": "à voir", "type": "ferme", "note": "" },
  { "nom": "métairie d'Audubert de Valiech", "numero": null, "voie": null, "rue": "à voir", "type": "ferme", "note": "" },
  { "nom": "métairie de la Tourasse", "numero": null, "voie": null, "rue": "à voir", "type": "ferme", "note": "" },
  { "nom": "métairie de Liffard-Vidault", "numero": null, "voie": null, "rue": "à voir", "type": "ferme", "note": "" },
  { "nom": "ferme rte Albi", "numero": null, "voie": "rte", "rue": "Albi", "type": "ferme", "note": "" },
  { "nom": "ferme", "numero": null, "voie": "rte", "rue": "Bayonne", "type": "ferme", "note": "" },
  { "nom": "Borde Blanche", "numero": null, "voie": "quartier", "rue": "Borde-Blanche", "type": "ferme", "note": "" },
  { "nom": "ferme rue Chapitre", "numero": null, "voie": "rue", "rue": "Chapitre", "type": "ferme", "note": "" },
  { "nom": "maison de maître", "numero": null, "voie": "avenue", "rue": "Lespinet", "type": "ferme", "note": "parc" },
  { "nom": "maison de maître", "numero": null, "voie": "avenue", "rue": "Lespinet", "type": "ferme", "note": "pigeonnier" },
  { "nom": "ferme", "numero": null, "voie": "rue", "rue": "Maubec", "type": "ferme", "note": "" },
  { "nom": "ferme", "numero": null, "voie": "chem", "rue": "Monredon", "type": "ferme", "note": "" },
  { "nom": "ferme route de Seysses", "numero": null, "voie": "rte", "rue": "Seysses", "type": "ferme", "note": "" },
  { "nom": "ferme route de Seysses", "numero": null, "voie": "rte", "rue": "Seysses", "type": "ferme", "note": "" },
  { "nom": "ferme", "numero": null, "voie": "imp", "rue": "Teynier", "type": "ferme", "note": "" },
  { "nom": "ferme rue Velasquez", "numero": 86, "voie": "rue", "rue": "Velasquez", "type": "ferme", "note": "" },
  { "nom": "Notre Dame de la Présentation", "numero": 47, "voie": "rue", "rue": "Trentre-six Ponts", "type": "foyer", "note": "" },
  { "nom": "halle Arnaud-Bernard", "numero": 0, "voie": "place", "rue": "Arnaud-Bernard", "type": "halle", "note": "" },
  { "nom": "Ozenne", "numero": 147, "voie": "rte", "rue": "Albi", "type": "château", "note": "mairie" },
  { "nom": "h. Porte Arnaud Bernard", "numero": 0, "voie": "rue", "rue": "Arnaud Bernard", "type": "hôpital", "note": "A. Bernard" },
  { "nom": "h. Saint-Jacques Bout du Pont", "numero": 0, "voie": "chaussée", "rue": "Bazacle", "type": "hôpital", "note": "Bazacle" },
  { "nom": "hôpital Saint-Rémézy", "numero": 32, "voie": "rue", "rue": "Dalbade", "type": "hôpital", "note": "Dalbade" },
  { "nom": "h. Notre Dame de la Daurade", "numero": 0, "voie": "chaussée", "rue": "Daurade", "type": "hôpital", "note": "Daurade" },
  { "nom": "h. Saint-Marie de la Daurade", "numero": 1, "voie": "place", "rue": "Daurade", "type": "hôpital", "note": "ancien" },
  { "nom": "hôpital de Guilhem de Trenis", "numero": 0, "voie": "place", "rue": "Jeanne d'Arc", "type": "hôpital", "note": "Jeanne d'Arc" },
  { "nom": "hôpital du Grand Selve", "numero": 0, "voie": "place", "rue": "Jeanne d'Arc", "type": "hôpital", "note": "Jeanne d'Arc" },
  { "nom": "Léproserie Matabiau", "numero": 0, "voie": "place", "rue": "Jeanne d'Arc", "type": "hôpital", "note": "Jeanne d'Arc" },
  { "nom": "hôpital Saint-Antoine", "numero": 2, "voie": "allées", "rue": "Jules Guesde", "type": "hôpital", "note": "Plantes" },
  { "nom": "hôpital général", "numero": 0, "voie": "place", "rue": "Lange", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "hôpital Saint-Sébastien", "numero": 0, "voie": "place", "rue": "Lange", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "hospice des fous", "numero": 0, "voie": "place", "rue": "Lange", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "Saint-Joseph de la Grave", "numero": 0, "voie": "place", "rue": "Lange", "type": "hôpital", "note": "" },
  { "nom": "hôpital Larrey", "numero": 17, "voie": "rue", "rue": "Larrey", "type": "hôpital", "note": "Saint-Pierre" },
  { "nom": "Léproserie Arnaud-Bernard", "numero": 0, "voie": "rue", "rue": "Lascrosses", "type": "hôpital", "note": "Compans" },
  { "nom": "Léproserie Pouzonville", "numero": 0, "voie": "rue", "rue": "Merly", "type": "hôpital", "note": "Strasbourg" },
  { "nom": "Léproserie Narbonnaise", "numero": 1, "voie": "place", "rue": "Parlement", "type": "hôpital", "note": "Salin" },
  { "nom": "hôpital Saint-Jacques du Taur", "numero": 1, "voie": "rue", "rue": "Pénitents Gris", "type": "hôpital", "note": "Lois" },
  { "nom": "Léproserie Villeneuve & Neuve", "numero": 0, "voie": "rue", "rue": "Rem Saint-Etienne", "type": "hôpital", "note": "entre" },
  { "nom": "Léproserie Saint-Cyprien", "numero": 0, "voie": "rue", "rue": "République", "type": "hôpital", "note": "entre" },
  { "nom": "hôpital du Corps de Dieu", "numero": 0, "voie": "gde rue", "rue": "Saint-Michel", "type": "hôpital", "note": "Saint-Michel" },
  { "nom": "h. Notre Dame de la Daurade", "numero": 0, "voie": "gde rue", "rue": "Saint-Nicolas", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "hôpital de Bernard Mainadier", "numero": 12, "voie": "place", "rue": "Saint-Pierre", "type": "hôpital", "note": "Saint-Pierre" },
  { "nom": "hôpital Sainte-Radegonde", "numero": 12, "voie": "place", "rue": "Saint-Pierre", "type": "hôpital", "note": "Saint-Pierre" },
  { "nom": "Léproserie Meynadière", "numero": 12, "voie": "place", "rue": "Saint-Pierre", "type": "hôpital", "note": "Saint-Pierre" },
  { "nom": "Léproserie Sainte-Radegonde", "numero": 12, "voie": "place", "rue": "Saint-Pierre", "type": "hôpital", "note": "Saint-Pierre" },
  { "nom": "mainaderie", "numero": 12, "voie": "place", "rue": "Saint-Pierre", "type": "hôpital", "note": "Saint-Pierre" },
  { "nom": "hôpital Saint-Jacques du Bourg", "numero": 0, "voie": "place", "rue": "Saint-Sernin", "type": "hôpital", "note": "ancien" },
  { "nom": "hôpital Saint-Raymond", "numero": 1, "voie": "place", "rue": "Saint-Sernin", "type": "hôpital", "note": "ancien" },
  { "nom": "hôpital Saint-Jacques du Bourg", "numero": 2, "voie": "place", "rue": "Saint-Sernin", "type": "hôpital", "note": "vierge" },
  { "nom": "champs des Sept-Deniers", "numero": 0, "voie": "champs", "rue": "Sept-Deniers", "type": "hôpital", "note": "pestiférés" },
  { "nom": "hôpital du Saint-Esprit", "numero": 21, "voie": "rue", "rue": "Taur", "type": "hôpital", "note": "ancien" },
  { "nom": "hôpital Saint-Jacques du Bourg", "numero": 64, "voie": "rue", "rue": "Taur", "type": "hôpital", "note": "" },
  { "nom": "Léproserie Saint-Cyprien", "numero": 0, "voie": "rue", "rue": "Teinturiers", "type": "hôpital", "note": "entre" },
  { "nom": "hôpital de Saint-Orens", "numero": 0, "voie": null, "rue": "Toulouse", "type": "hôpital", "note": "" },
  { "nom": "hôpital du Puy Milan", "numero": 0, "voie": null, "rue": "Toulouse", "type": "hôpital", "note": "" },
  { "nom": "hôpital Saint-Anian", "numero": 0, "voie": null, "rue": "Toulouse", "type": "hôpital", "note": "" },
  { "nom": "hôpital Saint-Europe", "numero": 0, "voie": null, "rue": "Toulouse", "type": "hôpital", "note": "" },
  { "nom": "asile Olivier", "numero": 15, "voie": "rue", "rue": "Varsovie", "type": "hôpital", "note": "" },
  { "nom": "Léproserie Villeneuve & Neuve", "numero": 0, "voie": "place", "rue": "Victor Hugo", "type": "hôpital", "note": "entre" },
  { "nom": "h. Notre Dame de la Daurade", "numero": 2, "voie": "rue", "rue": "Viguerie", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "hôpital Nouvel", "numero": 2, "voie": "rue", "rue": "Viguerie", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "Léproserie Saint-Jacques", "numero": 2, "voie": "rue", "rue": "Viguerie", "type": "hôpital", "note": "Saint-Cyprien" },
  { "nom": "hôtel-Dieu Saint-Jacques", "numero": 2, "voie": "rue", "rue": "Viguerie", "type": "hôpital", "note": "" },
  { "nom": "maison le Lazareth", "numero": null, "voie": null, "rue": "à voir", "type": "hôtel", "note": "" },
  { "nom": "maison modèle Urbain Vitry", "numero": 17, "voie": "allées", "rue": "Jean Jaures", "type": "hôtel", "note": "" },
  { "nom": "hôtel particulier de Hautpoul", "numero": 25, "voie": "rue", "rue": "Malaret", "type": "hôtel", "note": "" },
  { "nom": "institut catholique", "numero": 25, "voie": "rue", "rue": "Argelès", "type": "institut", "note": "L'Union" },
  { "nom": "institut av. Crampel", "numero": null, "voie": "avenue", "rue": "Crampel", "type": "institut", "note": "" },
  { "nom": "fondation de la Salle", "numero": null, "voie": "chem", "rue": "Duroux", "type": "institut", "note": "" },
  { "nom": "Frère des Ecoles Chrétiennes", "numero": null, "voie": "chem", "rue": "Duroux", "type": "institut", "note": "" },
  { "nom": "centre Jean-Baptiste de la Salle", "numero": null, "voie": "chem", "rue": "Duroux", "type": "institut", "note": "" },
  { "nom": "Institut Catholique", "numero": 31, "voie": "rue", "rue": "Fonderie", "type": "institut", "note": "" },
  { "nom": "studium des Dominicains", "numero": 0, "voie": "imp", "rue": "Lacordaire", "type": "institut", "note": "" },
  { "nom": "Saint-Jean de Lassalle", "numero": 5, "voie": "chem", "rue": "Lafilaire", "type": "institut", "note": "" },
  { "nom": "institut des aveugles", "numero": 37, "voie": "rue", "rue": "Monplaisir", "type": "institut", "note": "" },
  { "nom": "institut des aveugles", "numero": null, "voie": "rue", "rue": "Monplaisir", "type": "institut", "note": "" },
  { "nom": "Faculté de Théologie", "numero": 8, "voie": "place", "rue": "Parlement", "type": "institut", "note": "" },
  { "nom": "institut de guidance", "numero": 10, "voie": "rue", "rue": "Saint-Léon", "type": "institut", "note": "" },
  { "nom": "institut", "numero": 12, "voie": "port", "rue": "Saint-Sauveur", "type": "institut", "note": "" },
  { "nom": "Institut Lafon Notre Dame", "numero": null, "voie": "rue", "rue": "Ste Catherine", "type": "institut", "note": "" },
  { "nom": "Séminaire Saint-Cyprien", "numero": 9, "voie": "rue", "rue": "Teinturiers", "type": "institut", "note": "" },
  { "nom": "Grand Rond", "numero": null, "voie": "rd pt", "rue": "Grand-Rond", "type": "kiosque", "note": "" },
  { "nom": "Lardenne", "numero": null, "voie": "place", "rue": "Jacques Sauvegrain", "type": "kiosque", "note": "" },
  { "nom": "pl Pinel", "numero": null, "voie": "place", "rue": "Pinel", "type": "kiosque", "note": "" },
  { "nom": "Grande Loge Nationale", "numero": 32, "voie": "rue", "rue": "Gabriel Péri", "type": "loge", "note": "" },
  { "nom": "Sainte-Marie des Champs", "numero": 169, "voie": "avenue", "rue": "Jean Rieux", "type": "lycée", "note": "" },
  { "nom": "Émilie de Rodat", "numero": 25, "voie": "avenue", "rue": "Lombez", "type": "lycée", "note": "" },
  { "nom": "Sainte-Marie de Saint-Sernin", "numero": 20, "voie": "rue", "rue": "Merly", "type": "lycée", "note": "" },
  { "nom": "Institut Notre Dame", "numero": 42, "voie": "rue", "rue": "Trentre-six Ponts", "type": "lycée", "note": "" },
  { "nom": "manoir", "numero": null, "voie": "rte", "rue": "Albi", "type": "manoir", "note": "" },
  { "nom": "manoir chem Etroits", "numero": null, "voie": "chem", "rue": "Etroits", "type": "manoir", "note": "" },
  { "nom": "Saint-Simon", "numero": 0, "voie": "quartier", "rue": "Saint-Simon", "type": "manoir", "note": "r. Trucaud" },
  { "nom": "manoir du Prince", "numero": 999, "voie": "rte", "rue": "Seysses", "type": "manoir", "note": "" },
  { "nom": "Monplaisir", "numero": 0, "voie": "rue", "rue": "Monplaisir", "type": "métairie", "note": "disparu" },
  { "nom": "petit séminaire", "numero": 28, "voie": "rue", "rue": "Aude", "type": "monastère", "note": "" },
  { "nom": "couvent Bonnefoy", "numero": 1, "voie": "place", "rue": "ch. Philippe Ravary", "type": "monastère", "note": "" },
  { "nom": "monastère Bonnefoy", "numero": 1, "voie": "place", "rue": "ch. Philippe Ravary", "type": "monastère", "note": "" },
  { "nom": "Cordeliers", "numero": 2, "voie": "rue", "rue": "Collège de Foix", "type": "monastère", "note": "banque" },
  { "nom": "couvent de la Mission", "numero": null, "voie": "avenue", "rue": "Crampel", "type": "monastère", "note": "" },
  { "nom": "Templiers", "numero": 13, "voie": "rue", "rue": "Dalbade", "type": "monastère", "note": "" },
  { "nom": "Saint-Jean de Jérusalem", "numero": 32, "voie": "rue", "rue": "Dalbade", "type": "monastère", "note": "" },
  { "nom": "grand séminaire", "numero": 32, "voie": "rue", "rue": "Dalbade", "type": "monastère", "note": "" },
  { "nom": "Noviciat des Jésuites", "numero": 17, "voie": "place", "rue": "Daurade", "type": "monastère", "note": "" },
  { "nom": "Cénacle", "numero": 2, "voie": "rue", "rue": "Deville", "type": "monastère", "note": "résidence" },
  { "nom": "Dominicaines de Monteils", "numero": 2, "voie": "rue", "rue": "Furgole", "type": "monastère", "note": "" },
  { "nom": "maison de retraite St-Augustin", "numero": null, "voie": "rue", "rue": "Gravette", "type": "monastère", "note": "" },
  { "nom": "couvent des Capucins", "numero": 33, "voie": "avenue", "rue": "Jean Rieux", "type": "monastère", "note": "" },
  { "nom": "petite soeur des Pauvres", "numero": 130, "voie": "avenue", "rue": "Jean Rieux", "type": "monastère", "note": "" },
  { "nom": "couvent Capucins", "numero": null, "voie": "avenue", "rue": "Jean Rieux", "type": "monastère", "note": "" },
  { "nom": "couvent des Franciscains", "numero": null, "voie": "avenue", "rue": "Jean Rieux", "type": "monastère", "note": "" },
  { "nom": "Saint-Antoine du T", "numero": 6, "voie": "rue", "rue": "L. C. Pélissier", "type": "monastère", "note": "mairie" },
  { "nom": "Couvent des Dominicains", "numero": 0, "voie": "imp", "rue": "Lacordaire", "type": "monastère", "note": "" },
  { "nom": "Missionnaires Lazaristes", "numero": 28, "voie": "rue", "rue": "Luchet", "type": "monastère", "note": "" },
  { "nom": "Notre-Dame du Cénacle", "numero": 5, "voie": "rue", "rue": "Lucien Cassagne", "type": "monastère", "note": "" },
  { "nom": "Augustins", "numero": 21, "voie": "rue", "rue": "Metz", "type": "monastère", "note": "musée" },
  { "nom": "Archevêché", "numero": 24, "voie": "rue", "rue": "Perchepinte", "type": "monastère", "note": "" },
  { "nom": "Petit Soeurs de l'Agneau", "numero": 20, "voie": "rue", "rue": "Pharaon", "type": "monastère", "note": "" },
  { "nom": "Sainte-Ursule", "numero": 13, "voie": "rue", "rue": "Sainte-Ursule", "type": "monastère", "note": "" },
  { "nom": "Sainte-Claire", "numero": 216, "voie": "avenue", "rue": "Saint-Exupéry", "type": "monastère", "note": "" },
  { "nom": "monastère Sainte-Claire", "numero": null, "voie": "avenue", "rue": "Saint-Exupéry", "type": "monastère", "note": "" },
  { "nom": "Fraternité Des Petites Soeurs", "numero": 49, "voie": "chem", "rue": "Vallon", "type": "monastère", "note": "" },
  { "nom": "monument aux morts", "numero": 22, "voie": "allées", "rue": "Alfred Mayssonnié", "type": "morts", "note": "nautique" },
  { "nom": "monument aux morts", "numero": 5, "voie": "allées", "rue": "Antonio Machado", "type": "morts", "note": "université" },
  { "nom": "monument aux morts", "numero": 3, "voie": "chem", "rue": "Audibert", "type": "morts", "note": "école" },
  { "nom": "monument aux morts", "numero": 144, "voie": "rte", "rue": "Bayonne", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 45, "voie": "chem", "rue": "Bitet", "type": "morts", "note": "Montaudran" },
  { "nom": "monument aux morts", "numero": 53, "voie": "rte", "rue": "Blagnac", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 62, "voie": "rte", "rue": "Blagnac", "type": "morts", "note": "Sept Deniers" },
  { "nom": "monument aux morts", "numero": 29, "voie": "square", "rue": "Boulingrin", "type": "morts", "note": "Shoah" },
  { "nom": "monument aux morts", "numero": 42, "voie": "avenue", "rue": "Camille Pujol", "type": "morts", "note": "Le Caousou" },
  { "nom": "monument aux morts", "numero": 104, "voie": "avenue", "rue": "Camille Pujol", "type": "morts", "note": "St-Fs d'Assise" },
  { "nom": "monument aux morts", "numero": 112, "voie": "avenue", "rue": "Camille Pujol", "type": "morts", "note": "école" },
  { "nom": "monument aux morts", "numero": 114, "voie": "avenue", "rue": "Camille Pujol", "type": "morts", "note": "école" },
  { "nom": "monument aux morts", "numero": 118, "voie": "avenue", "rue": "Camille Pujol", "type": "morts", "note": "plaque" },
  { "nom": "monument aux morts", "numero": 13, "voie": "bd", "rue": "Canon d'Arcole", "type": "morts", "note": "école" },
  { "nom": "monument aux morts", "numero": 13, "voie": "bd", "rue": "Canon d'Arcole", "type": "morts", "note": "plaque" },
  { "nom": "monument aux morts", "numero": 23, "voie": "chem", "rue": "Capelle", "type": "morts", "note": "vétérinaire" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Capitole", "type": "morts", "note": "mairie" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Capitole", "type": "morts", "note": "cénotaphe" },
  { "nom": "monument aux morts", "numero": 1, "voie": "place", "rue": "Capitole", "type": "morts", "note": "hôtel" },
  { "nom": "monument aux morts", "numero": 1, "voie": "place", "rue": "ch. Philippe Ravary", "type": "morts", "note": "Immaculée" },
  { "nom": "monument aux morts", "numero": 3, "voie": "rue", "rue": "Chairedon", "type": "morts", "note": "école" },
  { "nom": "monument aux morts", "numero": 3, "voie": "rue", "rue": "Chairedon", "type": "morts", "note": "Lespinasse" },
  { "nom": "monument aux morts", "numero": 17, "voie": "allées", "rue": "Charles de Fitte", "type": "morts", "note": "Vion" },
  { "nom": "monument aux morts", "numero": 76, "voie": "allées", "rue": "Charles de Fitte", "type": "morts", "note": "Tutsis" },
  { "nom": "monument aux morts", "numero": 0, "voie": "square", "rue": "Charles de Gaulle", "type": "morts", "note": "square" },
  { "nom": "monument aux morts", "numero": 0, "voie": "imp", "rue": "cim. Croix-Daurade", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 6, "voie": "chem", "rue": "Clotasses", "type": "morts", "note": "plaque" },
  { "nom": "monument aux morts", "numero": 0, "voie": "quartier", "rue": "Colonel Edme", "type": "morts", "note": "Francazal" },
  { "nom": "monument aux morts", "numero": 0, "voie": "chem", "rue": "Crabe", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Croix de pierre", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Croix de Pierre", "type": "morts", "note": "Croix Pierre" },
  { "nom": "monument aux morts", "numero": 30, "voie": "rue", "rue": "Dalbade", "type": "morts", "note": "Dalbade" },
  { "nom": "monument aux morts", "numero": 35, "voie": "rue", "rue": "Danièle Casanova", "type": "morts", "note": "STT" },
  { "nom": "monument aux morts", "numero": 1, "voie": "place", "rue": "Daurade", "type": "morts", "note": "Daurade" },
  { "nom": "monument aux morts", "numero": 5, "voie": "quai", "rue": "Daurade", "type": "morts", "note": "Beaux-Arts" },
  { "nom": "monument aux morts", "numero": 5, "voie": "quai", "rue": "Daurade", "type": "morts", "note": "Beaux-Arts" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rue", "rue": "Dr Joseph Laurent", "type": "morts", "note": "St-Martin" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "du 8 Mai 1945", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Église de Lalande", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Église Saint-Simon", "type": "morts", "note": "église" },
  { "nom": "monument aux morts", "numero": 23, "voie": "bd", "rue": "Embouchure", "type": "morts", "note": "Police" },
  { "nom": "monument aux morts", "numero": 101, "voie": "rte", "rue": "Espagne", "type": "morts", "note": "AZF" },
  { "nom": "monument aux morts", "numero": 134, "voie": "rte", "rue": "Espagne", "type": "morts", "note": "hôpital" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Europe", "type": "morts", "note": "caserne" },
  { "nom": "monument aux morts", "numero": 0, "voie": "imp", "rue": "Flamarion", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 31, "voie": "rue", "rue": "Fonderie", "type": "morts", "note": "Inst. Catho." },
  { "nom": "monument aux morts", "numero": 0, "voie": "rue", "rue": "Fondeville", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 38, "voie": "rue", "rue": "Fondeville", "type": "morts", "note": "Madeleine" },
  { "nom": "monument aux morts", "numero": 0, "voie": "allées", "rue": "François Verdier", "type": "morts", "note": "arc Triomphe" },
  { "nom": "monument aux morts", "numero": 0, "voie": "allées", "rue": "François Verdier", "type": "morts", "note": "cénotaphe" },
  { "nom": "monument aux morts", "numero": 77, "voie": "allées", "rue": "François Verdier", "type": "morts", "note": "guerre 1870" },
  { "nom": "monument aux morts", "numero": 0, "voie": "allées", "rue": "Frédéric Mistral", "type": "morts", "note": "justes" },
  { "nom": "monument aux morts", "numero": 24, "voie": "allées", "rue": "Frédéric Mistral", "type": "morts", "note": "féministe" },
  { "nom": "monument aux morts", "numero": 102, "voie": "chem", "rue": "Gabardie", "type": "morts", "note": "Infanterie" },
  { "nom": "monument aux morts", "numero": 1, "voie": "rue", "rue": "Gambetta", "type": "morts", "note": "Fermat" },
  { "nom": "monument aux morts", "numero": 22, "voie": "rue", "rue": "Général Bourbaki", "type": "morts", "note": "St-Frs de Paule" },
  { "nom": "monument aux morts", "numero": 45, "voie": "avenue", "rue": "Gloire", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 257, "voie": "rue", "rue": "Henri Desbals", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Héraclès", "type": "morts", "note": "Sport" },
  { "nom": "monument aux morts", "numero": 5, "voie": "rue", "rue": "Jean Aillet", "type": "morts", "note": "Lougnon" },
  { "nom": "monument aux morts", "numero": 202, "voie": "avenue", "rue": "Jean Rieux", "type": "morts", "note": "Courèges" },
  { "nom": "monument aux morts", "numero": 2, "voie": "allées", "rue": "Jules Guesde", "type": "morts", "note": "TGI" },
  { "nom": "monument aux morts", "numero": 33, "voie": "allées", "rue": "Jules Guesde", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 34, "voie": "allées", "rue": "Jules Guesde", "type": "morts", "note": "jardin Plantes" },
  { "nom": "monument aux morts", "numero": 37, "voie": "allées", "rue": "Jules Guesde", "type": "morts", "note": "faculté" },
  { "nom": "monument aux morts", "numero": 39, "voie": "allées", "rue": "Jules Guesde", "type": "morts", "note": "faculté" },
  { "nom": "monument aux morts", "numero": 6, "voie": "rue", "rue": "Kennedy", "type": "morts", "note": "PTT" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rue", "rue": "L.C. Pélissier", "type": "morts", "note": "église" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rue", "rue": "L.C. Pélissier", "type": "morts", "note": "Saint-Jérôme" },
  { "nom": "monument aux morts", "numero": 22, "voie": "rue", "rue": "Lacassagne", "type": "morts", "note": "école" },
  { "nom": "monument aux morts", "numero": 12, "voie": "place", "rue": "Lafourcade", "type": "morts", "note": "Gendarmerie" },
  { "nom": "monument aux morts", "numero": 102, "voie": "chem", "rue": "Lapujade", "type": "morts", "note": "colonies" },
  { "nom": "monument aux morts", "numero": 207, "voie": "avenue", "rue": "Lardenne", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 207, "voie": "rue", "rue": "Lardenne", "type": "morts", "note": "Saint-Michel" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rue", "rue": "Lautman", "type": "morts", "note": "faculté" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rte", "rue": "Lautmann", "type": "morts", "note": "Droit" },
  { "nom": "monument aux morts", "numero": 0, "voie": "rue", "rue": "Le Verrier", "type": "morts", "note": "Afrique Nord" },
  { "nom": "monument aux morts", "numero": 0, "voie": "rue", "rue": "Lizop", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "chem", "rue": "Loge", "type": "morts", "note": "Ariane Group" },
  { "nom": "monument aux morts", "numero": 14, "voie": "rue", "rue": "Longaud", "type": "morts", "note": "Berthelot" },
  { "nom": "monument aux morts", "numero": 0, "voie": "imp", "rue": "M. Bordelongue", "type": "morts", "note": "Martyrs" },
  { "nom": "monument aux morts", "numero": 22, "voie": "bd", "rue": "Marquette", "type": "morts", "note": "EDF" },
  { "nom": "monument aux morts", "numero": 48, "voie": "avenue", "rue": "Minimes", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 85, "voie": "avenue", "rue": "Minimes", "type": "morts", "note": "Retirada" },
  { "nom": "monument aux morts", "numero": 153, "voie": "avenue", "rue": "Muret", "type": "morts", "note": "St-Fs Xavier" },
  { "nom": "monument aux morts", "numero": 63, "voie": "chem", "rue": "Néboude", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 5, "voie": "rue", "rue": "Orient", "type": "morts", "note": "Loge" },
  { "nom": "monument aux morts", "numero": 2, "voie": "rue", "rue": "Palaprat", "type": "morts", "note": "synaguogue" },
  { "nom": "monument aux morts", "numero": 2, "voie": "place", "rue": "Patte d'Oie", "type": "morts", "note": "Sacré-Coeur" },
  { "nom": "monument aux morts", "numero": 135, "voie": "rue", "rue": "Périole", "type": "morts", "note": "Latécoère" },
  { "nom": "monument aux morts", "numero": 6, "voie": "rue", "rue": "Perroud", "type": "morts", "note": "Nexter" },
  { "nom": "monument aux morts", "numero": 64, "voie": "bd", "rue": "Pierre Sémard", "type": "morts", "note": "gare" },
  { "nom": "monument aux morts", "numero": 64, "voie": "bd", "rue": "Pierre Sémard", "type": "morts", "note": "gare" },
  { "nom": "monument aux morts", "numero": 6, "voie": "rue", "rue": "Reille", "type": "morts", "note": "Saint-Sylve" },
  { "nom": "monument aux morts", "numero": 45, "voie": "rue", "rue": "Riquet", "type": "morts", "note": "Saint-Aubin" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Roquelaine", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Saint-Aubin", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Saint-Etienne", "type": "morts", "note": "cathédrale" },
  { "nom": "monument aux morts", "numero": 0, "voie": "place", "rue": "Saint-Etienne", "type": "morts", "note": "cathédrale" },
  { "nom": "monument aux morts", "numero": 29, "voie": "avenue", "rue": "Saint-Exupéry", "type": "morts", "note": "anc. Lido" },
  { "nom": "monument aux morts", "numero": 40, "voie": "avenue", "rue": "Saint-Exupéry", "type": "morts", "note": "Saint-Joseph" },
  { "nom": "monument aux morts", "numero": 63, "voie": "avenue", "rue": "Saint-Exupéry", "type": "morts", "note": "" },
  { "nom": "monument aux morts", "numero": 18, "voie": "gde rue", "rue": "Saint-Michel", "type": "morts", "note": "prison" },
  { "nom": "monument aux morts", "numero": 81, "voie": "rue", "rue": "Saint-Roch", "type": "morts", "note": "caserne" },
  { "nom": "monument aux morts", "numero": 7, "voie": "rue", "rue": "Salenques", "type": "morts", "note": "faculté" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "Philippeville" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "indochinois" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "américains" },
  { "nom": "monument aux morts", "numero": 0, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "Belfort" },
  { "nom": "monument aux morts", "numero": 7, "voie": "cim.", "rue": "Salonique", "type": "morts", "note": "cimetière" },
  { "nom": "monument aux morts", "numero": 1, "voie": "rue", "rue": "San Subra", "type": "morts", "note": "église" },
  { "nom": "monument aux morts", "numero": 61, "voie": "chem", "rue": "Sang de Serp", "type": "morts", "note": "usine St-Eloi" },
  { "nom": "monument aux morts", "numero": 195, "voie": "rte", "rue": "Seysses", "type": "morts", "note": "arc Triomphe" },
  { "nom": "monument aux morts", "numero": 12, "voie": "rue", "rue": "Taur", "type": "morts", "note": "église" },
  { nom: 'monument aux morts', numero: 1, voie: 'cim.', rue: 'Terre-Cabade', type: 'morts', note: 'cimetière' },
  { nom: 'monument aux morts', numero: 5, voie: 'cim.', rue: 'Terre-Cabade', type: 'morts', note: 'cimetière' },
  { nom: 'monument aux morts', numero: 5, voie: 'cim.', rue: 'Terre-Cabade', type: 'morts', note: 'cimetière' },
  { nom: 'monument aux morts', numero: 4, voie: 'imp', rue: 'Trésorerie', type: 'morts', note: 'temple' },
  { nom: 'monument aux morts', numero: 114, voie: 'rue', rue: 'Troènes', type: 'morts', note: 'stade' },
  { nom: 'monument aux morts', numero: 114, voie: 'rue', rue: 'Troènes', type: 'morts', note: 'stade' },
  { nom: 'monument aux morts', numero: 0, voie: 'place', rue: 'Trois Cocus', type: 'morts', note: 'plaque' },
  { nom: 'monument aux morts', numero: 56, voie: 'avenue', rue: 'U.R.S.S.', type: 'morts', note: 'Normale' },
  { nom: 'monument aux morts', numero: 59, voie: 'avenue', rue: 'U.R.S.S.', type: 'morts', note: 'Ste-Germaine' },
  { nom: 'monument aux morts', numero: 59, voie: 'rue', rue: 'U.R.S.S.', type: 'morts', note: '' },
  { nom: 'monument aux morts', numero: 21, voie: 'rue', rue: 'Valade', type: 'morts', note: 'église' },
  { nom: 'monument aux morts', numero: 21, voie: 'rue', rue: 'Valade', type: 'morts', note: 'Chartreux' },
  { nom: 'monument aux morts', numero: 0, voie: 'place', rue: 'Vigneau', type: 'morts', note: '' },
  { nom: 'monument aux morts', numero: 2, voie: 'rue', rue: 'Viguerie', type: 'morts', note: 'hôpital' },
  { nom: 'monument aux morts', numero: 2, voie: 'rue', rue: 'Viguerie', type: 'morts', note: 'hôpital' },
  { nom: 'Mosquée Mirail', numero: 1, voie: 'place', rue: 'E. Bouillères', type: 'mosquée', note: '' },
  { nom: 'Masjid Omar Ibn Al-Khattab', numero: 3, voie: 'chem', rue: 'Edgard Varèse', type: 'mosquée', note: '' },
  { nom: 'Mosquée Turque', numero: 4, voie: 'rue', rue: 'Emile Baudot', type: 'mosquée', note: '' },
  { nom: 'Mosquée Rahma', numero: 59, voie: 'rue', rue: 'Faourette', type: 'mosquée', note: '' },
  { nom: 'Mosquée Tawhid', numero: 21, voie: 'rue', rue: 'Gramat', type: 'mosquée', note: '' },
  { nom: 'Mosquée al Fath', numero: 64, voie: 'chem', rue: 'Izards', type: 'mosquée', note: '' },
  { nom: 'Grande Mosquée', numero: 22, voie: 'rue', rue: 'Jean Lebas', type: 'mosquée', note: '' },
  { nom: 'Mosquée AS-Salam', numero: 1, voie: 'imp', rue: 'Londres', type: 'mosquée', note: '' },
  { nom: 'Mosquée (CTSM)', numero: 8, voie: 'rue', rue: 'Nivernais', type: 'mosquée', note: '' },
  { nom: 'moulin Touch', numero: 90, voie: 'rte', rue: 'Bayonne', type: 'moulin', note: '' },
  { nom: 'moulin à vent', numero: 0, voie: 'rte', rue: 'Bayonne', type: 'moulin', note: '' },
  { nom: 'moulin Touch', numero: 0, voie: 'imp', rue: 'Flambère', type: 'moulin', note: '' },
  { nom: 'moulin', numero: 0, voie: 'imp', rue: 'Flambère', type: 'moulin', note: '' },
  { nom: 'moulin à eau du Carquet', numero: 100, voie: 'chem', rue: 'Joël le Goff', type: 'moulin', note: '' },
  { nom: 'moulin à eau Comminges', numero: 0, voie: 'rue', rue: 'Peyrolade', type: 'moulin', note: '' },
  { nom: 'moulin Hers', numero: 21, voie: 'rue', rue: 'Rougenet', type: 'moulin', note: '' },
  { nom: 'Bazacle', numero: 11, voie: 'quai', rue: 'Saint-Pierre', type: 'moulin', note: '' },
  { nom: 'château Narbonais', numero: 0, voie: 'dallage', rue: 'Tounis', type: 'moulin', note: 'disparu' },
  { nom: 'poste du Pont de l\'Hers', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Paris', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste des Sept-Deniers', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Ginestous', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Montpellier', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Saint-Agne', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de messageries', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Fontaine Lestang', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Purpan', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'poste de Montaudran', numero: 0, voie: 'à voir', rue: '', type: 'octroi', note: '' },
  { nom: 'Salenques', numero: 0, voie: '1, r.', rue: 'des Salenques', type: 'ordre', note: '' },
  { nom: 'Carmélites', numero: 0, voie: '1, rue', rue: 'Périgord', type: 'ordre', note: '' },
  { nom: 'Dames d\'Andouin', numero: 0, voie: '14 - 16, rue', rue: 'des Arts', type: 'ordre', note: '' },
  { nom: 'Augustines', numero: 0, voie: '1bis, r', rue: 'St-Jérôme', type: 'ordre', note: '' },
  { nom: 'Bernardins', numero: 0, voie: '2, rue', rue: 'Salenques', type: 'ordre', note: '' },
  { nom: 'Sainte-Catherine de Sienne', numero: 0, voie: '20, rue', rue: 'Lafayette', type: 'ordre', note: '' },
  { nom: 'Doctrinaires', numero: 0, voie: '3, r', rue: 'Jules Chalande', type: 'ordre', note: '' },
  { nom: 'Oratoriens', numero: 0, voie: '33, 35, 37 r.', rue: 'Dalbade', type: 'ordre', note: '' },
  { nom: 'Augustines', numero: 0, voie: '47 - 49, r.', rue: 'Couteliers', type: 'ordre', note: '' },
  { nom: 'Madeleine', numero: 0, voie: '47 - 49, r.', rue: 'Couteliers', type: 'ordre', note: '' },
  { nom: 'Dames Noires', numero: 0, voie: '5, rue', rue: 'Astorg', type: 'ordre', note: '' },
  { nom: 'Hospitalières', numero: 0, voie: '5, rue', rue: 'Rivalz', type: 'ordre', note: '' },
  { nom: 'Capucins', numero: 0, voie: '57, rue', rue: 'Valade', type: 'ordre', note: '' },
  { nom: 'Bon-Pasteur', numero: 0, voie: '6, rue', rue: 'Hache', type: 'ordre', note: '' },
  { nom: 'Trinitaires', numero: 0, voie: '8 et 12 pl', rue: 'Trinité', type: 'ordre', note: '' },
  { nom: 'Dames du Bon Jésus', numero: 0, voie: '8, rue', rue: 'Régeans', type: 'ordre', note: '' },
  { nom: 'Visitandines', numero: 0, voie: '9, rue', rue: 'Périgord', type: 'ordre', note: '' },
  { nom: 'Tiercerettes', numero: 0, voie: 'à la r.', rue: 'Embarthe', type: 'ordre', note: '' },
  { nom: 'Carmes Déchaussés', numero: 0, voie: 'all.', rue: 'Jules Guesde', type: 'ordre', note: '' },
  { nom: 'Pères de Saint-Georges', numero: 0, voie: 'angle r', rue: 'St-Antoine du T', type: 'ordre', note: '' },
  { nom: 'Minimes', numero: 0, voie: 'aux', rue: 'Minimes', type: 'ordre', note: '' },
  { nom: 'Récollets', numero: 0, voie: 'bd', rue: 'Récollets', type: 'ordre', note: '' },
  { nom: 'Théarins', numero: 0, voie: 'commanderie', rue: 'du T', type: 'ordre', note: '' },
  { nom: 'Refuge', numero: 0, voie: 'Dame', rue: 'de Nevers', type: 'ordre', note: '' },
  { nom: 'Bénédictins', numero: 0, voie: 'Daurade', rue: '', type: 'ordre', note: '' },
  { nom: 'Urbanistes', numero: 0, voie: 'dites', rue: 'Sainte-Claire', type: 'ordre', note: '' },
  { nom: 'Dominicains', numero: 0, voie: 'gde rue', rue: 'Nazareth', type: 'ordre', note: '' },
  { nom: 'Dames de Sainte-Claire', numero: 0, voie: 'La', rue: 'Grave', type: 'ordre', note: '' },
  { nom: 'Primitive Observance', numero: 0, voie: 'La', rue: 'Grave', type: 'ordre', note: '' },
  { nom: 'Grands Augustins', numero: 0, voie: 'musée', rue: 'Augustins', type: 'ordre', note: '' },
  { nom: 'Religieuses de Notre-Dame', numero: 0, voie: 'Notre Dame', rue: 'du Sac', type: 'ordre', note: '' },
  { nom: 'Grands Carmes', numero: 0, voie: 'pl.', rue: 'Carmes', type: 'ordre', note: '' },
  { nom: 'Jacobiens', numero: 0, voie: 'pl.', rue: 'Jacobains', type: 'ordre', note: '' },
  { nom: 'Capucins', numero: 0, voie: 'place', rue: 'Anatole France', type: 'ordre', note: '' },
  { nom: 'Père de la Merci', numero: 0, voie: 'place', rue: 'Saint-Aubin', type: 'ordre', note: '' },
  { nom: 'Cordeliers', numero: 0, voie: 'rue', rue: 'Deville', type: 'ordre', note: '' },
  { nom: 'Dames de Sainte-Claire', numero: 0, voie: 'rue', rue: 'Fonderie', type: 'ordre', note: '' },
  { nom: 'Dames de Fourquevaux', numero: 0, voie: 'rue', rue: 'Orme sec', type: 'ordre', note: '' },
  { nom: 'Tierçaires', numero: 0, voie: 'rue', rue: 'Pargaminières', type: 'ordre', note: '' },
  { nom: 'pères de Saint-Antoine du Salin', numero: 0, voie: 'rue', rue: 'Pharaon', type: 'ordre', note: '' },
  { nom: 'Petits Augustins', numero: 0, voie: 'rue', rue: 'Saint-Antoine du T', type: 'ordre', note: '' },
  { nom: 'Dames de Saint-Panthaléon', numero: 0, voie: 'rue', rue: 'Saint-Pantaléon', type: 'ordre', note: '' },
  { nom: 'Dames de Saint-Sernin', numero: 0, voie: 'rue', rue: 'Sénéchal', type: 'ordre', note: '' },
  { nom: 'Providences', numero: 0, voie: 'rue', rue: 'Sénéchal', type: 'ordre', note: '' },
  { nom: 'Feuillants', numero: 0, voie: 'rue', rue: 'Teinturiers', type: 'ordre', note: '' },
  { nom: 'Grand Prieuré de Malte', numero: 0, voie: 'St-Jean', rue: 'de Malte', type: 'ordre', note: '' },
  { nom: 'Chartreux', numero: 0, voie: 'St-Pierre', rue: 'Chartreux', type: 'ordre', note: '' },
  { nom: 'Dames Maltaises', numero: 0, voie: 'vis-à-vis', rue: 'des Feuillants', type: 'ordre', note: '' },
  { nom: 'Feuillantines', numero: 0, voie: 'vis-à-vis', rue: 'des Feuillants', type: 'ordre', note: '' },
  { nom: 'Paroisse Orthodoxe Roumaine', numero: 185, voie: 'avenue', rue: 'Boudou', type: 'orthodoxe', note: 'Launaguet' },
  { nom: 'La Protection de la Mère de Dieu', numero: 185, voie: 'chem', rue: 'Boudou', type: 'orthodoxe', note: 'Launaguet' },
  { nom: 'Saint Nicolas le Thaumaturge', numero: 302, voie: 'avenue', rue: 'Grande-Bretagne', type: 'orthodoxe', note: '' },
  { nom: 'église orthodoxe Lourdes', numero: 2, voie: 'avenue', rue: 'Jean Prat', type: 'orthodoxe', note: 'Lourdes' },
  { nom: 'Église orthodoxe russe', numero: 108, voie: 'avenue', rue: 'Lavaur', type: 'orthodoxe', note: '' },
  { nom: 'La Nativité de la Mère de Dieu', numero: 162, voie: 'avenue', rue: 'Pic du Ger', type: 'orthodoxe', note: 'Muret' },
  { nom: 'église orthodoxe ukrainienne', numero: 8, voie: 'rue', rue: 'Ukraine', type: 'orthodoxe', note: 'Lourdes' },
  { nom: 'Kadampa Vajravarahi', numero: 6, voie: 'rue', rue: 'A. Fourtanier', type: 'pagode', note: '' },
  { nom: 'Sambacademia', numero: 110, voie: 'rue', rue: 'A. Viadieu', type: 'pagode', note: '' },
  { nom: 'Quang Duc', numero: 43, voie: 'rte', rue: 'Aussonne', type: 'pagode', note: 'Cornebarrieu' },
  { nom: 'Chùa Quảng Đức', numero: 43, voie: 'rte', rue: 'Aussonne', type: 'pagode', note: 'Cornebarrieu' },
  { nom: 'Sambacademia', numero: 36, voie: 'rue', rue: 'Filatiers', type: 'pagode', note: '' },
  { nom: 'rooftop du roya', numero: 61, voie: 'chem', rue: 'Lapujade', type: 'pagode', note: '' },
  { nom: 'Jardin japonais', numero: 0, voie: 'bd', rue: 'Lascrosses', type: 'pagode', note: 'Jardin japo.' },
  { nom: 'Wat Bodhidhamm', numero: 1, voie: 'rue', rue: 'Mésanges', type: 'pagode', note: 'Beauzelle' },
  { nom: 'khmer', numero: 125, voie: 'rte', rue: 'Toulouse', type: 'pagode', note: 'Cugnaux' },
  { nom: 'Khmers', numero: 125, voie: 'rte', rue: 'Toulouse', type: 'pagode', note: 'Cugnaux' },
  { nom: 'Linh Son', numero: 65, voie: 'rte', rue: 'Tournefeuille', type: 'pagode', note: 'Cugnaux' },
  { nom: 'Association Boudhisme Lao', numero: 1, voie: 'rue', rue: 'Trianon', type: 'pagode', note: '' },
  { nom: 'Sukyo Mahikari France', numero: 24, voie: 'rue', rue: 'Verrerie', type: 'pagode', note: '' },
  { nom: 'Pénitents bleus', numero: 2, voie: 'rue', rue: 'L. C. Pélissier', type: 'pénitents', note: '' },
  { nom: 'Pénitents noir', numero: 10, voie: 'rue', rue: 'Paul Mériel', type: 'pénitents', note: '' },
  { nom: 'Pénitents blancs', numero: 11, voie: 'rue', rue: 'Pénitents blancs', type: 'pénitents', note: '' },
  { nom: 'Pénitents gris', numero: 1, voie: 'rue', rue: 'Pénitents gris', type: 'pénitents', note: '' },
  { nom: 'Arnaud-Bernard', numero: 0, voie: 'place', rue: 'Arnaud-Bernard', type: 'porte rempart', note: 'ancien' },
  { nom: 'Saint-Etienne', numero: 0, voie: 'rue', rue: 'Bertrand de l\'Isle', type: 'porte rempart', note: 'ancien' },
  { nom: 'Porterie', numero: 0, voie: 'place', rue: 'Capitole', type: 'porte rempart', note: 'ancien' },
  { nom: 'Muret', numero: 0, voie: 'place', rue: 'Fer à Cheval', type: 'porte rempart', note: 'ancien' },
  { nom: 'Matabiau', numero: 0, voie: 'place', rue: 'Jeanne d\'Arc', type: 'porte rempart', note: 'ancien' },
  { nom: 'Lascrosses', numero: 0, voie: 'rue', rue: 'Lascrosses', type: 'porte rempart', note: 'ancien' },
  { nom: 'Pouzonville', numero: 0, voie: 'rue', rue: 'Merly', type: 'porte rempart', note: 'ancien' },
  { nom: 'Montoulieu', numero: 0, voie: 'place', rue: 'Montoulieu', type: 'porte rempart', note: 'ancien' },
  { nom: 'Montgaillard', numero: 0, voie: 'rue', rue: 'Ozenne', type: 'porte rempart', note: 'ancien' },
  { nom: 'Narbonnaise', numero: 1, voie: 'place', rue: 'Parlement', type: 'porte rempart', note: 'ancien' },
  { nom: 'Sardane', numero: 0, voie: 'rue', rue: 'Porte Sardane', type: 'porte rempart', note: 'ancien' },
  { nom: 'Porterie', numero: 0, voie: 'rue', rue: 'Porterie', type: 'porte rempart', note: 'ancien' },
  { nom: 'Isle', numero: 0, voie: 'rue', rue: 'Réclusane', type: 'porte rempart', note: 'ancien' },
  { nom: 'Neuve', numero: 51, voie: 'rue', rue: 'Rem Saint-Etienne', type: 'porte rempart', note: 'ancien' },
  { nom: 'Bazacle', numero: 11, voie: 'quai', rue: 'Saint-Pierre', type: 'porte rempart', note: 'ancien' },
  { nom: 'Comminges', numero: 0, voie: 'place', rue: 'Salin', type: 'porte rempart', note: 'ancien' },
  { nom: 'Taillefer', numero: 0, voie: 'rue', rue: 'Teinturiers', type: 'porte rempart', note: 'ancien' },
  { nom: 'Villeneuve', numero: 0, voie: 'place', rue: 'Victor Hugo', type: 'porte rempart', note: 'ancien' },
  { nom: 'ancienne prison militaire', numero: 0, voie: 'place', rue: 'hauts murats', type: 'prison', note: '' },
  { nom: 'Ravelin', numero: 0, voie: 'place', rue: 'Ravelin', type: 'ravelin', note: 'disparu' },
  { nom: 'Redoutes', numero: 0, voie: 'rue', rue: 'Redoutes', type: 'redoute', note: 'disparu' },
  { nom: 'Adath Israel', numero: 17, voie: 'rue', rue: 'Alsace Lorraine', type: 'synagogue', note: '' },
  { nom: 'Adath Yechouroun', numero: 3, voie: 'rue', rue: 'Jules Chalande', type: 'synagogue', note: '' },
  { nom: 'Jules Dalou', numero: 33, voie: 'rue', rue: 'Jules Dalou', type: 'synagogue', note: '' },
  { nom: 'Palaprat', numero: 2, voie: 'rue', rue: 'Palaprat', type: 'synagogue', note: '' },
  { nom: 'Chaare Emeth', numero: 35, voie: 'rue', rue: 'Rembrandt', type: 'synagogue', note: '' },
  { nom: 'Espace du Judaïsme', numero: 2, voie: 'rue', rue: 'Riquet', type: 'synagogue', note: '' },
  { nom: 'Église évangélique', numero: 30, voie: 'rue', rue: 'Adrien Legendre', type: 'temple', note: '' },
  { nom: 'Eglise CCR Balma', numero: 13, voie: 'rue', rue: 'André Citroën', type: 'temple', note: 'Balma' },
  { nom: 'Assemblée Chrétienne Morija', numero: 8, voie: 'imp', rue: 'André Marestan', type: 'temple', note: '' },
  { nom: 'ACT', numero: 8, voie: 'imp', rue: 'André Marestan', type: 'temple', note: '' },
  { nom: 'association témoins de Jéovah', numero: 0, voie: 'imp', rue: 'Bara', type: 'temple', note: '' },
  { nom: 'Toulouse International Church', numero: 33, voie: 'rte', rue: 'Bayonne', type: 'temple', note: '' },
  { nom: 'Eglise Protestante Evangelique', numero: 101, voie: 'rue', rue: 'Bonnat', type: 'temple', note: '' },
  { nom: 'Église protestante', numero: 108, voie: 'rue', rue: 'Bonnat', type: 'temple', note: '' },
  { nom: 'Église néo-apostolique', numero: 60, voie: 'chem', rue: 'Chapitre', type: 'temple', note: '' },
  { nom: 'BISERICA MARANATA PASTOR', numero: 17, voie: 'rue', rue: 'Charles Strickler', type: 'temple', note: '' },
  { nom: 'témoins de Jéovah', numero: 0, voie: 'rue', rue: 'Charonne', type: 'temple', note: '' },
  { nom: 'Espace Evangélique Protestant', numero: 6, voie: 'avenue', rue: 'Château d\'Eau', type: 'temple', note: 'culturel, Fonsorbes' },
  { nom: 'maison de maître', numero: 0, voie: 'rte', rue: 'Albi', type: 'villa', note: '' },
  { nom: 'maison bourgeoise', numero: 0, voie: 'rte', rue: 'Albi', type: 'villa', note: '' },
  { nom: 'villa des Palmiers', numero: 0, voie: 'rue', rue: 'Ammidonniers', type: 'villa', note: '' },
  { nom: 'villa Dufas-Marignac', numero: 52, voie: 'rue', rue: 'Pierre Molette', type: 'villa', note: '' },
  { nom: 'maison Cazeneuve', numero: 2, voie: 'gde rue', rue: 'Saint-Michel', type: 'villa', note: '' },
  { nom: 'orphelinat', numero: 41, voie: 'rue', rue: 'Achile Viadieu', type: 'orphelinat', note: '' },
  { nom: 'église', numero: 0, voie: 'place', rue: 'André Mathieu', type: 'chapelle mexicaine', note: '' },
  { nom: 'Collège Boulbonne, couvent, auj, imm. 1910 ?', numero: 12, voie: 'rue', rue: 'Arts', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent Dame Andouin : 14-16', numero: 14, voie: 'rue', rue: 'Arts', type: 'ancien monument', note: 'disparu' },
  { nom: 'Dames Noirs ou de St-Maur ou St Enfant Jésus', numero: 5, voie: 'rue', rue: 'Astorg', type: 'ancien monument', note: 'disparu' },
  { nom: 'Collège Boulbonne disp', numero: 21, voie: 'rue', rue: 'Boulbonne', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Ingolèse au milieu de la place', numero: 1, voie: 'place', rue: 'Bourse', type: 'ancien monument', note: 'disparu' },
  { nom: 'Maison Professe des Jésuites dispes; anc. Égl.', numero: 6, voie: 'rue', rue: 'Bourse', type: 'ancien monument', note: 'disparu' },
  { nom: 'et 24 rue Cujas, chappelles dont Ingolèse ?', numero: 19, voie: 'rue', rue: 'Bourse', type: 'ancien monument', note: 'disparu' },
  { nom: 'chap. du Mont-Carmel, à côté égl. des Carmes : 6 et 8', numero: '6 et 8', voie: 'rue', rue: 'Canard', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège des Pauvrets', numero: 1, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'coll St-Martial, rue Rommiguières, entrée pl Capitole', numero: 1, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Saint-Martial, grand hôtel de l\'Opéra', numero: 1, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'Saint-Martial, collège ou cloître ?', numero: 1, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'tour collège Saint-Martial : salon bar hôtel Opéra', numero: 1, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'égl St-Quentin : rue Porterie (entre r. St-Rome et Taur)', numero: 0, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Saint-Quentin : milieu place du Capitole', numero: 0, voie: 'place', rue: 'Capitole', type: 'ancien monument', note: 'disparu' },
  { nom: 'tête Christ 1821', numero: 16, voie: 'place', rue: 'Carmes', type: 'ancien monument', note: 'disparu' },
  { nom: 'ancien couvent', numero: 11, voie: 'rue', rue: 'Chaîne', type: 'ancien monument', note: 'disparu' },
  { nom: 'Jeu de Paume', numero: 13, voie: 'rue', rue: 'Chaîne', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent Religieuses Tiers Ordres St-François', numero: 0, voie: 'rue', rue: 'Chaîne', type: 'ancien monument', note: 'disparu' },
  { nom: 'bibliothèque Saint-Rome, tour Collège Saint-Rome', numero: 3, voie: 'rue', rue: 'Chalande', type: 'ancien monument', note: 'disparu' },
  { nom: 'Doctrinaires rue Saint-Rome', numero: 3, voie: 'rue', rue: 'Chalande', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Rieux', numero: 1, voie: 'rue', rue: 'Collège de Foix', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Rieux angle rue Lois et r. Coll. Foix, parall r C. F.', numero: 1, voie: 'rue', rue: 'Collège de Foix', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent Madeleine : 47 - 49', numero: '47 - 49', voie: 'rue', rue: 'Couteliers', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent Augustines : 47 - 49', numero: '47 - 49', voie: 'rue', rue: 'Couteliers', type: 'ancien monument', note: 'disparu' },
  { nom: 'ancienne église Sainte-Barbe', numero: 13, voie: 'rue', rue: 'Dalbade', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Notre Dame de la Conception : 13-15', numero: '13-15', voie: 'rue', rue: 'Dalbade', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent et église de la Visitation : 13-15', numero: '13-15', voie: 'rue', rue: 'Dalbade', type: 'ancien monument', note: 'disparu' },
  { nom: 'Congrégation de l\'Oratoire : 33-35-37', numero: '33-35-37', voie: 'rue', rue: 'Dalbade', type: 'ancien monument', note: 'disparu' },
  { nom: 'observatoire', numero: 4, voie: 'rue', rue: 'Darquier', type: 'ancien monument', note: 'disparu' },
  { nom: 'noviciat Jésuites', numero: 17, voie: 'quai', rue: 'Daurade', type: 'ancien monument', note: 'disparu' },
  { nom: 'écoles de théologie', numero: 1, voie: 'rue', rue: 'Deville', type: 'ancien monument', note: 'disparu' },
  { nom: 'Sœurs de Notre Dame de la Compassion', numero: 2, voie: 'rue', rue: 'Deville', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège de Narbonne : angle r Deville et r Al. Laut.', numero: 10, voie: 'rue', rue: 'Deville', type: 'ancien monument', note: 'disparu' },
  { nom: 'maison confrérie miséricorde', numero: 5, voie: 'rue', rue: 'Dumay', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Saint-Sauveur : clocher-mur halle aux grains', numero: 1, voie: 'place', rue: 'Dupuy', type: 'ancien monument', note: 'disparu' },
  { nom: 'cimetière St-Sauveur, de Halle aux grains à pl. Dupuy', numero: 1, voie: 'place', rue: 'Dupuy', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent des Tiercerettes', numero: 0, voie: 'rue', rue: 'Embarthes', type: 'ancien monument', note: 'disparu' },
  { nom: 'chappelle des bénédictines', numero: 1, voie: 'rue', rue: 'Emile Cartailhac', type: 'ancien monument', note: 'disparu' },
  { nom: 'Collège Papillon, angle r.Emile Cartailhac et pl. Peyrou', numero: 1, voie: 'rue', rue: 'Emile Cartailhac', type: 'ancien monument', note: 'disparu' },
  { nom: 'ancien cloître des dominicains', numero: 1, voie: 'rue', rue: 'Espinasse', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Saint-Géraud', numero: 10, voie: 'place', rue: 'Esquirol', type: 'ancien monument', note: 'disparu' },
  { nom: 'chappelle Saint-Géraud', numero: 12, voie: 'place', rue: 'Esquirol', type: 'ancien monument', note: 'disparu' },
  { nom: 'Sanctuaire, Halle de Pierre et marché couvert: 2 - 4 - 6 - 8', numero: '2 - 4 - 6 - 8', voie: 'place', rue: 'Esquirol', type: 'ancien monument', note: 'disparu' },
  { nom: 'halle de Pierre jusque 1862', numero: 0, voie: 'place', rue: 'Esquirol', type: 'ancien monument', note: 'disparu' },
  { nom: 'ancien hôtel Monnaie', numero: 1, voie: 'rue', rue: 'Fleurs', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Saint-Barthélémy', numero: 1, voie: 'rue', rue: 'Fleurs', type: 'ancien monument', note: 'disparu' },
  { nom: 'angle r. Nazareth et du Vieux-Raisin', numero: 1, voie: 'rue', rue: 'Fleurs', type: 'ancien monument', note: 'disparu' },
  { nom: 'observatoire', numero: 16, voie: 'rue', rue: 'Fleurs', type: 'ancien monument', note: 'disparu' },
  { nom: 'Clarisses', numero: 31, voie: 'rue', rue: 'Fonderie', type: 'ancien monument', note: 'disparu' },
  { nom: 'église des Gésu', numero: 1, voie: 'rue', rue: 'Furgole', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Ste Catherine ou de Pampelune', numero: 58, voie: 'rue', rue: 'Gambetta', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Saint-Catherine : clé de voûte, porte', numero: 58, voie: 'rue', rue: 'Gambetta', type: 'ancien monument', note: 'disparu' },
  { nom: 'tourelles collège Ste-Catherine, hôtel Crown Plaza', numero: 58, voie: 'rue', rue: 'Gambetta', type: 'ancien monument', note: 'disparu' },
  { nom: 'gauche maison inquisition : 6 & 8', numero: '6 & 8', voie: 'imp', rue: 'Hache', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent Bon Pasteur', numero: 6, voie: 'rue', rue: 'Hache', type: 'ancien monument', note: 'disparu' },
  { nom: 'Couvent Marie-Réparatrice : 6 & 8', numero: '6 & 8', voie: 'rue', rue: 'Hache', type: 'ancien monument', note: 'disparu' },
  { nom: 'jardin des Minorettes = Ste-Claire ou Clarisses', numero: 0, voie: 'rue', rue: 'Homme Armé', type: 'ancien monument', note: 'disparu' },
  { nom: 'Saint Orens ou de la Sainte-Croix', numero: '1b', voie: 'place', rue: 'Jeanne d\'Arc', type: 'ancien monument', note: 'disparu' },
  { nom: 'syna, entrée juifs', numero: 3, voie: 'rue', rue: 'Joutx Aigues', type: 'ancien monument', note: 'disparu' },
  { nom: 'temple', numero: 35, voie: 'rue', rue: 'Lafayette', type: 'ancien monument', note: 'disparu' },
  { nom: 'Bénédictines de Notre-Dame du Sac', numero: 17, voie: 'rue', rue: 'Larrey', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Saint-Jérôme', numero: '2 bis', voie: 'rue', rue: 'Lieutenant-Pélissier', type: 'ancien monument', note: 'disparu' },
  { nom: 'commanderie Saint-Antoine de Vienne', numero: '4 & 10', voie: 'rue', rue: 'Lieutenant-Pélissier', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège de Foix', numero: 9, voie: 'rue', rue: 'Lois', type: 'ancien monument', note: 'disparu' },
  { nom: 'Emplacement de la chapelle de Rieux', numero: 13, voie: 'rue', rue: 'Lois', type: 'ancien monument', note: 'disparu' },
  { nom: 'bas reliefs', numero: 17, voie: 'rue', rue: 'Lois', type: 'ancien monument', note: 'disparu' },
  { nom: 'Sainte-Epine', numero: 19, voie: 'rue', rue: 'Lois', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Esquile', numero: 34, voie: 'rue', rue: 'Lois', type: 'ancien monument', note: 'disparu' },
  { nom: 'écoles des Arts', numero: 34, voie: 'rue', rue: 'Lois', type: 'ancien monument', note: 'disparu' },
  { nom: 'Pénitents Noirs', numero: 0, voie: 'place', rue: 'Lucas', type: 'ancien monument', note: 'disparu' },
  { nom: 'Jésus Hostie', numero: 0, voie: 'rue', rue: 'Madeleine', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent', numero: 2, voie: 'rue', rue: 'Magne', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Gauthier, ex rue du Pont Neuf', numero: 0, voie: 'rue', rue: 'Metz', type: 'ancien monument', note: 'disparu' },
  { nom: 'Collège de Mirepoix', numero: 3, voie: 'rue', rue: 'Mirepoix', type: 'ancien monument', note: 'disparu' },
  { nom: 'Collège de Mirepoix', numero: 5, voie: 'rue', rue: 'Mirepoix', type: 'ancien monument', note: 'disparu' },
  { nom: 'école St-Thomas Acquin (façade hôtel Massencal)', numero: 40, voie: 'gde rue', rue: 'Nazareth', type: 'ancien monument', note: 'disparu' },
  { nom: 'Pension des Dames Berryes (Mansencal)', numero: 1, voie: 'rue', rue: 'Ninau', type: 'ancien monument', note: 'disparu' },
  { nom: 'Fac Théologie', numero: 8, voie: 'place', rue: 'Parlement', type: 'ancien monument', note: 'disparu' },
  { nom: 'Pénitents Noirs, inscription, tour', numero: 10, voie: 'rue', rue: 'Paul Mériel', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent des Carmélites', numero: 1, voie: 'rue', rue: 'Périgord', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent de la Visitation', numero: 9, voie: 'rue', rue: 'Périgord', type: 'ancien monument', note: 'disparu' },
  { nom: 'Sainte-Marie-de-Nevers', numero: 10, voie: 'rue', rue: 'Périgord', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège du Périgord', numero: 56, voie: 'rue', rue: 'Périgord', type: 'ancien monument', note: 'disparu' },
  { nom: 'Couvent Saint-Antoine de Lézat', numero: 18, voie: 'rue', rue: 'Pharaon', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent St François', numero: 20, voie: 'rue', rue: 'Pharaon', type: 'ancien monument', note: 'disparu' },
  { nom: 'monastère Saint-Antonin du Salin', numero: '18-20', voie: 'rue', rue: 'Pharaon', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Saint-Pantaléon', numero: 61, voie: 'rue', rue: 'Pomme', type: 'ancien monument', note: 'disparu' },
  { nom: 'halle poissons', numero: '12 & 14', voie: 'place', rue: 'pont-neuf', type: 'ancien monument', note: 'disparu' },
  { nom: 'prison de l\'écarlate', numero: 1, voie: 'imp', rue: 'Préfecture', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Saint-Pierre et Saint-Martin', numero: '3 & 5', voie: 'rue', rue: 'Prieuré', type: 'ancien monument', note: 'disparu' },
  { nom: 'Prieuré', numero: '5 - 5 bis', voie: 'rue', rue: 'Prieuré', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Saint-Pierre Saint-Martin', numero: '5 - 5 bis', voie: 'rue', rue: 'Prieuré', type: 'ancien monument', note: 'disparu' },
  { nom: 'derrière se trouve le couvent des Ursulines', numero: '5 - 5 bis', voie: 'rue', rue: 'Prieuré', type: 'ancien monument', note: 'disparu' },
  { nom: 'Ursulines', numero: '5 - 5 bis', voie: 'rue', rue: 'Prieuré', type: 'ancien monument', note: 'disparu' },
  { nom: 'oratoire Sainte-Marie des Fontaines (près pl Ravelin)', numero: 1, voie: 'place', rue: 'Ravelin', type: 'ancien monument', note: 'disparu' },
  { nom: 'Couvent S.N. de Jésus, chapelle', numero: 8, voie: 'rue', rue: 'Regans', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent Saint-Orens, entrée rue de la Poste', numero: 39, voie: 'rue', rue: 'Rémusat', type: 'ancien monument', note: 'disparu' },
  { nom: 'Hospitalières (rue Rivals) : verif La Poste', numero: 5, voie: 'rue', rue: 'Rivalz', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Saint-Barthélémy', numero: 25, voie: 'place', rue: 'Saint-Georges', type: 'ancien monument', note: 'disparu' },
  { nom: 'ancienne chambre souverraine du Clergé', numero: '9 & 11', voie: 'rue', rue: 'Saint-Jacques', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Saint-Jean angle r. Dalbade - Saint-Jean', numero: 1, voie: 'rue', rue: 'Saint-Jean', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle Mc Carthy', numero: 2, voie: 'rue', rue: 'Saint-Jean', type: 'ancien monument', note: 'disparu' },
  { nom: 'égl St-Georges reconstruite angle r St-Antoine du T', numero: 1, voie: 'rue', rue: 'Saint-Jérôme', type: 'ancien monument', note: 'disparu' },
  { nom: 'Augustines : couvent et leur chapelle se trouvaient', numero: '1b', voie: 'rue', rue: 'Saint-Jérôme', type: 'ancien monument', note: 'disparu' },
  { nom: 'Pénitents Noirs', numero: 0, voie: 'rue', rue: 'Saint-Jérôme', type: 'ancien monument', note: 'disparu' },
  { nom: 'don au collège Saint-Girons', numero: 12, voie: 'rue', rue: 'Saint-Rémésy', type: 'ancien monument', note: 'disparu' },
  { nom: 'halle aux poissons', numero: 18, voie: 'rue', rue: 'Saint-Rome', type: 'ancien monument', note: 'disparu' },
  { nom: 'Eglise Saint-Rome', numero: 24, voie: 'rue', rue: 'Saint-Rome', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Saint-Romain, reste bibliothèque', numero: 24, voie: 'rue', rue: 'Saint-Rome', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Saint-Romain', numero: 26, voie: 'rue', rue: 'Saint-Rome', type: 'ancien monument', note: 'disparu' },
  { nom: 'tourelle collège Ste-Catherine, hôtel Crown Plaza', numero: 42, voie: 'rue', rue: 'Saint-Rome', type: 'ancien monument', note: 'disparu' },
  { nom: 'Doctrinaires rue Saint-Rome', numero: '24 & 26', voie: 'rue', rue: 'Saint-Rome', type: 'ancien monument', note: 'disparu' },
  { nom: 'sœurs Saint-Vincent de Paul', numero: 1, voie: 'place', rue: 'Saint-Sernin', type: 'ancien monument', note: 'disparu' },
  { nom: 'chapelle N. D. des Bonnes Nouvelles', numero: 1, voie: 'place', rue: 'Saint-Sernin', type: 'ancien monument', note: 'disparu' },
  { nom: 'musée Saint-Raymond', numero: 2, voie: 'place', rue: 'Saint-Sernin', type: 'ancien monument', note: 'disparu' },
  { nom: 'monastère des dames bénédictines de Toulouse', numero: 3, voie: 'place', rue: 'Saint-Sernin', type: 'ancien monument', note: 'disparu' },
  { nom: 'Salanques ou Beguines', numero: 1, voie: 'rue', rue: 'Salenques', type: 'ancien monument', note: 'disparu' },
  { nom: 'Cloître des Bernardins', numero: 2, voie: 'rue', rue: 'Salenques', type: 'ancien monument', note: 'disparu' },
  { nom: 'verif 28 r Salanques ou 11bis', numero: '1b', voie: 'rue', rue: 'Salenques', type: 'ancien monument', note: 'disparu' },
  { nom: 'Bernardines (rue des Salenques)', numero: '1b', voie: 'rue', rue: 'Salenques', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Maguelonne', numero: 38, voie: 'rue', rue: 'Taur', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Esquile', numero: 69, voie: 'rue', rue: 'Taur', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Périgord', numero: '56 - 58', voie: 'rue', rue: 'Taur', type: 'ancien monument', note: 'disparu' },
  { nom: 'maison jeu de Paume', numero: 14, voie: 'rue', rue: 'Tolosane', type: 'ancien monument', note: 'disparu' },
  { nom: 'orphelinat', numero: 42, voie: 'rue', rue: 'Trente-six Ponts', type: 'orphelinat', note: '' },
  { nom: 'caserne', numero: '34, 36', voie: 'rue', rue: 'Trente-six Ponts', type: 'caserne', note: 'Pelet' },
  { nom: 'église Trinité dispe', numero: '8 & 12', voie: 'place', rue: 'Trinité', type: 'ancien monument', note: 'disparu' },
  { nom: 'cloître Trinitaire', numero: '8 & 12', voie: 'place', rue: 'Trinité', type: 'ancien monument', note: 'disparu' },
  { nom: 'église Trinité dispe', numero: '8 & 12', voie: 'rue', rue: 'Trinité', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent des trinitaires', numero: '8 & 12', voie: 'rue', rue: 'Trinité', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Secondat', numero: 42, voie: 'rue', rue: 'Valade', type: 'ancien monument', note: 'disparu' },
  { nom: 'collège Verdale', numero: 57, voie: 'rue', rue: 'Valade', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent des Capucins', numero: 57, voie: 'rue', rue: 'Valade', type: 'ancien monument', note: 'disparu' },
  { nom: 'bis ancien couvent', numero: '32bis', voie: 'rue', rue: 'Valade', type: 'ancien monument', note: 'disparu' },
  { nom: 'couvent des Capucins', numero: 57, voie: 'rue', rue: 'Valade', type: 'ancien monument', note: 'disparu' },
  { nom: 'bis ancien couvent', numero: '32bis', voie: 'rue', rue: 'Valade', type: 'ancien monument', note: 'disparu' }
];

export function GET() {
  return NextResponse.json(data);
}
