import { NextResponse } from 'next/server';

export async function GET() {
  const villes = [
    { rang: 1, nom: "Toulouse", dept: "Haute-Garonne (31)", pop: "514 819", info: "Capitale européenne de l'aéronautique et du spatial" },
    { rang: 2, nom: "Montpellier", dept: "Hérault (34)", pop: "310 240", info: "Métropole universitaire et centre médical de pointe" },
    { rang: 3, nom: "Nîmes", dept: "Gard (30)", pop: "151 839", info: "Rome française célèbre pour ses arènes intactes" },
    { rang: 4, nom: "Perpignan", dept: "Pyr.-Orientales (66)", pop: "121 616", info: "Capitale de la culture catalane et du Roussillon" },
    { rang: 5, nom: "Béziers", dept: "Hérault (34)", pop: "81 545", info: "Ville du rugby, de la vigne et du Canal du Midi" },
    { rang: 6, nom: "Montauban", dept: "Tarn-et-Garonne (82)", pop: "62 945", info: "Cité d'Ingres, bâtie en briques roses" },
    { rang: 7, nom: "Narbonne", dept: "Aude (11)", pop: "57 587", info: "Carrefour antique et station balnéaire (Narbonne-Plage)" },
    { rang: 8, nom: "Albi", dept: "Tarn (81)", pop: "51 290", info: "Cité épiscopale classée à l'UNESCO (Sainte-Cécile)" },
    { rang: 9, nom: "Alès", dept: "Gard (30)", pop: "46 520", info: "Capitale industrielle et porte des Cévennes" },
    { rang: 10, nom: "Carcassonne", dept: "Aude (11)", pop: "46 150", info: "Préfecture et plus grande cité médiévale d'Europe" },
    { rang: 11, nom: "Sète", dept: "Hérault (34)", pop: "45 480", info: "Ville portuaire, patrie de Brassens (l'Île Singulière)" },
    { rang: 12, nom: "Tarbes", dept: "Hautes-Pyrénées (65)", pop: "44 760", info: "Pôle industriel pyrénéen et ville des hussards" },
    { rang: 13, nom: "Castres", dept: "Tarn (81)", pop: "42 680", info: "Sous-préfecture, pôle de santé et siège de Pierre Fabre" },
    { rang: 14, nom: "Colomiers", dept: "Haute-Garonne (31)", pop: "41 420", info: "Premier pôle aéronautique (Toulouse Métropole)" },
    { rang: 15, nom: "Tournefeuille", dept: "Haute-Garonne (31)", pop: "30 490", info: "Banlieue résidentielle prisée de l'Ouest toulousain" },
    { rang: 16, nom: "Agde", dept: "Hérault (34)", pop: "30 150", info: "Station balnéaire majeure (Cap d'Agde) en pierre noire" },
    { rang: 17, nom: "Blagnac", dept: "Haute-Garonne (31)", pop: "28 460", info: "Siège mondial d'Airbus et aéroport international" },
    { rang: 18, nom: "Lunel", dept: "Hérault (34)", pop: "26 830", info: "Carrefour entre littoral, Camargue et vignobles" },
    { rang: 19, nom: "Muret", dept: "Haute-Garonne (31)", pop: "26 480", info: "Pôle urbain du sud toulousain et cité de l'aviation" },
    { rang: 20, nom: "Castelnau-le-Lez", dept: "Hérault (34)", pop: "26 210", info: "Première couronne montpelliéraine très dynamique" },
    { rang: 21, nom: "Rodez", dept: "Aveyron (12)", pop: "25 040", info: "Préfecture, cité médiévale et musée Soulages" },
    { rang: 22, nom: "Frontignan", dept: "Hérault (34)", pop: "24 010", info: "Littoral méditerranéen et célèbre Muscat" },
    { rang: 23, nom: "Auch", dept: "Gers (32)", pop: "23 480", info: "Capitale historique de la Gascogne (D'Artagnan)" },
    { rang: 24, nom: "Millau", dept: "Aveyron (12)", pop: "23 190", info: "Cité du Gant et porte du célèbre Viaduc" },
    { rang: 25, nom: "Cugnaux", dept: "Haute-Garonne (31)", pop: "21 780", info: "Pôle résidentiel et culturel du sud-ouest toulousain" },
    { rang: 26, nom: "Cahors", dept: "Lot (46)", pop: "20 520", info: "Préfecture, Pont Valentré et vignoble de Malbec" },
    { rang: 27, nom: "Plaisance-du-Touch", dept: "Haute-Garonne (31)", pop: "20 210", info: "Ville verte et dynamique de l'Ouest toulousain" },
    { rang: 28, nom: "Bagnols-sur-Cèze", dept: "Gard (30)", pop: "18 250", info: "Pôle industriel et technologique (Gard rhodanien)" },
    { rang: 29, nom: "Ramonville-St-Agne", dept: "Haute-Garonne (31)", pop: "18 210", info: "Technopole scientifique et port du Canal du Midi" },
    { rang: 30, nom: "Lattes", dept: "Hérault (34)", pop: "17 800", info: "Sud de Montpellier, zone protégée et littoral" },
    { rang: 31, nom: "Mauguio", dept: "Hérault (34)", pop: "17 150", info: "Aéroport de Montpellier et traditions camarguaises" },
    { rang: 32, nom: "Balma", dept: "Haute-Garonne (31)", pop: "17 050", info: "Est toulousain, pôle de services et sièges sociaux" },
    { rang: 33, nom: "Beaucaire", dept: "Gard (30)", pop: "16 100", info: "Ville d'Art et d'Histoire sur les bords du Rhône" },
    { rang: 34, nom: "Pamiers", dept: "Ariège (09)", pop: "15 950", info: "Capitale économique et ville la plus peuplée de l'Ariège" },
    { rang: 35, nom: "Gaillac", dept: "Tarn (81)", pop: "15 800", info: "Vignoble millénaire et patrimoine de briques" },
    { rang: 36, nom: "Saint-Gaudens", dept: "Haute-Garonne (31)", pop: "15 300", info: "Porte des Pyrénées centrales et belvédère naturel" },
    { rang: 37, nom: "Mende", dept: "Lozère (48)", pop: "15 100", info: "Plus haute préfecture de France, seule ville > 10k en Lozère" },
    { rang: 38, nom: "Castanet-Tolosan", dept: "Haute-Garonne (31)", pop: "14 900", info: "Sud-est toulousain, ville étape du Canal du Midi" },
    { rang: 39, nom: "Pont-Saint-Esprit", dept: "Gard (30)", pop: "13 900", info: "Carrefour entre Gard, Ardèche et Vaucluse" },
    { rang: 40, nom: "Lavaur", dept: "Tarn (81)", pop: "13 850", info: "Cité cathare et capitale du Pays de Cocagne" },
    { rang: 41, nom: "Villeneuve-lès-Avignon", dept: "Gard (30)", pop: "13 700", info: "Cité des Cardinaux face au Palais des Papes" },
    { rang: 42, nom: "Saint-Estève", dept: "Pyr.-Orientales (66)", pop: "13 500", info: "Dynamisme urbain dans la ceinture de Perpignan" },
    { rang: 43, nom: "Moissac", dept: "Tarn-et-Garonne (82)", pop: "13 400", info: "Abbaye classée à l'UNESCO et raisin Chasselas" },
    { rang: 44, nom: "Castelginest", dept: "Haute-Garonne (31)", pop: "13 100", info: "Pôle résidentiel en forte croissance du Nord toulousain" },
    { rang: 45, nom: "Canet-en-Roussillon", dept: "Pyr.-Orientales (66)", pop: "12 900", info: "Grande station balnéaire catalane et port de plaisance" },
    { rang: 46, nom: "Lourdes", dept: "Hautes-Pyrénées (65)", pop: "12 800", info: "Premier pôle hôtelier régional (Pèlerinage mondial)" },
    { rang: 47, nom: "Figeac", dept: "Lot (46)", pop: "12 400", info: "Pôle aéronautique lotois et ville de Champollion" },
    { rang: 48, nom: "Mèze", dept: "Hérault (34)", pop: "12 250", info: "Bassin de Thau (Ostréiculture et port de pêche)" },
    { rang: 49, nom: "Limoux", dept: "Aude (11)", pop: "11 900", info: "Cité de la Blanquette et du plus long carnaval" },
    { rang: 50, nom: "Bagnères-de-Bigorre", dept: "Hautes-Pyrénées (65)", pop: "11 800", info: "Thermalisme, casino et pied du Grand Tourmalet" },
    { rang: 51, nom: "Juvignac", dept: "Hérault (34)", pop: "9 950", info: "Banlieue ouest de Montpellier, ville thermale" },
    { rang: 52, nom: "Argelès-sur-Mer", dept: "Pyr.-Orientales (66)", pop: "9 880", info: "Station balnéaire majeure au pied des Albères" },
    { rang: 53, nom: "L'Union", dept: "Haute-Garonne (31)", pop: "9 820", info: "Banlieue nord-est résidentielle de Toulouse" },
    { rang: 54, nom: "Villefranche-de-Rouergue", dept: "Aveyron (12)", pop: "9 710", info: "Bastide royale et pôle économique de l'Ouest Aveyron" },
    { rang: 55, nom: "Saint-Jean", dept: "Haute-Garonne (31)", pop: "9 650", info: "Dynamisme résidentiel et commercial (Est toulousain)" },
    { rang: 56, nom: "Villeneuve-lès-Maguelone", dept: "Hérault (34)", pop: "9 580", info: "Entre étangs et mer, célèbre pour sa cathédrale isolée" },
    { rang: 57, nom: "Saint-Orens", dept: "Haute-Garonne (31)", pop: "9 490", info: "Pôle commercial et résidentiel majeur du Sud-Est" },
    { rang: 58, nom: "Pézenas", dept: "Hérault (34)", pop: "9 250", info: "Ville d'Art et d'Histoire, patrie de Molière" },
    { rang: 59, nom: "Pont-du-Casse", dept: "Tarn-et-Garonne (82)", pop: "9 100", info: "Pôle industriel et zone d'activité montalbanaise" },
    { rang: 60, nom: "Revel", dept: "Haute-Garonne (31)", pop: "8 950", info: "Bastide du meuble d'art et Lac de Saint-Ferréol" },
    { rang: 61, nom: "Auterive", dept: "Haute-Garonne (31)", pop: "8 800", info: "Centre industriel et commercial de la Vallée de l'Ariège" },
    { rang: 62, nom: "Uzès", dept: "Gard (30)", pop: "8 650", info: "Premier Duché de France, ville ducale préservée" },
    { rang: 63, nom: "Condom", dept: "Gers (32)", pop: "7 150", info: "Sous-préfecture et capitale de l'Armagnac" },
    { rang: 64, nom: "Graulhet", dept: "Tarn (81)", pop: "6 900", info: "Ancienne capitale mondiale du cuir" },
    { rang: 65, nom: "Lodève", dept: "Hérault (34)", pop: "6 750", info: "Sous-préfecture (Hérault profond) et ville d'art" },
    { rang: 66, nom: "Souillac", dept: "Lot (46)", pop: "6 400", info: "Porte du Périgord dans la Vallée de la Dordogne" },
    { rang: 67, nom: "Fleurance", dept: "Gers (32)", pop: "6 150", info: "Bastide gersoise réputée pour son festival d'astronomie" },
    { rang: 68, nom: "Ganges", dept: "Hérault (34)", pop: "5 800", info: "Porte sud des Cévennes et carrefour marchand" },
    { rang: 69, nom: "Luz-St-Sauveur", dept: "Hautes-Pyrénées (65)", pop: "5 400", info: "Pôle de haute montagne et thermalisme (Gavarnie)" },
    { rang: 70, nom: "Prades", dept: "Pyr.-Orientales (66)", pop: "5 150", info: "Sous-préfecture catalane au confluent du Canigou" },
    { rang: 71, nom: "Castelnaudary", dept: "Aude (11)", pop: "13 450", info: "Capitale mondiale du Cassoulet" },
    { rang: 72, nom: "Lézignan-Corbières", dept: "Aude (11)", pop: "13 250", info: "Centre viticole des Corbières" },
    { rang: 73, nom: "Fonsorbes", dept: "Haute-Garonne (31)", pop: "11 750", info: "Ouest toulousain résidentiel" },
    { rang: 74, nom: "L'Isle-Jourdain", dept: "Gers (32)", pop: "11 100", info: "Porte du Gers et pôle industriel" },
    { rang: 75, nom: "Saint-Orens-de-Gameville", dept: "Haute-Garonne (31)", pop: "10 800", info: "Pôle commercial du Sud-Est toulousain" },
    { rang: 76, nom: "Gratentour", dept: "Haute-Garonne (31)", pop: "9 150", info: "Forte expansion démographique au Nord de Toulouse" },
    { rang: 77, nom: "Saint-Gely-du-Fesc", dept: "Hérault (34)", pop: "8 910", info: "Commune résidentielle prisée au Nord de Montpellier" },
    { rang: 78, nom: "Céret", dept: "Pyr.-Orientales (66)", pop: "8 250", info: "Capitale de la cerise et musée d'Art Moderne" },
    { rang: 79, nom: "Saint-Jory", dept: "Haute-Garonne (31)", pop: "8 210", info: "Axe Toulouse-Montauban (Maraîchage et logistique)" },
    { rang: 80, nom: "Trèbes", dept: "Aude (11)", pop: "8 180", info: "Port sur le Canal du Midi, proche de Carcassonne" },
    { rang: 81, nom: "L'Isle-sur-Tarn", dept: "Tarn (81)", pop: "8 150", info: "Bastide historique célèbre pour sa place à arcades" },
    { rang: 82, nom: "Pins-Justaret", dept: "Haute-Garonne (31)", pop: "8 080", info: "Confluence des vallées au Sud de Toulouse" },
    { rang: 83, nom: "Pavie", dept: "Gers (32)", pop: "8 020", info: "Extension résidentielle et dynamique du Grand Auch" },
    { rang: 84, nom: "Portet-sur-Garonne", dept: "Haute-Garonne (31)", pop: "7 950", info: "Confluence Garonne-Ariège et pôle commercial" },
    { rang: 85, nom: "Léguevin", dept: "Haute-Garonne (31)", pop: "7 880", info: "Porte de la forêt de Bouconne (Ouest toulousain)" },
    { rang: 86, nom: "Grenade", dept: "Haute-Garonne (31)", pop: "7 750", info: "Bastide historique et sa halle médiévale classée" },
    { rang: 87, nom: "Balaruc-les-Bains", dept: "Hérault (34)", pop: "7 550", info: "Première station thermale de France (Étang de Thau)" },
    { rang: 88, nom: "Pignan", dept: "Hérault (34)", pop: "7 480", info: "Village de caractère de l'ouest montpelliérain" },
    { rang: 89, nom: "Odos", dept: "Hautes-Pyrénées (65)", pop: "7 350", info: "Ceinture résidentielle sud de Tarbes" },
    { rang: 90, nom: "Pibrac", dept: "Haute-Garonne (31)", pop: "7 280", info: "Cité de Sainte-Germaine, proche du pôle Airbus" },
    { rang: 91, nom: "Saint-Sulpice-la-Pointe", dept: "Tarn (81)", pop: "7 210", info: "Ville souterraine et carrefour Tarn / Haute-Garonne" },
    { rang: 92, nom: "Prades-le-Lez", dept: "Hérault (34)", pop: "7 150", info: "Vallée du Lez, cadre naturel préservé (Montpellier)" },
    { rang: 93, nom: "Vauvert", dept: "Gard (30)", pop: "6 950", info: "Capitale de la Petite Camargue gardoise" },
    { rang: 94, nom: "Launaguet", dept: "Haute-Garonne (31)", pop: "6 880", info: "Ville maraîchère devenue banlieue nord de Toulouse" },
    { rang: 95, nom: "Tarascon-sur-Ariège", dept: "Ariège (09)", pop: "6 780", info: "Carrefour des vallées et grottes préhistoriques" },
    { rang: 96, nom: "Gourdon", dept: "Lot (46)", pop: "6 650", info: "Cité médiévale, pôle central de la Bouriane" },
    { rang: 97, nom: "Roquettes", dept: "Haute-Garonne (31)", pop: "6 520", info: "Expansion résidentielle en bord de Garonne (Sud)" },
    { rang: 98, nom: "Vendargues", dept: "Hérault (34)", pop: "6 450", info: "Logistique et fortes traditions taurines" },
    { rang: 99, nom: "Quint-Fonsegrives", dept: "Haute-Garonne (31)", pop: "6 410", info: "Banlieue est très prisée (Santé et recherche)" },
    { rang: 100, nom: "Bruguières", dept: "Haute-Garonne (31)", pop: "6 350", info: "Dynamisme culturel au nord de Toulouse" },
    { rang: 101, nom: "Saint-Mathieu-de-Tréviers", dept: "Hérault (34)", pop: "6 280", info: "Au pied du Pic Saint-Loup (Vignobles)" },
    { rang: 102, nom: "Juillan", dept: "Hautes-Pyrénées (65)", pop: "6 210", info: "Proximité de l'aéroport et pôle aéronautique" },
    { rang: 103, nom: "Aucamville", dept: "Haute-Garonne (31)", pop: "6 080", info: "Banlieue nord dense, entre Toulouse et l'Union" },
    { rang: 104, nom: "Vic-en-Bigorre", dept: "Hautes-Pyrénées (65)", pop: "6 030", info: "Centre administratif et agricole du Val d'Adour" },
    { rang: 105, nom: "Elne", dept: "Pyr.-Orientales (66)", pop: "5 880", info: "Cité antique, ancienne capitale du Roussillon" },
    { rang: 106, nom: "Espalion", dept: "Aveyron (12)", pop: "5 820", info: "Traversée par le Lot, étape majeure de Saint-Jacques" },
    { rang: 107, nom: "Thuir", dept: "Pyr.-Orientales (66)", pop: "5 760", info: "Berceau du Byrrh et patrimoine industriel catalan" },
    { rang: 108, nom: "Fenouillet", dept: "Haute-Garonne (31)", pop: "5 730", info: "Zone commerciale et résidentielle (Toulouse Nord)" },
    { rang: 109, nom: "Le Boulou", dept: "Pyr.-Orientales (66)", pop: "5 710", info: "Thermalité et nœud stratégique vers l'Espagne" },
    { rang: 110, nom: "Beauzelle", dept: "Haute-Garonne (31)", pop: "5 630", info: "Cité aéronautique (proche du musée Aeroscopia)" },
    { rang: 111, nom: "Palavas-les-Flots", dept: "Hérault (34)", pop: "5 610", info: "Station balnéaire historique au sud de Montpellier" },
    { rang: 112, nom: "Gigean", dept: "Hérault (34)", pop: "5 540", info: "Village en pleine croissance près du Bassin de Thau" },
    { rang: 113, nom: "Bessières", dept: "Haute-Garonne (31)", pop: "5 510", info: "Dynamisme de la Vallée du Tarn (Nord-Est 31)" },
    { rang: 114, nom: "Bagnères-de-Luchon", dept: "Haute-Garonne (31)", pop: "5 490", info: "Reine des Pyrénées, thermalisme et grand ski" },
    { rang: 115, nom: "Saint-Juéry", dept: "Tarn (81)", pop: "5 410", info: "Pôle industriel historique de l'Albigeois" },
    { rang: 116, nom: "Marvejols", dept: "Lozère (48)", pop: "5 320", info: "Cité royale du Gévaudan, porte de l'Aubrac" },
    { rang: 117, nom: "Baziège", dept: "Haute-Garonne (31)", pop: "5 290", info: "Carrefour du Lauragais sur l'axe Toulouse-Narbonne" },
    { rang: 118, nom: "Carmaux", dept: "Tarn (81)", pop: "5 210", info: "Cité minière emblématique, berceau de Jaurès" },
    { rang: 119, nom: "Vic-Fezensac", dept: "Gers (32)", pop: "5 180", info: "Cité de caractère, capitale du Tempo Latino" },
    { rang: 120, nom: "Aigues-Mortes", dept: "Gard (30)", pop: "5 120", info: "Cité médiévale fortifiée et marais salants" },
    { rang: 121, nom: "Fabrègues", dept: "Hérault (34)", pop: "5 090", info: "Expansion résidentielle à l'ouest de Montpellier" },
    { rang: 122, nom: "Merville", dept: "Haute-Garonne (31)", pop: "5 060", info: "Célèbre pour son château et son grand labyrinthe" },
    { rang: 123, nom: "Mirepoix", dept: "Ariège (09)", pop: "5 010", info: "Bastide médiévale joyau de l'Ariège" },
    { rang: 124, nom: "Gimont", dept: "Gers (32)", pop: "4 990", info: "Capitale du foie gras" },
    { rang: 125, nom: "Villemoustaussou", dept: "Aude (11)", pop: "4 950", info: "Ceinture verte et résidentielle de Carcassonne" },
    { rang: 126, nom: "Montagnac", dept: "Hérault (34)", pop: "4 920", info: "Village viticole et d'art entre vignes et mer" }
  ];

  return NextResponse.json(villes);
}
