import { NextResponse } from 'next/server';

// Interface pour la structure des données des théâtres et salles de spectacle
interface Theatre {
    name: string;
    address: string;
    catégorie: string;
    url: string;
}

// Liste complète des théâtres et salles de spectacle de Toulouse et sa périphérie
const theatres: Theatre[] = [
    { name: "Théâtre du Capitole", address: "Place du Capitole, 31000 Toulouse", catégorie: "Théâtre", url: "https://opera.toulouse.fr/contact-et-infos-pratiques/" },
    { name: "Théâtre National de Toulouse (TNT) / Théâtre de la Cité", address: "22 Rue Saint-Pierre, 31000 Toulouse", catégorie: "Théâtre", url: "https://theatredelacite.com/" },
    { name: "Théâtre Sorano", address: "35 Avenue Jacques Douzans, 31000 Toulouse", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/theatre-sorano" },
    { name: "Théâtre du Grand Rond", address: "8 Rue des Amidonniers, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.grand-rond.fr/" },
    { name: "Théâtre Garonne", address: "1 Boulevard Léon Gambetta, 31000 Toulouse", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/theatre-garonne" },
    { name: "Théâtre Le Ring - Scènes Périphérique", address: "1 Rue Alfred de Musset, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.theatrelring.com/" },
    { name: "Théâtre du Pavé", address: "5 Rue du Pavé, 31300 Toulouse", catégorie: "Théâtre", url: "https://www.theatredupave.org/" },
    { name: "Théâtre du Fil à plomb", address: "1 Rue Jean Jaurès, 31100 Toulouse", catégorie: "Théâtre", url: "https://theatrelefilaplomb.fr/" },
    { name: "Théâtre des Mazades", address: "1 Avenue des Mazades, 31200 Toulouse", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-theatre-des-mazades" },
    { name: "Nouveau théâtre Jules-Julien", address: "1 Rue Jules-Julien, 31200 Toulouse", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/theatre-jules-julien" },
    { name: "Théâtre du Pont-Neuf (TPN)", address: "1 Place du Pont-Neuf, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.theatredupontneuf.fr/evenements/reservations/" },
    { name: "Théâtre de la Violette", address: "2 Rue de la Violette, 31200 Toulouse", catégorie: "Théâtre", url: "http://www.theatredelaviolette.com/" },
    { name: "Théâtre de Poche", address: "1 Rue du Poche, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.theatredepoche.com/" },
    { name: "Théâtre du Chien Blanc", address: "1 Rue du Chien Blanc, 31200 Toulouse", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/theatre-du-chien-blanc" },
    { name: "Théâtre Roquelaine (Stimuli Théâtre)", address: "1 Rue Roquelaine, 31000 Toulouse", catégorie: "Théâtre", url: "http://www.stimuli-theatre.fr/" },
    { name: "Café-théâtre les 3 T", address: "3 Rue des 3T, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.3tcafetheatre.com/spectacles/les-3t/" },
    { name: "Café-théâtre les Minimes / Café-théâtre Le 57", address: "57 Rue des Minimes, 31200 Toulouse", catégorie: "Théâtre", url: "https://www.le57.com/" },
    { name: "La Cave Poésie", address: "20 Rue Marcelin Albert, 31000 Toulouse", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/cave-poesie-rene-gouzenne" },
    { name: "La Comédie de Toulouse", address: "9 Rue des Tourneurs, 31000 Toulouse", catégorie: "Théâtre", url: "http://www.lacomediedetoulouse.com/" },
    { name: "Théâtre du Citron Bleu", address: "1 Rue du Citron Bleu, 31100 Toulouse", catégorie: "Théâtre", url: "https://www.lecitronbleu.fr/" },
    { name: "Théâtre Le Studio 55", address: "55 Rue du Studio, 31200 Toulouse", catégorie: "Théâtre", url: "https://www.studio-55.fr/" },
    { name: "Théâtre l'Ecluse", address: "1 Rue de l'Ecluse, 31000 Toulouse", catégorie: "Théâtre", url: "http://www.ecluse-prod.com/" },
    { name: "La Comédie de la Roseraie", address: "1 Rue de la Roseraie, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.comediedelaroseraie.fr/index.php/contact" },
    { name: "Le Chapeau Rouge - Espace Saint-Cyprien", address: "1 Rue Saint-Cyprien, 31300 Toulouse", catégorie: "Théâtre", url: "https://ma-source.info/annuaire/le-chapeau-rouge-espace-saint-cyprien/" },
    { name: "Grenier Théâtre", address: "1 Rue du Grenier, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.greniertheatre.org/infos-pratiques/" },
    { name: "Théâtre des sens", address: "1 Rue des Sens, 31000 Toulouse", catégorie: "Théâtre", url: "https://www.artcena.fr/annuaire/organismes/compagnie-des-sens" },
    { name: "Compagnie du dragon", address: "14 Rue Paul Dupin, 31000 Toulouse", catégorie: "Théâtre", url: "https://compagniedudragon.fr/" },
    { name: "Théâtre de verdure du Ramier", address: "18 Av. du Grand Ramier, 31400 Toulouse", catégorie: "Théâtre", url: "https://www.waze.com/fr/live-map/directions/fr/occitanie/toulouse/theatre-de-verdure-du-ramier?to=place.ChIJ599qJbO7rhIRxwHDmNYUx_8" },
    { name: "Théâtre de la Digue", address: "3 Rue de la Digue, 31300 Toulouse", catégorie: "Théâtre", url: "https://preprod.lanouvelledigue.com/" },
    { name: "Théâtre Le Hangar", address: "11 Rue des Cheminots, 31000 Toulouse", catégorie: "Théâtre", url: "http://www.lehangar.org" },
    { name: "Théâtre de verdure de Balma", address: "17 Rue Arthur Rimbaud, 31130 Balma (espace en plein air)", catégorie: "Théâtre", url: "https://www.pepinieresdulanguedoc.fr/Details/nos-references/39" },
    { name: "Théâtre 2 l'Acte", address: "151 Route de Blagnac, 31200 Toulouse", catégorie: "Théâtre", url: "https://www.theatre2lacte.com/" },
    { name: "Petit théâtre de la Chapelle Saint-Exupère", address: "Rue Saint-Exupère, 31700 Blagnac", catégorie: "Théâtre", url: "https://www.mairie-blagnac.fr/annuaires/equipements/equipement/petit-theatre-saint-exupere" },
    { name: "Théâtre Le Hangar", address: "Avenue Didier Daurat, 31700 Blagnac", catégorie: "Théâtre", url: "https://metropole.toulouse.fr/annuaire/theatre-le-hangar" },
    { name: "Petit Théâtre Saint-Exupère (Blagnac)", address: "1 Avenue Saint-Exupère, 31700 Blagnac", catégorie: "Théâtre", url: "https://www.mairie-blagnac.fr/annuaires/equipements/equipement/petit-theatre-saint-exupere" },
    { name: "Petit Théâtre du Centre (Colomiers)", address: "1 Rue du Centre, 31770 Colomiers", catégorie: "Théâtre", url: "https://billetterie.festik.net/petit-theatre-du-centre-colomiers/fr-agendafestik/" },
    { name: "Théâtre du Centre", address: "43 Rue du Centre, 31770 Colomiers", catégorie: "Théâtre", url: "http://theatreducentre-colomiers.com/" },
    { name: "Théâtre Municipal Marc Sebbah", address: "Place Léon Blum, 31600 Muret", catégorie: "Théâtre", url: "https://www.mairie-muret.fr/vie-culturelle/theatre" },
    { name: "Théâtre des Préambules", address: "22 Avenue Jacques Douzans, 31600 Muret", catégorie: "Théâtre", url: "http://theatredespreambules.com/" },
    { name: "La Théâtrerie Muret", address: "1 Square des Combattants d'Afrique du Nord, 31600 Muret", catégorie: "Théâtre", url: "https://www.mairie-muret.fr/muret-bouge/annuaire-des-associations/entr%C3%A9e/vue/77-la-th%C3%A9%C3%A2trerie-fabrique-d-art" },
    { name: "Théâtre Musical de Pibrac", address: "40 Rue Principale, 31820 Pibrac", catégorie: "Théâtre / Salle de spectacle", url: "https://tmp-pibrac.com/" },
    { name: "Théâtre du Hangar (Ramonville-Saint-Agne)", address: "17 Rue du Général de Gaulle, 31520 Ramonville-Saint-Agne", catégorie: "Théâtre", url: "https://www.lehangar.org/" },
    { name: "Grenier de Toulouse - The New Attic", address: "2 Rue George Sand, 31170 Tournefeuille", catégorie: "Théâtre", url: "https://www.grenierdetoulouse.fr/" },
    // SALLES DE SPECTACLE
    { name: "Halle aux Grains", address: "Rue des Filatiers, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/halle-aux-grains" },
    { name: "Zénith de Toulouse", address: "Boulevard Raymond Badiou, 31100 Toulouse", catégorie: "Salle de spectacle", url: "https://zenith-toulousemetropole.com/" },
    { name: "Auditorium de Saint-Pierre-des-Cuisines", address: "1 Rue Saint-Pierre, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/auditorium-saint-pierre-des-cuisines" },
    { name: "Casino-théâtre Barrière de Toulouse", address: "1 Boulevard de Strasbourg, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://www.casinosbarriere.com/fr/toulouse/infos-pratiques.html" },
    { name: "Salle Nougaro", address: "9 Rue Louis Plana, 31300 Toulouse", catégorie: "Salle de spectacle", url: "https://sallenougaro.com/" },
    { name: "Metronum", address: "1 Rue des Arts, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://lemetronum.fr/" },
    { name: "Le Bijou", address: "1 Rue du Bijou, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://www.le-bijou.net/" },
    { name: "Le Hangar de La Cépière", address: "8 Rue de Bagnolet, 31100 Toulouse", catégorie: "Salle de spectacle", url: "https://hangardelacepiere.org/" },
    { name: "Le Cap (Salle du CAP - Université Paul Sabatier)", address: "118 Route de Narbonne, 31400 Toulouse", catégorie: "Salle de spectacle", url: "https://culture.univ-tlse3.fr/" },
    { name: "Le Port (Centre Culturel Le Port)", address: "38 Route de Saint-Simon, 31100 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-le-port" },
    { name: "Le 111 Lunares", address: "111 Avenue des Minimes, 31200 Toulouse", catégorie: "Salle de spectacle", url: "http://www.le111lunares.com/" },
    { name: "Le Mandala", address: "11 Rue des Amidonniers, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://www.le-mandala.com/" },
    { name: "La Cabane", address: "16 ter Av. Raymond Badiou, 31300 Toulouse", catégorie: "Salle de spectacle", url: "https://www.la-cabane-toulouse.com/" },
    { name: "Le Rex (salle de concert)", address: "15 Av. Honoré Serres, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://www.lerextoulouse.com/fr/contact/infos/" },
    { name: "Salle Nougaro", address: "20 Chem. de Garric, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://sallenougaro.com/infos-pratiques/comment-reserver/" },
    { name: "Le 57", address: "57 Boulevard des Minimes, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://www.le57.com/" },
    { name: "La Petite Scène", address: "18 Rue Maurice Fonvieille, 31000 Toulouse", catégorie: "Salle de spectacle", url: "" },
    { name: "Le 9", address: "9 Rue Louis-François Lejeune, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://www.reservationsle9.fr/" },
    { name: "Salle du Sénéchal", address: "17 rue de Rémusat, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/agenda/la-pause-musicale-septembre-decembre-2025" },
    { name: "Le Kalinka", address: "10 bis Rue des Teinturiers, 31300 Toulouse", catégorie: "Salle de spectacle", url: "https://www.lekalinka.com/" },
    { name: "Espace Roguet", address: "9 rue de Gascogne, 31300 Toulouse", catégorie: "Salle de spectacle", url: "https://www.haute-garonne.fr/service/espace-roguet" },
    { name: "Le Taquin Jazz Club", address: "23 Rue des Amidonniers, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://www.le-taquin.fr/" },
    { name: "Péniche Le Cri de la Mouette", address: "78 Allée de Barcelone, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://shotgun.live/fr/venues/le-cri-de-la-mouette" },
    { name: "Lieu NEUFNEUF (Anciennement Le Ring)", address: "151 Route de Blagnac, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/lieu-neufneuf" },
    { name: "Le Chorus", address: "144 Avenue de Muret, Entrée par la Rue de la Digue, 31300 Toulouse", catégorie: "Salle de spectacle", url: "https://www.livetonight.fr/cafe-bar-restaurant-musique-live/717-le-chorus" },
    { name: "Cabaret La Vénus", address: "388 Avenue des États-Unis, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://lavenus-toulouse.com/contact/" },
    { name: "Samba Résille", address: "38 rue Roquelaine, 31000 TOULOUSE", catégorie: "Salle de spectacle", url: "http://www.samba-resille.org/" },
    { name: "Espace JOB", address: "105 Route de Blagnac, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-espace-job" },
    { name: "Salle des Fêtes de Limayrac", address: "22 Rue Xavier Darasse, 31500 Toulouse", catégorie: "Salle de spectacle", url: "http://www.val-de-limayrac.info/info-limayrac/activites-salle.php" },
    { name: "Centre culturel Renan (Salle des Fêtes)", address: "5 Chemin d'Audibert, 31200 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-renan" },
    { name: "L'Odyssée Spectacle", address: "29 Av. Antoine de Saint-Exupéry, 31400 Toulouse", catégorie: "Salle de spectacle", url: "https://www.lo-spectacle.com/" },
    { name: "Centre culturel La Brique Rouge", address: "9 Rue Maria Mombiola, 31400 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-la-brique-rouge" },
    { name: "Mac-Capsule culturelle", address: "1 Rue Saunière, 31000 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-mac-capsule-culturelle" },
    { name: "Labo Des Arts", address: "8 Rue Clément, 31500 Toulouse", catégorie: "Salle de spectacle", url: "https://www.labodesarts.fr/" },
    { name: "Le Lido (Centre des Arts du Cirque)", address: "14 Rue de la Tour, 31300 Toulouse", catégorie: "Salle de spectacle", url: "https://www.arts-du-cirque.toulouse.fr/" },
    { name: "Centre culturel Alban-Minville", address: "1 Pl. Martin Luther King, 31100 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/centre-culturel-alban-minville" },
    { name: "Espace Allegria", address: "110 Rue Achille Viadieu, 31400 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/espace-allegria" },
    { name: "Pavillon République (Hôtel du Département)", address: "1 Bd de la Marquette, 31090 Toulouse", catégorie: "Salle de spectacle", url: "https://metropole.toulouse.fr/annuaire/hotel-du-departement-pavillon-republique" },
    { name: "Salle Georges Brassens", address: "8 Rue des Écoles, 31140 Aucamville", catégorie: "Salle de spectacle", url: "https://www.ville-aucamville.fr/salle-georges-brassens/" },
    { name: "Espace Culturel La Gare (Aussonne)", address: "135 Avenue de la Gare, 31840 Aussonne", catégorie: "Salle de spectacle", url: "https://www.aussonne.fr/la-mairie/services-municipaux/salles-communales/espace-culturel-la-gare/" },
    { name: "Interférence", address: "56 Route de Lavaur, 31130 Balma", catégorie: "Salle de spectacle", url: "https://www.interference-toulouse.fr/" },
    { name: "La Grainerie (Fabrique des Arts du Cirque et de l'Itinérance)", address: "61 Rue Saint-Jean, 31130 Balma", catégorie: "Salle de spectacle", url: "https://www.la-grainerie.net/" },
    { name: "Auditorium de Balma", address: "Place de la Libération, 31130 Balma", catégorie: "Salle de spectacle", url: "https://www.mairie-balma.fr/culture/auditorium-de-balma" },
    { name: "Odyssud", address: "4 avenue du Parc, 31706 Blagnac Cedex", catégorie: "Salle de spectacle", url: "https://www.odyssud.com/" },
    { name: "Le Bascala", address: "12 Rue de la Briqueterie, 31150 Bruguières", catégorie: "Salle de spectacle", url: "https://www.le-bascala.com/" },
    { name: "Espace Jacques-Brel (Castanet-Tolosan)", address: "Rue des Champs Pinsons, 31320 Castanet-Tolosan", catégorie: "Salle de spectacle", url: "https://www.castanet-tolosan.fr/ville-pratique/annuaire-des-services/espace-jacques-brel-79.html" },
    { name: "Espace Culturel La Prairie (Castelginest)", address: "39 Route de Toulouse, 31780 Castelginest", catégorie: "Salle de spectacle", url: "https://www.mairie-castelginest.fr/les-salles-municipales-a-votre-disposition/" },
    { name: "L'Aria", address: "1 Rue du 11 Novembre 1918, 31700 Cornebarrieu", catégorie: "Salle de spectacle", url: "https://www.cornebarrieu.fr/la-culture/laria/" },
    { name: "L'Odyssée - Nouvelle Salle des Fêtes (Cugnaux)", address: "24 Rue du Guesclin, 31270 Cugnaux", catégorie: "Salle de spectacle", url: "https://www.cugnaux.fr/fr/cadre-de-vie/location-de-salles/lodyssee-nouvelle-salle-des-fetes.html" },
    { name: "Salle Molière", address: "153 Rue Saturne, 31140 Launaguet", catégorie: "Salle de spectacle", url: "http://www.mairie-launaguet.fr/salle-moliere.html" },
    { name: "Espace culturel Albert Camus (Launaguet)", address: "Impasse des Arènes, 31140 Launaguet", catégorie: "Salle de spectacle", url: "http://www.mairie-launaguet.fr/espace-culturel-albert-camus.html" },
    { name: "Le Tempo (Léguevin)", address: "Avenue de Gascogne, 31490 Léguevin", catégorie: "Salle de spectacle", url: "https://www.ville-leguevin.fr/culture/tempo-salle-de-spectacle/" },
    { name: "Salle polyvalente de Montgiscard", address: "Chemin des Écoliers, 31450 Montgiscard", catégorie: "Salle de spectacle", url: "https://www.montgiscard.com/salle-polyvalente/" },
    { name: "Salle Horizon Pyrénées", address: "Av. des Pyrénées, 31600 Muret", catégorie: "Salle de spectacle", url: "https://www.mairie-muret.fr/salle-horizon-pyrenees" },
    { name: "Le Château des Confluences (Pinsaguel)", address: "Chemin de la Poutre, 31120 Pinsaguel", catégorie: "Salle de spectacle", url: "https://www.chateaudesconfluences.fr/" },
    { name: "L'Onyx - Salle de spectacle Espace Monestié", address: "1 Rue des Fauvettes, 31830 Plaisance-du-Touch", catégorie: "Salle de spectacle", url: "https://www.plaisancedutouch.fr/culture-et-animations/lonys-espace-monestie" },
    { name: "Espace culturel Le Colombier (Plaisance-du-Touch)", address: "16 Rue des Fauvettes, 31830 Plaisance-du-Touch", catégorie: "Salle de spectacle", url: "https://www.plaisancedutouch.fr/culture-et-animations/le-colombier" },
    { name: "Salle Angèle del Rio Bettini", address: "All. du Grand Chêne, 31120 Portet-sur-Garonne", catégorie: "Salle de spectacle", url: "https://www.portet-sur-garonne.fr/salles-communales/" },
    { name: "Salle du Confluent", address: "6 Rue de l'Hôtel de Ville, 31120 Portet-sur-Garonne", catégorie: "Salle de spectacle", url: "https://www.portet-sur-garonne.fr/salles-communales/" },
    { name: "La Fontaine (Préserville)", address: "Impasse du Pradou, 31570 Préserville", catégorie: "Salle de spectacle", url: "https://www.mairie-preserville.fr/la-mairie/informations-pratiques/salle-de-la-fontaine-location/" },
    { name: "Le Bikini", address: "Rue Théodore Monod, Parc Technologique du Canal, 31520 Ramonville-Saint-Agne", catégorie: "Salle de spectacle", url: "https://lebikini.com/" },
    { name: "Péniche Didascalie", address: "Port-Sud, Rue Federico Garcia Lorca, 31520 Ramonville-Saint-Agne", catégorie: "Salle de spectacle", url: "http://www.penichedidascalie.com/" },
    { name: "Espace Palumbo", address: "33 Ter Rte d'Albi, 31240 Saint-Jean", catégorie: "Salle de spectacle", url: "https://www.mairie-saint-jean.fr/fr/lieux/espace-palumbo" },
    { name: "Espace Culturel La Ramée (Saint-Jory)", address: "Place du Château, 31790 Saint-Jory", catégorie: "Salle de spectacle", url: "https://www.saint-jory.fr/mon-quotidien/culture/espace-culturel-la-ramee-2029/" },
    { name: "Altigone", address: "1 bis Place Jean Bellières, 31650 Saint-Orens-de-Gameville", catégorie: "Salle de spectacle", url: "https://www.altigone.fr/" },
    { name: "L’Entretoise (Seysses)", address: "Rue du Onze Novembre 1918, 31600 Seysses", catégorie: "Salle de spectacle", url: "https://www.seysses.fr/culture/l-entretoise/" },
    { name: "Le Phare", address: "32 Route de Tarbes, 31170 Tournefeuille", catégorie: "Salle de spectacle", url: "https://lephare-tournefeuille.com/" },
    { name: "L’Escale", address: "Place de la Mairie, 31170 Tournefeuille", catégorie: "Salle de spectacle", url: "https://lescale-tournefeuille.fr/" },
    { name: "L'Usine (Tournefeuille)", address: "6 Impasse Marcel-Cavaillé, 31170 Tournefeuille", catégorie: "Salle de spectacle", url: "https://www.lusine.net/" },
    { name: "Grande Halle (L'Union)", address: "Boulevard Ratalens, 31240 L'Union", catégorie: "Salle de spectacle", url: "https://www.ville-lunion.fr/annuaire/grande-halle/" },
    { name: "Salle Horizon (L'Union)", address: "Boulevard Ratalens, 31240 L'Union", catégorie: "Salle de spectacle", url: "https://www.ville-lunion.fr/annuaire/salle-horizon/" },
    { name: "Château de la Garrigue", address: "980 Chem. de Pellausy, 31340 Villemur-sur-Tarn", catégorie: "Salle de spectacle", url: "https://www.chateaudelagarrigue.com/" },
];

// Gère les requêtes GET pour retourner la liste des théâtres et salles de spectacle
export async function GET() {
    return NextResponse.json(theatres);
}
