// src/app/api/museestoulouse/route.ts - Liste complète des lieux culturels et patrimoniaux de Toulouse et sa banlieue

import { NextRequest, NextResponse } from "next/server";

interface MuseePlace {
  id: number;           // Identifiant unique
  nomLieu: string;
  catégorie: string;
  num: string;
  typeRue: string;
  nomRue: string;
  site: string;       // Zone (Centre, Ouest, Banlieue Est, etc.)
  quartier: string;   // Quartier précis ou Ville pour la banlieue
  établissement: string; // Description de l'établissement/type de musée
  sigles: string;     // Sigles ou type court
  signification: string; // URL principale
  ville: string;      // Ajouté pour distinguer la ville (Toulouse ou Banlieue)
}

export async function GET(req: NextRequest) {
  const data: MuseePlace[] = [
    // ... (LIEUX DANS TOULOUSE : ID 1 à 67) ...

    // --- ARTS (1-11) ---
    { "id": 1, "nomLieu": "Fondation Bemberg Art classique", "catégorie": "Art", "num": "0", "typeRue": "Pl.", "nomRue": "d'Assezat", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Hôtel particulier, Musée d'Art", "sigles": "HDA", "signification": "http://www.fondation-bemberg.fr/fr", "ville": "Toulouse", "lat": 43.6001483, "lng": 1.4421916 },
    { "id": 2, "nomLieu": "Musée des Augustins Art classique", "catégorie": "Art", "num": "21", "typeRue": "Rue", "nomRue": "de Metz", "site": "Centre Ville", "quartier": "Saint-Étienne", "établissement": "Ancien Couvent, Musée Beaux-Arts", "sigles": "MBA", "signification": "http://www.augustins.org/", "ville": "Toulouse", "lat": 43.6007949, "lng": 1.446679 },
    { "id": 3, "nomLieu": "Musée de la photographie du Château d'Eau", "catégorie": "Art", "num": "1", "typeRue": "Pl.", "nomRue": "Laganne", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Galerie de Photographie", "sigles": "Ph", "signification": "http://www.galeriechateaudeau.org/", "ville": "Toulouse", "lat": 43.5987193, "lng": 1.4369378 },
    { "id": 4, "nomLieu": "Les Abattoirs Art Contemporain", "catégorie": "Art", "num": "76", "typeRue": "Allées", "nomRue": "Charles de Fitte", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Musée d'Art Contemporain", "sigles": "MAC", "signification": "http://www.lesabattoirs.org/", "ville": "Toulouse", "lat": 43.6008332, "lng": 1.4294097 },
    { "id": 5, "nomLieu": "Couvent des Jacobins", "catégorie": "Art", "num": "0", "typeRue": "Rue", "nomRue": "Lakanal", "site": "Centre Ville", "quartier": "Capitole", "établissement": "Monument Gothique (visite payante)", "sigles": "MH", "signification": "http://www.jacobins.toulouse.fr/", "ville": "Toulouse", "lat": 43.6034816, "lng": 1.4404851 },
    { "id": 6, "nomLieu": "Musée de l'Affiche (Matou)", "catégorie": "Art", "num": "58", "typeRue": "Allées", "nomRue": "Charles de Fitte", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Musée des arts graphiques", "sigles": "Matou", "signification": "http://www.toulouse-tourisme.com/matou-musee-de-l-affiche-de-toulouse/toulouse/pcumid031fs0004b", "ville": "Toulouse", "lat": 43.5987544, "lng": 1.4305196 },
    { "id": 7, "nomLieu": "BBB centre d'art", "catégorie": "Art", "num": "41", "typeRue": "Rue", "nomRue": "des Amidonniers", "site": "Ouest", "quartier": "Amidonniers", "établissement": "Centre d'Art Contemporain (CRAC)", "sigles": "BBB", "signification": "http://www.toulouse-tourisme.com/bbb-centre-d-art/toulouse/pcumid031v5015a7", "ville": "Toulouse", "lat": 43.6269848, "lng": 1.4474794 },
    { "id": 8, "nomLieu": "Palais des Beaux-Arts (ISDAT)", "catégorie": "Art", "num": "5", "typeRue": "Quai", "nomRue": "de la Daurade", "site": "Centre Ville", "quartier": "Daurade", "établissement": "École/Expositions Beaux-Arts", "sigles": "ISDAT", "signification": "http://www.isdat.fr/beaux-arts/presentation/", "ville": "Toulouse", "lat": 43.6002465, "lng": 1.4401922 },
    { "id": 9, "nomLieu": "Lieu-Commun centre d'art", "catégorie": "Art", "num": "25", "typeRue": "Rue", "nomRue": "des Amidonniers", "site": "Ouest", "quartier": "Amidonniers", "établissement": "Artist Run Space", "sigles": "LC", "signification": "http://www.toulouse-tourisme.com/lieu-commun-artist-run-space/toulouse/pcumid031v5015bg", "ville": "Toulouse", "lat": 43.6169496, "lng": 1.4560978 },
    { "id": 10, "nomLieu": "La Galerie 3.1", "catégorie": "Art", "num": "7", "typeRue": "Rue", "nomRue": "Jules Chalande", "site": "Centre Ville", "quartier": "Capitole", "établissement": "Galerie d'Art (Haute-Garonne)", "sigles": "HG", "signification": "https://www.haute-garonne.fr/service/la-galerie-31", "ville": "Toulouse", "lat": 43.602304, "lng": 1.444479 },
    { "id": 11, "nomLieu": "Micro-Folie Toulouse Ernest-Renan", "catégorie": "Art", "num": "5", "typeRue": "Chemin", "nomRue": "d'Audibert", "site": "Nord", "quartier": "Borderouge / Trois Cocus", "établissement": "Musée Numérique et Micro-Folie", "sigles": "MF", "signification": "https://metropole.toulouse.fr/annuaire/micro-folie-toulouse-ernest-renan", "ville": "Toulouse", "lat": 43.6364456, "lng": 1.4425251 },
    { "id": 12, "nomLieu": "Espace Cobalt", "catégorie": "Art", "num": "55", "typeRue": "Av.", "nomRue": "Louis Breguet", "site": "Sud-Est", "quartier": "Montaudran", "établissement": "Espace événementiel", "sigles": "EC", "signification": "https://www.abcsalles.com/lieu/espace-cobalt", "ville": "Toulouse", "lat": 43.5771884, "lng": 1.4755345 },

    // --- CIVILISATIONS (13-14) ---
    { "id": 13, "nomLieu": "Musée Georges Labit Antiquité", "catégorie": "Civilisations", "num": "43", "typeRue": "Rue", "nomRue": "des Martyrs de la Libération", "site": "Sud-Est", "quartier": "Saint-Sauveur", "établissement": "Arts d'Asie, Égypte ancienne", "sigles": "Labit", "signification": "http://www.museegeorgeslabit.fr/", "ville": "Toulouse", "lat": 43.5911015, "lng": 1.4584428 },
    { "id": 14, "nomLieu": "Ostal Occitania Maison de l'Occitanie", "catégorie": "Civilisations", "num": "11", "typeRue": "Rue", "nomRue": "Malaret", "site": "Centre Ville", "quartier": "Saint-Cyprien", "établissement": "Lieu d'Exposition Occitane", "sigles": "Ostal", "signification": "http://www.ostaldoccitania.net/", "ville": "Toulouse", "lat": 43.600704, "lng": 1.4432567 },

    // --- HISTOIRE (15-23) ---
    { "id": 15, "nomLieu": "Musée du Vieux-Toulouse", "catégorie": "Histoire", "num": "7", "typeRue": "Rue", "nomRue": "du May", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Histoire et Traditions locales", "sigles": "MVT", "signification": "http://toulousainsdetoulouse.fr/", "ville": "Toulouse", "lat": 43.6023916, "lng": 1.4432047 },
    { "id": 16, "nomLieu": "Musée Saint-Raymond Antiquité", "catégorie": "Histoire", "num": "1", "typeRue": "Pl.", "nomRue": "Saint-Sernin", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Musée Archéologique (Antiquité)", "sigles": "MSR", "signification": "http://saintraymond.toulouse.fr/", "ville": "Toulouse", "lat": 43.6078326, "lng": 1.4410633 },
    { "id": 17, "nomLieu": "Musée Archéologique Georges Baccrabère", "catégorie": "Histoire", "num": "31", "typeRue": "Rue", "nomRue": "de la Fonderie", "site": "Centre Ville", "quartier": "Saint-Cyprien", "établissement": "Espace muséographique (ICT)", "sigles": "ICT", "signification": "http://www.ict-toulouse.fr/espace-museographique-georges-baccrabere/", "ville": "Toulouse", "lat": 43.5955739, "lng": 1.4420005 },
    { "id": 18, "nomLieu": "Monument de la Résistance", "catégorie": "Histoire", "num": "1", "typeRue": "Allées", "nomRue": "Frédéric Mistral", "site": "Sud Centre", "quartier": "Jardin des Plantes", "établissement": "Mémorial", "sigles": "Mém", "signification": "http://www.toulouse-tourisme.com/le-monument-a-la-gloire-de-la-resistance/toulouse/pcumid031fs000a4", "ville": "Toulouse", "lat": 43.5917057, "lng": 1.4531196 },
    { "id": 19, "nomLieu": "Musée de la Résistance et Déportation", "catégorie": "Histoire", "num": "52", "typeRue": "Allée", "nomRue": "des Demoiselles", "site": "Sud", "quartier": "Saint-Michel", "établissement": "Musée Mémoriel (Seconde Guerre Mondiale)", "sigles": "MRD", "signification": "http://musee-resistance.haute-garonne.fr/", "ville": "Toulouse", "lat": 43.5889094, "lng": 1.4566329 },
    { "id": 20, "nomLieu": "Le Castelet ancienne prison", "catégorie": "Histoire", "num": "18 bis", "typeRue": "Gd Rue", "nomRue": "Saint-Michel", "site": "Sud", "quartier": "Saint-Michel", "établissement": "Monument historique / Patrimoine", "sigles": "LC", "signification": "https://metropole.toulouse.fr/annuaire/le-castelet", "ville": "Toulouse", "lat": 43.5861149, "lng": 1.4474162 },
    { "id": 21, "nomLieu": "IRIS Mémoires d'Espagne", "catégorie": "Histoire", "num": "15", "typeRue": "Rue", "nomRue": "Plaisance", "site": "Sud", "quartier": "Saint-Michel", "établissement": "Centre Doc. Exil Espagnol", "sigles": "IRIS", "signification": "https://iris-memoiresdespagne.com/", "ville": "Toulouse", "lat": 43.5888697, "lng": 1.4462248 },
    { "id": 22, "nomLieu": "Bibliothèque d'Étude et du Patrimoine", "catégorie": "Histoire", "num": "1", "typeRue": "Rue", "nomRue": "du Périgord", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Patrimoine écrit (expositions)", "sigles": "BEP", "signification": "https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-etude-et-patrimoine/", "ville": "Toulouse", "lat": 43.6078617, "lng": 1.4438475 },
    { "id": 23, "nomLieu": "Musée du Père Marie Antoine", "catégorie": "Histoire", "num": "0", "typeRue": "Pl.", "nomRue": "Saint-Sernin", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Petit musée (Basilique St-Sernin)", "sigles": "BSA", "signification": "https://basilique-saint-sernin.fr/petit-musee-pere-marie-antoine/", "ville": "Toulouse", "lat": 43.6058482, "lng": 1.4431532 },

    // --- INDUSTRIE (24-28) ---
    { id: 24, nomLieu: "Musée de l'Abeille", catégorie: "Industrie", num: "0", typeRue: "Rue", nomRue: "Riquet", site: "Est Centre", quartier: "Matabiau", établissement: "Musée d'apiculture", sigles: "Abeille", signification: "http://www.apiculture31.com/musee", ville: "Toulouse" },
    { id: 25, nomLieu: "Maison de la Violette", catégorie: "Industrie", num: "0", typeRue: "Bd.", nomRue: "Bonrepos", site: "Est Centre", quartier: "Matabiau", établissement: "Bateau-musée et boutique (Violette)", sigles: "Bateau", signification: "http://www.lamaisondelaviolette.com/fr/", ville: "Toulouse" },
    { id: 26, nomLieu: "MIN (Marché d'Intérêt National)", catégorie: "Industrie", num: "148", typeRue: "Av.", nomRue: "des États-Unis", site: "Nord", quartier: "Lalande", établissement: "Marché de gros (visites sur demande)", sigles: "MIN", signification: "http://www.toulouse-tourisme.com/grand-marche-d-interet-national-toulouse-occitanie/toulouse/pcumid031v502mlc", ville: "Toulouse" },
    { id: 27, nomLieu: "La Dépêche du Midi", catégorie: "Industrie", num: "0", typeRue: "Avenue", nomRue: "Jean Baylet", site: "Ouest", quartier: "Saint-Martin-du-Touch", établissement: "Siège du journal (visite sur demande)", sigles: "Presse", signification: "http://www.toulouse-tourisme.com/la-depeche-du-midi/toulouse/pcumid031fs00023", ville: "Toulouse" },
    { id: 28, nomLieu: "Setmi (société d'exploitation thermique du Mirail)", catégorie: "Industrie", num: "262", typeRue: "Route", nomRue: "de Launaguet", site: "Nord-Est", quartier: "Launaguet", établissement: "Usine de valorisation énergétique (visites)", sigles: "Usine", signification: "http://www.toulouse-tourisme.com/setmi-usine-de-valorisation-energetique-des-dechets/toulouse/pcumid031fs0096h", ville: "Toulouse" },

    // --- LOISIRS, SPECTACLES (29-30) ---
    { "id": 29, "nomLieu": "Halle aux Machines", "catégorie": "Loisirs, Spectacles", "num": "3", "typeRue": "Rue", "nomRue": "Eugène Montel", "site": "Sud-Est", "quartier": "Montaudran", "établissement": "Lieu de spectacle mécanique", "sigles": "LdM", "signification": "http://www.halledelamachine.fr/", "ville": "Toulouse", "lat": 43.5727854, "lng": 1.4780588 },
    { "id": 30, "nomLieu": "Aquarium (Fédération de pêche)", "catégorie": "Loisirs, Spectacles", "num": "134", "typeRue": "Route", "nomRue": "d'Espagne", "site": "Sud", "quartier": "Empalot", "établissement": "Aquarium et centre de pêche", "sigles": "Aqua", "signification": "http://www.fede-peche31.com/", "ville": "Toulouse", "lat": 43.5594498, "lng": 1.4236675 },

    // --- MONUMENTS (31-43) ---
    { "id": 31, "nomLieu": "EDF Bazacle, ancien moulin", "catégorie": "Monuments", "num": "11", "typeRue": "Quai", "nomRue": "du Bazacle", "site": "Centre Ville", "quartier": "Saint-Pierre", "établissement": "Ancien moulin, Espace d'exposition", "sigles": "MH, EDF", "signification": "http://www.toulouse-tourisme.com/espace-edf-bazacle/toulouse/pcumid031fs0003b", "ville": "Toulouse", "lat": 43.6033591, "lng": 1.4330965 },
    { "id": 32, "nomLieu": "Arènes Romaines de Purpan", "catégorie": "Monuments", "num": "51", "typeRue": "Allée", "nomRue": "d'Ancely", "site": "Ouest", "quartier": "Purpan", "établissement": "Vestiges antiques (Amphithéâtre et Thermes)", "sigles": "MH, Archéo", "signification": "http://www.toulouse-tourisme.com/amphitheatre-romain-de-purpan-et-thermes-d-ancely/toulouse/pcumid031fs0008e", "ville": "Toulouse", "lat": 43.6133096, "lng": 1.4013401 },
    { "id": 33, "nomLieu": "Trésor de la basilique Saint-Sernin", "catégorie": "Monuments", "num": "0", "typeRue": "Pl.", "nomRue": "Saint-Sernin", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Crypte et trésor (visite payante)", "sigles": "BSA", "signification": "http://www.basilique-saint-sernin.fr/reliques/", "ville": "Toulouse", "lat": 43.608381, "lng": 1.4418641 },
    { "id": 34, "nomLieu": "Salle des Illustres du Capitole", "catégorie": "Monuments", "num": "0", "typeRue": "Pl.", "nomRue": "du Capitole", "site": "Centre Ville", "quartier": "Capitole", "établissement": "Salle d'apparat de l'Hôtel de Ville", "sigles": "Mairie", "signification": "http://www.toulouse-tourisme.com/le-capitole-hotel-de-ville/toulouse/pcumid031fs000a3", "ville": "Toulouse", "lat": 43.6044737, "lng": 1.4442111 },
    { "id": 35, "nomLieu": "Chapelle Saint-Joseph de la Grave", "catégorie": "Monuments", "num": "0", "typeRue": "Pl.", "nomRue": "Lange", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Chapelle emblématique (ouverte événement)", "sigles": "MH", "signification": "http://www.toulouse-tourisme.com/chapelle-saint-joseph-de-la-grave/toulouse/pcumid031v50160o", "ville": "Toulouse", "lat": 43.6006126, "lng": 1.4326508 },
    { "id": 36, "nomLieu": "Chapelle des Carmélites", "catégorie": "Monuments", "num": "1", "typeRue": "Rue", "nomRue": "du Périgord", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Chapelle baroque (ouverte événement)", "sigles": "MH", "signification": "https://www.toulouse-tourisme.com/chapelle-des-carmelites/toulouse/pcumid031fs00094", "ville": "Toulouse", "lat": 43.6080516, "lng": 1.443586 },
    { "id": 37, "nomLieu": "Hôtel de Bernuy", "catégorie": "Monuments", "num": "5", "typeRue": "Rue", "nomRue": "Loi", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Hôtel particulier Renaissance", "sigles": "MH", "signification": "http://www.toulouse-tourisme.com/hotel-de-bernuy/toulouse/pcumid031fs0098w", "ville": "Toulouse", "lat": 43.6039578, "lng": 1.4418978 },
    { "id": 38, "nomLieu": "Crypte Archéologique St-Pierre des Cuisines", "catégorie": "Monuments", "num": "19", "typeRue": "Rue", "nomRue": "de la Fonderie", "site": "Centre Ville", "quartier": "Saint-Cyprien", "établissement": "Vestiges paléochrétiens", "sigles": "MH, Archéo", "signification": "http://saintraymond.toulouse.fr/La-basilique-funeraire-de-Saint-Pierre-des-Cuisines_a95.html", "ville": "Toulouse", "lat": 43.6046026, "lng": 1.4355554 },
    { "id": 39, "nomLieu": "Hôtel-Dieu Saint-Jacques (Salles Patrimoniales)", "catégorie": "Monuments", "num": "2", "typeRue": "Rue", "nomRue": "Viguerie", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Salles patrimoniales (visite)", "sigles": "MH, CHU", "signification": "http://www.chu-toulouse.fr/-salles-patrimoniales-de-l-hotel-dieu-saint-", "ville": "Toulouse", "lat": 43.5996677, "lng": 1.4369796 },
    { "id": 40, "nomLieu": "Maison Seilhan des Dominicains (Inquisition)", "catégorie": "Monuments", "num": "12", "typeRue": "Pl.", "nomRue": "du Parlement", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Maison de l'Inquisition, Saint-Dominique", "sigles": "Maison", "signification": "https://metropole.toulouse.fr/annuaire/maison-seilhan", "ville": "Toulouse", "lat": 43.5937171, "lng": 1.4442749 },
    { "id": 41, "nomLieu": "Crypte Archéologique du Palais de Justice", "catégorie": "Monuments", "num": "0", "typeRue": "Pl.", "nomRue": "du Salin", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Vestiges de l'Ancien Parlement", "sigles": "Archéo", "signification": "https://metropole.toulouse.fr/annuaire/ancien-parlement-palais-de-justice", "ville": "Toulouse", "lat": 43.5934149, "lng": 1.4447094 },
    { "id": 42, "nomLieu": "Cimetière Terre-Cabade Salonique Hérédia", "catégorie": "Monuments", "num": "135", "typeRue": "Rue", "nomRue": "du Faubourg Bonnefoy", "site": "Est", "quartier": "Bonnefoy", "établissement": "Cimetière historique, Patrimoine funéraire", "sigles": "Patrimoine", "signification": "https://metropole.toulouse.fr/annuaire/cimetiere-terre-cabade", "ville": "Toulouse", "lat": 43.6094396, "lng": 1.4632837 },
    { "id": 43, "nomLieu": "Église du Gesù", "catégorie": "Monuments", "num": "22", "typeRue": "Rue", "nomRue": "des Fleurs", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Édifice religieux", "sigles": "MH", "signification": "https://fr.wikipedia.org/wiki/%C3%89glise_du_Ges%C3%B9_de_Toulouse", "ville": "Toulouse", "lat": 43.5941913, "lng": 1.4452077 },

    // --- PATRIMOINE (44-49) ---
    { "id": 44, "nomLieu": "Musée Paul Dupuy des arts précieux", "catégorie": "Patrimoine", "num": "13", "typeRue": "Rue", "nomRue": "de la Pleau", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Arts graphiques et décoratifs", "sigles": "AMPD", "signification": "http://www.ampdupuy.fr/", "ville": "Toulouse", "lat": 43.5969665, "lng": 1.4469387 },
    { "id": 45, "nomLieu": "Musée du Compagnonnage", "catégorie": "Patrimoine", "num": "12", "typeRue": "Rue", "nomRue": "Tripière", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Musée des savoir-faire", "sigles": "Comp", "signification": "http://www.museecompagnonnage.fr/", "ville": "Toulouse", "lat": 43.6017316, "lng": 1.4430219 },
    { "id": 46, "nomLieu": "Maison des Compagnons du Devoir", "catégorie": "Patrimoine", "num": "28", "typeRue": "Rue", "nomRue": "Pyrénées", "site": "Centre Ville", "quartier": "Carmes", "établissement": "Maison de formation et d'accueil", "sigles": "Comp", "signification": "http://www.compagnons-du-devoir.com/la-maison-de-toulouse", "ville": "Toulouse", "lat": 43.5870766, "lng": 1.4556995 },
    { "id": 47, "nomLieu": "Espace Patrimoine", "catégorie": "Patrimoine", "num": "8", "typeRue": "Pl.", "nomRue": "Daurade", "site": "Centre Ville", "quartier": "Saint-Sernin", "établissement": "Information sur l'architecture et l'histoire", "sigles": "EP", "signification": "https://metropole.toulouse.fr/annuaire/espace-patrimoine", "ville": "Toulouse", "lat": 43.6017235, "lng": 1.4396851 },
    { "id": 48, "nomLieu": "Maison de l'Architecture Occitanie-Pyrénées", "catégorie": "Patrimoine", "num": "1", "typeRue": "Rue", "nomRue": "Renée Aspe", "site": "Centre Ville", "quartier": "Toulouse", "établissement": "Maison de l'Architecture", "sigles": "MAOP", "signification": "https://maop.fr/", "ville": "Toulouse", "lat": 43.6025235, "lng": 1.449044 },
    { "id": 49, "nomLieu": "Maison Grand parc Garonne", "catégorie": "Patrimoine", "num": "4", "typeRue": "Chemin", "nomRue": "de la Loge", "site": "Banlieue", "quartier": "Toulouse", "établissement": "Découverte de la future île du Ramier", "sigles": "MGP", "signification": "https://www.ladepeche.fr/2025/02/14/la-maison-du-grand-parc-garonne-pour-decouvrir-la-future-ile-du-ramier-poumon-vert-de-toulouse-12511360.php", "ville": "Toulouse", "lat": 43.5774041, "lng": 1.4334094 },

    // --- PERSONNALITÉS (50) ---
    { "id": 50, "nomLieu": "Maison Claude Nougaro", "catégorie": "Personnalités", "num": "20", "typeRue": "Rue", "nomRue": "Pénitents Gris", "site": "Centre Ville", "quartier": "Daurade", "établissement": "Maison-musée Claude Nougaro", "sigles": "CN", "signification": "http://maison-nougaro.fr/", "ville": "Toulouse", "lat": 43.603380, "lng": 1.439560 },

    // --- SPORT (51-53) ---
    { "id": 51, "nomLieu": "Stade Ernest Wallon (Visite)", "catégorie": "Sport", "num": "110", "typeRue": "Rue", "nomRue": "des Troènes", "site": "Nord", "quartier": "Sept Deniers", "établissement": "Visite du Stade Toulousain", "sigles": "ST", "signification": "https://www.stadetoulousain.fr/visites-ernest-wallon", "ville": "Toulouse", "lat": 43.621548, "lng": 1.415136 },
    { "id": 52, "nomLieu": "Stadium de Toulouse (Visite)", "catégorie": "Sport", "num": "1", "typeRue": "Allées", "nomRue": "Gabriel Biénès", "site": "Sud Centre", "quartier": "Île du Ramier", "établissement": "Visite du Stadium et TFC", "sigles": "TFC", "signification": "https://www.toulouse-tourisme.com/decouvrez-les-coulisses-du-stadium-et-du-tfc/toulouse/pcumid031v50fjo8", "ville": "Toulouse", "lat": 43.583297, "lng": 1.434048 },
    { "id": 53, "nomLieu": "Musée du Rugby Futur", "catégorie": "Sport", "num": "0", "typeRue": "Campus", "nomRue": "ST", "site": "Nord", "quartier": "Sept Deniers", "établissement": "Projet de Musée du Rugby", "sigles": "ST", "signification": "https://actu.fr/occitanie/toulouse_31555/toulouse-musee-rugby-campus-sport-hotel-bodega-gros-projet-stade-toulousain_22044858.html", "ville": "Toulouse", "lat": 43.620703, "lng": 1.415368 },

    // --- SANTÉ, MÉDECINE (54-57) ---
    { "id": 54, "nomLieu": "Musée Dentaire", "catégorie": "Santé, Médecine", "num": "37", "typeRue": "Allées", "nomRue": "Jules Guesde", "site": "Sud Centre", "quartier": "Busca / Saint-Michel", "établissement": "Musée des collections dentaires (CHU)", "sigles": "CHU", "signification": "http://www.biusante.parisdescartes.fr/aspad/expo95.htm", "ville": "Toulouse", "lat": 43.5944305, "lng": 1.4499057 },
    { "id": 55, "nomLieu": "Musée d'Histoire de la Médecine", "catégorie": "Santé, Médecine", "num": "2", "typeRue": "Rue", "nomRue": "Viguerie", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Musée dans l'Hôtel-Dieu Saint-Jacques", "sigles": "CHU", "signification": "https://www.musee-medecine.com/", "ville": "Toulouse", "lat": 43.5994332, "lng": 1.4364889 },
    { "id": 56, "nomLieu": "Musée des Instruments de Médecine", "catégorie": "Santé, Médecine", "num": "2", "typeRue": "Rue", "nomRue": "Viguerie", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Collection d'instruments (CHU)", "sigles": "CHU", "signification": "https://www.chu-toulouse.fr/les-musees-du-chu", "ville": "Toulouse", "lat": 43.5992055, "lng": 1.4365216 },
    { "id": 57, "nomLieu": "Histoire des hôpitaux de Toulouse Hôtel-Dieux Saint-Jacques", "catégorie": "Santé, Médecine", "num": "2", "typeRue": "Rue", "nomRue": "Viguerie", "site": "Rive Gauche", "quartier": "Saint-Cyprien", "établissement": "Espace documentaire CHU", "sigles": "CHU", "signification": "http://www.chu-toulouse.fr/-histoire-des-hopitaux-de-toulouse-", "ville": "Toulouse", "lat": 43.599300, "lng": 1.436400 },

    // --- SCIENCES (58-61) ---
    { "id": 58, "nomLieu": "Muséum d'Histoire Naturelle", "catégorie": "Sciences", "num": "35", "typeRue": "Allées", "nomRue": "Jules Guesde", "site": "Sud Centre", "quartier": "Busca / Saint-Michel", "établissement": "Muséum", "sigles": "MHN", "signification": "http://www.museum.toulouse.fr/", "ville": "Toulouse", "lat": 43.594246, "lng": 1.449337 },
    { "id": 59, "nomLieu": "Jardins du Muséum d'Histoire Naturelle la Maourine", "catégorie": "Sciences", "num": "24-26", "typeRue": "Avenue", "nomRue": "Maurice Bourgès-Maunoury", "site": "Nord-Est", "quartier": "Borderouge", "établissement": "Jardins botaniques du Muséum", "sigles": "MHN", "signification": "http://www.toulouse-tourisme.com/les-jardins-du-museum-parc-de-la-maourine/toulouse/pcumid031fs00968", "ville": "Toulouse", "lat": 43.632281, "lng": 1.451961 },
    { "id": 60, "nomLieu": "Observatoire du Jolimont", "catégorie": "Sciences", "num": "1", "typeRue": "Av.", "nomRue": "Camille Flammarion", "site": "Est", "quartier": "Jolimont", "établissement": "Observatoire astronomique", "sigles": "SAPT", "signification": "http://saptoulouse.net/", "ville": "Toulouse", "lat": 43.613611, "lng": 1.464167 },
    { "id": 61, "nomLieu": "Quai des Savoirs", "catégorie": "Sciences", "num": "39", "typeRue": "Allées", "nomRue": "Jules Guesde", "site": "Sud Centre", "quartier": "Busca / Saint-Michel", "établissement": "Lieu de culture scientifique", "sigles": "QdS", "signification": "http://www.quaidessavoirs.fr/", "ville": "Toulouse", "lat": 43.594038, "lng": 1.451457 },

    // --- TRANSPORTS (62-70) ---
    { "id": 62, "nomLieu": "Aérothèque", "catégorie": "Transports", "num": "12", "typeRue": "Rue", "nomRue": "Dard", "site": "Nord", "quartier": "Les Minimes", "établissement": "Musée aéronautique", "sigles": "Aéro", "signification": "http://www.aerotheque.com/", "ville": "Toulouse", "lat": 43.567751, "lng": 1.472425 },
    { "id": 63, "nomLieu": "Terre d'Envol", "catégorie": "Transports", "num": "0", "typeRue": "Rue", "nomRue": "Airbus", "site": "Ouest", "quartier": "Colomiers", "établissement": "Espace Rotary lié à l'aviation", "sigles": "Rotary", "signification": "http://www.rotary-terre-envol.fr/", "ville": "Toulouse", "lat": 43.612000, "lng": 1.341000 },
    { "id": 64, "nomLieu": "Hôtel du Grand Balcon", "catégorie": "Transports", "num": "8", "typeRue": "Rue", "nomRue": "Romiguières", "site": "Centre Ville", "quartier": "Capitole", "établissement": "Lieu mémoriel des pionniers de l'aviation", "sigles": "Aéro", "signification": "http://grandbalconhotel.com/fr/", "ville": "Toulouse", "lat": 43.604863, "lng": 1.442390 },
    { "id": 65, "nomLieu": "Musée des Transports", "catégorie": "Transports", "num": "93", "typeRue": "Avenue", "nomRue": "Jules Julien", "site": "Est", "quartier": "Jolimont", "établissement": "Musée du transport et des communications", "sigles": "MTTC", "signification": "http://www.toulouse-tourisme.com/musee-des-transports-et-des-communications/toulouse/pcumid031fs00064", "ville": "Toulouse", "lat": 43.580000, "lng": 1.455000 },
    { "id": 66, "nomLieu": "Musée des Transports Urbains", "catégorie": "Transports", "num": "126", "typeRue": "route", "nomRue": "Espagne", "site": "Est", "quartier": "Anglade", "établissement": "Collection de véhicules urbains (ASPTUIT)", "sigles": "ASPTUIT", "signification": "http://asptuit.free.fr/", "ville": "Toulouse", "lat": 43.571960, "lng": 1.389269 },
    { "id": 67, "nomLieu": "Musée des Transports Ambulants Postal", "catégorie": "Transports", "num": "70", "typeRue": "Rue", "nomRue": "Pierre Cazeneuve", "site": "Ouest", "quartier": "Amidonniers", "établissement": "Musée du patrimoine postal/ferroviaire", "sigles": "Ambulants", "signification": "http://www.ambulants.fr/", "ville": "Toulouse", "lat": 43.574107, "lng": 1.479061 },
    { "id": 68, "nomLieu": "Musée Envol des Pionniers de l'Aéropostale", "catégorie": "Transports", "num": "6", "typeRue": "Av.", "nomRue": "Jacqueline Auriol", "site": "Sud-Est", "quartier": "Montaudran", "établissement": "L'Envol des Pionniers", "sigles": "Aérop", "signification": "http://www.lenvol-des-pionniers.com/", "ville": "Toulouse", "lat": 43.574268, "lng": 1.477036 },
    { "id": 69, "nomLieu": "Cité de l'Espace", "catégorie": "Transports", "num": "0", "typeRue": "Av.", "nomRue": "Jean Gonord", "site": "Est Toulouse", "quartier": "Est (Côte Pavée)", "établissement": "Parc à thème scientifique", "sigles": "CE", "signification": "http://www.cite-espace.com/", "ville": "Toulouse", "lat": 43.586627, "lng": 1.493357 },
    { "id": 70, "nomLieu": "Le Train historique de Toulouse", "catégorie": "Transports", "num": "0", "typeRue": "Gare", "nomRue": "Matabiau", "site": "Est Centre", "quartier": "Matabiau", "établissement": "Association de trains historiques", "sigles": "THT", "signification": "http://www.trainhistorique-toulouse.com/", "ville": "Toulouse", "lat": 43.611257, "lng": 1.453623 },

    // --- FAUNE, NATURE & ÉLEVAGE (71-72) ---
    { "id": 71, "nomLieu": "Arche de Noé de Solyange", "catégorie": "Faune, Nature & Élevage", "num": "60", "typeRue": "Chem.", "nomRue": "du Renard", "site": "Sud", "quartier": "Le Renard", "établissement": "Mini-zoo, Parc animalier, ferme pédagogique", "sigles": "AS", "signification": "http://www.archedenoedesolyange.com/", "ville": "Toulouse", "lat": 43.559312, "lng": 1.411651 },
    { "id": 72, "nomLieu": "Sentier Nature de l'université (Paul Sabatier)", "catégorie": "Faune, Nature & Élevage", "num": "0", "typeRue": "Av.", "nomRue": "de Rangueil", "site": "Sud-Est", "quartier": "Rangueil", "établissement": "Sentier/Circuit pédagogique (Veracruz)", "sigles": "ZNIEFF", "signification": "https://www.univ-tlse3.fr/vie-associative-universitaire/veracruz", "ville": "Toulouse", "lat": 43.560667, "lng": 1.468752 },
    
    // --- LIEUX EN BANLIEUE DE TOULOUSE (73-117) --- 
    
    // --- ART (73-78) ---
    { "id": 73, "nomLieu": "Pavillon Blanc Henri Molina", "catégorie": "Art", "num": "1", "typeRue": "Pl.", "nomRue": "Alexandre Dumas", "site": "Banlieue Ouest", "quartier": "Colomiers", "établissement": "Centre d'Art Contemporain", "sigles": "PBHM", "signification": "http://www.pavillonblanc-colomiers.fr", "ville": "Colomiers", "lat": 43.610184, "lng": 1.334518 },
    { "id": 74, "nomLieu": "Espace Imparfait", "catégorie": "Art", "num": "688", "typeRue": "Chemin", "nomRue": "des Dourels", "site": "Banlieue Nord-Est", "quartier": "Mondouzil", "établissement": "Galerie et centre d'art", "sigles": "EI", "signification": "https://www.espace-imparfait.fr/", "ville": "Mondouzil", "lat": 43.626477, "lng": 1.574600 },
    { "id": 75, "nomLieu": "Maison Atelier Henri Guérin", "catégorie": "Art", "num": "9", "typeRue": "Rue", "nomRue": "du docteur Armaing", "site": "Banlieue Ouest", "quartier": "Plaisance", "établissement": "Atelier d'art", "sigles": "MAHG", "signification": "https://henriguerin.com/", "ville": "Plaisance-du-Touch", "lat": 43.564758, "lng": 1.296564 },
    { "id": 76, "nomLieu": "Centre Culturel Le Moulin", "catégorie": "Art", "num": "14", "typeRue": "Av.", "nomRue": "de la Gare", "site": "Banlieue Sud", "quartier": "Roques-sur-Garonne", "établissement": "Centre culturel", "sigles": "CCM", "signification": "https://www.lemoulin-roques.com/", "ville": "Roques-sur-Garonne", "lat": 43.510100, "lng": 1.375600 },
    { "id": 77, "nomLieu": "Château Catala", "catégorie": "Art", "num": "49", "typeRue": "Bd", "nomRue": "Català", "site": "Banlieue Est", "quartier": "Saint-Orens-de-Gameville", "établissement": "Château / musée d'art", "sigles": "CC", "signification": "https://www.ville-saint-orens.fr/chateau-catala/", "ville": "Saint-Orens-de-Gameville", "lat": 43.555000, "lng": 1.533000 },
    { "id": 78, "nomLieu": "Le Plumarium les métiers d'art", "catégorie": "Art", "num": "58", "typeRue": "Av.", "nomRue": "de Gascogne", "site": "Banlieue Ouest", "quartier": "Léguevin", "établissement": "Centre des métiers d'art", "sigles": "Plum", "signification": "https://www.plumarium.com/", "ville": "Léguevin", "lat": 43.597652, "lng": 1.229154 },

    // --- HISTOIRE (79-84) ---
    { "id": 79, "nomLieu": "Musée archéologique de Bessière", "catégorie": "Histoire", "num": "0", "typeRue": "Rue", "nomRue": "des Écoles", "site": "Banlieue Nord", "quartier": "Bessière", "établissement": "Musée archéologique local", "sigles": "Archéo", "signification": "http://www.hautegaronnetourisme.com/preparer/voir-faire/culture-et-patrimoine/musee-archeologique-956726", "ville": "Bessières", "lat": 43.801646, "lng": 1.606368 },
    { "id": 80, "nomLieu": "Musée du Vieux-Castanet", "catégorie": "Histoire", "num": "0", "typeRue": "Pl.", "nomRue": "du 8 Mai 1945", "site": "Banlieue Sud-Est", "quartier": "Castanet", "établissement": "Histoire et traditions locales", "sigles": "MVC", "signification": "http://www.castanet-tolosan.fr/annuaires-de-batiments-structures/annuaire-des-equipements-260/musee-du-vieux-castanet-417.html", "ville": "Castanet-Tolosan", "lat": 43.515233, "lng": 1.496986 },
    { "id": 81, "nomLieu": "Maison de l'histoire à Larra", "catégorie": "Histoire", "num": "0", "typeRue": "Mairie", "nomRue": "Larra", "site": "Banlieue Nord-Ouest", "quartier": "Larra", "établissement": "Lieu d'exposition historique", "sigles": "MH", "signification": "http://tourisme.hautstolosans.fr/fr/diffusio/patrimoine-culturel/maison-de-l-histoire-larra_TFOPCUMID031FS00030", "ville": "Larra", "lat": 43.739456, "lng": 1.233729 },
    { "id": 82, "nomLieu": "Musée de la mémoire des camps de déportation", "catégorie": "Histoire", "num": "0", "typeRue": "Av.", "nomRue": "des Palmiers", "site": "Banlieue Sud", "quartier": "Portet", "établissement": "Musée mémoriel (Guerres)", "sigles": "MM", "signification": "http://www.portetgaronne.fr/le-musee-de-la-memoire-504.html", "ville": "Portet-sur-Garonne", "lat": 43.541368, "lng": 1.407683 },
    { "id": 83, "nomLieu": "Musée du vieux Verfeil", "catégorie": "Histoire", "num": "0", "typeRue": "Pl.", "nomRue": "François Mitterrand", "site": "Banlieue Est", "quartier": "Verfeil", "établissement": "Musée local (Verfeil)", "sigles": "MVV", "signification": "http://musee-de-verfeil.webnode.fr/", "ville": "Verfeil", "lat": 43.656872, "lng": 1.661784 },
    { "id": 84, "nomLieu": "Mémothèque Populaire", "catégorie": "Histoire", "num": "0", "typeRue": "Allée", "nomRue": "de l'Ormeau", "site": "Banlieue Ouest", "quartier": "Colomiers", "établissement": "Archives et mémoire populaire", "sigles": "MP", "signification": "https://www.ville-colomiers.fr/1/mon-quotidien/espace-citoyens/memotheque-populaire", "ville": "Colomiers", "lat": 43.616082, "lng": 1.328846 },

    // --- INDUSTRIE (85-89) ---
    { "id": 85, "nomLieu": "Musée du foie gras", "catégorie": "Industrie", "num": "3", "typeRue": "Rue", "nomRue": "du Chanoine Dieuzaide", "site": "Sud-Ouest", "quartier": "Samatan", "établissement": "Musée gastronomique", "sigles": "Foie Gras", "signification": "https://www.tourisme-saves.com/musee-du-foie-gras-et-traditions-populaires", "ville": "Samatan", "lat": 43.492491, "lng": 0.930359 },
    { "id": 86, "nomLieu": "Musée du Potier de Cox", "catégorie": "Industrie", "num": "9", "typeRue": "Lieu-dit", "nomRue": "Village", "site": "Banlieue Nord-Ouest", "quartier": "Cox", "établissement": "Musée de la poterie locale", "sigles": "Poterie", "signification": "http://www.museecox.fr/", "ville": "Cox", "lat": 43.759182, "lng": 1.046048 },
    { "id": 87, "nomLieu": "Musée du Pastel", "catégorie": "Industrie", "num": "629", "typeRue": "Rue", "nomRue": "Max Planck", "site": "Banlieue Sud-Est", "quartier": "Labège", "établissement": "Musée sur l'histoire du pastel", "sigles": "Pastel", "signification": "http://terredepastel.com/resort/le-museum-du-pastel/", "ville": "Labège", "lat": 43.553593, "lng": 1.508495 },
    { "id": 88, "nomLieu": "Chocolaterie maison Escarnot", "catégorie": "Industrie", "num": "4", "typeRue": "Rte", "nomRue": "de Pechbonnieu", "site": "Banlieue Nord", "quartier": "Saint-Loup-Cammas", "établissement": "Chocolaterie artisanale", "sigles": "Escarnot", "signification": "https://www.maison-escarnot.fr/", "ville": "Saint-Loup-Cammas", "lat": 43.696243, "lng": 1.478396 },
    { "id": 89, "nomLieu": "Chocolaterie - de la Fève au Palais - le Palais du Cacao", "catégorie": "Industrie", "num": "2", "typeRue": "Chemin", "nomRue": "de Cantegraille", "site": "Banlieue Sud-Ouest", "quartier": "Fonsorbes", "établissement": "Chocolaterie", "sigles": "Palais Cacao", "signification": "https://www.delafeveaupalais.com/le-palais-du-cacao.html", "ville": "Fonsorbes", "lat": 43.528781, "lng": 1.214411 },

    // --- LOISIRS, SPECTACLES (90-91) ---
    { "id": 90, "nomLieu": "Musée de la marionnette (Théâtre des Préambules)", "catégorie": "Loisirs, Spectacles", "num": "22", "typeRue": "Av.", "nomRue": "Jacques Douzans", "site": "Banlieue Sud", "quartier": "Muret", "établissement": "Musée/collection de marionnettes", "sigles": "Marion", "signification": "https://theatredespreambules.com/", "ville": "Muret", "lat": 43.463455, "lng": 1.325737 },
    { "id": 91, "nomLieu": "Odradek / Pupella-Noguès", "catégorie": "Loisirs, Spectacles", "num": "46", "typeRue": "Chem.", "nomRue": "des Rosiers", "site": "Banlieue Est", "quartier": "Quint-Fonsegrives", "établissement": "Pôle de création et développement pour les arts de la marionnette", "sigles": "Marion", "signification": "http://www.pupella-nogues.com/", "ville": "Quint-Fonsegrives", "lat": 43.582223, "lng": 1.562401 },

    // --- MONUMENTS (92-101) ---
    { "id": 92, "nomLieu": "Musée de l'église de Bruguières", "catégorie": "Monuments", "num": "34", "typeRue": "Rue", "nomRue": "de l'Église", "site": "Banlieue Nord", "quartier": "Bruguières", "établissement": "Musée dans l'église locale", "sigles": "MH", "signification": "https://www.paroisse-bruguieres-fenouillet.fr/", "ville": "Bruguières", "lat": 43.727581, "lng": 1.410423 },
    { "id": 93, "nomLieu": "Château de Merville", "catégorie": "Monuments", "num": "2", "typeRue": "Pl.", "nomRue": "du Château", "site": "Banlieue Nord-Ouest", "quartier": "Merville", "établissement": "Château et labyrinthe", "sigles": "MH", "signification": "http://www.chateau-merville.com/", "ville": "Merville", "lat": 43.719238, "lng": 1.300897 },
    { "id": 94, "nomLieu": "Chapelle Notre Dame d'Alet", "catégorie": "Monuments", "num": "0", "typeRue": "Chem.", "nomRue": "de Notre Dame d'Alet", "site": "Banlieue Nord-Ouest", "quartier": "Montaigut", "établissement": "Chapelle historique", "sigles": "MH", "signification": "https://notredamedegrandselve.fr/", "ville": "Montaigut-sur-Save", "lat": 43.691231, "lng": 1.235832 },
    { "id": 95, "nomLieu": "Basilique Sainte-Germaine", "catégorie": "Monuments", "num": "0", "typeRue": "Pl.", "nomRue": "Sainte-Germaine", "site": "Banlieue Ouest", "quartier": "Pibrac", "établissement": "Basilique historique", "sigles": "MH", "signification": "https://www.saintegermainedepibrac.fr/", "ville": "Pibrac", "lat": 43.618185, "lng": 1.282888 },
    { "id": 96, "nomLieu": "Château des comtes de Toulouse", "catégorie": "Monuments", "num": "0", "typeRue": "Place", "nomRue": "Jean Jaurès", "site": "Banlieue Ouest", "quartier": "La Salvetat-Saint-Gilles", "établissement": "Château historique", "sigles": "CT", "signification": "http://www.lasalvetat31.fr/ma-ville/decouvrir-la-salvetat/chateau-raymond-iv/", "ville": "La Salvetat-Saint-Gilles", "lat": 43.577928, "lng": 1.271409 },
    { "id": 97, "nomLieu": "Ancien couvent des Ursulines", "catégorie": "Monuments", "num": "56", "typeRue": "Rue", "nomRue": "Roquemaurel", "site": "Banlieue Ouest", "quartier": "Grenade-sur-Garonne", "établissement": "Couvent historique", "sigles": "CU", "signification": "http://lesursulines.free.fr/", "ville": "Grenade-sur-Garonne", "lat": 43.774171, "lng": 1.293430 },
    { "id": 98, "nomLieu": "Abbaye Sainte-Marie du Désert", "catégorie": "Monuments", "num": "35", "typeRue": "chemin", "nomRue": "de Saint Bernard", "site": "Banlieue Ouest", "quartier": "Bellegarde-Sainte-Marie", "établissement": "Abbaye cistercienne", "sigles": "ASMD", "signification": "https://abbayedudesert.fr/", "ville": "Bellegarde-Sainte-Marie", "lat": 43.690844, "lng": 1.116740 },
    { "id": 99, "nomLieu": "Château de Laréole", "catégorie": "Monuments", "num": "0", "typeRue": "Château", "nomRue": "de Laréole", "site": "Banlieue Ouest", "quartier": "Laréole", "établissement": "Château départemental", "sigles": "CL", "signification": "https://www.haute-garonne.fr/service/le-chateau-de-lareole", "ville": "Laréole", "lat": 43.736077, "lng": 1.023630 },
    { "id": 100, "nomLieu": "Château Bonrepos-Riquet", "catégorie": "Monuments", "num": "1", "typeRue": "Pl.", "nomRue": "Paul Riquet", "site": "Banlieue Est", "quartier": "Bonrepos-Riquet", "établissement": "Château historique", "sigles": "CBR", "signification": "https://www.bonrepos-riquet.fr/", "ville": "Bonrepos-Riquet", "lat": 43.676309, "lng": 1.624643 },
    { "id": 101, "nomLieu": "Cimetière des petites filles modèles", "catégorie": "Monuments", "num": "0", "typeRue": "Pl.", "nomRue": "Saint-Sernin", "site": "Banlieue Est", "quartier": "Verfeil", "établissement": "Patrimoine historique", "sigles": "CPFM", "signification": "https://www.hautegaronnetourisme.com/", "ville": "Verfeil", "lat": 43.654445, "lng": 1.656924 },

    // --- PATRIMOINE (102-104) ---
    { "id": 102, "nomLieu": "Musée Cap Al Campestre", "catégorie": "Patrimoine", "num": "29", "typeRue": "Chem.", "nomRue": "des Français", "site": "Banlieue Sud-Ouest", "quartier": "Lherm", "établissement": "Musée de la vie rurale", "sigles": "Campestre", "signification": "http://www.museecapalcampestre.fr/", "ville": "Lherm", "lat": 43.439909, "lng": 1.262736 },
    { "id": 103, "nomLieu": "La ferme d'autrefois (Musée de l'ancien temps)", "catégorie": "Patrimoine", "num": "440", "typeRue": "Rte", "nomRue": "de Potié", "site": "Banlieue Est", "quartier": "Montlaur", "établissement": "Ferme musée pédagogique", "sigles": "Ferme", "signification": "http://www.hautegaronnetourisme.com/activites/la-ferme-d-autrefois/", "ville": "Montlaur", "lat": 43.479852, "lng": 1.593070 },
    { "id": 104, "nomLieu": "Maison de la nature", "catégorie": "Patrimoine", "num": "1", "typeRue": "Allée", "nomRue": "des Érables", "site": "Banlieue Est", "quartier": "Odars", "établissement": "Centre d'interprétation nature", "sigles": "Nature", "signification": "http://www.mairie-odars.fr/", "ville": "Odars", "lat": 43.523000, "lng": 1.593500 },

    // --- PERSONNALITÉS (105) ---
    { "id": 105, "nomLieu": "Musée Clément-Ader", "catégorie": "Personnalités", "num": "6", "typeRue": "Boulevard", "nomRue": "Aristide Briand", "site": "Banlieue Sud", "quartier": "Muret", "établissement": "Musée sur Clément-Ader et Grands Hommes", "sigles": "CA", "signification": "http://www.mairie-muret.fr/20-muret-bouge/vie-culturelle/49-musee", "ville": "Muret", "lat": 43.460833, "lng": 1.326389 },

    // --- TRANSPORTS (106-110) ---
{ "id": 106, "nomLieu": "Ailes anciennes - Toulouse", "catégorie": "Transports", "num": "0", "typeRue": "Allée", "nomRue": "André Turcat", "site": "Banlieue Nord-Ouest", "quartier": "Blagnac", "établissement": "Musée d'avions de collection", "sigles": "AATLSE", "signification": "http://aatlse.org/fr/", "ville": "Blagnac", "lat": 43.657657, "lng": 1.359366 },
    { "id": 107, "nomLieu": "Airbus (Visite)", "catégorie": "Transports", "num": "0", "typeRue": "Allée", "nomRue": "André Turcat", "site": "Banlieue Nord-Ouest", "quartier": "Blagnac", "établissement": "Visites usines Airbus", "sigles": "Airbus", "signification": "https://www.manatour.fr/airbus", "ville": "Blagnac", "lat": 43.659715, "lng": 1.359377 },
    { "id": 108, "nomLieu": "Aéroport de Blagnac (Visite)", "catégorie": "Transports", "num": "0", "typeRue": "Aéroport", "nomRue": "Blagnac", "site": "Banlieue Nord-Ouest", "quartier": "Blagnac", "établissement": "Visite côté pistes", "sigles": "ATB", "signification": "https://www.toulouse.aeroport.fr/", "ville": "Blagnac", "lat": 43.631346, "lng": 1.364490 },
    { "id": 109, "nomLieu": "Aéroscopia", "catégorie": "Transports", "num": "1", "typeRue": "Allée", "nomRue": "André Turcat", "site": "Banlieue Nord-Ouest", "quartier": "Blagnac", "établissement": "Musée aéronautique", "sigles": "Aéro", "signification": "http://www.musee-aeroscopia.fr/", "ville": "Blagnac", "lat": 43.659806, "lng": 1.359571 },
    { "id": 110, "nomLieu": "Aéroconstellation", "catégorie": "Transports", "num": "0", "typeRue": "Rue", "nomRue": "Félix Kracht", "site": "Banlieue Nord-Ouest", "quartier": "Blagnac", "établissement": "Site industriel aéronautique", "sigles": "Airbus", "signification": "https://www.airbus.com/", "ville": "Blagnac", "lat": 43.663420, "lng": 1.362560 },

    // --- TECHNOLOGIE (111) ---
{ "id": 111, "nomLieu": "Musée de l'informatique (Silicium)", "catégorie": "Technologie", "num": "0", "typeRue": "Espace", "nomRue": "Polytech", "site": "Banlieue Sud-Est", "quartier": "Labège", "établissement": "Musée de l'histoire de l'informatique", "sigles": "SI", "signification": "http://silicium.org/", "ville": "Labège", "lat": 43.538562, "lng": 1.517315 },

    // --- FAUNE, NATURE & ÉLEVAGE (112-117) --- (Mise à jour et ajout des 4 nouveaux lieux)
{ "id": 112, "nomLieu": "Maison de la Pêche et de la Nature", "catégorie": "Faune, Nature & Élevage", "num": "1", "typeRue": "Rue", "nomRue": "des Jardins", "site": "Banlieue Sud", "quartier": "Muret", "établissement": "Lieu pédagogique sur l'environnement et la pêche", "sigles": "Féd Pêche", "signification": "https://www.peche31.com/", "ville": "Muret", "lat": 43.460877, "lng": 1.328325 },
    { "id": 113, "nomLieu": "Ferme de Cinquante", "catégorie": "Faune, Nature & Élevage", "num": "0", "typeRue": "Chem.", "nomRue": "de Mange Pommes", "site": "Banlieue Sud-Est", "quartier": "Ramonville", "établissement": "Ferme pédagogique et espace nature", "sigles": "Ferme 50", "signification": "https://ferme50.org/", "ville": "Ramonville-Saint-Agne", "lat": 43.544621, "lng": 1.494643 },
    { "id": 114, "nomLieu": "Zoo African Safari", "catégorie": "Faune, Nature & Élevage", "num": "41", "typeRue": "Rue", "nomRue": "des Landes", "site": "Banlieue Ouest", "quartier": "Plaisance", "établissement": "Parc animalier, zoo", "sigles": "Zoo", "signification": "https://www.zoo-africansafari.com/", "ville": "Plaisance-du-Touch", "lat": 43.561401, "lng": 1.264259 },
    { "id": 115, "nomLieu": "AnimaParc® Occitanie", "catégorie": "Faune, Nature & Élevage", "num": "3000", "typeRue": "Pouchot", "nomRue": "N/A", "site": "Banlieue Nord", "quartier": "Le Burgaud", "établissement": "Parc d'attractions et parc animalier", "sigles": "Parc", "signification": "https://www.animaparc.com/", "ville": "Le Burgaud", "lat": 43.787123, "lng": 1.131935 },
    { "id": 116, "nomLieu": "Jardin des Senteurs et des Couleurs", "catégorie": "Faune, Nature & Élevage", "num": "11", "typeRue": "Chemin", "nomRue": "de Peyre-Escalles", "site": "Banlieue Sud-Est", "quartier": "Ramonville", "établissement": "Jardin botanique et circuit de découverte", "sigles": "Jardin", "signification": "https://www.hautegaronnetourisme.com/activites/jardin-des-senteurs-et-des-couleurs-chemin-de-decouvertes/", "ville": "Ramonville-Saint-Agne", "lat": 43.538621, "lng": 1.456282 },
    { "id": 117, "nomLieu": "Château de Merville Labyrinthe Nature", "catégorie": "Faune, Nature & Élevage", "num": "1175", "typeRue": "Chem.", "nomRue": "de Grande Borde", "site": "Banlieue Nord-Ouest", "quartier": "Merville", "établissement": "Labyrinthe végétal et forêt", "sigles": "MH", "signification": "http://www.chateau-merville.com/", "ville": "Merville", "lat": 43.720378, "lng": 1.303917 },
    { "id": 118, "nomLieu": "Le Refuge des Tortues", "catégorie": "Faune, Nature & Élevage", "num": "2920", "typeRue": "Route", "nomRue": "de Paulhac", "site": "Banlieue Nord-Est", "quartier": "Bessières", "établissement": "Parc animalier refuge des tortues", "sigles": "Refuge", "signification": "https://lerefugedestortues.fr/", "ville": "Bessières", "lat": 43.773670, "lng": 1.594205 },
  ];

  return NextResponse.json(data);
}
