// src/app/api/patrimoine31/route.ts
import { NextResponse } from 'next/server';

// Définition de type mise à jour pour les données d'un site
export interface SitePatrimoine31 {
  id: number;
  commune: string;
  description: string;
  lat: number;
  lng: number;
  distanceKm: number; // Nouvelle donnée: Distance approximative à Toulouse en km
}

// Les données des sites de patrimoine de Haute-Garonne (31) avec distance à Toulouse
const patrimoine31Sites: SitePatrimoine31[] = [
// Secteur Nord-Est de Toulouse (Tarn-Frontonnais)
{ id: 1, commune: "Azas", description: "château, pavillon, communs", lat: 43.763, lng: 1.696, distanceKm: 30, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 2, commune: "Bazus", description: "moulin à eau", lat: 43.743, lng: 1.488, distanceKm: 17, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 3, commune: "Bessières", description: "ferme fortifiée", lat: 43.818, lng: 1.626, distanceKm: 30, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 4, commune: "Buzet sur Tarn", description: "église, forêt, vestiges de pont", lat: 43.785, lng: 1.603, distanceKm: 25, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 5, commune: "Garidech", description: "château, couvent, commanderie Saint-Jean de Jérusalem", lat: 43.708, lng: 1.550, distanceKm: 18, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 6, commune: "Gémil", description: "four banal", lat: 43.719, lng: 1.606, distanceKm: 19, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 7, commune: "Lapeyrouse-Fossat", description: "deux châteaux", lat: 43.754, lng: 1.464, distanceKm: 16, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 8, commune: "Montastruc la Conseillère", description: "trois châteaux, église, arcades, halle", lat: 43.725, lng: 1.604, distanceKm: 20, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 9, commune: "Montjoire", description: "forêt", lat: 43.784, lng: 1.547, distanceKm: 23, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
{ id: 10, commune: "Saint-Jean Lherm", description: "séchoir à maïs, moulin à vent", lat: 43.725, lng: 1.637, distanceKm: 21, secteur: "Nord-Est Toulousain (Tarn-Frontonnais)" },
// Secteur Sud-Ouest (Proche Muret/Cazères)
{ id: 11, commune: "Castagnac", description: "château, moulin à vent", lat: 43.239, lng: 1.258, distanceKm: 55, secteur: "Sud-Ouest (Proche Muret/Cazères)" },
{ id: 12, commune: "Montbrun-Bocage", description: "château médiéval en ruine, maison en corondage, halle", lat: 43.155, lng: 1.157, distanceKm: 60, secteur: "Sud-Ouest (Proche Muret/Cazères)" },
{ id: 13, commune: "Montesquieu-Volvestre", description: "trois châteaux, église, ancien hospice, moulin, hôtel, maison à corondage", lat: 43.250, lng: 1.300, distanceKm: 50, secteur: "Sud-Ouest (Proche Muret/Cazères)" },
{ id: 14, commune: "Saint-Christaud", description: "pont du diable, moulin à eau, donjon", lat: 43.230, lng: 1.180, distanceKm: 58, secteur: "Sud-Ouest (Proche Muret/Cazères)" },
// Secteur Sud-Est (Lauragais)
{ id: 15, commune: "Ayguevives", description: "quatre châteaux, aqueduc, moulin à eau", lat: 43.435, lng: 1.583, distanceKm: 20, secteur: "Sud-Est (Lauragais)" },
{ id: 16, commune: "Baziège", description: "trois châteaux, maison à corondage, pountil, halle, cimetière des anglais de 1814", lat: 43.468, lng: 1.575, distanceKm: 22, secteur: "Sud-Est (Lauragais)" },
{ id: 17, commune: "Corronsac", description: "château", lat: 43.460, lng: 1.480, distanceKm: 15, secteur: "Sud-Est (Lauragais)" },
{ id: 18, commune: "Donneville", description: "ancienne forge", lat: 43.475, lng: 1.520, distanceKm: 18, secteur: "Sud-Est (Lauragais)" },
{ id: 19, commune: "Escalquens", description: "trois châteaux", lat: 43.513, lng: 1.520, distanceKm: 12, secteur: "Sud-Est (Lauragais)" },
{ id: 20, commune: "Espanès", description: "château, moulin à vent", lat: 43.447, lng: 1.545, distanceKm: 18, secteur: "Sud-Est (Lauragais)" },
{ id: 21, commune: "Fourquevaux", description: "deux châteaux, orangerie, maison de campagne", lat: 43.488, lng: 1.625, distanceKm: 22, secteur: "Sud-Est (Lauragais)" },
{ id: 22, commune: "Labastide-Beauvoir", description: "château", lat: 43.490, lng: 1.700, distanceKm: 28, secteur: "Sud-Est (Lauragais)" },
{ id: 23, commune: "Massabrac", description: "moulin à vent", lat: 43.340, lng: 1.340, distanceKm: 35, secteur: "Sud-Est (Lauragais)" },
{ id: 24, commune: "Montbrun-Lauragais", description: "deux châteaux, moulin à vent", lat: 43.470, lng: 1.600, distanceKm: 21, secteur: "Sud-Est (Lauragais)" },
{ id: 25, commune: "Montgiscard", description: "château, église, halle", lat: 43.450, lng: 1.530, distanceKm: 19, secteur: "Sud-Est (Lauragais)" },
{ id: 26, commune: "Montlaur", description: "château, moulin à vent", lat: 43.490, lng: 1.635, distanceKm: 23, secteur: "Sud-Est (Lauragais)" },
{ id: 27, commune: "Odars", description: "trois châteaux", lat: 43.530, lng: 1.595, distanceKm: 15, secteur: "Sud-Est (Lauragais)" },
{ id: 28, commune: "Pompertuzat", description: "deux châteaux", lat: 43.495, lng: 1.490, distanceKm: 14, secteur: "Sud-Est (Lauragais)" },
{ id: 29, commune: "Varennes", description: "château", lat: 43.477, lng: 1.688, distanceKm: 35, secteur: "Lauragais Est (Caraman)" }, 
// Secteur Sud (Comminges)
{ id: 30, commune: "Montréjeau", description: "château de Valmirande, église, arcades, hôtel, halle", lat: 43.080, lng: 0.560, distanceKm: 90, secteur: "Sud (Comminges)" },
{ id: 31, commune: "Saint-Plancard", description: "deux église, motte féodale", lat: 43.100, lng: 0.610, distanceKm: 85, secteur: "Sud (Comminges)" },
{ id: 32, commune: "Villeneuve Lécussan", description: "motte féodale, voie romaine, moulins à eau, oppidum de Castelviel", lat: 43.140, lng: 0.650, distanceKm: 80, secteur: "Sud (Comminges)" },
// Secteur Ouest (Muretain)
{ id: 33, commune: "Frouzins", description: "deux châteaux, tombes", lat: 43.515, lng: 1.320, distanceKm: 15, secteur: "Ouest (Muretain)" },
{ id: 34, commune: "Lherm", description: "château", lat: 43.460, lng: 1.250, distanceKm: 25, secteur: "Ouest (Muretain)" },
{ id: 35, commune: "Muret", description: "trois châteaux, rempart, deux églises, chapelle, villa, centre émetteur, oppidum d’Ox", lat: 43.457, lng: 1.330, distanceKm: 20, secteur: "Ouest (Muretain)" },
{ id: 36, commune: "Seysses", description: "château, église", lat: 43.470, lng: 1.340, distanceKm: 17, secteur: "Ouest (Muretain)" },
// Secteur Lauragais Sud (Canton de Villefranche)
{ id: 37, commune: "Auragne", description: "château, four à pain", lat: 43.345, lng: 1.515, distanceKm: 30, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 38, commune: "Caignac", description: "château, moulin à eau", lat: 43.325, lng: 1.545, distanceKm: 35, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 39, commune: "Gibel", description: "temple protestant, maison à corondage, moulin à vent", lat: 43.270, lng: 1.635, distanceKm: 45, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 40, commune: "Mauvasin", description: "château", lat: 43.290, lng: 1.570, distanceKm: 40, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 41, commune: "Monestrol", description: "château", lat: 43.320, lng: 1.590, distanceKm: 38, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 42, commune: "Montgeard", description: "deux châteaux, église fortifiée, moulin à vent", lat: 43.375, lng: 1.645, distanceKm: 35, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 43, commune: "Nailloux", description: "château, moulin à vent, halle au blé, foyer", lat: 43.370, lng: 1.580, distanceKm: 30, secteur: "Lauragais Sud (Canton de Villefranche)" },
{ id: 44, commune: "Seyre", description: "moulin à vent", lat: 43.295, lng: 1.700, distanceKm: 48, secteur: "Lauragais Sud (Canton de Villefranche)" },
// Secteur Sud de Toulouse (Portet/Muret)
{ id: 45, commune: "Eaunes", description: "ancienne abbaye, prieuré", lat: 43.433, lng: 1.346, distanceKm: 22, secteur: "Sud de Toulouse (Portet/Muret)" },
{ id: 46, commune: "Labarthe sur Léze", description: "moulin à vent, église", lat: 43.468, lng: 1.385, distanceKm: 15, secteur: "Sud de Toulouse (Portet/Muret)" },
{ id: 47, commune: "Pinsaguel", description: "moulin à vent", lat: 43.492, lng: 1.393, distanceKm: 12, secteur: "Sud de Toulouse (Portet/Muret)" },
{ id: 48, commune: "Portet sur Garonne", description: "moulin à vent, halle, cimetière israélite, moulin à eau", lat: 43.522, lng: 1.398, distanceKm: 8, secteur: "Sud de Toulouse (Portet/Muret)" },
// Secteur Lauragais (Est)
{ id: 49, commune: "Bélesta en Lauragais", description: "moulin à vent, moulin pastelier, moulin à vent", lat: 43.376, lng: 1.830, distanceKm: 50, secteur: "Lauragais (Est)" },
{ id: 50, commune: "Juzes", description: "moulin à vent médiéval", lat: 43.435, lng: 1.830, distanceKm: 45, secteur: "Lauragais (Est)" },
{ id: 51, commune: "Mourvilles-Hautes", description: "église, moulin à vent, four à pain, tombe", lat: 43.398, lng: 1.770, distanceKm: 42, secteur: "Lauragais (Est)" },
{ id: 52, commune: "Revel", description: "moulin à vent, maison à corondage, halle, lac, hôpital, caisse d'Epargne, bain douche", lat: 43.465, lng: 2.004, distanceKm: 55, secteur: "Lauragais (Est)" },
{ id: 53, commune: "Saint-Félix Lauraguais", description: "moulin à vent, chemin de ronde, remparts, donjon, tour, église, collégiale", lat: 43.450, lng: 1.888, distanceKm: 48, secteur: "Lauragais (Est)" },
{ id: 54, commune: "Saint-Julia", description: "remparts, église, orangerie, maison à corondage", lat: 43.535, lng: 1.850, distanceKm: 45, secteur: "Lauragais (Est)" },
{ id: 55, commune: "Vaudreuille", description: "centre de vol à voile", lat: 43.430, lng: 1.870, distanceKm: 46, secteur: "Lauragais (Est)" },
{ id: 56, commune: "Vaux", description: "château, rempart, maison à corondage", lat: 43.490, lng: 1.825, distanceKm: 44, secteur: "Lauragais (Est)" },
// Secteur Garonne Sud-Ouest (Rieumes)
{ id: 57, commune: "Beaufort", description: "église", lat: 43.327, lng: 1.150, distanceKm: 48, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 58, commune: "Forgues", description: "castéras, moulin à vent", lat: 43.390, lng: 1.180, distanceKm: 38, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 59, commune: "Labastide-Clermon", description: "château, porterie, moulin à vent", lat: 43.385, lng: 1.130, distanceKm: 40, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 60, commune: "Lahage", description: "château, église, grange", lat: 43.407, lng: 1.150, distanceKm: 38, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 61, commune: "Montastruc-Savès", description: "château, moulin à vent, maison à corondage", lat: 43.428, lng: 1.090, distanceKm: 45, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 62, commune: "Poucharramet", description: "deux châteaux, grange, maison à corondage", lat: 43.410, lng: 1.110, distanceKm: 42, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 63, commune: "Rieumes", description: "château, moulin à vent, maison à corondage, halle, hôtel", lat: 43.410, lng: 1.100, distanceKm: 40, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 64, commune: "Sabonnères", description: "couvent, maison en corondage", lat: 43.400, lng: 1.050, distanceKm: 45, secteur: "Garonne Sud-Ouest (Rieumes)" },
{ id: 65, commune: "Savères", description: "moulin à vent, maison à corondage", lat: 43.435, lng: 1.080, distanceKm: 42, secteur: "Garonne Sud-Ouest (Rieumes)" },
// Secteur Garonne Sud (Rieux-Volvestre)
{ id: 66, commune: "Gensac sur Garonne", description: "moulin à vent, maison à corondage", lat: 43.275, lng: 1.250, distanceKm: 45, secteur: "Garonne Sud (Rieux-Volvestre)" },
{ id: 67, commune: "Lacaugne", description: "moulin à vent", lat: 43.270, lng: 1.200, distanceKm: 50, secteur: "Garonne Sud (Rieux-Volvestre)" },
{ id: 68, commune: "Latrape", description: "tour", lat: 43.280, lng: 1.370, distanceKm: 40, secteur: "Garonne Sud (Rieux-Volvestre)" },
{ id: 69, commune: "Rieux-Volvestre", description: "cathédrale, théâtre, maison à corondage, halle", lat: 43.277, lng: 1.206, distanceKm: 48, secteur: "Garonne Sud (Rieux-Volvestre)" },
{ id: 70, commune: "Saint-Julien", description: "village gaulois", lat: 43.345, lng: 1.350, distanceKm: 35, secteur: "Garonne Sud (Rieux-Volvestre)" }, // Saint-Julien sur Garonne
// Secteur Pyrénées (Haute-Garonne)
{ id: 71, commune: "Bezins-Garraux", description: "moulin à vent, maison à corondage", lat: 42.925, lng: 0.690, distanceKm: 100, secteur: "Pyrénées (Haute-Garonne)" },
{ id: 72, commune: "Cierp-Gaud", description: "château, marbre", lat: 42.940, lng: 0.660, distanceKm: 105, secteur: "Pyrénées (Haute-Garonne)" },
{ id: 73, commune: "Fronsac", description: "château", lat: 42.960, lng: 0.670, distanceKm: 100, secteur: "Pyrénées (Haute-Garonne)" },
{ id: 74, commune: "Guran", description: "château", lat: 42.920, lng: 0.650, distanceKm: 108, secteur: "Pyrénées (Haute-Garonne)" },
{ id: 75, commune: "Lez", description: "brèche romaine", lat: 42.940, lng: 0.700, distanceKm: 100, secteur: "Pyrénées (Haute-Garonne)" },
{ id: 76, commune: "Saint-Béat", description: "deux châteaux, église, logis seigneurial, chapelle, fours à chaux, marbre", lat: 42.970, lng: 0.700, distanceKm: 98, secteur: "Pyrénées (Haute-Garonne)" },
// Secteur Saint-Gaudens
{ id: 77, commune: "Aspret-Sarrat", description: "halle", lat: 43.080, lng: 0.680, distanceKm: 80, secteur: "Saint-Gaudens" },
{ id: 78, commune: "Labarthe-Rivière", description: "pile romaine, monument à la Révolution, thermes, centrale électrique", lat: 43.075, lng: 0.600, distanceKm: 85, secteur: "Saint-Gaudens" },
{ id: 79, commune: "Labarthe-Inard", description: "deux châteaux, usine", lat: 43.145, lng: 0.690, distanceKm: 75, secteur: "Saint-Gaudens" },
{ id: 80, commune: "Lodes", description: "tuilerie", lat: 43.150, lng: 0.730, distanceKm: 70, secteur: "Saint-Gaudens" },
{ id: 81, commune: "Pointis-Inard", description: "deux châteaux, église, chapelle, usine", lat: 43.130, lng: 0.710, distanceKm: 75, secteur: "Saint-Gaudens" },
{ id: 82, commune: "Saint-Gaudens", description: "château, collégiale, papèterie, couvent, église, chapelle, hôtel, halle aux grains, palais de justice, théâtre, banque de France Postes", lat: 43.107, lng: 0.720, distanceKm: 75, secteur: "Saint-Gaudens" },
{ id: 83, commune: "Saint-Ignan", description: "château", lat: 43.140, lng: 0.750, distanceKm: 70, secteur: "Saint-Gaudens" },
{ id: 84, commune: "Saint-Marcet", description: "château, église, ruine du château comtal, grange", lat: 43.180, lng: 0.810, distanceKm: 70, secteur: "Saint-Gaudens" },
{ id: 85, commune: "Valentine", description: "château, rempart, villa gallo-romaine, chapelle", lat: 43.100, lng: 0.690, distanceKm: 78, secteur: "Saint-Gaudens" },
{ id: 86, commune: "Villeneuve-Rivière", description: "château, église, vestige ancienne église", lat: 43.120, lng: 0.680, distanceKm: 77, secteur: "Saint-Gaudens" },
// Secteur Ouest de Toulouse (Fonsorbes / Rieumes Nord)
{ id: 87, commune: "Bonrepos sur Aussonelle", description: "château", lat: 43.485, lng: 1.155, distanceKm: 25, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 88, commune: "Cambernard", description: "château, maison hospitalière, église", lat: 43.490, lng: 1.180, distanceKm: 27, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 89, commune: "Empeaux", description: "château", lat: 43.475, lng: 1.185, distanceKm: 25, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 90, commune: "Fonsorbes", description: "rempart, église, chapelle, bascule, café", lat: 43.518, lng: 1.250, distanceKm: 20, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 91, commune: "Fontenilles", description: "église, travail", lat: 43.535, lng: 1.190, distanceKm: 25, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 92, commune: "Saint-Lys", description: "château, arcades, moulin à vent, halle, immeuble ancien", lat: 43.500, lng: 1.200, distanceKm: 23, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 93, commune: "Saint-Thomas", description: "château, église, chapelle", lat: 43.480, lng: 1.165, distanceKm: 28, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
{ id: 94, commune: "Sainte-Foy de Peyrolières", description: "deux églises, maison à pigeonnier", lat: 43.480, lng: 1.130, distanceKm: 30, secteur: "Ouest de Toulouse (Fonsorbes / Rieumes Nord)" },
// Secteur Garonne Sud (Saint-Martory / Cazères)
{ id: 95, commune: "Auzas", description: "église, sépulture de chemin de Saint-Jacques, travail, forge", lat: 43.140, lng: 1.050, distanceKm: 65, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 96, commune: "Beauchalot", description: "remparts, église", lat: 43.160, lng: 0.985, distanceKm: 68, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 97, commune: "Castillon de Saint-Martory", description: "château, papèterie", lat: 43.145, lng: 1.055, distanceKm: 65, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 98, commune: "Le Fréchet", description: "château", lat: 43.155, lng: 1.080, distanceKm: 62, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 99, commune: "Laffite-Toupière", description: "église, moulin à eau, fortin, carrière de pierre", lat: 43.160, lng: 0.965, distanceKm: 70, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 100, commune: "Lestelle Saint-Martory", description: "motte féodale, église, chapelle", lat: 43.125, lng: 1.010, distanceKm: 68, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 101, commune: "Mancioux", description: "menhirs, viaduc, centrale hydro-électrique", lat: 43.160, lng: 1.060, distanceKm: 62, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 102, commune: "Proupiary", description: "abbatiale", lat: 43.140, lng: 1.010, distanceKm: 67, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 103, commune: "Saint-Martory", description: "château, deux grottes, menhir, tour, église, hôtel, moulin à eau, pont couvert, papèterie, canal, oppidum de l’Escalère", lat: 43.135, lng: 1.015, distanceKm: 67, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
{ id: 104, commune: "Sepx", description: "remparts, église", lat: 43.180, lng: 0.980, distanceKm: 68, secteur: "Garonne Sud (Saint-Martory / Cazères)" },
// Secteur Salies-du-Salat / Volvestre Sud
{ id: 105, commune: "Ausseing", description: "hôtel", lat: 43.130, lng: 0.920, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 106, commune: "Belbèze en Comminges", description: "carrière de pierre, moulin à vent", lat: 43.110, lng: 1.010, distanceKm: 68, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 107, commune: "Cassagne", description: "grotte, carrière à furne, grotte, pont", lat: 43.140, lng: 0.880, distanceKm: 75, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 108, commune: "Castagnède", description: "usine à chaux", lat: 43.100, lng: 0.890, distanceKm: 75, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 109, commune: "Castelbiague", description: "château, pont, ancienne scierie, église, chapelle", lat: 43.100, lng: 0.930, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 110, commune: "Figarol", description: "moulin à eau", lat: 43.115, lng: 0.860, distanceKm: 78, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 111, commune: "His", description: "château, auberge", lat: 43.150, lng: 0.850, distanceKm: 75, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 112, commune: "Mane", description: "église, pont, ancienne laiterie", lat: 43.125, lng: 0.950, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 113, commune: "Marsoulat", description: "grotte", lat: 43.070, lng: 0.950, distanceKm: 75, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 114, commune: "Mazères sur Salat", description: "château, usine, passerelle, papèterie", lat: 43.160, lng: 1.010, distanceKm: 67, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 115, commune: "Montastruc de Salies", description: "oratoire, malaxeur", lat: 43.140, lng: 0.895, distanceKm: 73, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 116, commune: "Montespan", description: "château, grotte, scierie", lat: 43.150, lng: 0.930, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 117, commune: "Montgaillard de Salies", description: "métairie fortifiée", lat: 43.165, lng: 0.910, distanceKm: 72, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 118, commune: "Montsaunès", description: "château", lat: 43.170, lng: 0.940, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 119, commune: "Roquefort sur Garonne", description: "château, ruines du château médiéval, église", lat: 43.180, lng: 1.040, distanceKm: 65, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 120, commune: "Rouède", description: "tumuls", lat: 43.100, lng: 0.980, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 121, commune: "Saleich", description: "vestiges du château comtal, église, chapelle, fontaine et source", lat: 43.085, lng: 0.965, distanceKm: 75, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 122, commune: "Salies du Salat", description: "donjon, église, chapelle, halle aux grains, four banal, thermes, usine à sel", lat: 43.107, lng: 0.970, distanceKm: 73, secteur: "Salies-du-Salat / Volvestre Sud" },
{ id: 123, commune: "Touilles", description: "château", lat: 43.185, lng: 0.960, distanceKm: 70, secteur: "Salies-du-Salat / Volvestre Sud" },
// Secteur Est et Nord-Est de Toulouse (Périphérie)
{ id: 124, commune: "Balma", description: "trois châteaux, manoir, deux églises, chapelle, vestige du château des archevêques, four à pain, villa, oppidum Les Barthes", lat: 43.615, lng: 1.488, distanceKm: 5, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 125, commune: "Beaupuy", description: "château, orangerie", lat: 43.660, lng: 1.570, distanceKm: 12, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 126, commune: "Colomiers", description: "quatre châteaux", lat: 43.600, lng: 1.320, distanceKm: 10, secteur: "Ouest de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 127, commune: "Drémil-Lafage", description: "deux châteaux, maison de maître, église, chapelle, caveau", lat: 43.600, lng: 1.630, distanceKm: 15, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 128, commune: "Fenouillet", description: "église, maison seigneuriale, usine Saint-Gobain", lat: 43.670, lng: 1.390, distanceKm: 10, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 129, commune: "Flourens", description: "lac", lat: 43.610, lng: 1.550, distanceKm: 10, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 130, commune: "Fonbeauzard", description: "château, communs, vestiges d'écuries", lat: 43.655, lng: 1.430, distanceKm: 8, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 131, commune: "Launaguet", description: "château, séchoir à tabac, briqueterie, hangar, orangerie", lat: 43.645, lng: 1.450, distanceKm: 7, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 132, commune: "Mons", description: "château, deux maisons de maître", lat: 43.630, lng: 1.580, distanceKm: 12, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 133, commune: "Montberon", description: "château, orangerie, écuries, grenier", lat: 43.700, lng: 1.480, distanceKm: 15, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 134, commune: "Pin-Balma", description: "château, cloître", lat: 43.600, lng: 1.555, distanceKm: 12, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 135, commune: "Quint-Fonsegrives", description: "château, église, mairie", lat: 43.590, lng: 1.520, distanceKm: 8, secteur: "Est et Nord-Est de Toulouse (Périphérie)" },
{ id: 136, commune: "Ramonville Saint-Agne", description: "château", lat: 43.560, lng: 1.470, distanceKm: 7, secteur: "Sud-Est de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 137, commune: "Saint-Genièes-Bellevue", description: "château", lat: 43.680, lng: 1.485, distanceKm: 12, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 138, commune: "Saint-Jean", description: "église, caveau, maison de maître", lat: 43.650, lng: 1.490, distanceKm: 8, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
{ id: 139, commune: "L'Union", description: "manoir, église", lat: 43.645, lng: 1.475, distanceKm: 7, secteur: "Nord de Toulouse (Périphérie)" }, // Ajusté pour cohérence
// Secteur Sud-Ouest Proche (Périphérie Ouest de Toulouse)
{ id: 140, commune: "Cugnaux", description: "deux châteaux, église, chapelle", lat: 43.550, lng: 1.340, distanceKm: 12, secteur: "Sud-Ouest Proche (Périphérie Ouest de Toulouse)" },
{ id: 141, commune: "Tournefeuille", description: "château, maison de maître, maison du président de la république", lat: 43.585, lng: 1.340, distanceKm: 8, secteur: "Sud-Ouest Proche (Périphérie Ouest de Toulouse)" },
{ id: 142, commune: "Villeneuve-Tolosane", description: "fort, église", lat: 43.520, lng: 1.335, distanceKm: 15, secteur: "Sud-Ouest Proche (Périphérie Ouest de Toulouse)" },
// Secteur Est (Verfeil / Lauragais Nord)
{ id: 143, commune: "Bonrepos-Riquet", description: "château", lat: 43.645, lng: 1.700, distanceKm: 25, secteur: "Est (Verfeil / Lauragais Nord)" },
{ id: 144, commune: "Gauré", description: "deux châteaux", lat: 43.640, lng: 1.685, distanceKm: 22, secteur: "Est (Verfeil / Lauragais Nord)" },
{ id: 145, commune: "Gragnague", description: "château", lat: 43.680, lng: 1.600, distanceKm: 17, secteur: "Est (Verfeil / Lauragais Nord)" },
{ id: 146, commune: "Lavalette", description: "église, ferme", lat: 43.620, lng: 1.690, distanceKm: 20, secteur: "Est (Verfeil / Lauragais Nord)" },
{ id: 147, commune: "Saint-Marcel-Paulel", description: "château, moulin à eau, hôtel", lat: 43.700, lng: 1.640, distanceKm: 22, secteur: "Est (Verfeil / Lauragais Nord)" },
{ id: 148, commune: "Verfeil", description: "deux châteaux, église, chapelle, rempart, cité médiévale, tombe de Montségur", lat: 43.650, lng: 1.730, distanceKm: 28, secteur: "Est (Verfeil / Lauragais Nord)" },
// Secteur Lauragais (Villefranche)
{ id: 149, commune: "Avignonet-Lauragais", description: "château, rempart, deux églises, métairie fortifiée, tour, moulin à eau, tour télégraphe", lat: 43.340, lng: 1.745, distanceKm: 40, secteur: "Lauragais (Villefranche)" },
{ id: 150, commune: "Beauteville", description: "château", lat: 43.380, lng: 1.700, distanceKm: 35, secteur: "Lauragais (Villefranche)" },
{ id: 151, commune: "Cessales", description: "maison forte", lat: 43.390, lng: 1.770, distanceKm: 40, secteur: "Lauragais (Villefranche)" },
{ id: 152, commune: "Gardouch", description: "remparts, moulin à eau, aqueduc, borne, moulin à vent, pavillon des poids publics", lat: 43.385, lng: 1.595, distanceKm: 30, secteur: "Lauragais (Villefranche)" },
{ id: 153, commune: "Lagarde", description: "grenier à blé", lat: 43.300, lng: 1.640, distanceKm: 42, secteur: "Lauragais (Villefranche)" },
{ id: 154, commune: "Lux", description: "église, tour", lat: 43.380, lng: 1.670, distanceKm: 35, secteur: "Lauragais (Villefranche)" },
{ id: 155, commune: "Mauremont", description: "château, orangerie, fossé, église", lat: 43.330, lng: 1.630, distanceKm: 40, secteur: "Lauragais (Villefranche)" },
{ id: 156, commune: "Montclar-Lauragais", description: "moulin à vent", lat: 43.300, lng: 1.695, distanceKm: 45, secteur: "Lauragais (Villefranche)" },
{ id: 157, commune: "Montesquieu-Lauragais", description: "deux châteaux, église, aqueduc, auberge, ponceau", lat: 43.380, lng: 1.615, distanceKm: 32, secteur: "Lauragais (Villefranche)" },
{ id: 158, commune: "Renneville", description: "moulin à vent, canon de 1916", lat: 43.355, lng: 1.625, distanceKm: 35, secteur: "Lauragais (Villefranche)" },
{ id: 159, commune: "Saint-Germier", description: "grenier à blé", lat: 43.335, lng: 1.700, distanceKm: 40, secteur: "Lauragais (Villefranche)" },
{ id: 160, commune: "Saint-Rome", description: "village modèle", lat: 43.360, lng: 1.740, distanceKm: 42, secteur: "Lauragais (Villefranche)" },
{ id: 161, commune: "Trébons sur la Grasse", description: "château barronal, moulin à eau", lat: 43.390, lng: 1.730, distanceKm: 38, secteur: "Lauragais (Villefranche)" },
{ id: 162, commune: "Vieillevigne", description: "château, halle", lat: 43.330, lng: 1.700, distanceKm: 40, secteur: "Lauragais (Villefranche)" },
{ id: 163, commune: "Villefranche de Lauragais", description: "château, halle, tribunal, église", lat: 43.360, lng: 1.730, distanceKm: 40, secteur: "Lauragais (Villefranche)" },
{ id: 164, commune: "Villenouvelle", description: "château, église, halle", lat: 43.410, lng: 1.620, distanceKm: 28, secteur: "Lauragais (Villefranche)" },
// Secteur Nord (Villemur)
{ id: 165, commune: "Bondigoux", description: "château, tour, église, ferme", lat: 43.890, lng: 1.540, distanceKm: 45, secteur: "Nord (Villemur)" },
{ id: 166, commune: "Layrac sur Tarn", description: "maison à pigeonnier", lat: 43.830, lng: 1.550, distanceKm: 35, secteur: "Nord (Villemur)" },
{ id: 167, commune: "Miremont sur Tarn", description: "église, mairie, pont suspendu, café", lat: 43.805, lng: 1.555, distanceKm: 30, secteur: "Nord (Villemur)" },
{ id: 168, commune: "Villemur sur Tarn", description: "château, grenier du roi, moulin à eau, maison à corondage, deux églises, cimetière, jardin ouvrier, minoterie, mairie, pont suspendu, Poste", lat: 43.880, lng: 1.515, distanceKm: 40, secteur: "Nord (Villemur)" },
// Secteur Pyrénées Ouest (Aspet)
{ id: 169, commune: "Arbas", description: "manoir", lat: 43.010, lng: 0.860, distanceKm: 85, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 170, commune: "Arbon", description: "vestige du château", lat: 43.000, lng: 0.770, distanceKm: 90, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 171, commune: "Aspet", description: "église, oratoire, tour, moulin à eau, hôpital, vierge noire, maison à corondage, couvents, arcades, institut", lat: 43.010, lng: 0.775, distanceKm: 88, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 172, commune: "Cabanc-Cazaux", description: "moulin à eau", lat: 43.005, lng: 0.900, distanceKm: 85, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 173, commune: "Chein-Dessus", description: "filature de lainage, tour", lat: 43.030, lng: 0.810, distanceKm: 85, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 174, commune: "Couret", description: "thermes, moulin à eau", lat: 43.050, lng: 0.760, distanceKm: 88, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 175, commune: "Encausse les Thermes", description: "thermes, moulin à eau", lat: 43.080, lng: 0.900, distanceKm: 78, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 176, commune: "Estadens", description: "donjon, grotte", lat: 43.030, lng: 0.880, distanceKm: 85, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 177, commune: "Fougaron", description: "moulin à eau", lat: 43.000, lng: 0.790, distanceKm: 88, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 178, commune: "Ganties", description: "grotte", lat: 43.080, lng: 0.840, distanceKm: 80, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 179, commune: "Izaut de l'Hôtel", description: "manoir, hôtel", lat: 43.020, lng: 0.740, distanceKm: 90, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 180, commune: "Razecueillé", description: "tour, église", lat: 42.980, lng: 0.780, distanceKm: 92, secteur: "Pyrénées Ouest (Aspet)" },
{ id: 181, commune: "Soueich", description: "moulin à eau", lat: 43.070, lng: 0.860, distanceKm: 80, secteur: "Pyrénées Ouest (Aspet)" },
// Secteur Aurignac / Garonne Ouest
{ id: 182, commune: "Alan", description: "maison à fossé, remparts, barbacane, maison à corondage, porche du palais des évêques, hospice, tour, moulures, halle, oratoire", lat: 43.235, lng: 1.050, distanceKm: 60, secteur: "Aurignac / Garonne Ouest" },
{ id: 183, commune: "Aulon", description: "église, moulin à eau, source, donjon, remparts, fontaine, usine", lat: 43.150, lng: 1.055, distanceKm: 65, secteur: "Aurignac / Garonne Ouest" },
{ id: 184, commune: "Aurignac", description: "château, grotte, aurigniacien, couvent, remparts, église, hôtel, maison en corondage", lat: 43.190, lng: 1.055, distanceKm: 65, secteur: "Aurignac / Garonne Ouest" },
{ id: 185, commune: "Bachas", description: "église, couvent", lat: 43.210, lng: 1.010, distanceKm: 68, secteur: "Aurignac / Garonne Ouest" },
{ id: 186, commune: "Benque", description: "château", lat: 43.230, lng: 1.000, distanceKm: 65, secteur: "Aurignac / Garonne Ouest" },
{ id: 187, commune: "Boussan", description: "château, vestige du château-fort, carrière, oratoire, moulin à eau, thermes", lat: 43.180, lng: 1.020, distanceKm: 68, secteur: "Aurignac / Garonne Ouest" },
{ id: 188, commune: "Cassagnère-Tournas", description: "motte féodale, four à pain, tumulus, église", lat: 43.220, lng: 1.010, distanceKm: 66, secteur: "Aurignac / Garonne Ouest" },
{ id: 189, commune: "Eoux", description: "château, église", lat: 43.190, lng: 1.000, distanceKm: 68, secteur: "Aurignac / Garonne Ouest" },
{ id: 190, commune: "Latoue", description: "deux châteaux, source", lat: 43.150, lng: 0.990, distanceKm: 70, secteur: "Aurignac / Garonne Ouest" },
{ id: 191, commune: "Montoulieu Saint-Bernard", description: "piscine gallo-romaine, hypocauste", lat: 43.100, lng: 1.030, distanceKm: 70, secteur: "Aurignac / Garonne Ouest" },
{ id: 192, commune: "Peyrouzet", description: "dégazolinage", lat: 43.195, lng: 1.060, distanceKm: 65, secteur: "Aurignac / Garonne Ouest" },
{ id: 193, commune: "Terrebasse", description: "château, moulin", lat: 43.260, lng: 1.070, distanceKm: 60, secteur: "Aurignac / Garonne Ouest" },
// Secteur Auterive / Lèze
{ id: 194, commune: "Auribail", description: "château", lat: 43.325, lng: 1.395, distanceKm: 32, secteur: "Auterive / Lèze" },
{ id: 195, commune: "Auterive", description: "château, rempart, hôtel, tour, arche, église, hôtel-Dieu, maison comtale, manufacture royale, deux halles", lat: 43.355, lng: 1.470, distanceKm: 28, secteur: "Auterive / Lèze" },
{ id: 196, commune: "Beaumont sur Lèze", description: "château", lat: 43.400, lng: 1.340, distanceKm: 25, secteur: "Auterive / Lèze" },
{ id: 197, commune: "Grépiac", description: "église, vestige de pont", lat: 43.385, lng: 1.430, distanceKm: 24, secteur: "Auterive / Lèze" },
{ id: 198, commune: "Lagrâce-Dieu", description: "prieuré, moulin à vent, fontaine, pigeonnier, église, chapelle", lat: 43.300, lng: 1.400, distanceKm: 35, secteur: "Auterive / Lèze" },
{ id: 199, commune: "Miremont", description: "église, poids public", lat: 43.375, lng: 1.415, distanceKm: 26, secteur: "Auterive / Lèze" },
{ id: 200, commune: "Puydaniel", description: "maison à corondage", lat: 43.310, lng: 1.440, distanceKm: 33, secteur: "Auterive / Lèze" },
{ id: 201, commune: "Vénerque", description: "église fortifiée", lat: 43.440, lng: 1.430, distanceKm: 18, secteur: "Auterive / Lèze" },
{ id: 202, commune: "Le Vernet", description: "château, église, moulin à eau, mémorial de la déportation, cimetière anglais", lat: 43.415, lng: 1.435, distanceKm: 20, secteur: "Auterive / Lèze" },
// Secteur Luchon / Pyrénées
{ id: 203, commune: "Bagnères de Luchon", description: "château, thermes, villas, église, hospice, chapelle, tour, arboretum, hôtel, hôpital, cimetière, abattoir, théâtre, gare, halle, kiosque, funiculaire, parc, centrale hydro-électrique, café, piscine", lat: 42.787, lng: 0.590, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 204, commune: "Castillon de Larboust", description: "maison de noble, funiculaire", lat: 42.825, lng: 0.535, distanceKm: 105, secteur: "Luchon / Pyrénées" },
{ id: 205, commune: "Cathervielle", description: "église, castel", lat: 42.840, lng: 0.560, distanceKm: 108, secteur: "Luchon / Pyrénées" },
{ id: 206, commune: "Mayrègne", description: "donjon", lat: 42.790, lng: 0.550, distanceKm: 112, secteur: "Luchon / Pyrénées" },
{ id: 207, commune: "Montauban de Luchon", description: "église, chalet", lat: 42.820, lng: 0.570, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 208, commune: "Moustajon", description: "ancienne tour", lat: 42.800, lng: 0.595, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 209, commune: "Oô", description: "donjon", lat: 42.810, lng: 0.585, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 210, commune: "Portet de Luchon", description: "presbytère", lat: 42.815, lng: 0.580, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 211, commune: "Saccourvielle", description: "ancienne tour, manoir", lat: 42.805, lng: 0.575, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 212, commune: "Saint-Aventin", description: "église, maison noble, grand hôtel", lat: 42.830, lng: 0.565, distanceKm: 108, secteur: "Luchon / Pyrénées" },
{ id: 213, commune: "Saint-Mamet", description: "église, vestiges du château, vestiges du moulin, villa", lat: 42.780, lng: 0.600, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 214, commune: "Saint-Paul d'Oueil", description: "château", lat: 42.870, lng: 0.540, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 215, commune: "Sode", description: "tour", lat: 42.795, lng: 0.610, distanceKm: 110, secteur: "Luchon / Pyrénées" },
{ id: 216, commune: "Trébons de Luchon", description: "donjon", lat: 42.850, lng: 0.580, distanceKm: 108, secteur: "Luchon / Pyrénées" },
// Secteur Saint-Bertrand / Comminges
{ id: 217, commune: "Barbazan", description: "église, parc, kiosque, grand hôtel, lac, thermes", lat: 43.050, lng: 0.620, distanceKm: 85, secteur: "Saint-Bertrand / Comminges" },
{ id: 218, commune: "Galié", description: "remparts, vestige du château-fort, monument de la Mont-Joie", lat: 43.020, lng: 0.630, distanceKm: 88, secteur: "Saint-Bertrand / Comminges" },
{ id: 219, commune: "Gourdan-Polignan", description: "château, grotte, tunnel, gare", lat: 43.065, lng: 0.615, distanceKm: 82, secteur: "Saint-Bertrand / Comminges" },
{ id: 220, commune: "Huos", description: "grotte de Lourdes", lat: 43.045, lng: 0.650, distanceKm: 85, secteur: "Saint-Bertrand / Comminges" },
{ id: 221, commune: "Labroquère", description: "château, oratoire", lat: 43.060, lng: 0.640, distanceKm: 83, secteur: "Saint-Bertrand / Comminges" },
{ id: 222, commune: "Lourde", description: "église, tombe", lat: 43.020, lng: 0.650, distanceKm: 88, secteur: "Saint-Bertrand / Comminges" },
{ id: 223, commune: "Luscan", description: "château", lat: 43.030, lng: 0.610, distanceKm: 88, secteur: "Saint-Bertrand / Comminges" },
{ id: 224, commune: "Malvezie", description: "grotte fortifiée", lat: 43.050, lng: 0.650, distanceKm: 85, secteur: "Saint-Bertrand / Comminges" },
{ id: 225, commune: "Martres de Rivière", description: "château", lat: 43.070, lng: 0.660, distanceKm: 80, secteur: "Saint-Bertrand / Comminges" },
{ id: 226, commune: "Ore", description: "source, charpente", lat: 43.030, lng: 0.600, distanceKm: 88, secteur: "Saint-Bertrand / Comminges" },
{ id: 227, commune: "Pointis de Rivière", description: "moulin à eau, église, chapelle", lat: 43.060, lng: 0.650, distanceKm: 82, secteur: "Saint-Bertrand / Comminges" },
{ id: 228, commune: "Saint-Bertrand de Comminges", description: "cathédrale, églises, cité médiévale, vestige de la cité gallo-romaine, maisons de corondage, remparts", lat: 43.028, lng: 0.672, distanceKm: 85, secteur: "Saint-Bertrand / Comminges" },
{ id: 229, commune: "Saint-Pé d'Ardet", description: "église, lac, chemin de croix", lat: 43.050, lng: 0.635, distanceKm: 85, secteur: "Saint-Bertrand / Comminges" },
{ id: 230, commune: "Sauverterre de Comminges", description: "remparts, tour, église", lat: 43.040, lng: 0.640, distanceKm: 87, secteur: "Saint-Bertrand / Comminges" },
{ id: 231, commune: "Seilhan", description: "source", lat: 43.060, lng: 0.625, distanceKm: 83, secteur: "Saint-Bertrand / Comminges" },
{ id: 232, commune: "Valcabrère", description: "basilique, tour, cimetière gallo-romain", lat: 43.035, lng: 0.665, distanceKm: 85, secteur: "Saint-Bertrand / Comminges" },
// Secteur Ouest/Nord-Ouest (Blagnac / Périphérie)
{ id: 233, commune: "Beauzelle", description: "château, moulin à eau, orangerie", lat: 43.665, lng: 1.350, distanceKm: 10, secteur: "Ouest/Nord-Ouest (Blagnac / Périphérie)" },
{ id: 234, commune: "Blagnac", description: "château, église, monastère, maison à corondage, fours de briqueterie, café", lat: 43.630, lng: 1.370, distanceKm: 5, secteur: "Ouest/Nord-Ouest (Blagnac / Périphérie)" },
{ id: 235, commune: "Cornebarrieu", description: "deux châteaux, borne, maison forte, moulin à eau", lat: 43.645, lng: 1.300, distanceKm: 12, secteur: "Ouest/Nord-Ouest (Blagnac / Périphérie)" },
{ id: 236, commune: "Mondonville", description: "deux châteaux, ancienne tour du château, horloge, moulin à vent, source, remparts, église", lat: 43.670, lng: 1.250, distanceKm: 15, secteur: "Ouest/Nord-Ouest (Blagnac / Périphérie)" },
// Secteur Gascogne/Ouest (Boulogne sur Gesse)
{ id: 237, commune: "Blajan", description: "château, maison à corondage, fontaine, tuilerie", lat: 43.190, lng: 0.700, distanceKm: 70, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 238, commune: "Boulogne sur Gesse", description: "château, remparts, église, abbaye de Nizors, viaduc, arcades", lat: 43.275, lng: 0.675, distanceKm: 75, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 239, commune: "Escanecrabe", description: "motte castrale", lat: 43.200, lng: 0.810, distanceKm: 68, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 240, commune: "Gensac de Boulogne", description: "château des Comminges", lat: 43.250, lng: 0.730, distanceKm: 70, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 241, commune: "Larroque", description: "tour, chêne de Hourlagne, locomotive à charbon, briqueterie", lat: 43.340, lng: 0.840, distanceKm: 60, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 242, commune: "Lespugue", description: "grotte, Vénus de Lespugue, vestiges du château", lat: 43.080, lng: 0.720, distanceKm: 80, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 243, commune: "Lunax", description: "barrage de Gimone", lat: 43.330, lng: 0.780, distanceKm: 65, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 244, commune: "Montgaillard sur Save", description: "motte castrale", lat: 43.375, lng: 0.890, distanceKm: 55, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 245, commune: "Montmaurin", description: "villa gallo-romaine", lat: 43.210, lng: 0.650, distanceKm: 78, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 246, commune: "Nénigan", description: "moulin à eau", lat: 43.360, lng: 0.850, distanceKm: 60, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 247, commune: "Péguilhan", description: "château, chaussée d'eau du moulin, moulin", lat: 43.200, lng: 0.720, distanceKm: 75, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 248, commune: "Saint-Loup en Comminges", description: "tour", lat: 43.180, lng: 0.760, distanceKm: 70, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
{ id: 249, commune: "Sarremezan", description: "château, oppidum", lat: 43.230, lng: 0.820, distanceKm: 65, secteur: "Gascogne/Ouest (Boulogne sur Gesse)" },
// Secteur Nord-Ouest (Cadours / Gimone)
{ id: 250, commune: "Bellegarde Sainte-Marie", description: "abbaye", lat: 43.720, lng: 1.150, distanceKm: 30, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 251, commune: "Brignemont", description: "moulin à vent, deux églises", lat: 43.800, lng: 1.150, distanceKm: 40, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 252, commune: "Cabanac-Séguenville", description: "château, moulin à vent", lat: 43.770, lng: 1.100, distanceKm: 45, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 253, commune: "Cadours", description: "église, halle, moulin à vent, ail", lat: 43.760, lng: 1.150, distanceKm: 35, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 254, commune: "Le Castéra", description: "deux églises, maison à corondage", lat: 43.750, lng: 1.100, distanceKm: 38, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 255, commune: "Caubiac", description: "église, pigeonnier", lat: 43.730, lng: 1.130, distanceKm: 35, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 256, commune: "Cox", description: "maison du potier, halle, église", lat: 43.800, lng: 1.180, distanceKm: 42, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 257, commune: "Drudas", description: "château", lat: 43.790, lng: 1.250, distanceKm: 35, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 258, commune: "Garaud", description: "église, maison avec tours pigeonniers", lat: 43.755, lng: 1.220, distanceKm: 30, secteur: "Nord-Ouest (Cadours / Gimone)" },
{ id: 259, commune: "Laréole", description: "château, église", lat: 43.740, lng: 1.050, distanceKm: 40, secteur: "Nord-Ouest (Cadours / Gimone)" },
// Secteur Lauragais Est (Caraman)
{ id: 260, commune: "Albiac", description: "motte féodale", lat: 43.590, lng: 1.770, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 261, commune: "Auriac sur Vendinelle", description: "église-donjon, pont, halle, pigeonnier, moulin à vent", lat: 43.460, lng: 1.830, distanceKm: 40, secteur: "Lauragais Est (Caraman)" },
{ id: 262, commune: "Beauville", description: "château, ancienne tour", lat: 43.535, lng: 1.750, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 263, commune: "Cabanial", description: "porte du château-fort", lat: 43.480, lng: 1.800, distanceKm: 35, secteur: "Lauragais Est (Caraman)" },
{ id: 264, commune: "Cambiac", description: "deux châteaux, église, calvaire, moulin à vent", lat: 43.520, lng: 1.775, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 265, commune: "Caragoudes", description: "château, moulin à vent", lat: 43.545, lng: 1.700, distanceKm: 25, secteur: "Lauragais Est (Caraman)" },
{ id: 266, commune: "Caraman", description: "château, église, cimetière, castrum, tour, hôtel, halle aux grains, borde, grenier messal, fontaine, école des frères", lat: 43.560, lng: 1.720, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 267, commune: "Le Faget", description: "château-fort, remparts", lat: 43.530, lng: 1.840, distanceKm: 35, secteur: "Lauragais Est (Caraman)" },
{ id: 268, commune: "Fancarville", description: "deux églises, moulin à vent", lat: 43.500, lng: 1.725, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 269, commune: "Loubens-Lauragais", description: "château-fort, moulin à vent, maison à corondage, église, tour, pavillon de bain, pavillon de chasse, bascule publique", lat: 43.585, lng: 1.750, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 270, commune: "Mascarville", description: "château, four à pain, moulin à eau, moulin à vent", lat: 43.570, lng: 1.680, distanceKm: 25, secteur: "Lauragais Est (Caraman)" },
{ id: 271, commune: "Maureville", description: "château", lat: 43.500, lng: 1.750, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 272, commune: "Mourvilles-Basses", description: "deux châteaux, église", lat: 43.530, lng: 1.740, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 273, commune: "Prunet", description: "moulin à vent", lat: 43.540, lng: 1.790, distanceKm: 32, secteur: "Lauragais Est (Caraman)" },
{ id: 274, commune: "La Salvetat Lauragais", description: "château, temporal, église", lat: 43.540, lng: 1.750, distanceKm: 30, secteur: "Lauragais Est (Caraman)" },
{ id: 275, commune: "Saussens", description: "château, fontaine miraculeuse", lat: 43.590, lng: 1.720, distanceKm: 28, secteur: "Lauragais Est (Caraman)" },
{ id: 276, commune: "Ségreville", description: "château, motte féodale, église", lat: 43.560, lng: 1.780, distanceKm: 32, secteur: "Lauragais Est (Caraman)" },
{ id: 277, commune: "Toutens", description: "voie romaine", lat: 43.510, lng: 1.680, distanceKm: 25, secteur: "Lauragais Est (Caraman)" },
{ id: 278, commune: "Vendine", description: "motte castrale, ancien relais de Poste, moulin à eau", lat: 43.570, lng: 1.800, distanceKm: 35, secteur: "Lauragais Est (Caraman)" },
// Secteur Garonne Sud (Carbonne / Rieux)
{ id: 279, commune: "Bois de la Pierre", description: "château", lat: 43.340, lng: 1.250, distanceKm: 35, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 280, commune: "Capens", description: "trois châteaux", lat: 43.300, lng: 1.255, distanceKm: 40, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 281, commune: "Carbonne", description: "château, deux églises, maison à corondage, pigeonnier, halle aux grains, chalet, tombe", lat: 43.300, lng: 1.230, distanceKm: 40, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 282, commune: "Longages", description: "château-fort, orangerie, prieuré, porte du couvent, halle art déco", lat: 43.320, lng: 1.250, distanceKm: 38, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 283, commune: "Marquefave", description: "château", lat: 43.325, lng: 1.220, distanceKm: 38, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 284, commune: "Mauzac", description: "deux châteaux, site préhistorique, église, halle", lat: 43.340, lng: 1.270, distanceKm: 35, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 285, commune: "Montaut", description: "église", lat: 43.305, lng: 1.300, distanceKm: 35, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 286, commune: "Noé", description: "château, obélisque, maison à corondage, église, camp de déportation", lat: 43.375, lng: 1.255, distanceKm: 30, secteur: "Garonne Sud (Carbonne / Rieux)" },
{ id: 287, commune: "Saint-Sulpice sur Lèze", description: "château, église, maison à corondage, arcades, orangerie, moulin à vent, ferme avec tour-pigeonnier, moulin à eau", lat: 43.300, lng: 1.360, distanceKm: 35, secteur: "Garonne Sud (Carbonne / Rieux)" },
// Secteur Sud-Est Proche (Sicoval / Castanet)
{ id: 288, commune: "Aureville", description: "château", lat: 43.460, lng: 1.450, distanceKm: 15, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 289, commune: "Auzeville-Tolosane", description: "château, castel", lat: 43.535, lng: 1.470, distanceKm: 10, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 290, commune: "Auzielle", description: "château, église", lat: 43.565, lng: 1.545, distanceKm: 10, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 291, commune: "Castanet-Tolosan", description: "château, léproserie, hôpital, église, aqueduc", lat: 43.510, lng: 1.485, distanceKm: 10, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 292, commune: "Clermont le Fort", description: "fort, motte castrale, église, remparts, oratoire, belvédère", lat: 43.435, lng: 1.465, distanceKm: 18, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 293, commune: "Goyrans", description: "château, église", lat: 43.480, lng: 1.455, distanceKm: 13, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 294, commune: "Labège", description: "château, église", lat: 43.535, lng: 1.515, distanceKm: 12, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 295, commune: "Lacroix-Falgarde", description: "château, église, chapelle, moulin à vent, passerelle", lat: 43.475, lng: 1.450, distanceKm: 14, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 296, commune: "Mervilla", description: "deux châteaux, tombe, halle", lat: 43.490, lng: 1.465, distanceKm: 12, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 297, commune: "Rebigue", description: "moulin à vent", lat: 43.470, lng: 1.500, distanceKm: 15, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 298, commune: "Saint-Orens de Gameville", description: "mairie, maison de retraite", lat: 43.555, lng: 1.530, distanceKm: 10, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 299, commune: "Vieille-Toulouse", description: "oppidum", lat: 43.530, lng: 1.440, distanceKm: 8, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
{ id: 300, commune: "Vigoulet-Auzil", description: "château, église", lat: 43.510, lng: 1.440, distanceKm: 10, secteur: "Sud-Est Proche (Sicoval / Castanet)" },
// Secteur Martres / Cazères Sud
{ id: 301, commune: "Boussens", description: "église, mairie, usine", lat: 43.200, lng: 1.050, distanceKm: 65, secteur: "Martres / Cazères Sud" },
{ id: 302, commune: "Cazères", description: "deux châteaux, église, deux chapelles, site préhistorique, pigeonnier, retenue d'eau, cave, maison à corondage, grotte, fontaine miraculeuse, cloître, pigeonnier, arcades, halle", lat: 43.205, lng: 1.085, distanceKm: 60, secteur: "Martres / Cazères Sud" },
{ id: 303, commune: "Couladère", description: "château, four à tuiles", lat: 43.230, lng: 1.130, distanceKm: 55, secteur: "Martres / Cazères Sud" },
{ id: 304, commune: "Lescuns", description: "château", lat: 43.200, lng: 1.120, distanceKm: 60, secteur: "Martres / Cazères Sud" },
{ id: 305, commune: "Marignac-Laspeyres", description: "site des dinosaures, église, faïencerie", lat: 43.235, lng: 1.150, distanceKm: 55, secteur: "Martres / Cazères Sud" },
{ id: 306, commune: "Martres-Tolosane", description: "deux châteaux, site préhistorique, faïencerie, église, pigeonnier, cimenterie, four faïence", lat: 43.260, lng: 1.025, distanceKm: 55, secteur: "Martres / Cazères Sud" },
{ id: 307, commune: "Mauran", description: "château, vestiges de château féodal, vestige d'église, église", lat: 43.220, lng: 1.040, distanceKm: 60, secteur: "Martres / Cazères Sud" },
{ id: 308, commune: "Mondavezan", description: "motte féodale", lat: 43.200, lng: 1.180, distanceKm: 55, secteur: "Martres / Cazères Sud" },
{ id: 309, commune: "Montberaud", description: "château féodal, église, moulin à eau", lat: 43.190, lng: 1.200, distanceKm: 58, secteur: "Martres / Cazères Sud" },
{ id: 310, commune: "Montclar de Comminges", description: "église", lat: 43.205, lng: 1.140, distanceKm: 58, secteur: "Martres / Cazères Sud" },
{ id: 311, commune: "Palaminy", description: "château féodal, dépendances, église, chapelle, tour, maison Renaissance, manoir", lat: 43.245, lng: 1.070, distanceKm: 55, secteur: "Martres / Cazères Sud" },
{ id: 312, commune: "Le Plan", description: "église, maison à corondage, moulin à eau, remparts, chapelle du couvent, halle", lat: 43.220, lng: 1.110, distanceKm: 58, secteur: "Martres / Cazères Sud" },
{ id: 313, commune: "Saint-Michel", description: "château, vestige du château féodal, communs, église, four", lat: 43.270, lng: 1.120, distanceKm: 50, secteur: "Martres / Cazères Sud" },
{ id: 314, commune: "Sana", description: "église", lat: 43.250, lng: 1.100, distanceKm: 55, secteur: "Martres / Cazères Sud" },
// Secteur Lèze / Cintegabelle
{ id: 315, commune: "Caujac", description: "deux châteaux, arcades, colombier", lat: 43.320, lng: 1.500, distanceKm: 32, secteur: "Lèze / Cintegabelle" },
{ id: 316, commune: "Cintegabelle", description: "quatre châteaux, hôpital, remparts, tour, deux églises, pigeonnier, abbaye, escalier, hôtel", lat: 43.300, lng: 1.480, distanceKm: 35, secteur: "Lèze / Cintegabelle" },
{ id: 317, commune: "Esperce", description: "maisons à corondages", lat: 43.300, lng: 1.520, distanceKm: 38, secteur: "Lèze / Cintegabelle" },
{ id: 318, commune: "Gailhac-Toulza", description: "château, motte castrale, abbaye, chapelle, église, moulin à vent, couvent, caveau", lat: 43.300, lng: 1.550, distanceKm: 40, secteur: "Lèze / Cintegabelle" },
{ id: 319, commune: "Grazac", description: "église, deux maisons de maître, arcades", lat: 43.300, lng: 1.450, distanceKm: 35, secteur: "Lèze / Cintegabelle" },
// Secteur Fousseret / Sud-Ouest
{ id: 320, commune: "Castelnau-Picampeau", description: "deux châteaux, tuilerie, moulin à vent", lat: 43.280, lng: 1.000, distanceKm: 55, secteur: "Fousseret / Sud-Ouest" },
{ id: 321, commune: "Casties-Labrande", description: "vestiges du château, moulin à vent, hangar", lat: 43.280, lng: 1.050, distanceKm: 50, secteur: "Fousseret / Sud-Ouest" },
{ id: 322, commune: "Le Fousseret", description: "deux châteaux, église, carrera major, halle, maison à corondage, chapelle, domaine, maison de retraite, loggia, couvent, métairie, abattoir, halle, forge", lat: 43.270, lng: 1.110, distanceKm: 48, secteur: "Fousseret / Sud-Ouest" },
{ id: 323, commune: "Gratens", description: "château, moulin à eau, briqueterie", lat: 43.320, lng: 1.150, distanceKm: 40, secteur: "Fousseret / Sud-Ouest" },
{ id: 324, commune: "Lafitte-Vigordane", description: "voie romaine, site préhistorique", lat: 43.330, lng: 1.180, distanceKm: 40, secteur: "Fousseret / Sud-Ouest" },
{ id: 325, commune: "Lussan-Adeilhac", description: "château, moulin à eau", lat: 43.250, lng: 1.050, distanceKm: 52, secteur: "Fousseret / Sud-Ouest" },
{ id: 326, commune: "Marignac-Lasclares", description: "cimetière, moulin à eau", lat: 43.280, lng: 1.150, distanceKm: 45, secteur: "Fousseret / Sud-Ouest" },
{ id: 327, commune: "Montoussin", description: "château, église", lat: 43.250, lng: 1.150, distanceKm: 50, secteur: "Fousseret / Sud-Ouest" },
{ id: 328, commune: "Le Pouy-de-Touges", description: "château", lat: 43.340, lng: 1.080, distanceKm: 45, secteur: "Fousseret / Sud-Ouest" },
{ id: 329, commune: "Saint-Araille", description: "château, manoir, moulin à vent", lat: 43.290, lng: 1.080, distanceKm: 48, secteur: "Fousseret / Sud-Ouest" },
{ id: 330, commune: "Saint-Elix le château", description: "château, obélisque, Elysées, copie du petit Trianon, église, bascule publique", lat: 43.250, lng: 1.250, distanceKm: 45, secteur: "Fousseret / Sud-Ouest" },
{ id: 331, commune: "Sénarens", description: "vestiges de la bastide, moulin à vent, couvent", lat: 43.270, lng: 1.050, distanceKm: 50, secteur: "Fousseret / Sud-Ouest" },
// Secteur Nord (Frontonnais / Garonne)
{ id: 332, commune: "Bouloc", description: "église", lat: 43.780, lng: 1.390, distanceKm: 25, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 333, commune: "Bruguières", description: "château, castelet, écuries, maison de maître, maison de charité, lavoir", lat: 43.690, lng: 1.400, distanceKm: 15, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 334, commune: "Castelnau d'Estrétrefonds", description: "château, église, cheminée d'usine, lavoir", lat: 43.800, lng: 1.340, distanceKm: 30, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 335, commune: "Cépet", description: "deux châteaux, four banal", lat: 43.765, lng: 1.405, distanceKm: 22, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 336, commune: "Fronton", description: "maisons à corondage, bascule publique, ancienne usine", lat: 43.830, lng: 1.350, distanceKm: 35, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 337, commune: "Lespinasse", description: "minoterie", lat: 43.695, lng: 1.380, distanceKm: 12, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 338, commune: "Saint-Jory", description: "château, église", lat: 43.725, lng: 1.350, distanceKm: 18, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 339, commune: "Saint-Rustice", description: "église", lat: 43.820, lng: 1.300, distanceKm: 35, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 340, commune: "Villariès", description: "chêne de Sully", lat: 43.655, lng: 1.550, distanceKm: 15, secteur: "Nord (Frontonnais / Garonne)" },
{ id: 341, commune: "Villaudric", description: "château, chai", lat: 43.790, lng: 1.400, distanceKm: 30, secteur: "Nord (Frontonnais / Garonne)" },
// Secteur Garonne Ouest (Grenade / Save)
{ id: 342, commune: "Aussonne", description: "église, pigeonnier", lat: 43.660, lng: 1.300, distanceKm: 12, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 343, commune: "Bretx", description: "château, église", lat: 43.700, lng: 1.250, distanceKm: 20, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 344, commune: "Le Burgaud", description: "ferme avec tours-pigeonniers, église, chapelle", lat: 43.820, lng: 1.150, distanceKm: 40, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 345, commune: "Daux", description: "deux châteaux, église", lat: 43.700, lng: 1.280, distanceKm: 18, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 346, commune: "Grenade sur Garonne", description: "château, couvent, halle, église", lat: 43.765, lng: 1.285, distanceKm: 25, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 347, commune: "Larra", description: "château, pigeonnier", lat: 43.730, lng: 1.250, distanceKm: 25, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 348, commune: "Launac", description: "château, halle", lat: 43.780, lng: 1.200, distanceKm: 30, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 349, commune: "Merville", description: "château, pigeonnier", lat: 43.690, lng: 1.280, distanceKm: 18, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 350, commune: "Montaigut sur Save", description: "cloître, église, chapelle, cimetière", lat: 43.680, lng: 1.200, distanceKm: 25, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 351, commune: "Ondes", description: "château, église, arcades", lat: 43.765, lng: 1.295, distanceKm: 22, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 352, commune: "Saint-Paul sur Save", description: "château, maison à corondage, chai", lat: 43.700, lng: 1.220, distanceKm: 22, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 353, commune: "Seilh", description: "deux châteaux, orangerie", lat: 43.680, lng: 1.350, distanceKm: 12, secteur: "Garonne Ouest (Grenade / Save)" },
{ id: 354, commune: "Thil", description: "trois châteaux, tumulus, maison à corondage, église, chapelle, maison de maître", lat: 43.720, lng: 1.200, distanceKm: 30, secteur: "Garonne Ouest (Grenade / Save)" },
// Secteur Sud-Ouest Extrême (L'Isle en Dodon / Save)
{ id: 355, commune: "Agassac", description: "motte castrale, forge banale, four tuilier", lat: 43.340, lng: 0.900, distanceKm: 60, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 356, commune: "Ambax", description: "château, tour féodale", lat: 43.270, lng: 0.950, distanceKm: 60, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 357, commune: "Anan", description: "barrage sur la Save, moulin à eau", lat: 43.340, lng: 0.880, distanceKm: 62, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 358, commune: "Boissède", description: "château, tour féodale, pigeonnier, communs", lat: 43.330, lng: 0.850, distanceKm: 65, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 359, commune: "Castelgaillard", description: "ancien château, moulin à vent", lat: 43.310, lng: 0.900, distanceKm: 60, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 360, commune: "Cazac", description: "moulins à vent jumeaux", lat: 43.300, lng: 0.950, distanceKm: 58, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 361, commune: "Fabas", description: "deux églises, forge, maison à corondage", lat: 43.280, lng: 0.900, distanceKm: 62, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 362, commune: "Frontignan-Savès", description: "château", lat: 43.300, lng: 0.850, distanceKm: 65, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 363, commune: "L'Isle en Dodon", description: "château, église, maison de l'abbé, galerie couverte, tuilerie, halles, château d'eau", lat: 43.340, lng: 0.800, distanceKm: 70, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 364, commune: "Labastide-Paumès", description: "château", lat: 43.280, lng: 0.880, distanceKm: 65, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 365, commune: "Martisserre", description: "église, tour d'angle, ferme avec pigeonnier", lat: 43.310, lng: 0.780, distanceKm: 70, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 366, commune: "Mauvezin", description: "motte castrale", lat: 43.290, lng: 0.980, distanceKm: 58, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 367, commune: "Mirambeau", description: "motte castrale, moulin à eau", lat: 43.300, lng: 0.820, distanceKm: 68, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 368, commune: "Molas", description: "église, grange", lat: 43.300, lng: 0.920, distanceKm: 60, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 369, commune: "Montbernard", description: "pachère, oratoire", lat: 43.320, lng: 0.750, distanceKm: 72, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 370, commune: "Montesquieu-Guittaut", description: "deux châteaux", lat: 43.270, lng: 0.780, distanceKm: 75, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 371, commune: "Puymaurin", description: "maisons à corondage, halle", lat: 43.350, lng: 0.700, distanceKm: 75, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 372, commune: "Riolas", description: "château", lat: 43.290, lng: 0.750, distanceKm: 72, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 373, commune: "Saint-Frajou", description: "église, source", lat: 43.250, lng: 0.850, distanceKm: 70, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 374, commune: "Saint-Laurent", description: "château, site préhistorique, ancien monastère, moulin à eau, maison haute, moulin à vent", lat: 43.260, lng: 0.700, distanceKm: 75, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
{ id: 375, commune: "Salerm", description: "château, oratoire, caveau", lat: 43.300, lng: 0.720, distanceKm: 75, secteur: "Sud-Ouest Extrême (L'Isle en Dodon / Save)" },
// Secteur Lauragais Proche (Lanta / Caraman Ouest)
{ id: 376, commune: "Aurin", description: "église, moulin à vent", lat: 43.535, lng: 1.630, distanceKm: 18, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 377, commune: "Bourg Saint-Bernard", description: "château, site préhistorique, église, motte castrale", lat: 43.590, lng: 1.700, distanceKm: 25, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 378, commune: "Lanta", description: "trois château, église, pigeonnier", lat: 43.585, lng: 1.630, distanceKm: 18, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 379, commune: "Lauzerville", description: "château", lat: 43.570, lng: 1.550, distanceKm: 12, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 380, commune: "Préserville", description: "deux châteaux, pigeonnier, borde", lat: 43.530, lng: 1.650, distanceKm: 20, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 381, commune: "Saint-Pierre de Lages", description: "château", lat: 43.565, lng: 1.640, distanceKm: 18, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 382, commune: "Sainte-Foy d'Aigrefeuille", description: "église, moulin à vent", lat: 43.480, lng: 1.650, distanceKm: 25, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 383, commune: "Tarabel", description: "château", lat: 43.510, lng: 1.650, distanceKm: 22, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
{ id: 384, commune: "Vallesvilles", description: "château, église", lat: 43.600, lng: 1.630, distanceKm: 18, secteur: "Lauragais Proche (Lanta / Caraman Ouest)" },
// Secteur Ouest Proche (Pibrac / Plaisance du Touch)
{ id: 385, commune: "Brax", description: "château, four, église, lampisterie, lavoir", lat: 43.615, lng: 1.255, distanceKm: 15, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 386, commune: "Lasserre", description: "église", lat: 43.655, lng: 1.250, distanceKm: 15, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 387, commune: "Léguevin", description: "château, mairie, escalette, ancien relais de Poste", lat: 43.600, lng: 1.240, distanceKm: 15, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 388, commune: "Lévignac", description: "couvent, domaine, hôtel", lat: 43.670, lng: 1.200, distanceKm: 20, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 389, commune: "Mérenvielle", description: "château", lat: 43.690, lng: 1.180, distanceKm: 25, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 390, commune: "Pibrac", description: "ancienne bastide, château, basilique, église, chapelle", lat: 43.610, lng: 1.300, distanceKm: 12, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 391, commune: "Plaisance du Touch", description: "château, église zoo Safari Parc, domaine, école des arts", lat: 43.570, lng: 1.320, distanceKm: 12, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 392, commune: "Pradère les Bourgets", description: "château, pigeonnier", lat: 43.600, lng: 1.150, distanceKm: 25, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 393, commune: "Sainte-Livrade", description: "église", lat: 43.660, lng: 1.150, distanceKm: 25, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
{ id: 394, commune: "La Salvetat Saint-Gilles", description: "château féodal des comtes de Toulouse", lat: 43.580, lng: 1.270, distanceKm: 15, secteur: "Ouest Proche (Pibrac / Plaisance du Touch)" },
];

export async function GET() {
  return NextResponse.json(patrimoine31Sites);
}