import { NextResponse } from "next/server";

interface Establishment {
  name: string;
  address: string;
}

const establishments: Establishment[] = [
  { "name": "bâtiment remarquable", "address": "1 rue Albert Lautman" },
  { "name": "bâtiment remarquable", "address": "3 rue Albert Lautman" },
  { "name": "immeuble", "address": "37 bd Armand Duportal" },
  { "name": "immeuble", "address": "49 bd Armand Duportal" },
  { "name": "hôtel Baichère, tour", "address": "7 rue Arts" },
  { "name": "hôtel Nolet disp ?", "address": "7 rue Arts" },
  { "name": "hôtel Dupuy-Montaut", "address": "10 rue Arts" },
  { "name": "Collège Boulbonne, couvent, auj, imm. 1910 ?", "address": "12 rue Arts" },
  { "name": "couvent Dame Andouin : 14-16", "address": "14 rue Arts" },
  { "name": "bâtiment remarquable", "address": "16 rue Arts" },
  { "name": "hôtel Duranti disp ?", "address": "17 rue Arts" },
  { "name": "couvent Dame Andouin : 14-16", "address": "14-16 rue Arts" },
  { "name": "hôtel d'Assézat, tour", "address": "1 place Assézat" },
  { "name": "Dames Noirs ou de St-Maur ou St Enfant Jésus", "address": "5 rue Astorg" },
  { "name": "bâtiment remarquable", "address": "20 rue Astorg" },
  { "name": "bâtiment remarquable", "address": "6 rue Aussargue d'" },
  { "name": "bâtiment remarquable", "address": "8 rue Aussargue d'" },
  { "name": "rue à compléter", "address": "9 rue Baour Lornian" },
  { "name": "façade", "address": "5 rue Baronie" },
  { "name": "maison Pierre Ducos : 12 & 14", "address": "12 & 14 rue Baronie" },
  { "name": "TNT", "address": "1 rue Baudis" },
  { "name": "immeuble Urbain vitry", "address": "3 rue Bellegarde" },
  { "name": "hôtel : maison avec galets", "address": "13 rue Bellegarde" },
  { "name": "bâtiment remarquable", "address": "5 rue Bida" },
  { "name": "rempart romain", "address": "7 rue Bida" },
  { "name": "rempart romain", "address": "11 rue Bida" },
  { "name": "3ème : terrasse sur rempart romain", "address": "13 rue Bida" },
  { "name": "rempart romain : 12 & 14", "address": "12 & 14 rue Bida" },
  { "name": "tours remparts romains : 1-5-11-17", "address": "1-5-11-17 rue Bida" },
  { "name": "fontaine Bienfaits de la Garonne", "address": "no place Boulbonne" },
  { "name": "bâtiment remarquable", "address": "13 rue Boulbonne" },
  { "name": "Collège Boulbonne disp", "address": "21 rue Boulbonne" },
  { "name": "bâtiment remarquable", "address": "42 rue Boulbonne" },
  { "name": "corrondage", "address": "42 rue Boulbonne" },
  { "name": "fontaine Labatut (en face)", "address": "50 rue Boulbonne" },
  { "name": "portail", "address": "50 rue Boulbonne" },
  { "name": "mosaïque", "address": "52 rue Boulbonne" },
  { "name": "bâtiment remarquable", "address": "9 rue Boule" },
  { "name": "maison Guignard 1931 Pilette angle Fr Verdier, Bouling", "address": "no Gd Rond Boulingrin" },
  { "name": "immeuble Thuriès 4 ét 1933", "address": "no Gd Rond Boulingrin" },
  { "name": "hôtel Calstroupat 1932 angle Fr. Verdier - r Brasserie", "address": "no Gd Rond Boulingrin" },
  { "name": "immeuble Jourde 1934 angle r. Potier et Boulingrin", "address": "no Gd Rond Boulingrin" },
  { "name": "hôtel Puivert ou hôtel de Gardouch, escalier int.", "address": "8 rue Bouquières" },
  { "name": "général Ramel", "address": "41 rue Bouquières" },
  { "name": "Bourse du Commerce", "address": "1 place Bourse" },
  { "name": "chapelle Ingolèse au milieu de la place", "address": "1 place Bourse" },
  { "name": "bâtiment remarquable", "address": "10 place Bourse" },
  { "name": "bâtiment remarquable", "address": "19 place Bourse" },
  { "name": "bâtiment remarquable", "address": "20 place Bourse" },
  { "name": "Maison Professe des Jésuites dispes; anc. Égl.", "address": "6 rue Bourse" },
  { "name": "Tour Clémence Isaure", "address": "16 rue Bourse" },
  { "name": "et 24 rue Cujas, chappelles dont Ingolèse ?", "address": "19 rue Bourse" },
  { "name": "hôtel Delfau, tour", "address": "20 rue Bourse" },
  { "name": "maison Gayssion, tour", "address": "5 rue Boyer-Fonfrède" },
  { "name": "bâtiment remarquable", "address": "9 allées Brienne" },
  { "name": "canal et quai de Brienne", "address": "no canal Brienne" },
  { "name": "disp : hôtel de Montmorency-Laval", "address": "angle rue Brunière" },
  { "name": "angle avec rue Dalbade", "address": "angle rue Brunière" },
  { "name": "école Fabre (1941) XVI°", "address": "angle rue Brunière" },
  { "name": "portail", "address": "8 rue Canard" },
  { "name": "griffons", "address": "12 rue Canard" },
  { "name": "chap. du Mont-Carmel, à côté égl. des Carmes : 6 et 8", "address": "6 et 8 rue Canard" },
  { "name": "bâtiment remarquable", "address": "2 rue Cantegril" },
  { "name": "collège des Pauvrets", "address": "1 place Capitole" },
  { "name": "coll St-Martial, rue Rommiguières, entrée pl Capitole", "address": "1 place Capitole" },
  { "name": "collège Saint-Martial, grand hôtel de l'Opéra", "address": "1 place Capitole" },
  { "name": "Saint-Martial, collège ou cloître ?", "address": "1 place Capitole" },
  { "name": "tour collège Saint-Martial : salon bar hôtel Opéra", "address": "1 place Capitole" },
  { "name": "Capitole", "address": "no place Capitole" },
  { "name": "cour Henri IV", "address": "no place Capitole" },
  { "name": "chapelle Saint-…", "address": "no place Capitole" },
  { "name": "égl St-Quentin : rue Porterie (entre r. St-Rome et Taur)", "address": "no place Capitole" },
  { "name": "église Saint-Quentin : milieu place du Capitole", "address": "no place Capitole" },
  { "name": "hôtel Puget, voici église St-Quentin vers r Gambetta", "address": "no place Capitole" },
  { "name": "tête Christ 1821", "address": "16 place Carmes" },
  { "name": "bâtiment remarquable", "address": "6 bd Carnot" },
  { "name": "maison modèle : Auguste Virebent", "address": "no bd Carnot" },
  { "name": "ancien couvent", "address": "11 rue Chaîne" },
  { "name": "Jeu de Paume", "address": "13 rue Chaîne" },
  { "name": "salamandre", "address": "15 rue Chaîne" },
  { "name": "couvent Religieuses Tiers Ordres St-François", "address": "no rue Chaîne" },
  { "name": "bibliothèque Saint-Rome, tour Collège Saint-Rome", "address": "3 rue Chalande" },
  { "name": "Doctrinaires rue Saint-Rome", "address": "3 rue Chalande" },
  { "name": "hôtel Bolé, tour", "address": "4 rue Chalande" },
  { "name": "tour de Séguy", "address": "4 rue Chalande" },
  { "name": "corrondage", "address": "1 rue Changes" },
  { "name": "corrondage", "address": "3 rue Changes" },
  { "name": "bâtiment remarquable", "address": "4 rue Changes" },
  { "name": "colombe du Lys", "address": "15 rue Changes" },
  { "name": "hôtel Astorg : escalier en bois, tour", "address": "16 rue Changes" },
  { "name": "hôtel de Saint-Germain", "address": "16 rue Changes" },
  { "name": "maison Boscredon, pastelier", "address": "17 rue Changes" },
  { "name": "bâtiment remarquable", "address": "19 rue Changes" },
  { "name": "hôtel Delpech, tour", "address": "20 rue Changes" },
  { "name": "tour d'angle", "address": "21 rue Changes" },
  { "name": "maison Labonne", "address": "22 rue Changes" },
  { "name": "tour Pierre de Lancefoc", "address": "25 rue Changes" },
  { "name": "hôtel Commère", "address": "27 rue Changes" },
  { "name": "seigneurs Montmaurs", "address": "29 rue Changes" },
  { "name": "maison Prohenques", "address": "32 rue Changes" },
  { "name": "corrondage", "address": "34 rue Changes" },
  { "name": "corrondage", "address": "35 rue Changes" },
  { "name": "corrondage", "address": "37 rue Changes" },
  { "name": "voir dernier étage tour Vinhas : 31-33", "address": "31-33 rue Changes" },
  { "name": "bâtiment remarquable", "address": "5 rue Clémence Isaure" },
  { "name": "bâtiment remarquable", "address": "7 rue Clémence Isaure" },
  { "name": "bâtiment remarquable", "address": "2bis rue Clémence Isaure" },
  { "name": "bâtiment remarquable", "address": "4bis rue Clémence Isaure" },
  { "name": "bâtiment remarquable", "address": "9bis rue Clémence Isaure" },
  { "name": "bâtiment remarquable", "address": "5 rue Coffres" },
  { "name": "chapelle Rieux", "address": "1 rue Collège de Foix" },
  { "name": "église Rieux angle rue Lois et r. Coll. Foix, parall r C. F.", "address": "1 rue Collège de Foix" },
  { "name": "rue à compléter", "address": "900 rue Collège de Foix" },
  { "name": "hôtel Segla disp ?", "address": "8 rue Coq d'Inde" },
  { "name": "maison XVII°", "address": "4 rue Couteliers" },
  { "name": "hôtel Alliés", "address": "6 rue Couteliers" },
  { "name": "bâtiment remarquable", "address": "12 rue Couteliers" },
  { "name": "corrondage", "address": "23 rue Couteliers" },
  { "name": "hôtel Verdiguier", "address": "43 rue Couteliers" },
  { "name": "tourelle Guillaume Tournié", "address": "44 rue Couteliers" },
  { "name": "hôtel Dassier", "address": "46 rue Couteliers" },
  { "name": "Couvent de la Madeleine", "address": "47 rue Couteliers" },
  { "name": "fenêtre goth hôtel de Barrassy XVII° : 42-44", "address": "42-44 rue Couteliers" },
  { "name": "couvent Madeleine : 47 - 49", "address": "47 - 49 rue Couteliers" },
  { "name": "couvent Augustines : 47 - 49", "address": "47 - 49 rue Couteliers" },
  { "name": "bâtiment remarquable", "address": "2 rue Croix-Baragnon" },
  { "name": "hôtel Castellane, Arnaud Faure, disp.", "address": "10 rue Croix-Baragnon" },
  { "name": "maison romane", "address": "15 rue Croix-Baragnon" },
  { "name": "bâtiment remarquable", "address": "17 rue Croix-Baragnon" },
  { "name": "hôtel Beringuier-Bonnefoy, tour", "address": "19 rue Croix-Baragnon" },
  { "name": "hôtel Montval, tour-proche Thomas Montval", "address": "22 rue Croix-Baragnon" },
  { "name": "néo gothique", "address": "28 rue Croix-Baragnon" },
  { "name": "hôtel Fumel : 2 & 6", "address": "2 & 6 rue Croix-Baragnon" },
  { "name": "bâtiment remarquable", "address": "1 rue Cujas" },
  { "name": "arc de boutique", "address": "6 rue Cujas" },
  { "name": "corrondage : 8 & 10", "address": "8 & 10 rue Cujas" },
  { "name": "statue ou sculpture ?", "address": "16 rue Dalayrac" },
  { "name": "statue ou sculpture ? : 2 & 10", "address": "2 & 10 rue Dalayrac" },
  { "name": "église Dalbade", "address": "1 rue Dalbade" },
  { "name": "école Fabre ?", "address": "4 rue Dalbade" },
  { "name": "hôtel Masuyer", "address": "5 rue Dalbade" },
  { "name": "manque", "address": "7 rue Dalbade" },
  { "name": "manque", "address": "10 rue Dalbade" },
  { "name": "manque", "address": "11 rue Dalbade" },
  { "name": "manque", "address": "12 rue Dalbade" },
  { "name": "ancienne église Sainte-Barbe", "address": "13 rue Dalbade" },
  { "name": "immeuble 1810 - 1860", "address": "13 rue Dalbade" },
  { "name": "escalier bois", "address": "14 rue Dalbade" },
  { "name": "hôtel de Villepigne", "address": "16 rue Dalbade" },
  { "name": "hôtel de Montbel", "address": "18 rue Dalbade" },
  { "name": "manque", "address": "20 rue Dalbade" },
  { "name": "hôtel Molinier (Felzins) ancien hôtel Catelan, tour", "address": "22 rue Dalbade" },
  { "name": "hôtel Bajuly", "address": "23 rue Dalbade" },
  { "name": "hôtel Clari ou de pierre (Bagis)", "address": "25 rue Dalbade" },
  { "name": "bâtiment remarquable", "address": "27 rue Dalbade" },
  { "name": "hôtel Aldéguier, tour", "address": "29 rue Dalbade" },
  { "name": "hôtel de Saint-Jean XVII°", "address": "30 rue Dalbade" },
  { "name": "hôtel Lamamye, tour", "address": "31 rue Dalbade" },
  { "name": "hôtel Bruni, tour", "address": "37 rue Dalbade" },
  { "name": "Maison Templier : 13-15", "address": "13-15 rue Dalbade" },
  { "name": "maison du Prieur (Saint-Jean) : 13-15", "address": "13-15 rue Dalbade" },
  { "name": "chapelle Notre Dame de la Conception : 13-15", "address": "13-15 rue Dalbade" },
  { "name": "couvent et église de la Visitation : 13-15", "address": "13-15 rue Dalbade" },
  { "name": "Congrégation de l'Oratoire : 33-35-37", "address": "33-35-37 rue Dalbade" },
  { "name": "portail", "address": "3 rue Darquié" },
  { "name": "bâtiment remarquable", "address": "4 rue Darquié" },
  { "name": "bâtiment remarquable", "address": "5 rue Darquié" },
  { "name": "tours Nicolas Lathony et Paul de Cazes", "address": "6 rue Darquié" },
  { "name": "bâtiment remarquable", "address": "8 rue Darquié" },
  { "name": "bâtiment remarquable", "address": "9 rue Darquié" },
  { "name": "tour Nicolas Boyssonet", "address": "10 rue Darquié" },
  { "name": "portail, tour Jean de Quinquiry", "address": "11 rue Darquié" },
  { "name": "école des beaux-arts", "address": "5 quai Daurade" },
  { "name": "palais des Arts", "address": "5 quai Daurade" },
  { "name": "noviciat", "address": "17 quai Daurade" },
  { "name": "corrondage : 9 & 13", "address": "9 & 13 rue Daurade" },
  { "name": "écoles de théologie", "address": "1 rue Deville" },
  { "name": "derrière : hôtel Cambolas disp ?", "address": "1 rue Deville" },
  { "name": "Sœurs de Notre Dame de la Compassion", "address": "2 rue Deville" },
  { "name": "collège de Narbonne : angle r Deville et r Al. Laut.", "address": "10 rue Deville" },
  { "name": "bâtiment remarquable", "address": "1 rue Dumay" },
  { "name": "bâtiment remarquable", "address": "3 rue Dumay" },
  { "name": "bâtiment remarquable", "address": "4 rue Dumay" },
  { "name": "maison confrérie miséricorde", "address": "5 rue Dumay" },
  { "name": "hôtel Dumay, tour", "address": "7 rue Dumay" },
  { "name": "bâtiment remarquable", "address": "9 rue Dumay" },
  { "name": "portail", "address": "16 rue Dumay" },
  { "name": "chapelle Saint-Sauveur : clocher-mur halle aux grains", "address": "1 place Dupuy" },
  { "name": "cimetière St-Sauveur, de Halle aux grains à pl. Dupuy", "address": "1 place Dupuy" },
  { "name": "hôtel", "address": "3 rue Echarpe" },
  { "name": "fée et tête lion", "address": "10 rue Echarpe" },
  { "name": "couvent des Tiercerettes", "address": "no rue Embarthes" },
  { "name": "chappelle des bénédictines", "address": "1 rue Emile Cartailhac" },
  { "name": "Collège Papillon, angle r.Emile Cartailhac et pl. Peyrou", "address": "1 rue Emile Cartailhac" },
  { "name": "bâtiment remarquable", "address": "2 rue Escoussières Montgaillard" },
  { "name": "bâtiment remarquable", "address": "4 rue Escoussières Montgaillard" },
  { "name": "bâtiment remarquable", "address": "10 rue Escoussières Montgaillard" },
  { "name": "bâtiment remarquable", "address": "14 rue Escoussières Montgaillard" },
  { "name": "bâtiment remarquable : 2bis", "address": "2bis rue Escoussières Montgaillard" },
  { "name": "hôtel Mansencal, tour", "address": "1 rue Espinasse" },
  { "name": "ancien cloître des dominicains", "address": "1 rue Espinasse" },
  { "name": "hôtel Tournier disp ?", "address": "4 rue Espinasse" },
  { "name": "hôtel ach disp ?", "address": "5 rue Espinasse" },
  { "name": "bâtiment remarquable", "address": "6 rue Espinasse" },
  { "name": "bâtiment remarquable", "address": "8 rue Espinasse" },
  { "name": "bâtiment remarquable", "address": "9 rue Espinasse" },
  { "name": "manque", "address": "24 rue Espinasse" },
  { "name": "bâtiment remarquable", "address": "2 rue Esquile" },
  { "name": "bâtiment remarquable", "address": "3 rue Esquile" },
  { "name": "bâtiment remarquable", "address": "3 rue Esquile" },
  { "name": "manque", "address": "4 rue Esquile" },
  { "name": "hôtel de Caylus XVIII° : 5 ou 6", "address": "5 ou 6 rue Esquile" },
  { "name": "portail coll. Esquile, face rue Pénitents Gris", "address": "no rue Esquile" },
  { "name": "église Saint-Géraud", "address": "10 place Esquirol" },
  { "name": "hôtel Desplats ou Palaminy", "address": "12 place Esquirol" },
  { "name": "chappelle Saint-Géraud", "address": "12 place Esquirol" },
  { "name": "Sanctuaire, Halle de Pierre et marché couvert: 2 - 4 - 6 - 8", "address": "2 - 4 - 6 - 8 place Esquirol" },
  { "name": "halle de Pierre jusque 1862", "address": "no place Esquirol" },
  { "name": "hôtel Auriol", "address": "1 rue Féral" },
  { "name": "manque", "address": "3 rue Féral" },
  { "name": "chapelle Nazareth", "address": "4 rue Féral" },
  { "name": "imp lycée Fermat tour de la pension Lacointa : 16°s", "address": "no imp Fermat" },
  { "name": "bâtiment remarquable", "address": "2 rue Fermat" },
  { "name": "hôtel Sevin-Mansencal : Statue, tours", "address": "3 rue Fermat" },
  { "name": "hôtel Malenfant", "address": "5 rue Fermat" },
  { "name": "escalier de pierre", "address": "11 rue Fermat" },
  { "name": "bâtiment remarquable", "address": "13 rue Fermat" },
  { "name": "maison orfèvre Gérauld", "address": "9 rue Filatiers" },
  { "name": "modillon", "address": "15 rue Filatiers" },
  { "name": "sirènes et corrondage", "address": "27 rue Filatiers" },
  { "name": "bois escalier corrondage", "address": "29 rue Filatiers" },
  { "name": "bâtiment remarquable", "address": "36 rue Filatiers" },
  { "name": "maison Lamothe", "address": "47 rue Filatiers" },
  { "name": "maison Calas", "address": "50 rue Filatiers" },
  { "name": "ancien hôtel Monnaie", "address": "1 rue Fleurs" },
  { "name": "(entre rue Azes et pl du Salin)", "address": "1 rue Fleurs" },
  { "name": "chapelle Saint-Barthélémy", "address": "1 rue Fleurs" },
  { "name": "angle r. Nazareth et du Vieux-Raisin)", "address": "1 rue Fleurs" },
  { "name": "bâtiment remarquable", "address": "12 rue Fleurs" },
  { "name": "portail, hôtel Fajole XVIII°", "address": "13 rue Fleurs" },
  { "name": "bâtiment remarquable", "address": "14 rue Fleurs" },
  { "name": "observatoire", "address": "16 rue Fleurs" },
  { "name": "hôtel de la Sénéchausée : avant église des Gésus", "address": "22 rue Fleurs" },
  { "name": "bâtiment remarquable", "address": "20bis rue Fleurs" },
  { "name": "bâtiment remarquable : 22bis", "address": "22bis rue Fleurs" },
  { "name": "hôtel de Margastaud", "address": "15 rue Fonderie" },
  { "name": "tourelle Gilles de Tiffaut", "address": "18 rue Fonderie" },
  { "name": "Clarisses", "address": "31 rue Fonderie" },
  { "name": "bâtiment remarquable", "address": "3 rue Fourtanier" },
  { "name": "bâtiment remarquable", "address": "14 rue Fourtanier" },
  { "name": "imm. Joseph Gilet", "address": "15 allées Frédéric Mistral" },
  { "name": "imm. Pierre Maure", "address": "18 allées Frédéric Mistral" },
  { "name": "hôtel Furgole", "address": "1 rue Furgole" },
  { "name": "église des Gésus", "address": "1 rue Furgole" },
  { "name": "hôtel Bernuy", "address": "1 rue Gambetta" },
  { "name": "bâtiment remarquable", "address": "35 rue Gambetta" },
  { "name": "hôtel Maleprade", "address": "43 rue Gambetta" },
  { "name": "façade", "address": "48 rue Gambetta" },
  { "name": "collège Ste Catherine ou de Pampelune", "address": "58 rue Gambetta" },
  { "name": "chapelle Saint-Catherine : clé de voûte, porte", "address": "58 rue Gambetta" },
  { "name": "tourelles collège Ste-Catherine, hôtel Crown Plaza", "address": "58 rue Gambetta" },
  { "name": "gauche maison inquisition : 6 & 8", "address": "6 & 8 imp Hache" },
  { "name": "couvent Bon Pasteur", "address": "6 rue Hache" },
  { "name": "Couvent Marie-Réparatrice : 6 & 8", "address": "6 & 8 rue Hache" },
  { "name": "bâtiment remarquable", "address": "1 place Hauts Murats" },
  { "name": "rue à compléter", "address": "9 rue Hauts Murats" },
  { "name": "homme armé : sauvage", "address": "18 rue Homme Armé" },
  { "name": "jardin des Minorettes = Ste-Claire ou Clarisses", "address": "no rue Homme Armé" },
  { "name": "bâtiment remarquable", "address": "1 place Jeanne d'Arc" },
  { "name": "statue Jeanne d'Arc", "address": "1 place Jeanne d'Arc" },
  { "name": "Saint Orens ou de la Sainte-Croix", "address": "1b place Jeanne d'Arc" },
  { "name": "statue Jeanne d'Arc", "address": "1t place Jeanne d'Arc" },
  { "name": "bâtiment remarquable", "address": "13 rue Joseph Vie" },
  { "name": "hôtel de Rességuier, tour", "address": "2 rue Joutx Aigues" },
  { "name": "syna, entrée juifs", "address": "3 rue Joutx Aigues" },
  { "name": "hôtel Sapte disp ?", "address": "3 rue Joutx Aigues" },
  { "name": "décagone Dalbade, hôt Roquette ?", "address": "4 rue Joutx Aigues" },
  { "name": "bâtiment remarquable", "address": "6 rue Joutx Aigues" },
  { "name": "maison Lespinasse", "address": "9 rue Joutx Aigues" },
  { "name": "bâtiment remarquable : 1ter", "address": "1ter rue Joutx Aigues" },
  { "name": "bâtiment remarquable", "address": "32 allées Jules Guesdes" },
  { "name": "bâtiment remarquable", "address": "9 rue Kennedy" },
  { "name": "pillastres", "address": "18 rue Lafayette" },
  { "name": "hôtel Chaumont", "address": "19 rue Lafayette" },
  { "name": "bâtiment remarquable", "address": "20 rue Lafayette" },
  { "name": "bâtiment remarquable", "address": "22 rue Lafayette" },
  { "name": "bâtiment remarquable", "address": "24 rue Lafayette" },
  { "name": "temple", "address": "35 rue Lafayette" },
  { "name": "bâtiment remarquable", "address": "3 place Lafourcade" },
  { "name": "gendarmerie : 1bis", "address": "1bis place Lafourcade" },
  { "name": "château d'eau", "address": "1 place Laganne" },
  { "name": "bâtiment remarquable", "address": "4 rue Lakanal" },
  { "name": "Rempart Romain", "address": "9 rue Lakanal" },
  { "name": "bâtiment remarquable : 15bis", "address": "15bis rue Lancefoc" },
  { "name": "Saint-Joseph la Grave : verif, arcades sinon", "address": "1 place Langé" },
  { "name": "bâtiment remarquable", "address": "10 rue Languedoc" },
  { "name": "bâtiment remarquable", "address": "11 rue Languedoc" },
  { "name": "bâtiment remarquable", "address": "14 rue Languedoc" },
  { "name": "hôtel Rabaudy de Paucy", "address": "16 rue Languedoc" },
  { "name": "bâtiment remarquable", "address": "22 rue Languedoc" },
  { "name": "plaque rue", "address": "24 rue Languedoc" },
  { "name": "hôtel de Guillaume Vesa XVIème", "address": "25 rue Languedoc" },
  { "name": "tour Auriol", "address": "26 rue Languedoc" },
  { "name": "bâtiment remarquable", "address": "29 rue Languedoc" },
  { "name": "hôtel Carreri, tour", "address": "30 rue Languedoc" },
  { "name": "hôtel de Mourlens", "address": "34 rue Languedoc" },
  { "name": "hôtel Maynier dit du Vieux-Raisin, Lasbordes, tour", "address": "36 rue Languedoc" },
  { "name": "bâtiment remarquable", "address": "44 rue Languedoc" },
  { "name": "bâtiment remarquable : 10bis", "address": "10bis rue Languedoc" },
  { "name": "plaque Silvio Trentin", "address": "44bis rue Languedoc" },
  { "name": "Bénédictines de Notre-Dame du Sac", "address": "17 rue Larrey" },
  { "name": "Sur son emplacement, a été édifié l'hôpital Larrey", "address": "17 rue Larrey" },
  { "name": "puis le Conservatoire de musique", "address": "17 rue Larrey" },
  { "name": "bâtiment remarquable : 2qu", "address": "2qu rue Larrey" },
  { "name": "bâtiment remarquable", "address": "22 rue Lejeune" },
  { "name": "hôtel Rességuier, tour", "address": "3 rue Lieutenant-Pélissier" },
  { "name": "maison Tailhasson", "address": "7 rue Lieutenant-Pélissier" },
  { "name": "bâtiment remarquable", "address": "11 rue Lieutenant-Pélissier" },
  { "name": "église Saint-Jérôme : 2 bis", "address": "2 bis rue Lieutenant-Pélissier" },
  { "name": "commanderie Saint-Antoine de Vienne : 4 & 10", "address": "4 & 10 rue Lieutenant-Pélissier" },
  { "name": "hôtel Grand Balcon", "address": "1 rue Lois" },
  { "name": "collège de Foix", "address": "9 rue Lois" },
  { "name": "Emplacement de la chapelle de Rieux", "address": "13 rue Lois" },
  { "name": "bas reliefs", "address": "17 rue Lois" },
  { "name": "Sainte-Epine", "address": "19 rue Lois" },
  { "name": "collège Esquile", "address": "34 rue Lois" },
  { "name": "écoles des Arts", "address": "34 rue Lois" },
  { "name": "bâtiment remarquable", "address": "24 quai Lombard" },
  { "name": "bâtiment remarquable", "address": "31 quai Lombard" },
  { "name": "Pénitents Noirs", "address": "no place Lucas" },
  { "name": "hôtel Tornié de Vaillac", "address": "3 rue Madeleine" },
  { "name": "hôtel Tournoër ou Tournié disp ?", "address": "3 rue Madeleine" },
  { "name": "tour dames Rapoude, Gaitapuech", "address": "4 rue Madeleine" },
  { "name": "bâtiment remarquable", "address": "5 rue Madeleine" },
  { "name": "Jésus Hostie", "address": "no rue Madeleine" },
  { "name": "hôtel d'Espie", "address": "3 rue Mage" },
  { "name": "imm XVIII°", "address": "4 rue Mage" },
  { "name": "escalier, vitraux", "address": "5 rue Mage" },
  { "name": "escalier, vitraux", "address": "7 rue Mage" },
  { "name": "bâtiment remarquable", "address": "9 rue Mage" },
  { "name": "hôtel Orbessan", "address": "11 rue Mage" },
  { "name": "imeuble", "address": "13 rue Mage" },
  { "name": "bâtiment remarquable", "address": "14 rue Mage" },
  { "name": "hôtel Ayguevives", "address": "16 rue Mage" },
  { "name": "bâtiment remarquable", "address": "18 rue Mage" },
  { "name": "tour de Reynier", "address": "20 rue Mage" },
  { "name": "hôtel Durasse", "address": "20 rue Mage" },
  { "name": "tour d'Antoine Turle", "address": "22 rue Mage" },
  { "name": "bâtiment remarquable", "address": "24 rue Mage" },
  { "name": "hôtel Cassan : statue", "address": "32 rue Mage" },
  { "name": "antéfixe", "address": "34 rue Mage" },
  { "name": "à compléter", "address": "0 rue Magne" },
  { "name": "couvent", "address": "2 rue Magne" },
  { "name": "hôtel Hautpoul disp", "address": "25 rue Malaret" },
  { "name": "maison Reynauld disp ? : 2 & 4 & 6", "address": "2&4&6 rue Malaret" },
  { "name": "bâtiment remarquable", "address": "12 rue Malbec" },
  { "name": "bâtiment remarquable", "address": "9 rue Malcousinat" },
  { "name": "hôtel Boysson, tour", "address": "11 rue Malcousinat" },
  { "name": "bâtiment remarquable", "address": "1 rue Maletache" },
  { "name": "verif : corrondage", "address": "16 rue Maletache" },
  { "name": "manufacture Tabacs", "address": "no manufacture Tabacs" },
  { "name": "cariatides", "address": "28 rue Marchands" },
  { "name": "bâtiment remarquable", "address": "30 rue Marchands" },
  { "name": "colonnes", "address": "33 rue Marchands" },
  { "name": "immeuble 1810 - 1860", "address": "34 rue Marchands" },
  { "name": "bâtiment remarquable", "address": "36 rue Marchands" },
  { "name": "immeuble 1810 - 1860", "address": "40 rue Marchands" },
  { "name": "bâtiment remarquable", "address": "0 bd Maurice Fontvielle" },
  { "name": "rue à compléter", "address": "900 rue Maurice Fontvielle" },
  { "name": "hôtel de Jessé, haut-relief", "address": "7 rue Mercié" },
  { "name": "chapelle Saint-Jean Baptiste", "address": "7 rue Mercié" },
  { "name": "cour", "address": "11 rue Mercié" },
  { "name": "bâtiment remarquable", "address": "13 rue Mercié" },
  { "name": "façade", "address": "15 rue Mercié" },
  { "name": "néo gothique", "address": "15 rue Mercié" },
  { "name": "bis façade avec personnages", "address": "11bis rue Mercié" },
  { "name": "bâtiment remarquable", "address": "13 rue Meriel" },
  { "name": "hôtel Cassan", "address": "4 rue Merlane" },
  { "name": "bâtiment remarquable", "address": "2 rue Metz" },
  { "name": "hôtel Assezat", "address": "9 rue Metz" },
  { "name": "bâtiment remarquable", "address": "14 rue Metz" },
  { "name": "Augustins", "address": "21 rue Metz" },
  { "name": "chapelle Gauthier, ex rue du Pont Neuf", "address": "no rue Metz" },
  { "name": "bâtiment remarquable", "address": "1 rue Mirepoix" },
  { "name": "Collège de Mirepoix", "address": "3 rue Mirepoix" },
  { "name": "bâtiment remarquable", "address": "4 rue Mirepoix" },
  { "name": "Collège de Mirepoix", "address": "5 rue Mirepoix" },
  { "name": "tour néogothique (jaune) XIX° s.", "address": "2 place Montoulieu" },
  { "name": "Palais Niel", "address": "2 rue Montoulieu-Saint-Jacques" },
  { "name": "hôtel Lestang, tour", "address": "3 rue Montoulieu-Saint-Jacques" },
  { "name": "bâtiment remarquable", "address": "15 rue Montoulieu-Vélane" },
  { "name": "bâtiment remarquable", "address": "21 rue Montoulieu-Vélane" },
  { "name": "bâtiment remarquable", "address": "5 rue Montoyol" },
  { "name": "bâtiment remarquable", "address": "6 rue Montoyol" },
  { "name": "bâtiment remarquable", "address": "7 rue Montoyol" },
  { "name": "homme armé", "address": "10 rue Moulins" },
  { "name": "bâtiment remarquable", "address": "14 gde rue Nazareth" },
  { "name": "portail", "address": "19 gde rue Nazareth" },
  { "name": "bâtiment remarquable", "address": "20 gde rue Nazareth" },
  { "name": "bâtiment remarquable", "address": "22 gde rue Nazareth" },
  { "name": "niche", "address": "23 gde rue Nazareth" },
  { "name": "hôtel Avizard : Statue, niche", "address": "24 gde rue Nazareth" },
  { "name": "bâtiment remarquable", "address": "26 gde rue Nazareth" },
  { "name": "hôtel Potier-Laterrasse", "address": "28 gde rue Nazareth" },
  { "name": "niche", "address": "34 gde rue Nazareth" },
  { "name": "hôtel Bauderon-Maussac", "address": "35 gde rue Nazareth" },
  { "name": "ancien hôtel Baderon-Maussac, disp", "address": "37 gde rue Nazareth" },
  { "name": "tour de l'hôtel subsiste au numéro 8 de la rue Ozenne", "address": "37 gde rue Nazareth" },
  { "name": "école St-Thomas Acquin (façade hôtel Massencal)", "address": "40 gde rue Nazareth" },
  { "name": "bâtiment remarquable", "address": "19bis gde rue Nazareth" },
  { "name": "Pension des Dames Berryes (Mansencal)", "address": "1 rue Ninau" },
  { "name": "bâtiment remarquable", "address": "6 rue Ninau" },
  { "name": "bâtiment remarquable", "address": "7 rue Ninau" },
  { "name": "bâtiment remarquable", "address": "8 rue Ninau" },
  { "name": "bâtiment remarquable", "address": "10 rue Ninau" },
  { "name": "hôtel Paulo : 12 & 14", "address": "12 rue Ninau" },
  { "name": "bâtiment remarquable", "address": "13 rue Ninau" },
  { "name": "hôtel Ulmo, tour", "address": "15 rue Ninau" },
  { "name": "hôtel Ulmo, tour", "address": "17 rue Ninau" },
  { "name": "hôtel de Castagnier d'Auriac", "address": "19 rue Ninau" },
  { "name": "hôtel Guérard", "address": "20 rue Ninau" },
  { "name": "hôtel Paulo : 12 & 14", "address": "12 & 14 rue Ninau" },
  { "name": "bâtiment remarquable", "address": "11 rue Novars" },
  { "name": "bâtiment remarquable", "address": "16 place Olivier" },
  { "name": "bâtiment remarquable", "address": "2 rue Ozenne" },
  { "name": "hôtel Saint-Martin 1921 3 ét rue Ozenne oculi", "address": "3 rue Ozenne" },
  { "name": "portail", "address": "3 rue Ozenne" },
  { "name": "maison Bernardin, gothique, 2 étage", "address": "3 rue Ozenne" },
  { "name": "bâtiment remarquable", "address": "5 rue Ozenne" },
  { "name": "hôtel Dahus", "address": "9 rue Ozenne" },
  { "name": "façade", "address": "23 rue Ozenne" },
  { "name": "bâtiment remarquable", "address": "29 rue Ozenne" },
  { "name": "bis Baderon-Maussac, tour", "address": "8bis rue Ozenne" },
  { "name": "hôtel Tournoër : 9bis", "address": "9bis rue Ozenne" },
  { "name": "corrondage", "address": "18 rue Paradoux" },
  { "name": "hôtel Castaing", "address": "28 rue Paradoux" },
  { "name": "escalier", "address": "32 rue Paradoux" },
  { "name": "maison Arquier", "address": "34 rue Paradoux" },
  { "name": "bâtiment remarquable", "address": "51 rue Paradoux" },
  { "name": "bâtiment remarquable", "address": "1 rue Pargaminières" },
  { "name": "portail", "address": "22 rue Pargaminières" },
  { "name": "bâtiment remarquable", "address": "25 rue Pargaminières" },
  { "name": "bâtiment remarquable", "address": "40 rue Pargaminières" },
  { "name": "tête lion + coquilles", "address": "42 rue Pargaminières" },
  { "name": "niche", "address": "44 rue Pargaminières" },
  { "name": "bâtiment remarquable", "address": "45 rue Pargaminières" },
  { "name": "bâtiment remarquable", "address": "54 rue Pargaminières" },
  { "name": "palais justice", "address": "1 place Parlement" },
  { "name": "maison Seilhan", "address": "7 place Parlement" },
  { "name": "Fac Théologie", "address": "8 place Parlement" },
  { "name": "Corrondage", "address": "11 place Parlement" },
  { "name": "hôtel Chalvet", "address": "12 place Parlement" },
  { "name": "maison de ville, néo gothique", "address": "14 rue Paul Feuga" },
  { "name": "Pénitents Noirs, inscription, tour", "address": "10 rue Paul Mériel" },
  { "name": "Corrondage", "address": "2 rue Perchepinte" },
  { "name": "Corrondage", "address": "9 rue Perchepinte" },
  { "name": "galerie", "address": "12 rue Perchepinte" },
  { "name": "Corrondage", "address": "13 rue Perchepinte" },
  { "name": "escalier", "address": "15 rue Perchepinte" },
  { "name": "portail", "address": "19 rue Perchepinte" },
  { "name": "arcades", "address": "22 rue Perchepinte" },
  { "name": "maison Castelpers", "address": "24 rue Perchepinte" },
  { "name": "arch evêché : Labat de Savignac", "address": "24 rue Perchepinte" },
  { "name": "couvent des Carmélites", "address": "1 rue Périgord" },
  { "name": "bibliothèque", "address": "3 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "5 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "7 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "8 rue Périgord" },
  { "name": "couvent de la Visitation", "address": "9 rue Périgord" },
  { "name": "Sainte-Marie-de-Nevers", "address": "10 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "14 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "18 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "20 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "22 rue Périgord" },
  { "name": "bâtiment remarquable", "address": "24 rue Périgord" },
  { "name": "collège du Périgord", "address": "56 rue Périgord" },
  { "name": "hôtel Maurand, tour", "address": "56 rue Périgord" },
  { "name": "Corrondage", "address": "1 rue Peyras" },
  { "name": "Corrondage", "address": "3 rue Peyras" },
  { "name": "Corrondage", "address": "6 rue Peyras" },
  { "name": "Corrondage", "address": "7 rue Peyras" },
  { "name": "façade immeuble Virebent", "address": "10 rue Peyras" },
  { "name": "hôtel Tiffy", "address": "13 rue Peyras" },
  { "name": "bâtiment remarquable", "address": "14 rue Peyras" },
  { "name": "bâtiment remarquable", "address": "26 rue Peyras" },
  { "name": "hôtel d'Olmières, tour", "address": "3 rue Peyrolières" },
  { "name": "bâtiment remarquable", "address": "6 rue Peyrolières" },
  { "name": "bâtiment remarquable", "address": "9 rue Peyrolières" },
  { "name": "bâtiment remarquable", "address": "16 rue Peyrolières" },
  { "name": "bâtiment remarquable", "address": "17 rue Peyrolières" },
  { "name": "hôtel Ysalguier, tour", "address": "18 rue Peyrolières" },
  { "name": "bâtiment remarquable", "address": "30 rue Peyrolières" },
  { "name": "hôtel Lagorré, tour", "address": "34 rue Peyrolières" },
  { "name": "hôtel Labat", "address": "34 rue Peyrolières" },
  { "name": "de Belvèze, tour", "address": "39 rue Peyrolières" },
  { "name": "maison Ortet", "address": "45 rue Peyrolières" },
  { "name": "mascaron", "address": "15 rue Pharaon" },
  { "name": "hôtel Waroquier", "address": "17 rue Pharaon" },
  { "name": "Couvent Saint-Antoine de Lézat", "address": "18 rue Pharaon" },
  { "name": "couvent St François", "address": "20 rue Pharaon" },
  { "name": "hôtel Taverne ou Rolle, tour", "address": "21 rue Pharaon" },
  { "name": "bâtiment remarquable", "address": "22 rue Pharaon" },
  { "name": "portail", "address": "29 rue Pharaon" },
  { "name": "maison Servientes, tour", "address": "35 rue Pharaon" },
  { "name": "escalier", "address": "41 rue Pharaon" },
  { "name": "fontaine, hôtel de Réversac XVII°", "address": "42 rue Pharaon" },
  { "name": "oculus et portail", "address": "43 rue Pharaon" },
  { "name": "hôtel de Lespinasse", "address": "45 rue Pharaon" },
  { "name": "bâtiment remarquable", "address": "47 rue Pharaon" },
  { "name": "hôtel Pastoureau, tour", "address": "52 rue Pharaon" },
  { "name": "bâtiment remarquable", "address": "56 rue Pharaon" },
  { "name": "monastère Saint-Antonin du Salin : 18-20", "address": "18-20 rue Pharaon" },
  { "name": "TNT", "address": "1 rue Pierre Baudis" },
  { "name": "Sorano, mort Simon de Montfort", "address": "no plaque jardin plante" },
  { "name": "bâtiment remarquable", "address": "13 rue Pleau" },
  { "name": "bâtiment remarquable", "address": "15 rue Pleau" },
  { "name": "hôtel Lapleau : inconnu", "address": "17 rue Pleau" },
  { "name": "colonnes", "address": "2 rue Poids de l'Huile" },
  { "name": "bâtiment remarquable", "address": "3 rue Pointurier" },
  { "name": "bâtiment remarquable", "address": "27 rue Polinaires" },
  { "name": "consoles", "address": "28 rue Polinaires" },
  { "name": "portail", "address": "30 rue Polinaires" },
  { "name": "bâtiment remarquable", "address": "33 rue Polinaires" },
  { "name": "tour romaine dans immeuble ?", "address": "no rue Polinaires" },
  { "name": "bâtiment remarquable", "address": "3 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "14 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "15 rue Pomme" },
  { "name": "maison Duranti", "address": "17 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "22 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "28 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "57 rue Pomme" },
  { "name": "chapelle Saint-Pantaléon", "address": "61 rue Pomme" },
  { "name": "oculus, fronton", "address": "63 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "66 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "68 rue Pomme" },
  { "name": "bâtiment remarquable", "address": "70 rue Pomme" },
  { "name": "tour collège Pauvrets ?", "address": "70 rue Pomme" },
  { "name": "immeuble", "address": "15 rue Pont de Tounis" },
  { "name": "bis Bachus", "address": "10bis rue Pont de Tounis" },
  { "name": "brasserie : 8 & 12", "address": "8 & 12 rue Pont de Tounis" },
  { "name": "maison d'angle", "address": "10 rue Pont Saint-Pierre" },
  { "name": "bâtiment remarquable", "address": "7 place pont-neuf" },
  { "name": "bâtiment remarquable", "address": "9 place pont-neuf" },
  { "name": "plaques entrée Louis XIV", "address": "10 place pont-neuf" },
  { "name": "halle poissons : 12 & 14", "address": "12 & 14 place pont-neuf" },
  { "name": "ponts-jumeaux", "address": "no Ponts" },
  { "name": "maison procureur au Parlement", "address": "2 rue Poutiroux" },
  { "name": "Jean Poitron", "address": "2 rue Poutiroux" },
  { "name": "bâtiment remarquable", "address": "4 rue Poutiroux" },
  { "name": "église Saint-Jacques", "address": "1 imp Préfecture" },
  { "name": "prison de l'écarlate", "address": "1 imp Préfecture" },
  { "name": "bâtiment remarquable", "address": "3 rue Prêtres" },
  { "name": "hôtel du Poids des Blés, tourelle", "address": "5 rue Prêtres" },
  { "name": "art nouveau", "address": "10 rue Prêtres" },
  { "name": "auberge Griffon d'or", "address": "16 rue Prêtres" },
  { "name": "Corrondage", "address": "1 rue Prieuré" },
  { "name": "bâtiment remarquable", "address": "2 rue Prieuré" },
  { "name": "bâtiment remarquable", "address": "6 rue Prieuré" },
  { "name": "bâtiment remarquable", "address": "7 rue Prieuré" },
  { "name": "bâtiment remarquable", "address": "8 rue Prieuré" },
  { "name": "bâtiment remarquable", "address": "9 rue Prieuré" },
  { "name": "portail", "address": "12 rue Prieuré" },
  { "name": "chapelle Saint-Pierre et Saint-Martin : 3 & 5", "address": "3 & 5 rue Prieuré" },
  { "name": "Prieuré : 5 - 5 bis", "address": "5 - 5 bis rue Prieuré" },
  { "name": "chapelle Saint-Pierre Saint-Martin : 5 - 5 bis", "address": "5 - 5 bis rue Prieuré" },
  { "name": "derrière se trouve le couvent des Ursulines : 5 - 5 bis", "address": "5 - 5 bis rue Prieuré" },
  { "name": "Ursulines : 5 - 5 bis", "address": "5 - 5 bis rue Prieuré" },
  { "name": "rue à compléter", "address": "900 place Puits-Clos" },
  { "name": "rue à compléter + place", "address": "900 rue Puits-Clos" },
  { "name": "rue à compléter", "address": "900 rue Puits-Creusés" },
  { "name": "rue à compléter", "address": "900 rue Puits-Verts" },
  { "name": "bâtiment remarquable", "address": "4 rue Quatre Billards" },
  { "name": "oratoire Sainte-Marie des Fontaines (près pl Ravelin)", "address": "1 place Ravelin" },
  { "name": "fontaine Wallace", "address": "1 place Ravelin" },
  { "name": "portail", "address": "1 rue Regans" },
  { "name": "bâtiment remarquable", "address": "3 rue Regans" },
  { "name": "hôtel Boissy", "address": "8 rue Regans" },
  { "name": "Couvent S.N. de Jésus, chappelle", "address": "8 rue Regans" },
  { "name": "mosaïques", "address": "13 rue Regans" },
  { "name": "puits", "address": "15 rue Regans" },
  { "name": "rue à compléter", "address": "900 rue Regans" },
  { "name": "anges", "address": "2 rue rempart Saint-Etienne" },
  { "name": "maison Vézian", "address": "5 rue rempart Saint-Etienne" },
  { "name": "hôtel Brué", "address": "7 rue rempart Saint-Etienne" },
  { "name": "immeuble 1810 - 1860", "address": "9 rue rempart Saint-Etienne" },
  { "name": "bâtiment remarquable", "address": "14 rue rempart Saint-Etienne" },
  { "name": "tête lion", "address": "17 rue rempart Saint-Etienne" },
  { "name": "maison Alary : 1 & 3", "address": "1 & 3 rue rempart Saint-Etienne" },
  { "name": "bâtiment remarquable", "address": "3 rue Rempart-Villeneuve" },
  { "name": "bâtiment remarquable", "address": "6 rue Rempart-Villeneuve" },
  { "name": "bâtiment remarquable", "address": "17 rue Rémusat" },
  { "name": "Atlantes", "address": "34 rue Rémusat" },
  { "name": "bâtiment remarquable", "address": "36 rue Rémusat" },
  { "name": "couvent Saint-Orens, entrée rue de la Poste", "address": "39 rue Rémusat" },
  { "name": "bâtiment remarquable", "address": "5 rue Renforts" },
  { "name": "bâtiment remarquable", "address": "6 rue Renforts" },
  { "name": "hôtel de Bruée", "address": "7 rue Renforts" },
  { "name": "cave : Remparts romains, jardins, échauguettes", "address": "7 rue Renforts" },
  { "name": "tourelle", "address": "8 rue Renforts" },
  { "name": "bâtiment remarquable", "address": "10 rue Renforts" },
  { "name": "bâtiment remarquable", "address": "15 rue Renforts" },
  { "name": "bâtiment remarquable", "address": "6 rue Rennes" },
  { "name": "hôtel Virebent", "address": "25 rue République" },
  { "name": "consoles", "address": "6 rue Resseguier" },
  { "name": "balustres", "address": "10 rue Resseguier" },
  { "name": "Hospitalières (rue Rivals) : verif La Poste", "address": "5 rue Rivalz" },
  { "name": "à compléter", "address": "0 rue Romiguières" },
  { "name": "à compléter", "address": "0 rue Romiguières" },
  { "name": "bis portail", "address": "6bis rue Romiguières" },
  { "name": "bâtiment remarquable", "address": "8 rue Roode" },
  { "name": "fontaine", "address": "0 place Rouaix" },
  { "name": "Danyen de Roaix", "address": "1 place Rouaix" },
  { "name": "doyen de Saint-Félix", "address": "1 place Rouaix" },
  { "name": "hôtel Caulet XVII°", "address": "3 rue Saint-Antoine du T" },
  { "name": "bâtiment remarquable", "address": "5 rue Saint-Antoine du T" },
  { "name": "bâtiment remarquable", "address": "6 rue Saint-Antoine du T" },
  { "name": "bâtiment remarquable", "address": "7 rue Saint-Antoine du T" },
  { "name": "bâtiment remarquable", "address": "12 rue Saint-Antoine du T" },
  { "name": "balustres", "address": "13 rue Saint-Antoine du T" },
  { "name": "puits", "address": "14 rue Saint-Antoine du T" },
  { "name": "griffons", "address": "20 rue Saint-Antoine du T" },
  { "name": "portail, griffons", "address": "24 rue Saint-Antoine du T" },
  { "name": "niches au 3ème", "address": "26 rue Saint-Antoine du T" },
  { "name": "hôtel Palaminy refait en 1843", "address": "47 rue Saint-Antoine du T" },
  { "name": "médaillons, statue chevalier dans cour, ange : 5 & 7", "address": "5 & 7 rue Saint-Antoine du T" },
  { "name": "villa dr Reygasse - Calbairac, Armandary", "address": "11 rue Saint-Bernard" },
  { "name": "angle Pouzonville - rue St-Bernard 1919 imm. Pilette", "address": "19 rue Saint-Bernard" },
  { "name": "rue à compléter + rues alentours, Arnaud Bernard", "address": "900 rue Saint-Charles" },
  { "name": "portes", "address": "1 place Saint-Cyprien" },
  { "name": "fontaine métro", "address": "1 place Saint-Cyprien" },
  { "name": "bâtiment remarquable", "address": "8 rue Sainte-Anne" },
  { "name": "maison bourgeoise", "address": "14 rue Sainte-Anne" },
  { "name": "chapelle Sainte-Anne", "address": "15 rue Sainte-Anne" },
  { "name": "bâtiment remarquable", "address": "16 rue Sainte-Anne" },
  { "name": "rempart romain", "address": "18 rue Sainte-Anne" },
  { "name": "fontaine", "address": "0 place Sainte-Scrabes" },
  { "name": "hôtel Muriel ou Castelpers", "address": "1 place Sainte-Scrabes" },
  { "name": "bâtiment remarquable", "address": "4 place Sainte-Scrabes" },
  { "name": "bâtiment remarquable", "address": "5 place Sainte-Scrabes" },
  { "name": "parvis", "address": "0 place Saint-Etienne" },
  { "name": "cathédrale", "address": "1 place Saint-Etienne" },
  { "name": "hôtel de Maran", "address": "4 place Saint-Etienne" },
  { "name": "hôtel Catel, tour", "address": "6 place Saint-Etienne" },
  { "name": "Corrondage", "address": "7 place Saint-Etienne" },
  { "name": "portail", "address": "9 place Saint-Etienne" },
  { "name": "Corrondage", "address": "10 place Saint-Etienne" },
  { "name": "hôtel de Froidour", "address": "11 place Saint-Etienne" },
  { "name": "bâtiment remarquable", "address": "12 place Saint-Etienne" },
  { "name": "hôtel Cambon", "address": "14 place Saint-Etienne" },
  { "name": "ballustres", "address": "7 rue Sainte-Ursule" },
  { "name": "portail, tour", "address": "11 rue Sainte-Ursule" },
  { "name": "couvent Ursulines", "address": "13 rue Sainte-Ursule" },
  { "name": "chappelle des Ursulines", "address": "13 rue Sainte-Ursule" },
  { "name": "hôtel Jean Boysson, tour", "address": "13 rue Sainte-Ursule" },
  { "name": "hôtel Jean Boysson, tour", "address": "22 rue Sainte-Ursule" },
  { "name": "ballustres : 18-20", "address": "18-20 rue Sainte-Ursule" },
  { "name": "bâtiment remarquable", "address": "17 place Saint-Georges" },
  { "name": "hôtel Lafage", "address": "19 place Saint-Georges" },
  { "name": "hôtel de Bertier, évêque de Rieux", "address": "24 place Saint-Georges" },
  { "name": "collège Saint-Barthélémy", "address": "25 place Saint-Georges" },
  { "name": "bâtiment remarquable : 7bis", "address": "7bis place Saint-Georges" },
  { "name": "bâtiment remarquable", "address": "1 place Saint-Jacques" },
  { "name": "hôtel Marmiesse", "address": "1 rue Saint-Jacques" },
  { "name": "bâtiment remarquable", "address": "5 rue Saint-Jacques" },
  { "name": "bâtiment remarquable", "address": "18 rue Saint-Jacques" },
  { "name": "hôtel Lestang, tour", "address": "20 rue Saint-Jacques" },
  { "name": "ancienne chambre souverraine du Clergé : 9 & 11", "address": "9 & 11 rue Saint-Jacques" },
  { "name": "couleuvre Colbert : 9 & 11", "address": "9 & 11 rue Saint-Jacques" },
  { "name": "église Saint-Jean angle r. Dalbade - Saint-Jean", "address": "1 rue Saint-Jean" },
  { "name": "chapelle Mc Carthy", "address": "2 rue Saint-Jean" },
  { "name": "école primaire", "address": "4 rue Saint-Jean" },
  { "name": "égl St-Georges reconstruite angle r St-Antoine du T", "address": "1 rue Saint-Jérôme" },
  { "name": "Augustines : couvent et leur chapelle se trouvaient", "address": "1b rue Saint-Jérôme" },
  { "name": "dans la rue Saint-Jérôme. voir 16, r St-Antoine du T : Int", "address": "1b rue Saint-Jérôme" },
  { "name": "Pénitents Noirs", "address": "no rue Saint-Jérôme" },
  { "name": "bâtiment remarquable", "address": "3 rue Saint-Panthaléon" },
  { "name": "bâtiment remarquable", "address": "5 rue Saint-Panthaléon" },
  { "name": "portail", "address": "10 rue Saint-Panthaléon" },
  { "name": "portail + puits", "address": "12 rue Saint-Panthaléon" },
  { "name": "niche", "address": "2 rue Saint-Rémésy" },
  { "name": "hôtel Borassol disp ?", "address": "3 rue Saint-Rémésy" },
  { "name": "portail anc. Hôtel Réqui", "address": "9 rue Saint-Rémésy" },
  { "name": "hôtel Hebrard disp ?", "address": "11 rue Saint-Rémésy" },
  { "name": "portail", "address": "11 rue Saint-Rémésy" },
  { "name": "don au collège Saint-Girons", "address": "12 rue Saint-Rémésy" },
  { "name": "immeuble", "address": "14 rue Saint-Rémésy" },
  { "name": "tour Paul de Marcorelle", "address": "18 rue Saint-Rémésy" },
  { "name": "bâtiment remarquable", "address": "22 rue Saint-Rémésy" },
  { "name": "bâtiment remarquable", "address": "26 rue Saint-Rémésy" },
  { "name": "bâtiment remarquable", "address": "28 rue Saint-Rémésy" },
  { "name": "Corrondage", "address": "46 rue Saint-Rémésy" },
  { "name": "bâtiment remarquable", "address": "9 bis rue Saint-Rémésy" },
  { "name": "bâtiment remarquable", "address": "1 rue Saint-Rome" },
  { "name": "bâtiment remarquable", "address": "13 rue Saint-Rome" },
  { "name": "Corrondage", "address": "15 rue Saint-Rome" },
  { "name": "Corrondage", "address": "17 rue Saint-Rome" },
  { "name": "halle aux poissons", "address": "18 rue Saint-Rome" },
  { "name": "Corrondage", "address": "20 rue Saint-Rome" },
  { "name": "Eglise Saint-Rome", "address": "24 rue Saint-Rome" },
  { "name": "église Saint-Romain, reste bibliothèque - 22 au 26", "address": "24 rue Saint-Rome" },
  { "name": "église Saint-Romain", "address": "26 rue Saint-Rome" },
  { "name": "bâtiment remarquable", "address": "37 rue Saint-Rome" },
  { "name": "nacquit Baour-Lomian", "address": "41 rue Saint-Rome" },
  { "name": "Corrondage", "address": "41 rue Saint-Rome" },
  { "name": "tourelle collège Ste-Catherine, hôtel Crown Plaza", "address": "42 rue Saint-Rome" },
  { "name": "bâtiment remarquable", "address": "55 rue Saint-Rome" },
  { "name": "maison Serta, tour : 2 & 4", "address": "2 & 4 rue Saint-Rome" },
  { "name": "Doctrinaires rue Saint-Rome : 24 & 26", "address": "24 & 26 rue Saint-Rome" },
  { "name": "sœurs Saint-Vincent de Paul", "address": "1 place Saint-Sernin" },
  { "name": "chapelle N. D. des Bonnes Nouvelles", "address": "1 place Saint-Sernin" },
  { "name": "musée Saint-Raymond", "address": "2 place Saint-Sernin" },
  { "name": "monastère des dames bénédictines de Toulouse", "address": "3 place Saint-Sernin" },
  { "name": "Bourse du Travail", "address": "19 place Saint-Sernin" },
  { "name": "St Sernin hôtel Dubarry : 1 & 3", "address": "1 & 3 place Saint-Sernin" },
  { "name": "fontaine", "address": "0 place Salengro" },
  { "name": "maison Riquet", "address": "1 place Salengro" },
  { "name": "motifs céramiques", "address": "4 place Salengro" },
  { "name": "colonne", "address": "6 place Salengro" },
  { "name": "maison Jean Jaurès", "address": "20 place Salengro" },
  { "name": "Salanques ou Beguines", "address": "1 rue Salenques" },
  { "name": "Cloître des Bernardins", "address": "2 rue Salenques" },
  { "name": "verif 28 r Salanques ou 11bis", "address": "1b rue Salenques" },
  { "name": "Bernardines (rue des Salenques)", "address": "1b rue Salenques" },
  { "name": "hôtel de la Monnaie : autour rue d'Azes", "address": "1 place Salin" },
  { "name": "bâtiment remarquable", "address": "5 rue Sénéchal" },
  { "name": "bâtiment remarquable", "address": "9 rue Sénéchal" },
  { "name": "église du Taur", "address": "10 rue Sénéchal" },
  { "name": "bâtiment remarquable", "address": "11 rue Sénéchal" },
  { "name": "relève façade immeuble 1810 - 1860", "address": "20 rue Sénéchal" },
  { "name": "portail", "address": "3 rue Sesquières" },
  { "name": "bâtiment remarquable", "address": "5 rue Sesquières" },
  { "name": "bâtiment remarquable", "address": "9 rue Sesquières" },
  { "name": "bâtiment remarquable", "address": "14 rue Sesquières" },
  { "name": "bâtiment remarquable", "address": "18 rue Sesquières" },
  { "name": "bâtiment remarquable", "address": "77 bd Strasbourg" },
  { "name": "bâtiment remarquable", "address": "2 rue Taur" },
  { "name": "bâtiment remarquable", "address": "7 rue Taur" },
  { "name": "bâtiment remarquable", "address": "8 rue Taur" },
  { "name": "bâtiment remarquable", "address": "19 rue Taur" },
  { "name": "bâtiment remarquable", "address": "30 rue Taur" },
  { "name": "bâtiment remarquable", "address": "33 rue Taur" },
  { "name": "hôtel Mazzoli", "address": "38 rue Taur" },
  { "name": "collège Maguelonne", "address": "38 rue Taur" },
  { "name": "immeuble 1810 - 1860", "address": "38 rue Taur" },
  { "name": "collège Maguelone", "address": "38 rue Taur" },
  { "name": "bâtiment remarquable", "address": "48 rue Taur" },
  { "name": "bâtiment remarquable", "address": "49 rue Taur" },
  { "name": "bâtiment remarquable", "address": "52 rue Taur" },
  { "name": "collège", "address": "58 rue Taur" },
  { "name": "immeuble XIXème", "address": "60 rue Taur" },
  { "name": "bâtiment remarquable", "address": "65 rue Taur" },
  { "name": "collège Esquile", "address": "69 rue Taur" },
  { "name": "bâtiment remarquable", "address": "73 rue Taur" },
  { "name": "couloir", "address": "79 rue Taur" },
  { "name": "collège Périgord : 56 - 58", "address": "56 - 58 rue Taur" },
  { "name": "Feuillants", "address": "9 rue Teinturiers" },
  { "name": "hôtel Ricardy, tour", "address": "2 rue Temponnières" },
  { "name": "hôtel de Baynaguet, tour", "address": "7 rue Temponnières" },
  { "name": "Hôtel de la Belle-Paule, Paule de Viguier", "address": "7 rue Temponnières" },
  { "name": "hôtel Delcros-Lancefoc, escalier, tour Vinhas", "address": "10 rue Temponnières" },
  { "name": "cour", "address": "12 rue Temponnières" },
  { "name": "châpiteaux", "address": "14 rue Temponnières" },
  { "name": "immeuble urbain vitry", "address": "15 rue Temponnières" },
  { "name": "Corrondage", "address": "16 rue Temponnières" },
  { "name": "immeuble 1810 - 1860", "address": "3 rue Tolosane" },
  { "name": "bâtiment remarquable", "address": "4 rue Tolosane" },
  { "name": "guirlandes", "address": "5 rue Tolosane" },
  { "name": "hôtel Candie de Saint-Simon", "address": "6 rue Tolosane" },
  { "name": "hôtel Ramondy", "address": "7 rue Tolosane" },
  { "name": "bâtiment remarquable", "address": "8 rue Tolosane" },
  { "name": "bâtiment remarquable", "address": "9 rue Tolosane" },
  { "name": "escalier, sphynx", "address": "10 rue Tolosane" },
  { "name": "bonsaïs", "address": "12 rue Tolosane" },
  { "name": "maison jeu de pomme", "address": "14 rue Tolosane" },
  { "name": "hôtel de Campistron : 2 & 4", "address": "2 & 4 rue Tolosane" },
  { "name": "à compléter", "address": "0 rue Tourneurs" },
  { "name": "maison Imbert", "address": "9 rue Tourneurs" },
  { "name": "Corrondage", "address": "11 rue Tourneurs" },
  { "name": "maison Ramondy", "address": "15 rue Tourneurs" },
  { "name": "Corrondage", "address": "19 rue Tourneurs" },
  { "name": "maison Astorg de Labat", "address": "20 rue Tourneurs" },
  { "name": "bâtiment remarquable", "address": "41 rue Tourneurs" },
  { "name": "hôtel Desplats, tour", "address": "45 rue Tourneurs" },
  { "name": "bâtiment remarquable", "address": "7 place Trinité" },
  { "name": "façade", "address": "8 place Trinité" },
  { "name": "hôtel Comère", "address": "9 place Trinité" },
  { "name": "balustres", "address": "14 place Trinité" },
  { "name": "maison Serta : 12 & 14", "address": "12 & 14 place Trinité" },
  { "name": "église Trinité dispe : 8 & 12", "address": "8 & 12 place Trinité" },
  { "name": "cloître Trinitaire : 8 & 12", "address": "8 & 12 place Trinité" },
  { "name": "immeuble Urbain vitry", "address": "no place Trinité" },
  { "name": "verrière", "address": "8 rue Trinité" },
  { "name": "tour Fossat (ou pl. Trinité)", "address": "19 rue Trinité" },
  { "name": "maison Pons Imbert", "address": "21 rue Trinité" },
  { "name": "maison Imbert, tour", "address": "21 rue Trinité" },
  { "name": "tour Imbert (ou pl. Trinité)", "address": "21 rue Trinité" },
  { "name": "pans de bois", "address": "23 rue Trinité" },
  { "name": "église Trinité dispe : 8 & 12", "address": "8 & 12 rue Trinité" },
  { "name": "couvent des trinitaires : 8 & 12", "address": "8 & 12 rue Trinité" },
  { "name": "portail : 8 bis", "address": "8 bis rue Trinité" },
  { "name": "immeuble", "address": "1 rue Tripière" },
  { "name": "hôtel Comère, cour, tour", "address": "9 rue Tripière" },
  { "name": "Hôtel de la Belle-Paule, Paule de Viguier", "address": "10 rue Tripière" },
  { "name": "bâtiment remarquable", "address": "18 rue Tripière" },
  { "name": "maison Serta : 12 & 14", "address": "12 & 14 rue Tripière" },
  { "name": "hôtel Virazel : 12 & 14", "address": "12 & 14 rue Tripière" },
  { "name": "bâtiment remarquable : 1bis", "address": "1bis rue Tripière" },
  { "name": "bâtiment remarquable : 1ter", "address": "1ter rue Tripière" },
  { "name": "bâtiment remarquable", "address": "6 rue Trois Journées" },
  { "name": "rue à compléter", "address": "900 rue Trois Journées" },
  { "name": "cour", "address": "9 rue Trois-Banquets" },
  { "name": "cour", "address": "11 rue Trois-Banquets" },
  { "name": "St Pierre Chartreux", "address": "21 rue Valade" },
  { "name": "bâtiment remarquable", "address": "23 rue Valade" },
  { "name": "bâtiment remarquable", "address": "24 rue Valade" },
  { "name": "bâtiment remarquable", "address": "27 rue Valade" },
  { "name": "bâtiment remarquable", "address": "38 rue Valade" },
  { "name": "collège Secondat", "address": "42 rue Valade" },
  { "name": "collège Verdale", "address": "57 rue Valade" },
  { "name": "couvent des Capucins", "address": "57 rue Valade" },
  { "name": "bâtiment remarquable : 16bis", "address": "16bis rue Valade" },
  { "name": "bis ancien couvent", "address": "32bis rue Valade" },
  { "name": "bâtiment remarquable : 32bis", "address": "32bis rue Valade" },
  { "name": "bâtiment remarquable", "address": "3 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "5 rue Vélane-Meneaux" },
  { "name": "portail", "address": "6 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "6 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "7 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "8 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "9 rue Vélane-Meneaux" },
  { "name": "meneaux", "address": "10 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "10 rue Vélane-Meneaux" },
  { "name": "personnages, statue, cadran, hôtel Jossé-Decars XVIII°", "address": "12 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "12 rue Vélane-Meneaux" },
  { "name": "bâtiment remarquable", "address": "21 place Victor Hugo" },
  { "name": "anc hôtel de l'Europe, cinéma Plaza", "address": "6 place Wilson" }
];

export async function GET() {
  return NextResponse.json(establishments);
}
