import { NextResponse } from 'next/server';

interface SiteHautesPyrenees {
  id: number;
  commune: string;
  site: string;
  niveau: number;
  categorie: 'incontournable' | 'remarquable' | 'suggéré';
  lat: number;
  lng: number;
}

const hpSites: SiteHautesPyrenees[] = [
  { id: 1, commune: 'Tarbes', site: 'Jardin Massey, Haras National, Cathédrale Notre-Dame-de-la-Sède, Marché Brauhauban', niveau: 1, categorie: 'incontournable', lat: 43.233, lng: 0.072 },
  { id: 2, commune: 'Lourdes', site: 'Sanctuaire Notre-Dame de Lourdes, Château Fort, Pic du Jer, centre historique', niveau: 1, categorie: 'incontournable', lat: 43.097, lng: -0.046 },
  { id: 3, commune: 'Aureilhan', site: 'Lac d’Aureilhan, espaces de loisirs et promenades', niveau: 3, categorie: 'suggéré', lat: 43.245, lng: 0.083 },
  { id: 4, commune: 'Ibos', site: 'Collégiale Saint-Laurent (gothique)', niveau: 1, categorie: 'incontournable', lat: 43.236, lng: 0.004 },
  { id: 5, commune: 'Argelès-Gazost', site: 'Parc thermal, centre ancien, église Saint-Saturnin', niveau: 1, categorie: 'incontournable', lat: 43.006, lng: -0.098 },
  { id: 6, commune: 'Arrens-Marsous', site: 'Église, Chapelle de Pouey-Laün, Val d’Azun', niveau: 1, categorie: 'incontournable', lat: 42.955, lng: -0.213 },
  { id: 7, commune: 'Cauterets', site: 'Thermes, Pont d’Espagne, Parc National des Pyrénées', niveau: 1, categorie: 'incontournable', lat: 42.889, lng: -0.114 },
  { id: 8, commune: 'Saint-Savin', site: 'Abbatiale romane, panorama, classé Plus Beaux Villages de France', niveau: 1, categorie: 'incontournable', lat: 42.981, lng: -0.120 },
  { id: 9, commune: 'Luz-Saint-Sauveur', site: 'Village, Église romane, Pont Napoléon, Musée', niveau: 1, categorie: 'incontournable', lat: 42.871, lng: -0.006 },
  { id: 10, commune: 'Gavarnie', site: 'Cirque de Gavarnie (UNESCO), village et sentiers', niveau: 1, categorie: 'incontournable', lat: 42.736, lng: -0.010 },
  { id: 11, commune: 'Bagnères-de-Bigorre', site: 'Thermes, centre historique, Musée Salies, Tour des Jacobins, Grand Tourmalet', niveau: 1, categorie: 'incontournable', lat: 43.065, lng: 0.150 },
  { id: 12, commune: 'Campan', site: 'Vallée de Campan, église Saint-Jean-Baptiste', niveau: 2, categorie: 'remarquable', lat: 43.017, lng: 0.177 },
  { id: 13, commune: 'La Mongie', site: 'Pic du Midi de Bigorre, station de montagne', niveau: 1, categorie: 'incontournable', lat: 42.909, lng: 0.177 },
  { id: 14, commune: 'Arreau', site: 'Maison des Lys, Église Saint-Exupère, Château des Nestes, confluent des vallées', niveau: 1, categorie: 'incontournable', lat: 42.905, lng: 0.358 },
  { id: 15, commune: 'Loudenvielle', site: 'Lac de Génos-Loudenvielle, centre balnéo Balnéa', niveau: 1, categorie: 'incontournable', lat: 42.817, lng: 0.413 },
  { id: 16, commune: 'Saint-Lary-Soulan', site: 'Village ancien, téléphérique, stations de montagne, Aquascope', niveau: 1, categorie: 'incontournable', lat: 42.816, lng: 0.322 },
  { id: 17, commune: 'Lannemezan', site: 'Plateau de Lannemezan, centre-ville', niveau: 2, categorie: 'remarquable', lat: 43.124, lng: 0.384 },
  { id: 18, commune: 'Ferrère', site: 'Vallée de la Barousse, paysages montagnards', niveau: 2, categorie: 'remarquable', lat: 42.953, lng: 0.528 },
  { id: 19, commune: 'Mauléon-Barousse', site: 'Château de Bramevaque, patrimoine pastoral', niveau: 2, categorie: 'remarquable', lat: 42.959, lng: 0.561 },
  { id: 20, commune: 'Trie-sur-Baïse', site: 'Place de la Mairie, Monastère des Carmes, bastide', niveau: 1, categorie: 'incontournable', lat: 43.321, lng: 0.341 },
  { id: 21, commune: 'Monléon-Magnoac', site: 'Collégiale, village perché', niveau: 2, categorie: 'remarquable', lat: 43.282, lng: 0.504 },
  { id: 22, commune: 'Castelnau-Magnoac', site: 'Maisons à colombages, cœur historique', niveau: 1, categorie: 'incontournable', lat: 43.298, lng: 0.482 },
  { id: 23, commune: 'Pouyastruc', site: 'Village perché, panorama des coteaux', niveau: 3, categorie: 'suggéré', lat: 43.291, lng: 0.285 },
  { id: 24, commune: 'Tournay', site: 'Abbaye cistercienne', niveau: 3, categorie: 'suggéré', lat: 43.182, lng: 0.243 },
  { id: 25, commune: 'Vic-en-Bigorre', site: 'Vieille bastide, Halles, Église Saint-Martin', niveau: 1, categorie: 'incontournable', lat: 43.385, lng: 0.054 },
  { id: 26, commune: 'Maubourguet', site: 'Église, Abbaye Saint-Martin, berges de l’Adour', niveau: 2, categorie: 'remarquable', lat: 43.468, lng: 0.032 },
  { id: 27, commune: 'Artagnan', site: 'Village natal de d’Artagnan', niveau: 1, categorie: 'incontournable', lat: 43.519, lng: 0.012 },
  { id: 28, commune: 'Madiran', site: 'Vignobles AOC Madiran, Église, village', niveau: 1, categorie: 'incontournable', lat: 43.547, lng: -0.062 },
  { id: 29, commune: 'Mauvezin', site: 'Ancienne forteresse, Château féodal', niveau: 1, categorie: 'incontournable', lat: 43.102, lng: 0.225 },
  { id: 30, commune: 'Sers', site: 'Église romane XIIe siècle, lavoirs, granges traditionnelles', niveau: 3, categorie: 'suggéré', lat: 42.94, lng: 0.19 },
  { id: 31, commune: 'Betpouey', site: 'Village de caractère, église romane, artisans locaux', niveau: 2, categorie: 'remarquable', lat: 42.89, lng: 0.05 },
  { id: 32, commune: 'Viey', site: 'Ruelles pavées, église XVe siècle, lavoir', niveau: 2, categorie: 'remarquable', lat: 42.92, lng: -0.09 },
  { id: 33, commune: 'Viella', site: 'Église Saint-Michel, retable, fontaines et portails', niveau: 2, categorie: 'remarquable', lat: 42.90, lng: 0.03 },
  { id: 34, commune: 'Esterre', site: 'Château Sainte-Marie, église Saint-Étienne', niveau: 1, categorie: 'incontournable', lat: 42.87, lng: -0.02 },
  { id: 35, commune: 'Esquièze-Sère', site: 'Villages en balcon, églises anciennes, ruelles', niveau: 2, categorie: 'remarquable', lat: 42.88, lng: -0.01 },
  { id: 36, commune: 'Sazos', site: 'Ruelles typiques, église XIIe siècle, moulins', niveau: 3, categorie: 'suggéré', lat: 42.88, lng: -0.03 },
  { id: 37, commune: 'Sassis', site: 'Église romane, tourisme thermal et nature', niveau: 3, categorie: 'suggéré', lat: 42.90, lng: -0.04 },
  { id: 38, commune: 'Grust', site: 'Église romane, lavoirs, table d’orientation', niveau: 3, categorie: 'suggéré', lat: 42.89, lng: -0.03 },
  { id: 39, commune: 'Saligos', site: 'Église romane, maisons en terrasses, panorama', niveau: 3, categorie: 'suggéré', lat: 42.90, lng: -0.07 },
  { id: 40, commune: 'Chèze', site: 'Cascade d’Escalère, église romane, lavoir, pigeonnier', niveau: 3, categorie: 'suggéré', lat: 42.95, lng: -0.08 },
  { id: 41, commune: 'Viscos', site: 'Village perché, ruelles pavées, architecture traditionnelle', niveau: 3, categorie: 'suggéré', lat: 42.87, lng: -0.04 },
  { id: 42, commune: 'Aragnouet', site: 'Chapelle des Templiers, Chapelle Notre-Dame-de-l’Assomption-du-Plan', niveau: 3, categorie: 'suggéré', lat: 42.78, lng: 0.13 },
{ id: 43, commune: 'Ourdis-Cotdoussan', site: 'Église Saint-Jacques de Cotdoussan', niveau: 3, categorie: 'suggéré', lat: 43.03, lng: 0.15 },
{ id: 44, commune: 'Ancizan', site: 'Maison du XVIe siècle, église, Musée de la vallée d’Aure', niveau: 2, categorie: 'remarquable', lat: 42.91, lng: 0.32 },
{ id: 45, commune: 'Andrest', site: 'Église Saint-Barthélemy', niveau: 2, categorie: 'remarquable', lat: 43.32, lng: 0.08 },
{ id: 46, commune: 'Bartrès', site: 'Dolmen, Maison Lagües (enfance de Bernadette)', niveau: 3, categorie: 'suggéré', lat: 43.10, lng: -0.02 },
{ id: 47, commune: 'Aureilhan', site: 'Lac d’Aureilhan, Usine blanche, Usine rouge', niveau: 2, categorie: 'remarquable', lat: 43.245, lng: 0.083 },
{ id: 48, commune: 'Lanespède', site: 'Viaduc ferroviaire', niveau: 1, categorie: 'incontournable', lat: 43.19, lng: 0.23 },
{ id: 49, commune: 'Cadéac', site: 'Église gothique du XVIe siècle', niveau: 2, categorie: 'remarquable', lat: 42.85, lng: 0.32 },
{ id: 50, commune: 'Bazus-Aure', site: 'Église romane, clefs de voûte sculptées', niveau: 3, categorie: 'suggéré', lat: 42.89, lng: 0.33 },
{ id: 51, commune: 'Bourisp', site: 'Église romane, peintures murales', niveau: 3, categorie: 'suggéré', lat: 42.82, lng: 0.31 },
{ id: 52, commune: 'Azet', site: 'Maison Pyrénéenne du Pastoralisme', niveau: 3, categorie: 'suggéré', lat: 42.82, lng: 0.44 },
{ id: 53, commune: 'Gargas', site: 'Grottes, grottes fortifiées', niveau: 1, categorie: 'incontournable', lat: 43.07, lng: 0.18 },
{ id: 54, commune: 'Labastide', site: 'Grottes, patrimoine fortifié', niveau: 1, categorie: 'incontournable', lat: 43.06, lng: 0.19 },
{ id: 55, commune: 'Lortet', site: 'Grottes fortifiées', niveau: 1, categorie: 'incontournable', lat: 43.04, lng: 0.20 },
{ id: 56, commune: 'Aste', site: 'Grottes de Médous, église XVIe siècle, vestiges de forteresse', niveau: 1, categorie: 'incontournable', lat: 43.04, lng: 0.17 },
{ id: 57, commune: 'Pouzac', site: 'Église gothique du XVIe siècle', niveau: 1, categorie: 'incontournable', lat: 43.07, lng: 0.17 },
{ id: 58, commune: 'Baudean', site: 'Église gothique du XVIe siècle', niveau: 1, categorie: 'incontournable', lat: 43.05, lng: 0.18 },
{ id: 59, commune: 'Saint-Pé-de-Bigorre', site: 'Grottes de Bétharram, vestiges de l’abbaye', niveau: 1, categorie: 'incontournable', lat: 43.10, lng: -0.15 },
{ id: 60, commune: 'Escaladieu', site: 'Abbaye cistercienne', niveau: 1, categorie: 'incontournable', lat: 43.28, lng: 0.34 },
{ id: 61, commune: 'Montmaurin', site: 'Villa gallo-romaine', niveau: 1, categorie: 'incontournable', lat: 43.06, lng: 0.68 },
{ id: 62, commune: 'Argelès-Gazost', site: 'Parc thermal, centre ancien, église Saint-Saturnin, Lycée climatique, Parc Animalier des Pyrénées', niveau: 1, categorie: 'incontournable', lat: 43.006, lng: -0.098 },
{ id: 63, commune: 'Peyragudes', site: 'Station de ski et domaine nordique', niveau: 3, categorie: 'suggéré', lat: 42.80, lng: 0.42 },
{ id: 64, commune: 'Piau-Engaly', site: 'Station de ski d’altitude', niveau: 3, categorie: 'suggéré', lat: 42.78, lng: 0.16 },
{ id: 65, commune: 'Val-Louron', site: 'Station de ski familiale', niveau: 3, categorie: 'suggéré', lat: 42.82, lng: 0.42 },
{ id: 66, commune: 'Hautacam', site: 'Station de ski et belvédères', niveau: 3, categorie: 'suggéré', lat: 42.97, lng: -0.10 },
{ id: 67, commune: 'Nistos', site: 'Station nordique, plateau pastoral', niveau: 3, categorie: 'suggéré', lat: 42.95, lng: 0.48 },
{ id: 68, commune: 'Payolle', site: 'Domaine nordique, lac de montagne', niveau: 3, categorie: 'suggéré', lat: 42.96, lng: 0.25 },
{ id: 69, commune: 'Barèges', site: 'Station thermale et village de montagne', niveau: 1, categorie: 'incontournable', lat: 42.89, lng: 0.07 },
{ id: 70, commune: 'Barzun', site: 'Village thermal', niveau: 1, categorie: 'incontournable', lat: 43.15, lng: -0.05 },
{ id: 71, commune: 'Capvern-les-Bains', site: 'Station thermale', niveau: 1, categorie: 'incontournable', lat: 43.10, lng: 0.32 },
{ id: 72, commune: 'Estarvielle', site: 'Église peinte du Val de Louron', niveau: 1, categorie: 'incontournable', lat: 42.82, lng: 0.44 },
{ id: 73, commune: 'Cazeaux-Fréchet', site: 'Église peinte du Val de Louron', niveau: 1, categorie: 'incontournable', lat: 42.83, lng: 0.45 },
{ id: 74, commune: 'Bordères-Louron', site: 'Église peinte du Val de Louron', niveau: 1, categorie: 'incontournable', lat: 42.83, lng: 0.43 },
{ id: 75, commune: 'Vieille-Louron', site: 'Église classée', niveau: 1, categorie: 'incontournable', lat: 42.83, lng: 0.44 },
{ id: 76, commune: 'Mont', site: 'Église classée', niveau: 1, categorie: 'incontournable', lat: 42.84, lng: 0.45 },
{ id: 77, commune: 'Arnè', site: 'Tumulus de Chourtigade', niveau: 1, categorie: 'incontournable', lat: 43.05, lng: 0.22 },
{ id: 78, commune: 'Gèdre', site: 'Village de montagne, ski et lien avec Gavarnie', niveau: 1, categorie: 'incontournable', lat: 42.78, lng: -0.02 },
  { id: 79, commune: 'Bagnères-de-Luchon', site: 'Station thermale, allées d’Étigny, téléphérique de Superbagnères, architecture Belle Époque', niveau: 1, categorie: 'incontournable', lat: 42.792, lng: 0.593 },
{ id: 80, commune: 'Bordères-sur-l’Échez', site: 'Village de la couronne tarbaise, église, berges de l’Échez', niveau: 3, categorie: 'suggéré', lat: 43.244, lng: 0.058 },
{ id: 81, commune: 'Séméac', site: 'Ville résidentielle, église Saint-Étienne, espaces verts et canal de l’Alaric', niveau: 3, categorie: 'suggéré', lat: 43.228, lng: 0.104 },
{ id: 82, commune: 'Soues', site: 'Village de plaine, église Saint-Pierre, proximité de l’Adour', niveau: 3, categorie: 'suggéré', lat: 43.206, lng: 0.097 },
{ id: 83, commune: 'Ossun', site: 'Village rural, église Saint-Pierre, patrimoine agricole', niveau: 3, categorie: 'suggéré', lat: 43.185, lng: -0.021 },
{ id: 84, commune: 'Juillan', site: 'Village proche de Tarbes, église Saint-Pierre, environnement rural', niveau: 3, categorie: 'suggéré', lat: 43.201, lng: -0.011 },
{ id: 85, commune: 'Pierrefitte-Nestalas', site: 'Porte des vallées de Gavarnie et Cauterets, église, patrimoine industriel', niveau: 2, categorie: 'remarquable', lat: 42.959, lng: -0.082 },
{ id: 86, commune: 'Sarrancolin', site: 'Village de la vallée de la Neste, marbre de Sarrancolin, église Saint-Ébons', niveau: 2, categorie: 'remarquable', lat: 42.967, lng: 0.372 },
{ id: 87, commune: 'Viella-Aure', site: 'Village de la vallée d’Aure, église Saint-Jean-Baptiste, architecture traditionnelle', niveau: 2, categorie: 'remarquable', lat: 42.816, lng: 0.342 },
{ id: 88, commune: 'La Barthe-de-Neste', site: 'Bourg de la Neste, église Saint-Barthélemy, carrefour de vallées', niveau: 2, categorie: 'remarquable', lat: 43.081, lng: 0.383 },
];

export async function GET() {
  return NextResponse.json(hpSites);
}
