import { NextResponse } from 'next/server';

// Dummy static dataset. Replace with a DB or external source if needed.
const libraries = [
  { name: "Médiathèque José Cabanis", address: "1 allée Jacques Chaban-Delmas, 31500 Toulouse" },
  { name: "Bibliothèque d'Étude et du Patrimoine (BEP)", address: "1 rue de Périgord, 31000 Toulouse" },
  { name: "Bibliothèque Ancely", address: "2 allées du Velay, 31300 Toulouse" },
  { name: "Bibliothèque Pinel", address: "7 place Marius Pinel, 31500 Toulouse" },
  { name: "Bibliothèque Pont des Demoiselles", address: "63 bis avenue Saint-Exupéry, 31000 Toulouse" },
  { name: "Bibliothèque Roseraie", address: "100 avenue Yves Brunaud, 31500 Toulouse" },
  { name: "Médiathèque Côte Pavée", address: "125 avenue Jean Rieux, 31500 Toulouse" },
  { name: "Médiathèque Danièle Damin", address: "122 route d’Albi, 31200 Toulouse" },
  { name: "Médiathèque des Izards", address: "1 place Micoulaud, 31200 Toulouse" },
  { name: "Médiathèque des Minimes", address: "3 place du Marché aux Cochons, 31200 Toulouse" },
  { name: "Médiathèque Empalot", address: "40 avenue Jean-Moulin, 31400 Toulouse" },
  { name: "Médiathèque Fabre", address: "6 rue Saint-Jean, 31000 Toulouse" },
  { name: "Médiathèque Grand M", address: "37 avenue de la Reynerie, 31100 Toulouse" },
  { name: "Médiathèque Pradettes", address: "3 avenue de la Dépêche, 31100 Toulouse" },
  { name: "Médiathèque Rangueil", address: "19 rue Claude-Forbin, 31400 Toulouse" },
  { name: "Médiathèque Saint-Cyprien", address: "63 rue Réclusane, 31300 Toulouse" },
  { name: "Médiathèque Saint-Exupéry", address: "37 rue du Lot, 31100 Toulouse" },
  { name: "Médiathèque Serveyrolles", address: "10 rue Charles Garnier, 31500 Toulouse" },

  { name: "Bib'INSA", address: "135 avenue de Rangueil, 31000 Toulouse cedex 4" },
  { name: "Bibliothèque de l'ENAC", address: "7 avenue Édouard Belin, 31400 Toulouse" },
  { name: "Médiathèque de l'INP-ENSIACET", address: "4 allée Émile Monso, CS 44362, 31000 Toulouse Cedex 4" },
  { name: "Aérothèque Marie Marvingt ISAE SUPAERO", address: "10 avenue Marc Pélegrin, BP 54032, 31055 Toulouse" },
  { name: "Bibliothèque d'études méridionales (BEM)", address: "56 rue du Taur, 31000 Toulouse" },
  { name: "Bibliothèque de l'École Nationale Vétérinaire de Toulouse", address: "23 Chemin des Capelles, BP 87614, 31076 Toulouse Cedex 3" },
  { name: "Bibliothèque de l'IUT de Blagnac", address: "1 place Georges Brassens, BP 60073, 31703 Blagnac" },
  { name: "Bibliothèque de l'INP-AgroToulouse", address: "Avenue de l'Agrobiopole, Auzeville Tolosane, BP 32607, 31326 Castanet-Tolosan Cedex" },
  { name: "Bibliothèque de l'INP-ENSEEIHT", address: "2 rue Charles Camichel, BP 7122, 31071 Toulouse Cedex 7" },
  { name: "Bibliothèque de mathématiques et mécanique", address: "Université Paul Sabatier, IMT - bât. 1R2, 90 allée Huguette Delavault, 118 route de Narbonne, 31062 Toulouse" },
  { name: "Bibliothèque du Laboratoire de Chimie de Coordination (LCC)", address: "Laboratoire de Chimie de Coordination du CNRS, BP 44099, 205 route de Narbonne, 31077 Toulouse cedex 4" },
  { name: "Bibliothèque INP-Météo France", address: "42 avenue Gaspard Coriolis, 31057 Toulouse Cedex 1" },
  { name: "Bibliothèque Sciences Po Toulouse", address: "21 allée de Brienne, CS 88526, 31685 Toulouse cedex 6" },
  { name: "Bibliothèque Universitaire Centrale", address: "5 allées Antonio Machado, Bât 25 - B.P. 40650, 31106 Toulouse" },
  { name: "Bibliothèque Universitaire de l'Arsenal", address: "11 rue des Puits-Creusés, 31000 Toulouse" },
  { name: "Bibliothèque Universitaire de la Manufacture des Tabacs", address: "21 allée de Brienne, Bât. H, BP 81519, 31015 Toulouse Cedex 06" },
  { name: "Bibliothèque Universitaire des Sciences", address: "118 Route de Narbonne, 31400 Toulouse" },
  { name: "Bibliothèque universitaire François de Boutaric", address: "2 rue du Doyen-Gabriel-Marty, Salle AR 106, 31042 Toulouse cedex 9" },
  { name: "Bibliothèque Universitaire Garrigou", address: "2ter rue des Puits-Creusés, 31042 Toulouse Cedex" },
  { name: "Bibliothèque Universitaire Santé (Allées Jules Guesde)", address: "37 Allées Jules Guesde, 31062 Toulouse Cedex 09" },
  { name: "Bibliothèque Universitaire Santé (Rangueil)", address: "65 chemin du Vallon, 31400 Toulouse" },
  { name: "Centre de Documentation de l'INP-École d'Ingénieurs Purpan", address: "75 voie du TOEC, BP 57611, 31076 Toulouse Cedex 3" },
  { name: "Centre de documentation de l'Observatoire Midi-Pyrénées", address: "14 avenue Édouard Belin, 31400 Toulouse" },
  { name: "Centre de ressources de langues (CRL)", address: "BU de l'Arsenal, rez-de-chaussée, 11 rue des Puits-creusés, 31000 Toulouse" },
  { name: "Centre de ressources de psychologie Louise Michel (CRPLM)", address: "5 allées Antonio Machado, Bât. Philippe Malrieu, B.P. 40650, 31106 Toulouse Cedex 1" },
  { name: "Centre de ressources documentaires de l'IUT site Ponsan (CRDoc Ponsan)", address: "133 avenue de Rangueil, Bâtiment C, RDC, 31077 Toulouse" },
  { name: "Centre de ressources documentaires de l'IUT site Rangueil (CRDoc Rangueil)", address: "133A avenue de Rangueil, BP 67701, 31077 Toulouse Cedex 4" },
  { name: "Centre de ressources Lettres Arts Philosophie (CLAP)", address: "Bât. Le Gai Savoir, 5 allées Antonio Machado, BP 40650, 31106 Toulouse Cedex 1" },
  { name: "Centre de Ressources Olympe de Gouges (CROG)", address: "5 allées Antonio Machado, 31058 Toulouse cedex 9" },
  { name: "Centre Documentation Recherche Sciences Humaines et Sociales (CDRSHS-UPS) - Suzanne Briet", address: "CDRSHS - IUT A Toulouse – Ponsan, 115D route de Narbonne, BP 67701, 31077 Toulouse Cedex 4" },
  { name: "Centre régional de documentation en santé publique (CRDSP)", address: "37 Allées Jules Guesde, Bâtiment F, 31000 Toulouse" },
  { name: "Centres de recherches UTC", address: "Université Toulouse 1 Capitole, 11 rue des Puits-Creusés, 31070 Toulouse Cedex 06" },
  { name: "INSPÉ - Toulouse Rangueil", address: "118 Route de Narbonne, 31078 Toulouse cedex 4" },
  { name: "INSPÉ - Toulouse Saint-Agne", address: "56 avenue de l'URSS Cedex 4, 31078 Toulouse" },
  { name: "INSPÉ – Toulouse Croix-de-Pierre", address: "181 avenue de Muret, BP 63215, 31027 Toulouse Cedex 3" },
  { name: "Médiathèque de l'École nationale supérieure d'audiovisuel (ENSAV)", address: "56 rue du Taur, 31000 Toulouse" }
]

export async function GET() {
  return NextResponse.json(libraries);
}
