import { NextResponse } from 'next/server';

// Dataset complet avec types
const establishments = [
// Bibliothèques
  { name: "Médiathèque José Cabanis", address: "1 allée Jacques Chaban-Delmas, 31500 Toulouse" },
  { name: "Bibliothèque d'Étude et du Patrimoine (BEP)", address: "1 rue de Périgord, 31000 Toulouse" },
  { name: "Bibliothèque Ancely", address: "2 allées du Velay, 31300 Toulouse" },
  { name: "Bibliothèque Pinel", address: "7 place Marius Pinel, 31500 Toulouse" },
  { name: "Bibliothèque Pont des Demoiselles", address: "63 bis avenue Saint-Exupéry, 31000 Toulouse" },
  { name: "Bibliothèque Roseraie", address: "100 avenue Yves Brunaud, 31500 Toulouse" },
  { name: "Médiathèque Côte Pavée", address: "125 avenue Jean Rieux, 31500 Toulouse" },
  { name: "Médiathèque Danièle Damin", address: "122 route d’Albi, 31200 Toulouse" },
  { name: "Médiathèque des Izards", address: "1 place Micoulaud, 31200 Toulouse" },
  { name: "Médiathèque des Minimes", address: "3 place du Marché aux Cochons, 31200 Toulouse" },
  { name: "Médiathèque Empalot", address: "40 avenue Jean-Moulin, 31400 Toulouse" },
  { name: "Médiathèque Fabre", address: "6 rue Saint-Jean, 31000 Toulouse" },
  { name: "Médiathèque Grand M", address: "37 avenue de la Reynerie, 31100 Toulouse" },
  { name: "Médiathèque Pradettes", address: "3 avenue de la Dépêche, 31100 Toulouse" },
  { name: "Médiathèque Rangueil", address: "19 rue Claude-Forbin, 31400 Toulouse" },
  { name: "Médiathèque Saint-Cyprien", address: "63 rue Réclusane, 31300 Toulouse" },
  { name: "Médiathèque Saint-Exupéry", address: "37 rue du Lot, 31100 Toulouse" },
  { name: "Médiathèque Serveyrolles", address: "10 rue Charles Garnier, 31500 Toulouse" },

  { name: "Bib'INSA", address: "135 avenue de Rangueil, 31000 Toulouse cedex 4" },
  { name: "Bibliothèque de l'ENAC", address: "7 avenue Édouard Belin, 31400 Toulouse" },
  { name: "Médiathèque de l'INP-ENSIACET", address: "4 allée Émile Monso, CS 44362, 31000 Toulouse Cedex 4" },
  { name: "Aérothèque Marie Marvingt ISAE SUPAERO", address: "10 avenue Marc Pélegrin, BP 54032, 31055 Toulouse" },
  { name: "Bibliothèque d'études méridionales (BEM)", address: "56 rue du Taur, 31000 Toulouse" },
  { name: "Bibliothèque de l'École Nationale Vétérinaire de Toulouse", address: "23 Chemin des Capelles, BP 87614, 31076 Toulouse Cedex 3" },
  { name: "Bibliothèque de l'IUT de Blagnac", address: "1 place Georges Brassens, BP 60073, 31703 Blagnac" },
  { name: "Bibliothèque de l'INP-AgroToulouse", address: "Avenue de l'Agrobiopole, Auzeville Tolosane, BP 32607, 31326 Castanet-Tolosan Cedex" },
  { name: "Bibliothèque de l'INP-ENSEEIHT", address: "2 rue Charles Camichel, BP 7122, 31071 Toulouse Cedex 7" },
  { name: "Bibliothèque de mathématiques et mécanique", address: "Université Paul Sabatier, IMT - bât. 1R2, 90 allée Huguette Delavault, 118 route de Narbonne, 31062 Toulouse" },
  { name: "Bibliothèque du Laboratoire de Chimie de Coordination (LCC)", address: "Laboratoire de Chimie de Coordination du CNRS, BP 44099, 205 route de Narbonne, 31077 Toulouse cedex 4" },
  { name: "Bibliothèque INP-Météo France", address: "42 avenue Gaspard Coriolis, 31057 Toulouse Cedex 1" },
  { name: "Bibliothèque Sciences Po Toulouse", address: "21 allée de Brienne, CS 88526, 31685 Toulouse cedex 6" },
  { name: "Bibliothèque Universitaire Centrale", address: "5 allées Antonio Machado, Bât 25 - B.P. 40650, 31106 Toulouse" },
  { name: "Bibliothèque Universitaire de l'Arsenal", address: "11 rue des Puits-Creusés, 31000 Toulouse" },
  { name: "Bibliothèque Universitaire de la Manufacture des Tabacs", address: "21 allée de Brienne, Bât. H, BP 81519, 31015 Toulouse Cedex 06" },
  { name: "Bibliothèque Universitaire des Sciences", address: "118 Route de Narbonne, 31400 Toulouse" },
  { name: "Bibliothèque universitaire François de Boutaric", address: "2 rue du Doyen-Gabriel-Marty, Salle AR 106, 31042 Toulouse cedex 9" },
  { name: "Bibliothèque Universitaire Garrigou", address: "2ter rue des Puits-Creusés, 31042 Toulouse Cedex" },
  { name: "Bibliothèque Universitaire Santé (Allées Jules Guesde)", address: "37 Allées Jules Guesde, 31062 Toulouse Cedex 09" },
  { name: "Bibliothèque Universitaire Santé (Rangueil)", address: "65 chemin du Vallon, 31400 Toulouse" },
  { name: "Centre de Documentation de l'INP-École d'Ingénieurs Purpan", address: "75 voie du TOEC, BP 57611, 31076 Toulouse Cedex 3" },
  { name: "Centre de documentation de l'Observatoire Midi-Pyrénées", address: "14 avenue Édouard Belin, 31400 Toulouse" },
  { name: "Centre de ressources de langues (CRL)", address: "BU de l'Arsenal, rez-de-chaussée, 11 rue des Puits-creusés, 31000 Toulouse" },
  { name: "Centre de ressources de psychologie Louise Michel (CRPLM)", address: "5 allées Antonio Machado, Bât. Philippe Malrieu, B.P. 40650, 31106 Toulouse Cedex 1" },
  { name: "Centre de ressources documentaires de l'IUT site Ponsan (CRDoc Ponsan)", address: "133 avenue de Rangueil, Bâtiment C, RDC, 31077 Toulouse" },
  { name: "Centre de ressources documentaires de l'IUT site Rangueil (CRDoc Rangueil)", address: "133A avenue de Rangueil, BP 67701, 31077 Toulouse Cedex 4" },
  { name: "Centre de ressources Lettres Arts Philosophie (CLAP)", address: "Bât. Le Gai Savoir, 5 allées Antonio Machado, BP 40650, 31106 Toulouse Cedex 1" },
  { name: "Centre de Ressources Olympe de Gouges (CROG)", address: "5 allées Antonio Machado, 31058 Toulouse cedex 9" },
  { name: "Centre Documentation Recherche Sciences Humaines et Sociales (CDRSHS-UPS) - Suzanne Briet", address: "CDRSHS - IUT A Toulouse – Ponsan, 115D route de Narbonne, BP 67701, 31077 Toulouse Cedex 4" },
  { name: "Centre régional de documentation en santé publique (CRDSP)", address: "37 Allées Jules Guesde, Bâtiment F, 31000 Toulouse" },
  { name: "Centres de recherches UTC", address: "Université Toulouse 1 Capitole, 11 rue des Puits-Creusés, 31070 Toulouse Cedex 06" },
  { name: "INSPÉ - Toulouse Rangueil", address: "118 Route de Narbonne, 31078 Toulouse cedex 4" },
  { name: "INSPÉ - Toulouse Saint-Agne", address: "56 avenue de l'URSS Cedex 4, 31078 Toulouse" },
  { name: "INSPÉ – Toulouse Croix-de-Pierre", address: "181 avenue de Muret, BP 63215, 31027 Toulouse Cedex 3" },
  { name: "Médiathèque de l'École nationale supérieure d'audiovisuel (ENSAV)", address: "56 rue du Taur, 31000 Toulouse" },

// Centres Culturels
{ name: "Alban-Minville", address: "1 Place Martin Luther King, 31100 Toulouse", type: "centre_culturel" },
{ name: "Bellegarde", address: "17 rue Bellegarde, 31000 Toulouse", type: "centre_culturel" },
{ name: "Bonnefoy", address: "4 rue du Faubourg Bonnefoy, 31500 Toulouse", type: "centre_culturel" },
{ name: "Bordeblanche", address: "5 rue Yves-Rouquette, 31100 Toulouse", type: "centre_culturel" },
{ name: "La Brique Rouge", address: "9 Rue Maria Mombiola, 31400 Toulouse", type: "centre_culturel" },
{ name: "Espace JOB", address: "105 Route de Blagnac, 31200 Toulouse", type: "centre_culturel" },
{ name: "Henri-Desbals", address: "128 rue Henri Desbals, 31100 Toulouse", type: "centre_culturel" },
{ name: "Renan", address: "5 chemin d'Audibert, 31200 Toulouse", type: "centre_culturel" },
{ name: "Reynerie", address: "Au sein de la Maison Toulouse Services Reynerie - 1 place Conchita Grangé Ramos (1er étage), 31100 Toulouse", type: "centre_culturel" },
{ name: "Saint-Cyprien", address: "56 allées Charles de Fitte, 31300 Toulouse", type: "centre_culturel" },
{ name: "Saint-Simon", address: "10 Chemin de Liffard, 31100 Toulouse", type: "centre_culturel" },
{ name: "Soupetard", address: "63 chemin de Hérédia, 31500 Toulouse", type: "centre_culturel" },
{ name: "Théâtre des Mazades", address: "10 Avenue des Mazades, 31200 Toulouse", type: "centre_culturel" },
{ name: "Cercle laïque Jean Chaubet", address: "7 Place Marius Pinel, 31500 Toulouse", type: "centre_culturel" },

// Maisons de quartier
{ name: "Maison de quartier Rangueil", address: "19 Rue Claude de Forbin", type: "maison_quartier" },
{ name: "Maison De Quartier De Pouvourville", address: "4 Imp. de Sarrangines", type: "maison_quartier" },
{ name: "Maison de Quartier de Croix Daurade", address: "7 Rue Francis Lopez", type: "maison_quartier" },
{ name: "Maison de Quartier de l'Hers", address: "56 Chem. du Château de l'Hers", type: "maison_quartier" },
{ name: "Maison de quartier des Ponts-Jumeaux", address: "7 Bis Rue Cécile Brunschvicg", type: "maison_quartier" },
{ name: "Maison de quartier de Bagatelle", address: "13 Imp. du Bachaga Boualam rue du", type: "maison_quartier" },
{ name: "Maison de Quartier Lafourguette", address: "1 Pl. des Glières", type: "maison_quartier" },
{ name: "Mairie Quartier Sauzelong de Toulouse", address: "80 Av. Albert Bedouce", type: "maison_quartier" },
{ name: "Maison de la Citoyenneté Sud-Est", address: "81 Rue Saint-Roch", type: "maison_quartier" },
{ name: "Maison de quartier La Vache", address: "7 Rue Marguerite Duras", type: "maison_quartier" },

// MJC
{ name: "Maison des Jeunes et de la Culture Jacques Prévert", address: "292 Route de Seysses, 31100 Toulouse", type: "mjc" },
{ name: "Maison des Jeunes et de la Culture Pont des Demoiselles", address: "63 avenue de Saint-Exupéry, 31400 Toulouse", type: "mjc" },
{ name: "Maison des Jeunes et de la Culture Croix-Daurade", address: "141 Chemin de Nicol, 31200 Toulouse", type: "mjc" },
{ name: "Maison des Jeunes et de la Culture Ponts-Jumeaux", address: "2 Port de l'Embouchure, 31000 Toulouse", type: "mjc" },
{ name: "Maison des Jeunes et de la Culture Ancely", address: "7 Allée des Causses, 31300 Toulouse", type: "mjc" },
{ name: "Maison des Jeunes et de la Culture Empalot", address: "9 rue Maria Mombiola, 31400 Toulouse", type: "mjc" },

// Conservatoires
{ name: "Conservatoire à Rayonnement Régional (CRR) – Site Larrey", address: "17 rue Larrey, 31000 Toulouse", type: "conservatoire" },
{ name: "Auditorium Saint-Pierre des Cuisines", address: "12 place Saint-Pierre, 31000 Toulouse", type: "conservatoire" },
{ name: "L'Imprimerie", address: "14, rue Ernest Renan, 31200 Toulouse", type: "conservatoire" },
{ name: "Antenne Pont des Demoiselles", address: "30, avenue Saint-Exupéry, 31400 Toulouse", type: "conservatoire" },
{ name: "Antenne Barrière de Paris – ZAC La Vache", address: "4, rue Marguerite Duras, 31200 Toulouse", type: "conservatoire" },
{ name: "Antenne Côte-Pavée – Courrège", address: "254, avenue Jean Rieux, 31500 Toulouse", type: "conservatoire" },
{ name: "Antenne Lafourguette", address: "6, place des Glières, 31100 Toulouse", type: "conservatoire" },
{ name: "Antenne Rangueil – Jules Julien", address: "9, avenue des écoles Jules-Julien, 31400 Toulouse", type: "conservatoire" }
// Ajoute ici toutes les autres entrées de ton dataset existant
];

export async function GET() {
return NextResponse.json(establishments);
}
