import { NextResponse } from 'next/server';

export type ClocherMurSite = {
  id: number;
  commune: string;
  dept: string; 
  description: string;
  secteur: string;
  distanceKm: number;
  lat: number;
  lng: number;
};

const clochersData: ClocherMurSite[] = [
  { id: 1, commune: "Aignes", dept: "Haute-Garonne", description: "Église Saint-Baudile", secteur: "Lauragais", distanceKm: 42, lat: 43.3211, lng: 1.5872 },
  { id: 2, commune: "Aigrefeuille", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 18, lat: 43.5689, lng: 1.5905 },
  { id: 3, commune: "Alan", dept: "Haute-Garonne", description: "Église Notre-Dame-de-la-Nativité", secteur: "Comminges", distanceKm: 75, lat: 43.2289, lng: 0.9394 },
  { id: 4, commune: "Albiac", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 32, lat: 43.5511, lng: 1.7792 },
  { id: 5, commune: "Ambax", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Savès", distanceKm: 60, lat: 43.3719, lng: 0.7958 },
  { id: 6, commune: "Anan", dept: "Haute-Garonne", description: "Église Saint-Clément", secteur: "Savès", distanceKm: 68, lat: 43.3522, lng: 0.8144 },
  { id: 7, commune: "Arbon", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Comminges", distanceKm: 110, lat: 43.0011, lng: 0.7478 },
  { id: 8, commune: "Arguenos", dept: "Haute-Garonne", description: "Église Saint-Laurent", secteur: "Comminges", distanceKm: 115, lat: 42.9969, lng: 0.7247 },
  { id: 9, commune: "Argut-Dessus", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Pyrénées", distanceKm: 135, lat: 42.8878, lng: 0.7042 },
  { id: 10, commune: "Artigue", dept: "Haute-Garonne", description: "Église Saint-Exupère", secteur: "Pyrénées", distanceKm: 145, lat: 42.8314, lng: 0.7411 },
  { id: 11, commune: "Aspret-Sarrat", dept: "Haute-Garonne", description: "Église Saint-Nazaire", secteur: "Comminges", distanceKm: 95, lat: 43.0647, lng: 0.7042 },
  { id: 12, commune: "Aureville", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Sud Toulousain", distanceKm: 18, lat: 43.4683, lng: 1.4558 },
  { id: 13, commune: "Auribail", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Vallée de la Lèze", distanceKm: 35, lat: 43.3408, lng: 1.3831 },
  { id: 14, commune: "Aurin", dept: "Haute-Garonne", description: "Église Saint-Apollinaire", secteur: "Lauragais", distanceKm: 22, lat: 43.5358, lng: 1.6311 },
  { id: 15, commune: "Auterive", dept: "Haute-Garonne", description: "Église Saint-Paul (clocher-mur monumental)", secteur: "Vallée de l'Ariège", distanceKm: 30, lat: 43.3517, lng: 1.4786 },
  { id: 16, commune: "Auzeville-Tolosane", dept: "Haute-Garonne", description: "Église Saint-Séverin", secteur: "Sud-Est Toulousain", distanceKm: 10, lat: 43.5264, lng: 1.4828 },
  { id: 17, commune: "Ayguevives", dept: "Haute-Garonne", description: "Église Saint-Saturnin", secteur: "Lauragais", distanceKm: 22, lat: 43.4386, lng: 1.5961 },
  { id: 18, commune: "Azas", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Nord-Est Toulousain", distanceKm: 28, lat: 43.7242, lng: 1.6742 },
  { id: 19, commune: "Bagnères-de-Luchon", dept: "Haute-Garonne", description: "Église Notre-Dame-de-l'Assomption", secteur: "Pyrénées", distanceKm: 140, lat: 42.7912, lng: 0.5917 },
  { id: 20, commune: "Balma", dept: "Haute-Garonne", description: "Église Saint-Joseph", secteur: "Toulouse Métropole", distanceKm: 5, lat: 43.6100, lng: 1.5000 },
  { id: 21, commune: "Baraignes", dept: "Aude", description: "Église Sainte-Marie (clocher-mur à 3 baies)", secteur: "Lauragais", distanceKm: 50, lat: 43.3289, lng: 1.8242 },
  { id: 22, commune: "Baren", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Pyrénées", distanceKm: 130, lat: 42.8717, lng: 0.6125 },
  { id: 23, commune: "Baziège", dept: "Haute-Garonne", description: "Église Saint-Étienne (clocher-mur monumental)", secteur: "Lauragais", distanceKm: 22, lat: 43.4542, lng: 1.6142 },
  { id: 24, commune: "Bazus", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Nord Toulousain", distanceKm: 20, lat: 43.7344, lng: 1.5169 },
  { id: 25, commune: "Beaufort", dept: "Haute-Garonne", description: "Église Sainte-Anne", secteur: "Sud-Ouest", distanceKm: 35, lat: 43.4589, lng: 1.1114 },
  { id: 26, commune: "Beaumont-sur-Lèze", dept: "Haute-Garonne", description: "Église Saint-Maurice", secteur: "Vallée de la Lèze", distanceKm: 25, lat: 43.3800, lng: 1.3500 },
  { id: 27, commune: "Beauteville", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Lauragais", distanceKm: 45, lat: 43.3456, lng: 1.7342 },
  { id: 28, commune: "Beauville", dept: "Haute-Garonne", description: "Église Sainte-Catherine", secteur: "Lauragais", distanceKm: 30, lat: 43.4758, lng: 1.7753 },
  { id: 29, commune: "Beauzelle", dept: "Haute-Garonne", description: "Église Saint-Julien", secteur: "Toulouse Métropole", distanceKm: 12, lat: 43.6653, lng: 1.3325 },
  { id: 30, commune: "Belbèze-de-Lauragais", dept: "Haute-Garonne", description: "Église Saint-André", secteur: "Lauragais", distanceKm: 18, lat: 43.4414, lng: 1.5547 },
  { id: 31, commune: "Bélesta-en-Lauragais", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 40, lat: 43.4172, lng: 1.8469 },
  { id: 32, commune: "Bellegarde-Sainte-Marie", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Ouest Toulousain", distanceKm: 40, lat: 43.6750, lng: 1.1147 },
  { id: 33, commune: "Bellesserre", dept: "Haute-Garonne", description: "Église Sainte-Marie", secteur: "Nord-Ouest", distanceKm: 45, lat: 43.7500, lng: 1.0500 },
  { id: 34, commune: "Belpech", dept: "Aude", description: "Église Saint-Saturnin (clocher-mur exceptionnel)", secteur: "Lauragais", distanceKm: 60, lat: 43.1983, lng: 1.7511 },
  { id: 35, commune: "Benque-Dessous-et-Dessus", dept: "Haute-Garonne", description: "Église Saint-Geniès", secteur: "Pyrénées", distanceKm: 145, lat: 42.8156, lng: 0.5539 },
  { id: 36, commune: "Billières", dept: "Haute-Garonne", description: "Église Saint-Loup", secteur: "Pyrénées", distanceKm: 148, lat: 42.8122, lng: 0.5286 },
  { id: 37, commune: "Binos", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Pyrénées", distanceKm: 135, lat: 42.8800, lng: 0.6300 },
  { id: 38, commune: "Boissède", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Savès", distanceKm: 65, lat: 43.3414, lng: 0.7969 },
  { id: 39, commune: "Bonrepos-sur-Aussonnelle", dept: "Haute-Garonne", description: "Église Saint-Roch", secteur: "Ouest Toulousain", distanceKm: 25, lat: 43.5408, lng: 1.1486 },
  { id: 40, commune: "Bordes-de-Rivière", dept: "Haute-Garonne", description: "Église Saint-Saturnin", secteur: "Comminges", distanceKm: 100, lat: 43.1381, lng: 0.6306 },
  { id: 41, commune: "Bouloc", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Nord Toulousain", distanceKm: 25, lat: 43.7803, lng: 1.4042 },
  { id: 42, commune: "Bourg-d'Oueil", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Pyrénées", distanceKm: 155, lat: 42.8586, lng: 0.4994 },
  { id: 43, commune: "Bragayrac", dept: "Haute-Garonne", description: "Église Saint-Quitterie", secteur: "Savès", distanceKm: 45, lat: 43.4797, lng: 1.0717 },
  { id: 44, commune: "Bretx", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Nord-Ouest", distanceKm: 25, lat: 43.7042, lng: 1.1961 },
  { id: 45, commune: "Bruguières", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Nord Toulousain", distanceKm: 15, lat: 43.7269, lng: 1.4119 },
  { id: 46, commune: "Burgalays", dept: "Haute-Garonne", description: "Église Saint-André", secteur: "Pyrénées", distanceKm: 135, lat: 42.8906, lng: 0.6289 },
  { id: 47, commune: "Cabanac-Cazaux", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Comminges", distanceKm: 95, lat: 43.0336, lng: 0.7389 },
  { id: 48, commune: "Cadenac", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Lauragais", distanceKm: 38, lat: 43.4947, lng: 1.8336 },
  { id: 49, commune: "Caignac", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Lauragais", distanceKm: 48, lat: 43.3106, lng: 1.7139 },
  { id: 50, commune: "Calmont", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Lauragais", distanceKm: 40, lat: 43.2875, lng: 1.6344 },
  { id: 51, commune: "Canens", dept: "Haute-Garonne", description: "Église Saint-Eutrope", secteur: "Volvestre", distanceKm: 55, lat: 43.2047, lng: 1.3789 },
  { id: 52, commune: "Capens", dept: "Haute-Garonne", description: "Église Saint-Benoît", secteur: "Sud Toulousain", distanceKm: 38, lat: 43.3381, lng: 1.2508 },
  { id: 53, commune: "Castagnède", dept: "Haute-Garonne", description: "Église Saint-Sébastien", secteur: "Comminges", distanceKm: 90, lat: 43.0306, lng: 0.9858 },
  { id: 54, commune: "Castelbiague", dept: "Haute-Garonne", description: "Église Sainte-Anne", secteur: "Comminges", distanceKm: 85, lat: 43.0353, lng: 0.9256 },
  { id: 55, commune: "Castelginest", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Toulouse Métropole", distanceKm: 12, lat: 43.6936, lng: 1.4328 },
  { id: 56, commune: "Castelmaurou", dept: "Haute-Garonne", description: "Église Sainte-Foy", secteur: "Nord-Est", distanceKm: 15, lat: 43.6767, lng: 1.5317 },
  { id: 57, commune: "Castelnau-Picampeau", dept: "Haute-Garonne", description: "Église Saint-Michel", secteur: "Savès", distanceKm: 62, lat: 43.3056, lng: 1.0311 },
  { id: 58, commune: "Casties-Labrande", dept: "Haute-Garonne", description: "Église Saint-Côme", secteur: "Savès", distanceKm: 65, lat: 43.3283, lng: 1.1111 },
  { id: 59, commune: "Caubous", dept: "Haute-Garonne", description: "Église Saint-Félix", secteur: "Pyrénées", distanceKm: 158, lat: 42.8469, lng: 0.5117 },
  { id: 60, commune: "Caujac", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Vallée de la Lèze", distanceKm: 42, lat: 43.3058, lng: 1.4722 },
  { id: 61, commune: "Cazalrenoux", dept: "Aude", description: "Église de l'Immaculée Conception", secteur: "Lauragais", distanceKm: 55, lat: 43.1989, lng: 1.9489 },
  { id: 62, commune: "Cazaux-Layrisse", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Pyrénées", distanceKm: 132, lat: 42.8711, lng: 0.6083 },
  { id: 63, commune: "Cépet", dept: "Haute-Garonne", description: "Église Sainte-Foy", secteur: "Nord Toulousain", distanceKm: 22, lat: 43.7508, lng: 1.4308 },
  { id: 64, commune: "Chein-Dessus", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Comminges", distanceKm: 105, lat: 43.0108, lng: 0.8572 },
  { id: 65, commune: "Cier-de-Luchon", dept: "Haute-Garonne", description: "Église Saint-Guy", secteur: "Pyrénées", distanceKm: 135, lat: 42.8578, lng: 0.6006 },
  { id: 66, commune: "Cierp-Gaud", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Pyrénées", distanceKm: 125, lat: 42.9150, lng: 0.6386 },
  { id: 67, commune: "Cintegabelle", dept: "Haute-Garonne", description: "Église Notre-Dame (clocher-mur monumental en brique)", secteur: "Vallée de l'Ariège", distanceKm: 38, lat: 43.3133, lng: 1.5311 },
  { id: 68, commune: "Clermont-le-Fort", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Sud Toulousain", distanceKm: 18, lat: 43.4583, lng: 1.4331 },
  { id: 69, commune: "Cornebarrieu", dept: "Haute-Garonne", description: "Église Saint-Clément", secteur: "Toulouse Métropole", distanceKm: 15, lat: 43.6500, lng: 1.3256 },
  { id: 70, commune: "Couladère", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Volvestre", distanceKm: 68, lat: 43.1764, lng: 1.1467 },
  { id: 71, commune: "Couret", dept: "Haute-Garonne", description: "Église Saint-Sébastien", secteur: "Comminges", distanceKm: 98, lat: 43.0286, lng: 0.8247 },
  { id: 72, commune: "Deyme", dept: "Haute-Garonne", description: "Église Sainte-Madeleine", secteur: "Lauragais", distanceKm: 15, lat: 43.4794, lng: 1.5261 },
  { id: 73, commune: "Dito", dept: "Haute-Garonne", description: "Chapelle de Dito", secteur: "Pyrénées", distanceKm: 138, lat: 42.8683, lng: 0.6133 },
  { id: 74, commune: "Donneville", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 18, lat: 43.4719, lng: 1.5494 },
  { id: 75, commune: "Drémil-Lafage", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Est Toulousain", distanceKm: 15, lat: 43.5969, lng: 1.6033 },
  { id: 76, commune: "Empeaux", dept: "Haute-Garonne", description: "Église Saint-Sabin", secteur: "Savès", distanceKm: 45, lat: 43.5233, lng: 1.0544 },
  { id: 77, commune: "Esperce", dept: "Haute-Garonne", description: "Église Saint-Hilaire", secteur: "Volvestre", distanceKm: 48, lat: 43.2981, lng: 1.4008 },
  { id: 78, commune: "Espagnac", dept: "Haute-Garonne", description: "Église Saint-Augustin", secteur: "Savès", distanceKm: 55, lat: 43.3764, lng: 0.7719 },
  { id: 79, commune: "Estenos", dept: "Haute-Garonne", description: "Église de la Nativité-de-la-Sainte-Vierge", secteur: "Pyrénées", distanceKm: 120, lat: 42.9469, lng: 0.6381 },
  { id: 80, commune: "Fabas", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Savès", distanceKm: 65, lat: 43.2847, lng: 0.8844 },
  { id: 81, commune: "Falga", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Lauragais", distanceKm: 50, lat: 43.4794, lng: 1.8622 },
  { id: 82, commune: "Flourens", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Est Toulousain", distanceKm: 10, lat: 43.5950, lng: 1.5625 },
  { id: 83, commune: "Folcarde", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 45, lat: 43.3711, lng: 1.7619 },
  { id: 84, commune: "Fontenilles", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Ouest Toulousain", distanceKm: 25, lat: 43.5531, lng: 1.1911 },
  { id: 85, commune: "Francarville", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 35, lat: 43.5858, lng: 1.7533 },
  { id: 86, commune: "Frontignan-Savès", dept: "Haute-Garonne", description: "Église Saint-Jacques", secteur: "Savès", distanceKm: 58, lat: 43.3961, lng: 0.9231 },
  { id: 87, commune: "Frouzins", dept: "Haute-Garonne", description: "Église Saint-Germier (clocher-mur typique)", secteur: "Sud-Ouest Toulousain", distanceKm: 15, lat: 43.5156, lng: 1.3250 },
  { id: 88, commune: "Fustignac", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Savès", distanceKm: 60, lat: 43.3086, lng: 1.0747 },
  { id: 89, commune: "Gagnac-sur-Garonne", dept: "Haute-Garonne", description: "Église Saint-Germier", secteur: "Nord Toulousain", distanceKm: 15, lat: 43.7078, lng: 1.3619 },
  { id: 90, commune: "Gaillac-Toulza", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Lauragais", distanceKm: 55, lat: 43.2553, lng: 1.4719 },
  { id: 91, commune: "Ganties", dept: "Haute-Garonne", description: "Église Saint-Eutrope", secteur: "Comminges", distanceKm: 95, lat: 43.0658, lng: 0.8353 },
  { id: 92, commune: "Garidech", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste (clocher-mur du XVe)", secteur: "Nord-Est Toulousain", distanceKm: 18, lat: 43.7094, lng: 1.5614 },
  { id: 93, commune: "Garin", dept: "Haute-Garonne", description: "Église Saint-Pé-de-la-Moraine", secteur: "Pyrénées", distanceKm: 150, lat: 42.8117, lng: 0.5161 },
  { id: 94, commune: "Gémil", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Nord-Est Toulousain", distanceKm: 20, lat: 43.7347, lng: 1.5900 },
  { id: 95, commune: "Gensac-sur-Garonne", dept: "Haute-Garonne", description: "Église Sainte-Radegonde", secteur: "Volvestre", distanceKm: 60, lat: 43.2189, lng: 1.1278 },
  { id: 96, commune: "Gibel", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 48, lat: 43.2936, lng: 1.6753 },
  { id: 97, commune: "Goudex", dept: "Haute-Garonne", description: "Église Saint-Loup", secteur: "Savès", distanceKm: 75, lat: 43.2464, lng: 0.7483 },
  { id: 98, commune: "Goutevernisse", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Volvestre", distanceKm: 62, lat: 43.2206, lng: 1.1719 },
  { id: 99, commune: "Gouzens", dept: "Haute-Garonne", description: "Église Saint-Félix", secteur: "Volvestre", distanceKm: 65, lat: 43.1611, lng: 1.1856 },
  { id: 100, commune: "Goyrans", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Sud Toulousain", distanceKm: 15, lat: 43.4831, lng: 1.4336 },
  { id: 101, commune: "Graissens", dept: "Haute-Garonne", description: "Église Saint-Eugène", secteur: "Lauragais", distanceKm: 42, lat: 43.4792, lng: 1.8000 },
  { id: 102, commune: "Gratens", dept: "Haute-Garonne", description: "Église Saint-Michel", secteur: "Volvestre", distanceKm: 50, lat: 43.3225, lng: 1.1114 },
  { id: 103, commune: "Gratentour", dept: "Haute-Garonne", description: "Église Sainte-Quitterie", secteur: "Nord Toulousain", distanceKm: 15, lat: 43.7225, lng: 1.4333 },
  { id: 104, commune: "Grazac", dept: "Haute-Garonne", description: "Église Saint-Martial", secteur: "Lauragais", distanceKm: 40, lat: 43.3253, lng: 1.7000 },
  { id: 105, commune: "His", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Comminges", distanceKm: 90, lat: 43.0564, lng: 0.9719 },
  { id: 106, commune: "Lorette", dept: "Haute-Garonne", description: "Hospice Notre-Dame-de-Lorette", secteur: "Volvestre", distanceKm: 70, lat: 43.1761, lng: 1.1853 },
  { id: 107, commune: "Issus", dept: "Haute-Garonne", description: "Église Saint-Genest", secteur: "Lauragais", distanceKm: 25, lat: 43.4217, lng: 1.5075 },
  { id: 108, commune: "Juzes", dept: "Haute-Garonne", description: "Église Saint-Léon", secteur: "Lauragais", distanceKm: 45, lat: 43.4686, lng: 1.7850 },
  { id: 109, commune: "La Magdelaine-sur-Tarn", dept: "Haute-Garonne", description: "Église Sainte-Madeleine", secteur: "Nord Toulousain", distanceKm: 32, lat: 43.8119, lng: 1.5414 },
  { id: 110, commune: "La Salvetat-Saint-Gilles", dept: "Haute-Garonne", description: "Église Saint-Gilles", secteur: "Ouest Toulousain", distanceKm: 18, lat: 43.5775, lng: 1.2725 },
  { id: 111, commune: "Labège", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Sud-Est Toulousain", distanceKm: 12, lat: 43.5286, lng: 1.5303 },
  { id: 112, commune: "Labarthe-Inard", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Comminges", distanceKm: 90, lat: 43.1064, lng: 0.8356 },
  { id: 113, commune: "Labastide-Saint-Sernin", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Nord Toulousain", distanceKm: 18, lat: 43.7392, lng: 1.4697 },
  { id: 114, commune: "Lagarde", dept: "Haute-Garonne", description: "Église Saint-Remi", secteur: "Lauragais", distanceKm: 42, lat: 43.3417, lng: 1.7164 },
  { id: 115, commune: "Lagardelle-sur-Lèze", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Vallée de la Lèze", distanceKm: 25, lat: 43.4117, lng: 1.3908 },
  { id: 116, commune: "Lagraulet-Saint-Nicolas", dept: "Haute-Garonne", description: "Église Saint-Nicolas", secteur: "Nord-Ouest", distanceKm: 38, lat: 43.7917, lng: 1.0778 },
  { id: 117, commune: "Lalouret-Laffiteau", dept: "Haute-Garonne", description: "Église Saint-Loup", secteur: "Comminges", distanceKm: 95, lat: 43.1842, lng: 0.7247 },
  { id: 118, commune: "Landorthe", dept: "Haute-Garonne", description: "Église Saint-Gaudens", secteur: "Comminges", distanceKm: 88, lat: 43.1333, lng: 0.7842 },
  { id: 119, commune: "Lanta", dept: "Haute-Garonne", description: "Église Notre-Dame (clocher-mur à 5 baies)", secteur: "Lauragais", distanceKm: 22, lat: 43.5597, lng: 1.6556 },
  { id: 120, commune: "Lapeyrouse-Fossat", dept: "Haute-Garonne", description: "Église de l'Assomption", secteur: "Nord-Est", distanceKm: 15, lat: 43.6931, lng: 1.5133 },
  { id: 121, commune: "Latour", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Volvestre", distanceKm: 65, lat: 43.2017, lng: 1.2825 },
  { id: 122, commune: "Latrape", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Volvestre", distanceKm: 55, lat: 43.2425, lng: 1.2881 },
  { id: 123, commune: "Lauzerville", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Lauragais", distanceKm: 15, lat: 43.5464, lng: 1.5647 },
  { id: 124, commune: "Layrac-sur-Tarn", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Nord Toulousain", distanceKm: 35, lat: 43.8347, lng: 1.5547 },
  { id: 125, commune: "Le Born", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Nord Toulousain", distanceKm: 38, lat: 43.8842, lng: 1.5061 },
  { id: 126, commune: "Le Burgaud", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Nord-Ouest", distanceKm: 42, lat: 43.7950, lng: 1.1194 },
  { id: 127, commune: "Le Cabanial", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 40, lat: 43.5286, lng: 1.8197 },
  { id: 128, commune: "Le Fauga", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Sud Toulousain", distanceKm: 32, lat: 43.3956, lng: 1.2950 },
  { id: 129, commune: "Le Fousseret", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Savès", distanceKm: 60, lat: 43.2817, lng: 1.0653 },
  { id: 130, commune: "Le Pin-Murelet", dept: "Haute-Garonne", description: "Église Saint-Sébastien", secteur: "Savès", distanceKm: 55, lat: 43.4014, lng: 1.0506 },
  { id: 131, commune: "Le Plan", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Volvestre", distanceKm: 70, lat: 43.1664, lng: 1.1211 },
  { id: 132, commune: "Le Puy-de-Touges", dept: "Haute-Garonne", description: "Église Saint-Loup", secteur: "Savès", distanceKm: 58, lat: 43.3400, lng: 1.0333 },
  { id: 133, commune: "Léguevin", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Ouest Toulousain", distanceKm: 20, lat: 43.5986, lng: 1.2325 },
  { id: 134, commune: "Lespinasse", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Nord Toulousain", distanceKm: 15, lat: 43.7083, lng: 1.3853 },
  { id: 135, commune: "Lespiteau", dept: "Haute-Garonne", description: "Église Saint-Michel", secteur: "Comminges", distanceKm: 98, lat: 43.0450, lng: 0.7789 },
  { id: 136, commune: "Lestelle-de-Saint-Martory", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Comminges", distanceKm: 85, lat: 43.1206, lng: 0.9133 },
  { id: 137, commune: "Lodes", dept: "Haute-Garonne", description: "Église Saint-Cizi", secteur: "Comminges", distanceKm: 105, lat: 43.1706, lng: 0.6961 },
  { id: 138, commune: "Lussan-Adeilhac", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Savès", distanceKm: 68, lat: 43.2981, lng: 0.9414 },
  { id: 139, commune: "Mailholas", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Volvestre", distanceKm: 55, lat: 43.2189, lng: 1.3111 },
  { id: 140, commune: "Mancioux", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Comminges", distanceKm: 75, lat: 43.1614, lng: 0.9525 },
  { id: 141, commune: "Maravals", dept: "Haute-Garonne", description: "Église de Maravals", secteur: "Savès", distanceKm: 50, lat: 43.3986, lng: 1.1347 },
  { id: 142, commune: "Marignac-Lasclares", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Volvestre", distanceKm: 62, lat: 43.2847, lng: 1.0911 },
  { id: 143, commune: "Marliac", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Vallée de la Lèze", distanceKm: 48, lat: 43.2325, lng: 1.4119 },
  { id: 144, commune: "Marquein", dept: "Aude", description: "Église Saint-Martin", secteur: "Lauragais", distanceKm: 52, lat: 43.3019, lng: 1.7289 },
  { id: 145, commune: "Mascarville", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Lauragais", distanceKm: 42, lat: 43.5517, lng: 1.7583 },
  { id: 146, commune: "Mauvezin", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Comminges", distanceKm: 92, lat: 43.1311, lng: 0.9103 },
  { id: 147, commune: "Mauzac", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Sud Toulousain", distanceKm: 30, lat: 43.3761, lng: 1.2911 },
  { id: 148, commune: "Mayreville", dept: "Aude", description: "Église Saint-Julien", secteur: "Lauragais", distanceKm: 58, lat: 43.2386, lng: 1.8389 },
  { id: 149, commune: "Mervilla", dept: "Haute-Garonne", description: "Église Saint-Nazaire", secteur: "Sud Toulousain", distanceKm: 12, lat: 43.5133, lng: 1.4878 },
  { id: 150, commune: "Merville", dept: "Haute-Garonne", description: "Église Saint-Saturnin", secteur: "Nord-Ouest", distanceKm: 22, lat: 43.7214, lng: 1.2989 },
  { id: 151, commune: "Molandier", dept: "Aude", description: "Église de l'Assomption", secteur: "Lauragais", distanceKm: 55, lat: 43.2458, lng: 1.7169 },
  { id: 152, commune: "Moncaup", dept: "Haute-Garonne", description: "Église de la Nativité-de-la-Sainte-Vierge", secteur: "Comminges", distanceKm: 105, lat: 42.9772, lng: 0.7061 },
  { id: 153, commune: "Mondavezan", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Comminges", distanceKm: 72, lat: 43.2389, lng: 1.0594 },
  { id: 154, commune: "Mondilhan", dept: "Haute-Garonne", description: "Église Saint-Laurent", secteur: "Savès", distanceKm: 90, lat: 43.3289, lng: 0.7683 },
  { id: 155, commune: "Mondouzil", dept: "Haute-Garonne", description: "Église Saint-Martial", secteur: "Est Toulousain", distanceKm: 12, lat: 43.6289, lng: 1.5583 },
  { id: 156, commune: "Monès", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Savès", distanceKm: 60, lat: 43.4319, lng: 1.0369 },
  { id: 157, commune: "Montastruc-la-Conseillère", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Nord-Est Toulousain", distanceKm: 22, lat: 43.7183, lng: 1.5908 },
  { id: 158, commune: "Montastruc-Savès", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Savès", distanceKm: 58, lat: 43.3556, lng: 0.9858 },
  { id: 159, commune: "Montauriol", dept: "Aude", description: "Église Saint-André", secteur: "Lauragais", distanceKm: 54, lat: 43.2750, lng: 1.8383 },
  { id: 160, commune: "Montbernard", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Savès", distanceKm: 85, lat: 43.2344, lng: 0.8119 },
  { id: 161, commune: "Montbrun-Bocage", dept: "Haute-Garonne", description: "Église Saint-Jean", secteur: "Volvestre", distanceKm: 75, lat: 43.1286, lng: 1.2728 },
  { id: 162, commune: "Montclar-Lauragais", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 48, lat: 43.3667, lng: 1.7256 },
  { id: 163, commune: "Montégut-Bourjac", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Savès", distanceKm: 65, lat: 43.2558, lng: 1.0014 },
  { id: 164, commune: "Montesquieu-Lauragais", dept: "Haute-Garonne", description: "Église Saint-Jacques", secteur: "Lauragais", distanceKm: 30, lat: 43.4169, lng: 1.6286 },
  { id: 165, commune: "Montesquieu-Volvestre", dept: "Haute-Garonne", description: "Église Saint-Victor (clocher-mur imposant)", secteur: "Volvestre", distanceKm: 55, lat: 43.2081, lng: 1.2333 },
  { id: 166, commune: "Montferrand", dept: "Aude", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 50, lat: 43.3600, lng: 1.8214 },
  { id: 167, commune: "Montgaillard-Lauragais", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Lauragais", distanceKm: 35, lat: 43.4150, lng: 1.6967 },
  { id: 168, commune: "Montgazin", dept: "Haute-Garonne", description: "Église Saint-Sulpice", secteur: "Volvestre", distanceKm: 52, lat: 43.3131, lng: 1.2825 },
  { id: 169, commune: "Montgeard", dept: "Haute-Garonne", description: "Église Notre-Dame-de-l'Assomption", secteur: "Lauragais", distanceKm: 40, lat: 43.3400, lng: 1.6353 },
  { id: 170, commune: "Montgiscard", dept: "Haute-Garonne", description: "Église Saint-André (clocher-mur monumental)", secteur: "Lauragais", distanceKm: 22, lat: 43.4578, lng: 1.5742 },
  { id: 171, commune: "Montgras", dept: "Haute-Garonne", description: "Église Saint-Jean", secteur: "Savès", distanceKm: 48, lat: 43.4636, lng: 1.0967 },
  { id: 172, commune: "Montpitol", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Nord-Est Toulousain", distanceKm: 25, lat: 43.7119, lng: 1.6114 },
  { id: 173, commune: "Montrabé", dept: "Haute-Garonne", description: "Église Saint-Martial", secteur: "Toulouse Métropole", distanceKm: 10, lat: 43.6425, lng: 1.5261 },
  { id: 174, commune: "Montsaunès", dept: "Haute-Garonne", description: "Église Saint-Christophe (portail roman)", secteur: "Comminges", distanceKm: 82, lat: 43.1114, lng: 0.9383 },
  { id: 175, commune: "Mourvilles-Hautes", dept: "Haute-Garonne", description: "Église Sainte-Anne", secteur: "Lauragais", distanceKm: 45, lat: 43.4258, lng: 1.8153 },
  { id: 176, commune: "Mourvilles-Basses", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Lauragais", distanceKm: 35, lat: 43.4914, lng: 1.7067 },
  { id: 177, commune: "Moustajon", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Pyrénées", distanceKm: 138, lat: 42.8083, lng: 0.5956 },
  { id: 178, commune: "Nailloux", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Lauragais", distanceKm: 35, lat: 43.3553, lng: 1.6239 },
  { id: 179, commune: "Nogaret", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Lauragais", distanceKm: 52, lat: 43.4908, lng: 1.9317 },
  { id: 180, commune: "Noumerens", dept: "Haute-Garonne", description: "Chapelle Notre-Dame", secteur: "Savès", distanceKm: 55, lat: 43.4356, lng: 1.0114 },
  { id: 181, commune: "Noueilles", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 25, lat: 43.4503, lng: 1.5214 },
  { id: 182, commune: "Odars", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Lauragais", distanceKm: 18, lat: 43.5153, lng: 1.5956 },
  { id: 183, commune: "Ondes", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Nord Toulousain", distanceKm: 25, lat: 43.7811, lng: 1.3089 },
  { id: 184, commune: "Palaminy", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Volvestre", distanceKm: 65, lat: 43.2036, lng: 1.0669 },
  { id: 185, commune: "Paulhac", dept: "Haute-Garonne", description: "Église Saint-Étienne", secteur: "Nord-Est Toulousain", distanceKm: 25, lat: 43.7558, lng: 1.5558 },
  { id: 186, commune: "Pechbonnieu", dept: "Haute-Garonne", description: "Église Saint-Aignan", secteur: "Nord Toulousain", distanceKm: 12, lat: 43.7039, lng: 1.4675 },
  { id: 187, commune: "Pechbusque", dept: "Haute-Garonne", description: "Église Saint-Jacques", secteur: "Sud Toulousain", distanceKm: 10, lat: 43.5275, lng: 1.4589 },
  { id: 188, commune: "Peyra-sur-l'Hers", dept: "Aude", description: "Église Sainte-Colombe", secteur: "Lauragais", distanceKm: 55, lat: 43.2975, lng: 1.8558 },
  { id: 189, commune: "Peyrouzet", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Comminges", distanceKm: 85, lat: 43.2058, lng: 0.9208 },
  { id: 190, commune: "Peyssies", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Volvestre", distanceKm: 48, lat: 43.3222, lng: 1.1836 },
  { id: 191, commune: "Pibrac", dept: "Haute-Garonne", description: "Église Sainte-Marie-Madeleine", secteur: "Ouest Toulousain", distanceKm: 15, lat: 43.6186, lng: 1.2850 },
  { id: 192, commune: "Pin-Balma", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Toulouse Métropole", distanceKm: 8, lat: 43.6106, lng: 1.5336 },
  { id: 193, commune: "Plaigne", dept: "Aude", description: "Église Saint-Celse-et-Saint-Nazaire", secteur: "Lauragais", distanceKm: 60, lat: 43.1750, lng: 1.8122 },
  { id: 194, commune: "Plaisance-du-Touch", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Ouest Toulousain", distanceKm: 15, lat: 43.5658, lng: 1.2961 },
  { id: 195, commune: "Pointis-Inard", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Comminges", distanceKm: 95, lat: 43.0886, lng: 0.8117 },
  { id: 196, commune: "Polastron", dept: "Haute-Garonne", description: "Église Saint-Roch", secteur: "Savès", distanceKm: 58, lat: 43.3183, lng: 1.1272 },
  { id: 197, commune: "Pompertuzat", dept: "Haute-Garonne", description: "Église Saint-André-et-Saint-Cloud", secteur: "Lauragais", distanceKm: 18, lat: 43.4897, lng: 1.5347 },
  { id: 198, commune: "Portet-sur-Garonne", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Sud Toulousain", distanceKm: 12, lat: 43.5239, lng: 1.4056 },
  { id: 199, commune: "Poucharramet", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste (commanderie)", secteur: "Sud-Ouest", distanceKm: 35, lat: 43.4175, lng: 1.1739 },
  { id: 200, commune: "Poujary", dept: "Haute-Garonne", description: "Église de Poujary", secteur: "Savès", distanceKm: 55, lat: 43.3447, lng: 1.0117 },
  { id: 201, commune: "Pouze", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 28, lat: 43.4358, lng: 1.5261 },
  { id: 202, commune: "Prunet", dept: "Haute-Garonne", description: "Église Saint-Hilaire", secteur: "Lauragais", distanceKm: 35, lat: 43.5186, lng: 1.7456 },
  { id: 203, commune: "Puydaniel", dept: "Haute-Garonne", description: "Église Saint-Baudile", secteur: "Vallée de l'Ariège", distanceKm: 38, lat: 43.3353, lng: 1.4339 },
  { id: 204, commune: "Quint-Fonsegrives", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Toulouse Métropole", distanceKm: 10, lat: 43.5847, lng: 1.5264 },
  { id: 205, commune: "Ramonville-Saint-Agne", dept: "Haute-Garonne", description: "Église Saint-Jean", secteur: "Sud-Est Toulousain", distanceKm: 8, lat: 43.5414, lng: 1.4756 },
  { id: 206, commune: "Razecueillé", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Pyrénées", distanceKm: 115, lat: 42.9714, lng: 0.7936 },
  { id: 207, commune: "Rechigue", dept: "Haute-Garonne", description: "Église de Rechigue", secteur: "Lauragais", distanceKm: 35, lat: 43.4117, lng: 1.7583 },
  { id: 208, commune: "Renneville", dept: "Haute-Garonne", description: "Église Saint-Jacques", secteur: "Lauragais", distanceKm: 42, lat: 43.3833, lng: 1.7289 },
  { id: 209, commune: "Rieumes", dept: "Haute-Garonne", description: "Église Saint-Gilles", secteur: "Sud-Ouest", distanceKm: 42, lat: 43.4122, lng: 1.1194 },
  { id: 210, commune: "Riolas", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Savès", distanceKm: 75, lat: 43.3517, lng: 0.7622 },
  { id: 211, commune: "Roques", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Sud Toulousain", distanceKm: 15, lat: 43.5103, lng: 1.3769 },
  { id: 212, commune: "Rouède", dept: "Haute-Garonne", description: "Église Saint-Sébastien", secteur: "Comminges", distanceKm: 98, lat: 43.0567, lng: 0.8803 },
  { id: 213, commune: "Roumens", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 50, lat: 43.4758, lng: 1.8486 },
  { id: 214, commune: "Sabonnères", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Savès", distanceKm: 45, lat: 43.4664, lng: 1.0631 },
  { id: 215, commune: "Saint-Anatoly", dept: "Haute-Garonne", description: "Église Saint-Anatoly", secteur: "Lauragais", distanceKm: 25, lat: 43.5889, lng: 1.6364 },
  { id: 216, commune: "Saint-Araille", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Savès", distanceKm: 65, lat: 43.3578, lng: 0.9856 },
  { id: 217, commune: "Saint-Cézert", dept: "Haute-Garonne", description: "Église Saint-Cézert", secteur: "Nord-Ouest", distanceKm: 32, lat: 43.7828, lng: 1.1917 },
  { id: 218, commune: "Saint-Christaud", dept: "Haute-Garonne", description: "Église Saint-Christophe", secteur: "Volvestre", distanceKm: 62, lat: 43.1819, lng: 1.2486 },
  { id: 219, commune: "Saint-Christol", dept: "Haute-Garonne", description: "Église Saint-Christophe", secteur: "Lauragais", distanceKm: 38, lat: 43.4931, lng: 1.7331 },
  { id: 220, commune: "Sainte-Foy-de-Peyrolières", dept: "Haute-Garonne", description: "Église Sainte-Foy", secteur: "Sud-Ouest", distanceKm: 35, lat: 43.4908, lng: 1.1450 },
  { id: 221, commune: "Sainte-Livrade", dept: "Haute-Garonne", description: "Église Sainte-Livrade", secteur: "Nord-Ouest", distanceKm: 30, lat: 43.6486, lng: 1.1017 },
  { id: 222, commune: "Saint-Élix-Séglan", dept: "Haute-Garonne", description: "Église Saint-Élix", secteur: "Comminges", distanceKm: 95, lat: 43.1953, lng: 0.8528 },
  { id: 223, commune: "Saint-Germier", dept: "Haute-Garonne", description: "Église Saint-Germier", secteur: "Lauragais", distanceKm: 42, lat: 43.4678, lng: 1.7247 },
  { id: 224, commune: "Saint-Jean", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Nord-Est Toulousain", distanceKm: 10, lat: 43.6658, lng: 1.5039 },
  { id: 225, commune: "Saint-Julia", dept: "Haute-Garonne", description: "Église Sainte-Agathe (clocher-mur à 5 baies)", secteur: "Lauragais", distanceKm: 55, lat: 43.4903, lng: 1.8978 },
  { id: 226, commune: "Saint-Julien", dept: "Haute-Garonne", description: "Église Saint-Julien", secteur: "Volvestre", distanceKm: 58, lat: 43.2436, lng: 1.1472 },
  { id: 227, commune: "Saint-Marcel-Paulel", dept: "Haute-Garonne", description: "Église Saint-Marcel", secteur: "Nord-Est Toulousain", distanceKm: 22, lat: 43.6631, lng: 1.6047 },
  { id: 228, commune: "Saint-Médard", dept: "Haute-Garonne", description: "Église Saint-Médard", secteur: "Comminges", distanceKm: 105, lat: 43.1286, lng: 0.8356 },
  { id: 229, commune: "Saint-Michel", dept: "Haute-Garonne", description: "Église Saint-Michel", secteur: "Lauragais", distanceKm: 35, lat: 43.4358, lng: 1.5261 },
  { id: 230, commune: "Saint-Michel-de-Lanès", dept: "Aude", description: "Église Saint-Michel", secteur: "Lauragais", distanceKm: 52, lat: 43.3283, lng: 1.7586 },
  { id: 231, commune: "Saint-Orens-de-Gameville", dept: "Haute-Garonne", description: "Église Saint-Orens", secteur: "Sud-Est Toulousain", distanceKm: 12, lat: 43.5511, lng: 1.5336 },
  { id: 232, commune: "Saint-Paul-sur-Save", dept: "Haute-Garonne", description: "Église Saint-Paul", secteur: "Nord-Ouest", distanceKm: 25, lat: 43.6989, lng: 1.2264 },
  { id: 233, commune: "Saint-Pierre", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 32, lat: 43.6264, lng: 1.6469 },
  { id: 234, commune: "Saint-Pierre-de-Lages", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 18, lat: 43.5683, lng: 1.6253 },
  { id: 235, commune: "Saint-Plancard", dept: "Haute-Garonne", description: "Chapelle Saint-Jean (fresques célèbres)", secteur: "Comminges", distanceKm: 110, lat: 43.1706, lng: 0.6053 },
  { id: 236, commune: "Saint-Rome", dept: "Haute-Garonne", description: "Église Saint-Rome", secteur: "Lauragais", distanceKm: 38, lat: 43.4244, lng: 1.6811 },
  { id: 237, commune: "Saint-Sauveur", dept: "Haute-Garonne", description: "Église Saint-Sauveur", secteur: "Nord Toulousain", distanceKm: 20, lat: 43.7492, lng: 1.4011 },
  { id: 238, commune: "Saint-Sernin-de-Sanissac", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Savès", distanceKm: 60, lat: 43.3883, lng: 0.8414 },
  { id: 239, commune: "Saint-Vincent", dept: "Haute-Garonne", description: "Église Saint-Vincent", secteur: "Lauragais", distanceKm: 45, lat: 43.4406, lng: 1.7967 },
  { id: 240, commune: "Sajas", dept: "Haute-Garonne", description: "Église Saint-Vincent", secteur: "Savès", distanceKm: 55, lat: 43.3831, lng: 1.0208 },
  { id: 241, commune: "Salguède", dept: "Haute-Garonne", description: "Église de Salguède", secteur: "Savès", distanceKm: 58, lat: 43.4111, lng: 1.0117 },
  { id: 242, commune: "Salies-du-Salat", dept: "Haute-Garonne", description: "Église Notre-Dame-de-la-Pitié", secteur: "Comminges", distanceKm: 80, lat: 43.1039, lng: 0.9606 },
  { id: 243, commune: "Salles-sur-l'Hers", dept: "Aude", description: "Église Saint-Barthélemy", secteur: "Lauragais", distanceKm: 58, lat: 43.2942, lng: 1.7853 },
  { id: 244, commune: "Saubens", dept: "Haute-Garonne", description: "Église Notre-Dame", secteur: "Sud Toulousain", distanceKm: 18, lat: 43.4789, lng: 1.3486 },
  { id: 245, commune: "Saux-et-Pomarède", dept: "Haute-Garonne", description: "Église Saint-Vincent", secteur: "Comminges", distanceKm: 90, lat: 43.1611, lng: 0.7844 },
  { id: 246, commune: "Savères", dept: "Haute-Garonne", description: "Église Saint-Barthélemy", secteur: "Savès", distanceKm: 52, lat: 43.3703, lng: 1.1044 },
  { id: 247, commune: "Sénarens", dept: "Haute-Garonne", description: "Église Saint-Sébastien", secteur: "Savès", distanceKm: 65, lat: 43.2731, lng: 0.9858 },
  { id: 248, commune: "Sepx", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Comminges", distanceKm: 88, lat: 43.1558, lng: 0.8414 },
  { id: 249, commune: "Seyre", dept: "Haute-Garonne", description: "Église Saint-Félix", secteur: "Lauragais", distanceKm: 42, lat: 43.3642, lng: 1.6631 },
  { id: 250, commune: "Tarabel", dept: "Haute-Garonne", description: "Église Saint-Martial", secteur: "Lauragais", distanceKm: 28, lat: 43.5189, lng: 1.6761 },
  { id: 251, commune: "Terrebasse", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Comminges", distanceKm: 85, lat: 43.2308, lng: 0.9575 },
  { id: 252, commune: "Thil", dept: "Haute-Garonne", description: "Église Saint-Laurent", secteur: "Nord-Ouest", distanceKm: 30, lat: 43.7125, lng: 1.1614 },
  { id: 253, commune: "Toulouse", dept: "Haute-Garonne", description: "Église du Taur (clocher-mur emblématique)", secteur: "Toulouse Centre", distanceKm: 0, lat: 43.6067, lng: 1.4428 },
  { id: 254, commune: "Trébons-sur-la-Grasse", dept: "Haute-Garonne", description: "Église Saint-Julien", secteur: "Lauragais", distanceKm: 35, lat: 43.4503, lng: 1.7225 },
  { id: 255, commune: "Vallègue", dept: "Haute-Garonne", description: "Église Saint-Paul", secteur: "Lauragais", distanceKm: 48, lat: 43.4222, lng: 1.7517 },
  { id: 256, commune: "Varennes", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Lauragais", distanceKm: 25, lat: 43.4583, lng: 1.6111 },
  { id: 257, commune: "Vaudreuille", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Lauragais", distanceKm: 60, lat: 43.4253, lng: 1.9819 },
  { id: 258, commune: "Vaux", dept: "Haute-Garonne", description: "Église Saint-Blaise", secteur: "Lauragais", distanceKm: 45, lat: 43.4561, lng: 1.8383 },
  { id: 259, commune: "Vendine", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Lauragais", distanceKm: 32, lat: 43.5858, lng: 1.7583 },
  { id: 260, commune: "Venerque", dept: "Haute-Garonne", description: "Église Saint-Pierre (style roman/gothique)", secteur: "Sud Toulousain", distanceKm: 22, lat: 43.4331, lng: 1.4436 },
  { id: 261, commune: "Verfeil", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Nord-Est Toulousain", distanceKm: 25, lat: 43.6558, lng: 1.6644 },
  { id: 262, commune: "Vernet", dept: "Haute-Garonne", description: "Église Saint-Benoît", secteur: "Sud Toulousain", distanceKm: 20, lat: 43.4339, lng: 1.4289 },
  { id: 263, commune: "Vieille-Toulouse", dept: "Haute-Garonne", description: "Église Saint-Jean-Baptiste", secteur: "Sud Toulousain", distanceKm: 10, lat: 43.5253, lng: 1.4461 },
  { id: 264, commune: "Vieillevigne", dept: "Haute-Garonne", description: "Église Saint-Sernin", secteur: "Lauragais", distanceKm: 40, lat: 43.4014, lng: 1.6575 },
  { id: 265, commune: "Vigoulet-Auzil", dept: "Haute-Garonne", description: "Église Saint-Martin", secteur: "Sud Toulousain", distanceKm: 12, lat: 43.5042, lng: 1.4589 },
  { id: 266, commune: "Villariès", dept: "Haute-Garonne", description: "Église Saint-Sulpice", secteur: "Nord Toulousain", distanceKm: 22, lat: 43.7506, lng: 1.4939 },
  { id: 267, commune: "Villefranche-de-Lauragais", dept: "Haute-Garonne", description: "Église Notre-Dame-de-l'Assomption", secteur: "Lauragais", distanceKm: 35, lat: 43.3992, lng: 1.7183 },
  { id: 268, commune: "Villematier", dept: "Haute-Garonne", description: "Église Saint-Pierre", secteur: "Nord Toulousain", distanceKm: 35, lat: 43.8289, lng: 1.5089 },
  { id: 269, commune: "Villemur-sur-Tarn", dept: "Haute-Garonne", description: "Église Saint-Michel", secteur: "Nord Toulousain", distanceKm: 40, lat: 43.8642, lng: 1.5058 },
  { id: 270, commune: "Villenouvelle", dept: "Haute-Garonne", description: "Église Saint-Saturnin", secteur: "Lauragais", distanceKm: 30, lat: 43.4356, lng: 1.6622 }
];

export async function GET() {
  return NextResponse.json(clochersData);
}