import { NextResponse } from 'next/server';

export async function GET() {
  const preteurs = [
    { rang: 1, pays: "Japon", details: "Premier créancier mondial (~1 225 Mds $ de dette US) depuis des décennies." },
    { rang: 2, pays: "Chine", details: "~760 Mds $ de dette US. En baisse constante (diversification vers l'or)." },
    { rang: 3, pays: "Royaume-Uni", details: "~720 Mds $ de dette US. Surtout via la place financière de Londres (fonds privés)." },
    { rang: 4, pays: "Luxembourg", details: "~420 Mds $ de dette US. Centre névralgique pour les fonds d'investissement mondiaux." },
    { rang: 5, pays: "Belgique", details: "~375 Mds $ de dette US. Souvent utilisé comme plateforme de conservation de titres." },
    { rang: 6, pays: "Canada", details: "Très actif via ses fonds de pension massifs (CPPIB, CDPQ)." },
    { rang: 7, pays: "France", details: "Prêteur via ses grandes banques et assureurs (AXA, BNP Paribas)." },
    { rang: 8, pays: "Suisse", details: "Sa Banque Nationale (BNS) est l'une des plus grandes acheteuses de titres mondiaux." },
    { rang: 9, pays: "Taïwan", details: "Accumule des créances grâce à ses exportations records de semi-conducteurs." },
    { rang: 10, pays: "Inde", details: "En forte progression ; utilise ses réserves pour stabiliser sa monnaie." },
    { rang: 11, pays: "Brésil", details: "Historiquement un grand acheteur de dette US pour sécuriser ses réserves." },
    { rang: 12, pays: "Singapour", details: "Agit via ses fonds souverains géants (GIC et Temasek)." },
    { rang: 13, pays: "Irlande", details: "Hub technique : beaucoup de fonds internationaux y sont domiciliés." },
    { rang: 14, pays: "Norvège", details: "Détient le plus grand fonds souverain au monde (pétrole), prêteur universel." },
    { rang: 15, pays: "Corée du Sud", details: "Créancier industriel majeur avec des réserves de change colossales." },
    { rang: 16, pays: "Îles Caïmans", details: "Centre \"Offshore\" où les fonds privés mondiaux achètent de la dette." },
    { rang: 17, pays: "Pays-Bas", details: "Fort excédent commercial systématiquement réinvesti à l'étranger." },
    { rang: 18, pays: "Mexique", details: "Détient des réserves importantes pour protéger la stabilité du Peso." },
    { rang: 19, pays: "Arabie Saoudite", details: "Prêteur stratégique via son fonds PIF et ses réserves pétrolières." },
    { rang: 20, pays: "Israël", details: "Secteur technologique puissant générant des surplus de capitaux massifs." },
    { rang: 21, pays: "Thaïlande", details: "Détient des réserves massives (~220 Mds $) pour protéger le Baht." },
    { rang: 22, pays: "Koweït", details: "Prêteur institutionnel via la Kuwait Investment Authority (fonds souverain)." },
    { rang: 23, pays: "Émirats Arabes Unis", details: "Un des plus gros investisseurs mondiaux (via ADIA et Mubadala)." },
    { rang: 24, pays: "Pologne", details: "En forte croissance, accumule des réserves pour stabiliser le Zloty." },
    { rang: 25, pays: "Autriche", details: "Banques prêteuses historiques majeures en Europe de l'Est." },
    { rang: 26, pays: "Suède", details: "Gestionnaire de capitaux très actif via ses fonds de pension publics (AP)." },
    { rang: 27, pays: "Australie", details: "Détenteur de titres étrangers via ses fonds \"Superannuation\" géants." },
    { rang: 28, pays: "Bermudes", details: "Place tournante internationale pour les assureurs et réassureurs." },
    { rang: 29, pays: "Malaisie", details: "Important détenteur de dettes régionales en Asie du Sud-Est." },
    { rang: 30, pays: "Indonésie", details: "Utilise ses réserves (~150 Mds $) pour influencer les marchés obligataires." },
    { rang: 31, pays: "Philippines", details: "Accumule des devises grâce aux transferts massifs de sa diaspora." },
    { rang: 32, pays: "Danemark", details: "Prêteur stable via ses excédents commerciaux récurrents." },
    { rang: 33, pays: "Rép. Tchèque", details: "Possède un stock de devises énorme par rapport à la taille de son PIB." },
    { rang: 34, pays: "Turquie", details: "Malgré l'inflation, elle reste un acteur obligataire régional clé." },
    { rang: 35, pays: "Argentine", details: "Situation complexe, mais détient historiquement des titres US." },
    { rang: 36, pays: "Chili", details: "Prêteur via ses fonds souverains issus des revenus du cuivre." },
    { rang: 37, pays: "Vietnam", details: "Nouvelle puissance exportatrice accumulant des réserves de change." },
    { rang: 38, pays: "Colombie", details: "Acteur financier et prêteur stable en Amérique latine." },
    { rang: 39, pays: "Luxembourg (hors hub)", details: "Créancier net solide si l'on exclut l'activité de transit bancaire." },
    { rang: 40, pays: "Kazakhstan", details: "Prêteur via son fonds pétrolier national (National Fund)." },
    { rang: 41, pays: "Qatar", details: "Prêteur massif via le Qatar Investment Authority (immobilier, tech)." },
    { rang: 42, pays: "Bulgarie", details: "Gestion très stricte des réserves en vue de l'adhésion à l'Euro." },
    { rang: 43, pays: "Hongrie", details: "Acteur obligataire très dynamique en Europe Centrale." },
    { rang: 44, pays: "Ukraine", details: "Cas particulier : détient des réserves pour stabiliser sa reconstruction." },
    { rang: 45, pays: "Maroc", details: "Réserve de change très stable (~35 Mds $), leader en Afrique du Nord." },
    { rang: 46, pays: "Portugal", details: "Créancier via son système bancaire malgré une dette publique d'État." },
    { rang: 47, pays: "Ouzbékistan", details: "Puissance émergente d'Asie centrale, accumule massivement de l'or." },
    { rang: 48, pays: "Nigeria", details: "Premier prêteur et investisseur interne au sein de la zone CEDEAO." },
    { rang: 49, pays: "Serbie", details: "Hub financier en pleine ascension dans les Balkans non-UE." },
    { rang: 50, pays: "Macao", details: "Coffre-fort de devises issu des revenus mondiaux du jeu." },
    { rang: 51, pays: "Liban", details: "Détient d'importantes réserves d'or malgré sa crise monétaire." },
    { rang: 52, pays: "Bangladesh", details: "Accumule des devises via ses exportations textiles mondiales." },
    { rang: 53, pays: "Guatemala", details: "Très stable en Amérique Centrale, prêteur régional discret." },
    { rang: 54, pays: "Cambodge", details: "Forte croissance de ses réserves de change libellées en Dollars." },
    { rang: 55, pays: "Jordanie", details: "Pivot financier stratégique soutenu par les flux internationaux." },
    { rang: 56, pays: "Oman", details: "Utilise ses revenus gaziers pour prêter via son fonds souverain." },
    { rang: 57, pays: "Finlande", details: "Prêteur institutionnel via ses fonds de pension publics et privés." },
    { rang: 58, pays: "Uruguay", details: "La \"Suisse de l'Amérique du Sud\", centre de gestion de fortune." },
    { rang: 59, pays: "Rép. Dominicaine", details: "Leader financier et attracteur de capitaux dans les Caraïbes." },
    { rang: 60, pays: "Nouvelle-Zélande", details: "Investisseur international actif via le NZ Super Fund." },
    { rang: 61, pays: "Angola", details: "Prêteur via son fonds souverain pétrolier (FSDEA)." },
    { rang: 62, pays: "Azerbaïdjan", details: "Gère des dizaines de milliards via son fonds pétrolier SOFAZ." },
    { rang: 63, pays: "Pakistan", details: "Volume financier de poids malgré la dépendance aux aides du FMI." },
    { rang: 64, pays: "Grèce", details: "Revient parmi les créanciers grâce à son redressement économique." },
    { rang: 65, pays: "Costa Rica", details: "Pionnier de la finance verte (obligations durables et nature)." },
    { rang: 66, pays: "Népal", details: "Réserves de change alimentées par les remises de fonds mondiales." },
    { rang: 67, pays: "Slovaquie", details: "Intégrée aux flux de la zone Euro, acteur industriel prêteur." },
    { rang: 68, pays: "Paraguay", details: "Exportateur d'énergie et de soja, accumule des surplus de devises." },
    { rang: 69, pays: "Panama", details: "Hub financier mondial gérant les capitaux de tiers." },
    { rang: 70, pays: "Kenya", details: "Leader de la Fintech africaine, redistribue les capitaux dans la région." }
  ];

  return NextResponse.json(preteurs);
}
