import { NextResponse } from 'next/server';

export async function GET() {
  const data = [
  { rang: 1, pays: "Vatican", superficie: "0,44 km²", region: "Europe (Italie)", info: "État enclavé dans la ville de Rome." },
  { rang: 2, pays: "Monaco", superficie: "2,02 km²", region: "Europe (France)", info: "Le pays le plus densément peuplé au monde." },
  { rang: 3, pays: "Nauru", superficie: "21 km²", region: "Océanie", info: "La plus petite république et nation insulaire." },
  { rang: 4, pays: "Tuvalu", superficie: "26 km²", region: "Océanie", info: "Menacé par la montée des eaux du Pacifique." },
  { rang: 5, pays: "Saint-Marin", superficie: "61 km²", region: "Europe (Italie)", info: "La plus ancienne république du monde." },
  { rang: 6, pays: "Liechtenstein", superficie: "160 km²", region: "Europe", info: "Situé dans les Alpes entre la Suisse et l'Autriche." },
  { rang: 7, pays: "Îles Marshall", superficie: "181 km²", region: "Océanie", info: "Un archipel de plus de 1 000 îles et îlots." },
  { rang: 8, pays: "Saint-Kitts-et-Nevis", superficie: "261 km²", region: "Caraïbes", info: "Le plus petit pays des Amériques." },
  { rang: 9, pays: "Maldives", superficie: "300 km²", region: "Asie (Océan Indien)", info: "Le plus petit pays d'Asie." },
  { rang: 10, pays: "Malte", superficie: "316 km²", region: "Europe", info: "Un point stratégique au centre de la Méditerranée." },
  { rang: 11, pays: "Saint-Vincent-et-les-Grenadines", superficie: "389 km²", region: "Caraïbes", info: "Composé d'une île principale et d'une chaîne de petites îles." },
  { rang: 12, pays: "Barbade", superficie: "430 km²", region: "Caraïbes", info: "Devenue une république en 2021." },
  { rang: 13, pays: "Antigua-et-Barbuda", superficie: "442 km²", region: "Caraïbes", info: "Surnommée l'île aux 365 plages." },
  { rang: 14, pays: "Seychelles", superficie: "452 km²", region: "Afrique (Océan Indien)", info: "Le plus petit pays d'Afrique." },
  { rang: 15, pays: "Palaos", superficie: "459 km²", region: "Océanie", info: "Un archipel de plus de 500 îles." },
  { rang: 16, pays: "Andorre", superficie: "468 km²", region: "Europe (Pyrénées)", info: "Co-principauté située entre la France et l'Espagne." },
  { rang: 17, pays: "Sainte-Lucie", superficie: "616 km²", region: "Caraïbes", info: "Célèbre pour ses deux pitons volcaniques." },
  { rang: 18, pays: "États fédérés de Micronésie", superficie: "702 km²", region: "Océanie", info: "Comprend quatre États : Chuuk, Kosrae, Pohnpei et Yap." },
  { rang: 19, pays: "Singapour", superficie: "719 km²", region: "Asie", info: "Ville-État souveraine et centre financier mondial." },
  { rang: 20, pays: "Tonga", superficie: "747 km²", region: "Océanie", info: "Le seul État souverain du Pacifique à n'avoir jamais été colonisé." },
  { rang: 21, pays: "Dominique", superficie: "751 km²", region: "Caraïbes", info: "Surnommée l'île de nature des Caraïbes." },
  { rang: 22, pays: "Bahreïn", superficie: "765 km²", region: "Moyen-Orient", info: "Un archipel de 33 îles dans le golfe Persique." },
  { rang: 23, pays: "Kiribati", superficie: "811 km²", region: "Océanie", info: "Le seul pays au monde situé dans les quatre hémisphères." },
  { rang: 24, pays: "Sao Tomé-et-Principe", superficie: "964 km²", region: "Afrique (Golfe de Guinée)", info: "Le deuxième plus petit pays d'Afrique." },
  { rang: 25, pays: "Comores", superficie: "1 862 km²", region: "Afrique (Océan Indien)", info: "Un archipel volcanique situé dans le canal du Mozambique." },
  { rang: 26, pays: "Maurice", superficie: "2 040 km²", region: "Afrique (Océan Indien)", info: "Ancien habitat naturel du Dodo." },
  { rang: 27, pays: "Luxembourg", superficie: "2 586 km²", region: "Europe", info: "Dernier Grand-Duché au monde." },
  { rang: 28, pays: "Samoa", superficie: "2 831 km²", region: "Océanie", info: "Anciennement appelé Samoa occidentales." },
  { rang: 29, pays: "Cap-Vert", superficie: "4 033 km²", region: "Afrique (Atlantique)", info: "Archipel de dix îles volcaniques." },
  { rang: 30, pays: "Trinité-et-Tobago", superficie: "5 128 km²", region: "Caraïbes", info: "Le berceau de la musique Steelpan." },
  { rang: 31, pays: "Brunéi", superficie: "5 765 km²", region: "Asie (Bornéo)", info: "Sultanat riche en pétrole et gaz naturel." },
  { rang: 32, pays: "Palestine", superficie: "6 020 km²", region: "Moyen-Orient", info: "État observateur non-membre aux Nations Unies." },
  { rang: 33, pays: "Chypre", superficie: "9 251 km²", region: "Europe / Asie", info: "Île divisée par la ligne verte de l'ONU." },
  { rang: 34, pays: "Liban", superficie: "10 452 km²", region: "Moyen-Orient", info: "Le plus petit pays du Moyen-Orient continental." },
  { rang: 35, pays: "Kosovo", superficie: "10 887 km²", region: "Europe (Balkans)", info: "État à reconnaissance limitée dans les Balkans." },
  { rang: 36, pays: "Jamaïque", superficie: "10 991 km²", region: "Caraïbes", info: "Troisième plus grande île des Grandes Antilles." },
  { rang: 37, pays: "Gambie", superficie: "11 295 km²", region: "Afrique", info: "Le plus petit pays d'Afrique continentale." },
  { rang: 38, pays: "Qatar", superficie: "11 586 km²", region: "Moyen-Orient", info: "Possède les troisièmes réserves mondiales de gaz naturel." },
  { rang: 39, pays: "Vanuatu", superficie: "12 189 km²", region: "Océanie", info: "Archipel composé d'environ 80 îles d'origine volcanique." },
  { rang: 40, pays: "Monténégro", superficie: "13 812 km²", region: "Europe (Balkans)", info: "Devenu indépendant de la Serbie en 2006." },
  { rang: 41, pays: "Bahamas", superficie: "13 878 km²", region: "Caraïbes", info: "Comprend plus de 700 îles et îlots." },
  { rang: 42, pays: "Timor oriental", superficie: "14 874 km²", region: "Asie du Sud-Est", info: "Le premier nouvel État souverain du XXIe siècle." },
  { rang: 43, pays: "Eswatini", superficie: "17 364 km²", region: "Afrique", info: "L'une des dernières monarchies absolues d'Afrique." },
  { rang: 44, pays: "Koweït", superficie: "17 818 km²", region: "Moyen-Orient", info: "Possède une part importante des réserves mondiales de pétrole." },
  { rang: 45, pays: "Fidji", superficie: "18 274 km²", region: "Océanie", info: "Archipel de plus de 300 îles dans le Pacifique Sud." },
  { rang: 46, pays: "Slovénie", superficie: "20 273 km²", region: "Europe", info: "Plus de la moitié du territoire est recouverte de forêts." },
  { rang: 47, pays: "Israël", superficie: "20 770 km²", region: "Moyen-Orient", info: "Seul pays au monde où l'hébreu est une langue officielle." },
  { rang: 48, pays: "Salvador", superficie: "21 041 km²", region: "Amérique centrale", info: "Le pays le plus petit et le plus densément peuplé d'Amérique centrale." },
  { rang: 49, pays: "Belize", superficie: "22 966 km²", region: "Amérique centrale", info: "Seul pays d'Amérique centrale avec l'anglais comme langue officielle." },
  { rang: 50, pays: "Djibouti", superficie: "23 200 km²", region: "Afrique (Corne de l'Afrique)", info: "Point le plus bas d'Afrique (lac Assal)." },
  { rang: 51, pays: "Macédoine du Nord", superficie: "25 713 km²", region: "Europe (Balkans)", info: "Pays enclavé situé au cœur des Balkans." },
  { rang: 52, pays: "Rwanda", superficie: "26 338 km²", region: "Afrique", info: "Surnommé le pays des mille collines." },
  { rang: 53, pays: "Haïti", superficie: "27 750 km²", region: "Caraïbes", info: "Première république noire indépendante au monde." },
  { rang: 54, pays: "Burundi", superficie: "27 834 km²", region: "Afrique", info: "Pays enclavé dans la région des Grands Lacs." },
  { rang: 55, pays: "Guinée équatoriale", superficie: "28 051 km²", region: "Afrique", info: "Seul pays d'Afrique dont l'espagnol est la langue officielle." },
  { rang: 56, pays: "Albanie", superficie: "28 748 km²", region: "Europe (Balkans)", info: "Possède un littoral sur les mers Adriatique et Ionienne." },
  { rang: 57, pays: "Îles Salomon", superficie: "28 896 km²", region: "Océanie", info: "Archipel de six îles principales et des centaines de petites." },
  { rang: 58, pays: "Arménie", superficie: "29 743 km²", region: "Asie (Caucase)", info: "Le premier pays à avoir adopté le christianisme comme religion d'État." },
  { rang: 59, pays: "Lesotho", superficie: "30 355 km²", region: "Afrique (enclavé en Afrique du Sud)", info: "Entièrement situé à plus de 1 400 mètres d'altitude." },
  { rang: 60, pays: "Belgique", superficie: "30 528 km²", region: "Europe", info: "Siège de l'OTAN et de l'Union européenne." },
  { rang: 61, pays: "Moldavie", superficie: "33 851 km²", region: "Europe", info: "Connue pour sa riche tradition de production de vin." },
  { rang: 62, pays: "Guinée-Bissau", superficie: "36 125 km²", region: "Afrique", info: "Archipel des Bijagos comprenant 88 îles." },
  { rang: 63, pays: "Bhoutan", superficie: "38 394 km²", region: "Asie (Himalaya)", info: "Mesure le Bonheur National Brut plutôt que le PIB." },
  { rang: 64, pays: "Suisse", superficie: "41 285 km²", region: "Europe", info: "Maintenant une politique de neutralité armée de longue date." },
  { rang: 65, pays: "Pays-Bas", superficie: "41 543 km²", region: "Europe", info: "Près d'un quart de son territoire est sous le niveau de la mer." },
  { rang: 66, pays: "Danemark", superficie: "43 094 km²", region: "Europe", info: "Comprend la péninsule du Jutland et 443 îles nommées." },
  { rang: 67, pays: "Estonie", superficie: "45 227 km²", region: "Europe (Baltique)", info: "Un des pays les plus avancés au monde en matière de services numériques." },
  { rang: 68, pays: "République dominicaine", superficie: "48 671 km²", region: "Caraïbes", info: "Partage l'île d'Hispaniola avec Haïti." },
  { rang: 69, pays: "Slovaquie", superficie: "49 035 km²", region: "Europe", info: "Le pays possédant le plus grand nombre de châteaux par habitant." },
  { rang: 70, pays: "Costa Rica", superficie: "51 100 km²", region: "Amérique centrale", info: "A aboli son armée de façon permanente en 1948." }
];

  return NextResponse.json(data);
}
