import { NextResponse } from 'next/server';

export async function GET() {
  const data = [
    { rang: 1, pays: "Vatican", superficie: "0,44 km²", region: "Europe (Italie)", info: "État enclavé dans la ville de Rome." },
    { rang: 2, pays: "Monaco", superficie: "2,02 km²", region: "Europe (France)", info: "Le pays le plus densément peuplé au monde." },
    { rang: 3, pays: "Nauru", superficie: "21 km²", region: "Océanie", info: "La plus petite république et nation insulaire." },
    { rang: 4, pays: "Tuvalu", superficie: "26 km²", region: "Océanie", info: "Menacé par la montée des eaux du Pacifique." },
    { rang: 5, pays: "Saint-Marin", superficie: "61 km²", region: "Europe (Italie)", info: "La plus ancienne république du monde." },
    { rang: 6, pays: "Liechtenstein", superficie: "160 km²", region: "Europe", info: "Situé dans les Alpes entre la Suisse et l'Autriche." },
    { rang: 7, pays: "Îles Marshall", superficie: "181 km²", region: "Océanie", info: "Un archipel de plus de 1 000 îles et îlots." },
    { rang: 8, pays: "Saint-Kitts-et-Nevis", superficie: "261 km²", region: "Caraïbes", info: "Le plus petit pays des Amériques." },
    { rang: 9, pays: "Maldives", superficie: "300 km²", region: "Asie (Océan Indien)", info: "Le plus petit pays d'Asie." },
    { rang: 10, pays: "Malte", superficie: "316 km²", region: "Europe", info: "Un point stratégique au centre de la Méditerranée." },
    // ... Données suivantes simplifiées pour la structure
    { rang: 11, pays: "Saint-Vincent-et-les-Grenadines", superficie: "389 km²", region: "Caraïbes" },
    { rang: 12, pays: "Barbade", superficie: "430 km²", region: "Caraïbes" },
    { rang: 13, pays: "Antigua-et-Barbuda", superficie: "442 km²", region: "Caraïbes" },
    { rang: 14, pays: "Seychelles", superficie: "452 km²", region: "Afrique (Océan Indien)" },
    { rang: 15, pays: "Palaos", superficie: "459 km²", region: "Océanie" },
    { rang: 16, pays: "Andorre", superficie: "468 km²", region: "Europe (Pyrénées)" },
    { rang: 17, pays: "Sainte-Lucie", superficie: "616 km²", region: "Caraïbes" },
    { rang: 18, pays: "États fédérés de Micronésie", superficie: "702 km²", region: "Océanie" },
    { rang: 19, pays: "Singapour", superficie: "719 km²", region: "Asie" },
    { rang: 20, pays: "Tonga", superficie: "747 km²", region: "Océanie" },
    { rang: 21, pays: "Dominique", superficie: "751 km²", region: "Caraïbes" },
    { rang: 22, pays: "Bahreïn", superficie: "765 km²", region: "Moyen-Orient" },
    { rang: 23, pays: "Kiribati", superficie: "811 km²", region: "Océanie" },
    { rang: 24, pays: "Sao Tomé-et-Principe", superficie: "964 km²", region: "Afrique (Golfe de Guinée)" },
    { rang: 25, pays: "Comores", superficie: "1 862 km²", region: "Afrique (Océan Indien)" },
    { rang: 26, pays: "Maurice", superficie: "2 040 km²", region: "Afrique (Océan Indien)" },
    { rang: 27, pays: "Luxembourg", superficie: "2 586 km²", region: "Europe" },
    { rang: 28, pays: "Samoa", superficie: "2 831 km²", region: "Océanie" },
    { rang: 29, pays: "Cap-Vert", superficie: "4 033 km²", region: "Afrique (Atlantique)" },
    { rang: 30, pays: "Trinité-et-Tobago", superficie: "5 128 km²", region: "Caraïbes" },
    { rang: 31, pays: "Trinité-et-Tobago", superficie: "5 130 km²", region: "Caraïbes" },
    { rang: 32, pays: "Brunéi", superficie: "5 765 km²", region: "Asie (Bornéo)" },
    { rang: 33, pays: "Palestine", superficie: "6 020 km²", region: "Moyen-Orient" },
    { rang: 34, pays: "Chypre", superficie: "9 251 km²", region: "Europe / Asie" },
    { rang: 35, pays: "Liban", superficie: "10 452 km²", region: "Moyen-Orient" },
    { rang: 36, pays: "Kosovo", superficie: "10 887 km²", region: "Europe (Balkans)" },
    { rang: 37, pays: "Jamaïque", superficie: "10 991 km²", region: "Caraïbes" },
    { rang: 38, pays: "Gambie", superficie: "11 295 km²", region: "Afrique" },
    { rang: 39, pays: "Qatar", superficie: "11 586 km²", region: "Moyen-Orient" },
    { rang: 40, pays: "Vanuatu", superficie: "12 189 km²", region: "Océanie" },
    { rang: 41, pays: "Monténégro", superficie: "13 812 km²", region: "Europe (Balkans)" },
    { rang: 42, pays: "Bahamas", superficie: "13 878 km²", region: "Caraïbes" },
    { rang: 43, pays: "Timor oriental", superficie: "14 874 km²", region: "Asie du Sud-Est" },
    { rang: 44, pays: "Eswatini", superficie: "17 364 km²", region: "Afrique" },
    { rang: 45, pays: "Koweït", superficie: "17 818 km²", region: "Moyen-Orient" },
    { rang: 46, pays: "Fidji", superficie: "18 274 km²", region: "Océanie" },
    { rang: 47, pays: "Slovénie", superficie: "20 273 km²", region: "Europe" },
    { rang: 48, pays: "Israël", superficie: "20 770 km²", region: "Moyen-Orient" },
    { rang: 49, pays: "Salvador", superficie: "21 041 km²", region: "Amérique centrale" },
    { rang: 50, pays: "Belize", superficie: "22 966 km²", region: "Amérique centrale" },
    { rang: 51, pays: "Djibouti", superficie: "23 200 km²", region: "Afrique" },
    { rang: 52, pays: "Macédoine du Nord", superficie: "25 713 km²", region: "Europe (Balkans)" },
    { rang: 53, pays: "Rwanda", superficie: "26 338 km²", region: "Afrique" },
    { rang: 54, pays: "Haïti", superficie: "27 750 km²", region: "Caraïbes" },
    { rang: 55, pays: "Burundi", superficie: "27 834 km²", region: "Afrique" },
    { rang: 56, pays: "Guinée équatoriale", superficie: "28 051 km²", region: "Afrique" },
    { rang: 57, pays: "Albanie", superficie: "28 748 km²", region: "Europe (Balkans)" },
    { rang: 58, pays: "Îles Salomon", superficie: "28 896 km²", region: "Océanie" },
    { rang: 59, pays: "Arménie", superficie: "29 743 km²", region: "Asie (Caucase)" },
    { rang: 60, pays: "Lesotho", superficie: "30 355 km²", region: "Afrique" },
    { rang: 61, pays: "Belgique", superficie: "30 528 km²", region: "Europe" },
    { rang: 62, pays: "Moldavie", superficie: "33 851 km²", region: "Europe" },
    { rang: 63, pays: "Guinée-Bissau", superficie: "36 125 km²", region: "Afrique" },
    { rang: 64, pays: "Bhoutan", superficie: "38 394 km²", region: "Asie (Himalaya)" },
    { rang: 65, pays: "Suisse", superficie: "41 285 km²", region: "Europe" },
    { rang: 66, pays: "Pays-Bas", superficie: "41 543 km²", region: "Europe" },
    { rang: 67, pays: "Danemark", superficie: "43 094 km²", region: "Europe" },
    { rang: 68, pays: "Estonie", superficie: "45 227 km²", region: "Europe (Baltique)" },
    { rang: 69, pays: "République dominicaine", superficie: "48 671 km²", region: "Caraïbes" },
    { rang: 70, pays: "Slovaquie", superficie: "49 035 km²", region: "Europe" },
  ];

  return NextResponse.json(data);
}
