// src/app/api/pyreneesorientales/route.ts
import { NextResponse } from 'next/server';

interface SitePyreneesOrientales {
  id: number;
  commune: string;
  description: string;
  niveau: number;
  categorie: 'incontournable' | 'remarquable' | 'suggéré';
  lat: number;
  lng: number;
}

const pyreneesOrientalesSites: SitePyreneesOrientales[] = [
  { id: 1, commune: "Amélie-les-Bains-Palalda", description: "Le mondony; le tech", niveau: 2, categorie: "remarquable", lat: 42.550, lng: 2.521 },
  { id: 2, commune: "Angoustrine-Villeneuve-des-Escaldes", description: "La tet; puig carlit; vallée d'angoustrine", niveau: 3, categorie: "suggéré", lat: 42.536, lng: 1.981 },
  { id: 3, commune: "Argelès-sur-Mer", description: "Parc valmy", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
  { id: 4, commune: "Argelès-sur-Mer", description: "Site naturel protégé du racou", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
  { id: 5, commune: "Argelès-sur-Mer", description: "Parc naturel marin du golfe du lion", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
  { id: 6, commune: "Argelès-sur-Mer", description: "Réserve naturelle nationale du mas larrieu", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
  { id: 7, commune: "Argelès-sur-Mer", description: "Réserve naturelle nationale de la forêt de la massane", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
  { id: 8, commune: "Argelès-sur-Mer", description: "Forêt domaniale des albères", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
  { id: 9, commune: "Banyuls-sur-Mer", description: "Biodiversarium : jardin méditerranéen du mas de la serre", niveau: 1, categorie: "incontournable", lat: 42.485, lng: 3.123 },
  { id: 10, commune: "Banyuls-sur-Mer", description: "Réserve naturelle marine cerbère - banyuls", niveau: 1, categorie: "incontournable", lat: 42.485, lng: 3.123 },
  { id: 11, commune: "Le Boulou", description: "Jardin du prieuré de serrabona", niveau: 2, categorie: "suggéré", lat: 42.614, lng: 2.597 },
  { id: 12, commune: "Cabestany", description: "Cité en lien avec une référence d'image (csrvilledecabestany)", niveau: 3, categorie: "suggéré", lat: 42.660, lng: 2.824 },
  { id: 13, commune: "Canet-en-Roussillon", description: "Etang de canet - saint nazaire", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 3.013 },
  { id: 14, commune: "Cerbère", description: "Réserve naturelle marine de cerbère-banyuls", niveau: 1, categorie: "incontournable", lat: 42.467, lng: 3.096 },
  { id: 15, commune: "Collioure", description: "Jardin saint vincent", niveau: 1, categorie: "incontournable", lat: 42.551, lng: 3.083 },
  { id: 16, commune: "Conat", description: "Réserve naturelle de conat", niveau: 3, categorie: "suggéré", lat: 42.584, lng: 2.501 },
  { id: 17, commune: "Elne", description: "Patrimoine religieux (cloîtres et abbayes). Contient le cloître d’elne (art gothique), près de la cathédrale", niveau: 1, categorie: "incontournable", lat: 42.616, lng: 3.037 },
  { id: 18, commune: "Err", description: "Pic du puigmal", niveau: 3, categorie: "suggéré", lat: 42.588, lng: 1.947 },
  { id: 19, commune: "Espira-de-l'Agly", description: "Le massif forestier de montpins", niveau: 2, categorie: "remarquable", lat: 42.641, lng: 2.804 },
  { id: 20, commune: "Eyne", description: "Réserve naturelle d'Eyne", niveau: 3, categorie: "suggéré", lat: 42.704, lng: 1.860 },
  { id: 21, commune: "Formiguères", description: "Pics péric", niveau: 3, categorie: "suggéré", lat: 42.493, lng: 2.146 },
  { id: 22, commune: "La Raho", description: "Site du lac de la raho", niveau: 3, categorie: "suggéré", lat: 42.713, lng: 2.906 },
  { id: 23, commune: "Laroque-des-Albères", description: "Pic neulos", niveau: 2, categorie: "remarquable", lat: 42.552, lng: 3.007 },
  { id: 24, commune: "Les Angles", description: "Lac de balcere", niveau: 2, categorie: "remarquable", lat: 42.545, lng: 2.082 },
  { id: 25, commune: "Le Barcarès", description: "Etang salses - leucate; site des dosses; la pinede", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 3.013 },
  { id: 26, commune: "Le Perthus", description: "Contient le fort bellegarde, vigile attentif de la vallée", niveau: 1, categorie: "incontournable", lat: 42.515, lng: 2.900 },
  { id: 27, commune: "Le Soler", description: "Jardin exotique du soler", niveau: 3, categorie: "suggéré", lat: 42.660, lng: 2.933 },
  { id: 28, commune: "Le Vivier", description: "Hêtre de le vivier", niveau: 1, categorie: "incontournable", lat: 42.610, lng: 2.790 },
  { id: 29, commune: "Llo", description: "Gorges du segre", niveau: 1, categorie: "incontournable", lat: 42.697, lng: 1.886 },
  { id: 30, commune: "Mont-Louis", description: "Cité fortifiée (citadelle), classée au patrimoine de l'unesco. Contient le puits des forçats", niveau: 1, categorie: "incontournable", lat: 42.682, lng: 1.865 },
  { id: 31, commune: "Nohèdes", description: "Réserve naturelle de nohedes", niveau: 1, categorie: "incontournable", lat: 42.539, lng: 2.414 },
  { id: 32, commune: "Olette", description: "Parc naturel régional des pyrénées catalanes", niveau: 2, categorie: "remarquable", lat: 42.497, lng: 2.309 },
  { id: 33, commune: "Perpignan", description: "Contient le campo santo; square bir hakeim; villa des tilleuls jardin puig; parc sant vicens; serrat d'en vaquer", niveau: 1, categorie: "incontournable", lat: 42.6887, lng: 2.8948 },
  { id: 34, commune: "Pézilla-la-Rivière", description: "Arboretum de st martin de jussens", niveau: 1, categorie: "incontournable", lat: 42.620, lng: 2.765 },
  { id: 35, commune: "Port-Vendres", description: "Site classé de l'anse de paulilles", niveau: 1, categorie: "incontournable", lat: 42.525, lng: 3.089 },
  { id: 36, commune: "Porté-Puymorens", description: "Etang de font vive; lac du lanoux; lac du passet", niveau: 3, categorie: "suggéré", lat: 42.504, lng: 1.780 },
  { id: 37, commune: "Prades", description: "Canigo grand site; platane de prades", niveau: 1, categorie: "incontournable", lat: 42.540, lng: 2.558 },
  { id: 38, commune: "Prats-de-Mollo", description: "Fort lagarde", niveau: 2, categorie: "remarquable", lat: 42.465, lng: 2.506 },
  { id: 39, commune: "Prats-de-Mollo-La Preste", description: "La baleta; pic de costabonne; réserve naturelle de prats de mollo la preste", niveau: 1, categorie: "incontournable", lat: 42.466, lng: 2.506 },
  { id: 40, commune: "Saint-Cyprien", description: "Parc de la prade; le jardin des capellans", niveau: 2, categorie: "remarquable", lat: 42.619, lng: 3.006 },
  { id: 41, commune: "Saint-Féliu-d'Avall", description: "Le lac des bouzigues", niveau: 3, categorie: "suggéré", lat: 42.652, lng: 2.755 },
  { id: 42, commune: "Saint-Jean-Pla-de-Corts", description: "Lac de saint jean pla de corts", niveau: 2, categorie: "remarquable", lat: 42.607, lng: 2.815 },
  { id: 43, commune: "Saint-Paul-de-Fenouillet", description: "Clue de la fou; gorges de galamus; l'agly", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 2.539 },
  { id: 44, commune: "Targassonne", description: "Le chaos de targassonne", niveau: 2, categorie: "remarquable", lat: 42.543, lng: 1.869 },
  { id: 45, commune: "Thuès-Entre-Valls", description: "Gorges de la caranca", niveau: 3, categorie: "suggéré", lat: 42.613, lng: 2.468 },
  { id: 46, commune: "Torreilles", description: "Le bourdigu", niveau: 2, categorie: "remarquable", lat: 42.696, lng: 3.010 },
  { id: 47, commune: "Toulouges", description: "Parc de clairfont", niveau: 3, categorie: "suggéré", lat: 42.684, lng: 2.983 },
  { id: 48, commune: "Valcebollère", description: "Vallée de valcebollère", niveau: 3, categorie: "suggéré", lat: 42.664, lng: 1.840 },
  { id: 49, commune: "Valmanya", description: "Forêt du canigou", niveau: 1, categorie: "incontournable", lat: 42.644, lng: 2.345 },
  { id: 50, commune: "Vinça", description: "Lac des escoumes de vinça; plan d'eau du barrage de vinça", niveau: 2, categorie: "remarquable", lat: 42.592, lng: 2.541 },
  { id: 51, commune: "Villeneuve-de-la-Raho", description: "Site du lac de la raho", niveau: 3, categorie: "suggéré", lat: 42.713, lng: 2.906 },
  { id: 52, commune: "Py", description: "Réserve naturelle de py", niveau: 3, categorie: "suggéré", lat: 42.597, lng: 2.422 },
  { id: 53, commune: "Cassagnes", description: "Le pic aubeil; site du plan d'eau sur l'agly", niveau: 2, categorie: "remarquable", lat: 42.575, lng: 2.561 },
  { id: 54, commune: "Py", description: "Réserve naturelle régionale de nyer", niveau: 1, categorie: "incontournable", lat: 42.532, lng: 2.260 },
  { id: 55, commune: "Prats-de-Mollo-La Preste", description: "Pic de costabonne", niveau: 1, categorie: "incontournable", lat: 42.466, lng: 2.506 },
  { id: 56, commune: "Vingrau", description: "Le cirque de vingrau", niveau: 2, categorie: "remarquable", lat: 42.641, lng: 2.950 },
  { id: 57, commune: "Porté-Puymorens", description: "Lac du lanoux", niveau: 3, categorie: "suggéré", lat: 42.504, lng: 1.780 },
  { id: 58, commune: "Porté-Puymorens", description: "Lac du passet", niveau: 3, categorie: "suggéré", lat: 42.504, lng: 1.780 },
  { id: 59, commune: "Saint-Paul-de-Fenouillet", description: "Gorges de galamus; clue de la fou", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 2.539 },
  { id: 60, commune: "Opoul", description: "", niveau: 1, categorie: "incontournable", lat: 42.761, lng: 2.740 },
  { id: 61, commune: "Latour-de-France", description: "", niveau: 1, categorie: "incontournable", lat: 42.729, lng: 2.653 },
  { id: 62, commune: "Caramany", description: "", niveau: 1, categorie: "incontournable", lat: 42.707, lng: 2.641 },
  { id: 63, commune: "Mosset", description: "Abbaye Sainte-Marie de Clariana de Jau", niveau: 2, categorie: "remarquable", lat: 42.679, lng: 2.305 },
  { id: 64, commune: "Arboussols", description: "Commune où se situe le Prieuré de Marcevol.", niveau: 1, categorie: "incontournable", lat: 42.657, lng: 2.603 },
  { id: 65, commune: "Eus", description: "", niveau: 2, categorie: "remarquable", lat: 42.598, lng: 2.650 },
  { id: 66, commune: "Molitg-les-Bains", description: "", niveau: 1, categorie: "incontournable", lat: 42.618, lng: 2.565 },
  { id: 67, commune: "Villefranche-de-Conflent", description: "Sites Vauban, Cité fortifiée, classée à l’UNESCO, labellisée Plus beaux Villages de France. Contient la Grotte fortifiée Cova Bastera et le souterrain vers le Fort Libéria.", niveau: 1, categorie: "incontournable", lat: 42.609, lng: 2.425 },
  { id: 68, commune: "Jujols", description: "", niveau: 2, categorie: "remarquable", lat: 42.621, lng: 2.400 },
  { id: 69, commune: "Joch", description: "", niveau: 3, categorie: "suggéré", lat: 42.639, lng: 2.442 },
  { id: 70, commune: "Baillestavy", description: "", niveau: 3, categorie: "suggéré", lat: 42.618, lng: 2.432 },
  { id: 71, commune: "Saint-Michel-de-Llotes", description: "", niveau: 3, categorie: "suggéré", lat: 42.608, lng: 2.481 },
  { id: 72, commune: "Castelnou", description: "", niveau: 1, categorie: "incontournable", lat: 42.599, lng: 2.618 },
  { id: 73, commune: "Sainte-Colombe", description: "", niveau: 2, categorie: "remarquable", lat: 42.595, lng: 2.631 },
  { id: 74, commune: "Perpignan", description: "Contient le Campo Santo (le plus vaste et le plus ancien cloître-cimetière de France).", niveau: 1, categorie: "incontournable", lat: 42.6887, lng: 2.8948 },
  { id: 75, commune: "Collioure", description: "", niveau: 1, categorie: "incontournable", lat: 42.551, lng: 3.083 },
  { id: 76, commune: "Vernet-les-Bains", description: "", niveau: 1, categorie: "incontournable", lat: 42.554, lng: 2.560 },
  { id: 77, commune: "Saint-Marsal", description: "", niveau: 3, categorie: "suggéré", lat: 42.590, lng: 2.580 },
  { id: 78, commune: "Palalda", description: "", niveau: 2, categorie: "remarquable", lat: 42.559, lng: 2.571 },
  { id: 79, commune: "Céret", description: "", niveau: 1, categorie: "incontournable", lat: 42.556, lng: 2.715 },
  { id: 80, commune: "Corsavy", description: "", niveau: 2, categorie: "remarquable", lat: 42.550, lng: 2.512 },
  { id: 81, commune: "Serralongue", description: "", niveau: 3, categorie: "suggéré", lat: 42.530, lng: 2.477 },
  { id: 82, commune: "Coustouges", description: "", niveau: 3, categorie: "suggéré", lat: 42.468, lng: 2.449 },
  { id: 83, commune: "Evol", description: "", niveau: 2, categorie: "remarquable", lat: 42.514, lng: 2.130 },
  { id: 84, commune: "Nyer", description: "Réserve naturelle régionale de Nyer", niveau: 1, categorie: "incontournable", lat: 42.532, lng: 2.260 },
  { id: 85, commune: "Mantet", description: "", niveau: 3, categorie: "suggéré", lat: 42.466, lng: 2.357 },
  { id: 86, commune: "Dorres", description: "", niveau: 3, categorie: "suggéré", lat: 42.684, lng: 1.857 },
  { id: 87, commune: "Sainte-Marie-la-Mer", description: "", niveau: 1, categorie: "incontournable", lat: 42.695, lng: 3.003 },
  { id: 88, commune: "Saint-Nazaire", description: "", niveau: 2, categorie: "remarquable", lat: 42.698, lng: 3.021 },
  { id: 89, commune: "Sainte-Marie", description: "", niveau: 1, categorie: "incontournable", lat: 42.696, lng: 3.004 },
  { id: 90, commune: "Arles-sur-Tech", description: "Abbaye Sainte-Marie et Cloître", niveau: 1, categorie: "incontournable", lat: 42.543, lng: 2.597 },
  { id: 91, commune: "Saint-Génis-des-Fontaines", description: "Abbaye de Saint-Génis-des-Fontaines", niveau: 1, categorie: "incontournable", lat: 42.602, lng: 2.936 },
  { id: 92, commune: "Casteil", description: "Abbaye Saint-Martin du Canigou", niveau: 1, categorie: "incontournable", lat: 42.622, lng: 2.526 },
  { id: 93, commune: "Codalet", description: "Abbaye Saint-Michel de Cuxa", niveau: 1, categorie: "incontournable", lat: 42.622, lng: 2.549 },
  { id: 94, commune: "Boule-d’Amont", description: "Prieuré de Serrabona", niveau: 1, categorie: "incontournable", lat: 42.614, lng: 2.597 },
  { id: 95, commune: "Marcevol", description: "Prieuré de Marcevol", niveau: 1, categorie: "incontournable", lat: 42.677, lng: 2.526 },
  { id: 96, commune: "Ponteilla", description: "Le Jardin Exotique", niveau: 3, categorie: "suggéré", lat: 42.590, lng: 2.650 },
  { id: 97, commune: "Perpignan", description: "Villa des Tilleuls Jardin Puig", niveau: 1, categorie: "incontournable", lat: 42.6887, lng: 2.8948 },
  { id: 98, commune: "Perpignan", description: "Parc Sant Vicens", niveau: 1, categorie: "incontournable", lat: 42.6887, lng: 2.8948 },
  { id: 99, commune: "Perpignan", description: "Serrat d'en Vaquer", niveau: 1, categorie: "incontournable", lat: 42.6887, lng: 2.8948 },
  { id: 100, commune: "Saint-Paul-de-Fenouillet", description: "L'Agly", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 2.539 },
  { id: 101, commune: "Salses", description: "Forteresse de Salses", niveau: 1, categorie: "incontournable", lat: 42.900, lng: 2.900 },
  { id: 102, commune: "Le Barcarès", description: "La Pinède", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 3.013 },
  { id: 103, commune: "Fontrabiouse", description: "La Vallée du Gable et grotte", niveau: 1, categorie: "incontournable", lat: 42.470, lng: 2.200 },
  { id: 104, commune: "Porté-Puymorens", description: "Lac du Lanoux", niveau: 3, categorie: "suggéré", lat: 42.504, lng: 1.780 },
  { id: 105, commune: "Porté-Puymorens", description: "Lac du Passet", niveau: 3, categorie: "suggéré", lat: 42.504, lng: 1.780 },
  { id: 106, commune: "Vingrau", description: "Vingrau", niveau: 2, categorie: "remarquable", lat: 42.641, lng: 2.950 },
  { id: 107, commune: "Prats-de-Mollo-la-Preste", description: "Réserve naturelle de Prats de Mollo la Preste", niveau: 1, categorie: "incontournable", lat: 42.466, lng: 2.506 },
  { id: 108, commune: "Cassagnes", description: "Lac du plan d'eau sur l'Agly", niveau: 1, categorie: "incontournable", lat: 42.575, lng: 2.561 },
  { id: 109, commune: "Cassagnes", description: "Le Pic Aubeil", niveau: 2, categorie: "remarquable", lat: 42.575, lng: 2.561 },
  { id: 110, commune: "Palau-del-Vidre", description: "Plan d'eau de Saint-Marti", niveau: 3, categorie: "suggéré", lat: 42.620, lng: 2.800 },
  { id: 111, commune: "Jujols", description: "Réserve naturelle de Jujols", niveau: 2, categorie: "suggéré", lat: 42.550, lng: 1.900 },
  { id: 112, commune: "Mantet", description: "Réserve naturelle de mantet", niveau: 3, categorie: "suggéré", lat: 42.600, lng: 1.950 },
  { id: 113, commune: "Font-Romeu-Odeillo-Via", description: "site classé des Bouillousses", niveau: 1, categorie: "incontournable", lat: 42.500, lng: 1.900 },
  { id: 114, commune: "Formiguères", description: "site classé des Camporells", niveau: 3, categorie: "suggéré", lat: 42.493, lng: 2.146 },
  { id: 115, commune: "Le Barcarès", description: "Site des Dosses", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 3.013 },
  { id: 116, commune: "Ille-sur-Têt", description: "Site des Orgues", niveau: 1, categorie: "incontournable", lat: 42.700, lng: 2.800 },
  { id: 117, commune: "Perpignan", description: "Palais des Rois de Majorque", niveau: 1, categorie: "incontournable", lat: 42.6887, lng: 2.8948 },
  { id: 118, commune: "Tautavel", description: "Musée de Préhistoire de Tautavel, un des plus grands musées de préhistoire d’Europe.", niveau: 1, categorie: "incontournable", lat: 42.738, lng: 2.843 },
  { id: 119, commune: "Rivesaltes", description: "Mémorial du Camp de Rivesaltes, site mémoriel, traces d’un lourd passé.", niveau: 1, categorie: "incontournable", lat: 42.760, lng: 2.878 },
];

export async function GET() {
  return NextResponse.json(pyreneesOrientalesSites);
}
