// src/app/api/pyreneesorientales/route.ts
import { NextResponse } from 'next/server';

interface SitePyreneesOrientales {
  id: number;
  commune: string;
  description: string;
  niveau: number;
  categorie: 'incontournable' | 'remarquable' | 'suggéré';
  lat: number;
  lng: number;
}

const pyreneesOrientalesSites: SitePyreneesOrientales[] = [
{ id: 1, commune: "Amélie-les-Bains-Palalda", description: "Le Mondony et le Tech; Chapelle du Rosaire; Église Sainte-Marie de Montalba; Église Saint-Quentin; Musée Al Casal de Palalda - CIAP; Thermes romains", niveau: 1, categorie: "incontournable", lat: 42.550, lng: 2.521 },
{ id: 2, commune: "Angoustrine-Villeneuve-des-Escaldes", description: "La Têt, Puig Carlit et Vallée d'Angoustrine; Église Saint-André d’Angoustrine", niveau: 3, categorie: "suggéré", lat: 42.536, lng: 1.981 },
{ id: 3, commune: "Ansignan", description: "Aqueduc romain", niveau: 1, categorie: "incontournable", lat: 42.761, lng: 2.479 },
{ id: 4, commune: "Arboussols", description: "Prieuré de Marcevol / Fondation du Prieuré", niveau: 1, categorie: "incontournable", lat: 42.657, lng: 2.603 },
{ id: 5, commune: "Argelès-sur-Mer", description: "Parc municipal de Valmy; Site naturel protégé du Racou; Parc naturel marin du Golfe du Lion; Réserve naturelle nationale du Mas Larrieu; Réserve naturelle nationale de la forêt de la Massane; Forêt domaniale des Albères; Casa de l’Albera – Maison du Patrimoine; Chapelle Saint-Laurent du Mont; Les Dolmens; Mémorial du Camp d’Argelès-sur-Mer", niveau: 1, categorie: "incontournable", lat: 42.547, lng: 3.022 },
{ id: 6, commune: "Arles-sur-Tech", description: "Abbaye Sainte-Marie d'Arles-sur-Tech et son Cloître", niveau: 1, categorie: "incontournable", lat: 42.456, lng: 2.634 },
{ id: 7, commune: "Baillas", description: "Église de la Nativité de Notre-Dame", niveau: 2, categorie: "remarquable", lat: 42.750, lng: 2.810 },
{ id: 8, commune: "Baillestavy", description: "Village et site naturel", niveau: 3, categorie: "suggéré", lat: 42.618, lng: 2.432 },
{ id: 9, commune: "Banyuls-sur-Mer", description: "Biodiversarium – Jardin Méditerranéen du Mas de la Serre; Réserve naturelle marine de Cerbère-Banyuls; Musée Aristide Maillol", niveau: 1, categorie: "incontournable", lat: 42.485, lng: 3.123 },
{ id: 10, commune: "Bélesta", description: "Château Musée de Bélesta", niveau: 1, categorie: "incontournable", lat: 42.716, lng: 2.610 },
{ id: 11, commune: "Boule-d’Amont", description: "Prieuré de Serrabone", niveau: 1, categorie: "incontournable", lat: 42.614, lng: 2.597 },
{ id: 12, commune: "Brouilla", description: "Église Sainte-Marie", niveau: 3, categorie: "suggéré", lat: 42.566, lng: 2.903 },
{ id: 13, commune: "Cabestany", description: "Centre de Sculpture Romane", niveau: 3, categorie: "suggéré", lat: 42.660, lng: 2.824 },
{ id: 14, commune: "Canet-en-Roussillon", description: "Arboretum Mas Roussillon; Étang de Canet - Saint-Nazaire", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 3.013 },
{ id: 15, commune: "Caramany", description: "Village et site du lac", niveau: 1, categorie: "incontournable", lat: 42.707, lng: 2.641 },
{ id: 16, commune: "Cassagnes", description: "Le Pic Aubeil; Site du plan d'eau sur l'Agly", niveau: 1, categorie: "incontournable", lat: 42.575, lng: 2.561 },
{ id: 17, commune: "Casteil", description: "Abbaye de Saint-Martin du Canigou", niveau: 1, categorie: "incontournable", lat: 42.622, lng: 2.526 },
{ id: 18, commune: "Castelnou", description: "Château de Castelnou et village classé", niveau: 1, categorie: "incontournable", lat: 42.599, lng: 2.618 },
{ id: 19, commune: "Catllar", description: "Prieuré Notre-Dame de Riquer", niveau: 2, categorie: "remarquable", lat: 42.634, lng: 2.433 },
{ id: 20, commune: "Caudiès-de-Fenouillèdes", description: "Notre-Dame de Laval", niveau: 1, categorie: "incontournable", lat: 42.814, lng: 2.378 },
{ id: 21, commune: "Cerbère", description: "Hôtel Belvédère du Rayon Vert; Réserve naturelle marine de Cerbère-Banyuls", niveau: 1, categorie: "incontournable", lat: 42.467, lng: 3.096 },
{ id: 22, commune: "Céret", description: "Musée d’Art Moderne de Céret; Musée de la Musique – CIMP; Le Pont du Diable; La Fontaine des 9 Jets; Église Saint-Pierre", niveau: 1, categorie: "incontournable", lat: 42.556, lng: 2.715 },
{ id: 23, commune: "Codalet", description: "Abbaye de Saint-Michel de Cuxa", niveau: 1, categorie: "incontournable", lat: 42.622, lng: 2.549 },
{ id: 24, commune: "Collioure", description: "Château Royal de Collioure; Église Notre-Dame des Anges; Fort Saint-Elme; Forts Rond et Carré; Musée d’Art Moderne; Jardin Saint-Vincent et Vitrine sur le Fauvisme", niveau: 1, categorie: "incontournable", lat: 42.551, lng: 3.083 },
{ id: 25, commune: "Conat", description: "Réserve naturelle de Conat", niveau: 3, categorie: "suggéré", lat: 42.584, lng: 2.501 },
{ id: 26, commune: "Corneilla-de-Conflent", description: "Église Sainte-Marie", niveau: 2, categorie: "remarquable", lat: 42.566, lng: 2.385 },
{ id: 27, commune: "Corsavy", description: "Tour de Batère et Tour de Corsavy; Village et site de montagne", niveau: 2, categorie: "remarquable", lat: 42.550, lng: 2.512 },
{ id: 28, commune: "Coustouges", description: "Église Sainte-Marie et village", niveau: 3, categorie: "suggéré", lat: 42.468, lng: 2.449 },
{ id: 29, commune: "Dorres", description: "Village et Bains romains", niveau: 3, categorie: "suggéré", lat: 42.684, lng: 1.857 },
{ id: 30, commune: "Elne", description: "Cathédrale Sainte-Eulalie et Sainte-Julie et son Cloître; Maternité Suisse d’Elne; Musée de Peinture et d’Archéologie Étienne Terrus", niveau: 1, categorie: "incontournable", lat: 42.616, lng: 3.037 },
{ id: 31, commune: "Err", description: "Pic du Puigmal", niveau: 3, categorie: "suggéré", lat: 42.440, lng: 2.032 },
{ id: 32, commune: "Escaro", description: "Musée de la Mine", niveau: 3, categorie: "suggéré", lat: 42.538, lng: 2.313 },
{ id: 33, commune: "Espira-de-Conflent", description: "Église Sainte-Marie", niveau: 3, categorie: "suggéré", lat: 42.618, lng: 2.499 },
{ id: 34, commune: "Espira-de-l'Agly", description: "Église Sainte-Marie d’Espira-de-l’Agly; Massif forestier de Montpins", niveau: 2, categorie: "remarquable", lat: 42.778, lng: 2.836 },
{ id: 35, commune: "Estavar", description: "Église Saint-Julien d’Estavar", niveau: 3, categorie: "suggéré", lat: 42.470, lng: 1.997 },
{ id: 36, commune: "Eus", description: "Village perché et Chapelle Saint-Vincent", niveau: 2, categorie: "remarquable", lat: 42.643, lng: 2.457 },
{ id: 37, commune: "Evol", description: "Hameau classé et Église Saint-André", niveau: 2, categorie: "remarquable", lat: 42.611, lng: 2.253 },
{ id: 38, commune: "Eyne", description: "Réserve naturelle d'Eyne et Maison de la Vallée", niveau: 3, categorie: "suggéré", lat: 42.473, lng: 2.081 },
{ id: 39, commune: "Fenouillet", description: "Château Saint-Pierre de Fenouillet", niveau: 1, categorie: "incontournable", lat: 42.793, lng: 2.380 },
{ id: 40, commune: "Fillols", description: "Église Saint-Félix", niveau: 3, categorie: "suggéré", lat: 42.562, lng: 2.411 },
{ id: 41, commune: "Font-Romeu-Odeillo-Via", description: "Site classé des Bouillousses; Église Saint-Martin", niveau: 1, categorie: "incontournable", lat: 42.497, lng: 2.035 },
{ id: 42, commune: "Fontrabiouse", description: "Grotte et Vallée du Galbe", niveau: 1, categorie: "incontournable", lat: 42.636, lng: 2.096 },
{ id: 43, commune: "Formiguères", description: "Site classé des Camporells et Pics Péric; Église Sainte-Nativité Notre-Dame", niveau: 3, categorie: "suggéré", lat: 42.614, lng: 2.102 },
{ id: 44, commune: "Fuilla", description: "Église Sainte-Eulalie de Fuilla", niveau: 2, categorie: "remarquable", lat: 42.561, lng: 2.361 },
{ id: 45, commune: "Ille-sur-Têt", description: "Site des Orgues; Hospice d’Ille et Patrimoine religieux (Églises St-Étienne, de la Rodona et des Carmes)", niveau: 1, categorie: "incontournable", lat: 42.671, lng: 2.620 },
{ id: 46, commune: "Joch", description: "Village et site", niveau: 3, categorie: "suggéré", lat: 42.617, lng: 2.525 },
{ id: 47, commune: "Jujols", description: "Village et Réserve naturelle de Jujols", niveau: 2, categorie: "remarquable", lat: 42.568, lng: 2.296 },
{ id: 48, commune: "Villeneuve-de-la-Raho", description: "Site du Lac de la Raho", niveau: 3, categorie: "suggéré", lat: 42.637, lng: 2.915 },
{ id: 49, commune: "Laroque-des-Albères", description: "Pic Neulos", niveau: 2, categorie: "remarquable", lat: 42.523, lng: 2.934 },
{ id: 50, commune: "Latour-de-France", description: "Village et site", niveau: 1, categorie: "incontournable", lat: 42.768, lng: 2.653 },
{ id: 51, commune: "Le Barcarès", description: "Paquebot Le Lydia; Étang Salses-Leucate, Site des Dosses et la Pinède", niveau: 1, categorie: "incontournable", lat: 42.787, lng: 3.037 },
{ id: 52, commune: "Le Boulou", description: "Église Sainte-Marie; Maison de l’Eau et de la Méditerranée; Jardin du Prieuré de Serrabona", niveau: 2, categorie: "remarquable", lat: 42.524, lng: 2.834 },
{ id: 53, commune: "Le Perthus", description: "Fort de Bellegarde et Site archéologique de Panissars", niveau: 1, categorie: "incontournable", lat: 42.464, lng: 2.863 },
{ id: 54, commune: "Le Soler", description: "Jardin exotique du Soler", niveau: 3, categorie: "suggéré", lat: 42.683, lng: 2.793 },
{ id: 55, commune: "Le Vivier", description: "Hêtre de l'Abattis", niveau: 1, categorie: "incontournable", lat: 42.768, lng: 2.453 },
{ id: 56, commune: "Les Angles", description: "Église paroissiale Saint-Michel; Vestiges de l'église Sainte-Marie de Vallsera; Vestiges de l'église Saint-Sauveur; Vestiges du château médiéval; Parc animalier; Station de sports d'hiver; Lac et refuge des Bouillouses", niveau: 2, categorie: "remarquable", lat: 42.577, lng: 2.075 },
{ id: 57, commune: "Llo", description: "Gorges du Sègre", niveau: 1, categorie: "incontournable", lat: 42.453, lng: 2.062 },
{ id: 58, commune: "Mantet", description: "Village et Réserve naturelle de Mantet", niveau: 3, categorie: "suggéré", lat: 42.479, lng: 2.307 },
{ id: 59, commune: "Marcevol / Arboussols", description: "Prieuré de Marcevol", niveau: 1, categorie: "incontournable", lat: 42.664, lng: 2.502 },
{ id: 60, commune: "Maureillas-las-Illas", description: "Chapelle St-Martin-de-Fenollar, Église St-Michel de Riunoguès et Musée du Liège", niveau: 3, categorie: "suggéré", lat: 42.491, lng: 2.810 },
{ id: 61, commune: "Millas", description: "Le Moulin Saint-Pierre", niveau: 2, categorie: "remarquable", lat: 42.692, lng: 2.697 },
{ id: 62, commune: "Molitg-les-Bains", description: "Village et Thermes", niveau: 1, categorie: "incontournable", lat: 42.652, lng: 2.388 },
{ id: 63, commune: "Montauriol", description: "Église Saint-Saturnin", niveau: 3, categorie: "suggéré", lat: 42.575, lng: 2.724 },
{ id: 64, commune: "Montferrer", description: "Église Sainte-Marie de Mollet", niveau: 3, categorie: "suggéré", lat: 42.434, lng: 2.568 },
{ id: 65, commune: "Mont-Louis", description: "Cité fortifiée (UNESCO), Puits des forçats, Four Solaire et Place Forte", niveau: 1, categorie: "incontournable", lat: 42.508, lng: 2.122 },
{ id: 66, commune: "Mosset", description: "Abbaye Sainte-Marie de Clariana de Jau", niveau: 2, categorie: "remarquable", lat: 42.668, lng: 2.348 },
{ id: 67, commune: "Nohèdes", description: "Réserve naturelle de Nohèdes", niveau: 1, categorie: "incontournable", lat: 42.622, lng: 2.288 },
{ id: 68, commune: "Nyer", description: "Réserve naturelle régionale de Nyer et Maison de la Réserve", niveau: 1, categorie: "incontournable", lat: 42.532, lng: 2.275 },
{ id: 69, commune: "Olette", description: "Parc naturel régional des Pyrénées catalanes et Église Saint-André d’Evol", niveau: 2, categorie: "remarquable", lat: 42.555, lng: 2.269 },
{ id: 70, commune: "Opoul-Périllos", description: "Village et Forteresse d'Opoul", niveau: 1, categorie: "incontournable", lat: 42.869, lng: 2.874 },
{ id: 71, commune: "Palalda", description: "Village et Musée Al Casal (CIAP)", niveau: 2, categorie: "remarquable", lat: 42.485, lng: 2.675 },
{ id: 72, commune: "Palau-del-Vidre", description: "Église Ste-Marie de l’Assomption et Plan d’eau de Saint-Marti", niveau: 3, categorie: "suggéré", lat: 42.572, lng: 2.967 },
{ id: 73, commune: "Passa", description: "Prieuré du Monastir del Camp", niveau: 1, categorie: "incontournable", lat: 42.580, lng: 2.812 },
{ id: 74, commune: "Perpignan", description: "Palais des Rois de Majorque, Cathédrale St-Jean-Baptiste, Castillet, Campo Santo, Loge de Mer; Musée d'Art Rigaud, Muséum d'Histoire Naturelle, Musée Puig, Casa Xanxo, Centre des Français d'Algérie, Cémoi; Couvent des Minimes, Église des Dominicains, Ste-Marie-la-Real, St-Jacques, St-Jean-le-Vieux, Chapelle du Tiers-Ordre, Ste-Claire; Serrat d’en Vaquer, Parc Sant Vicens, Villa des Tilleuls, Square Bir Hakeim, Jardin de la Pépinière, Jardin Muchard", niveau: 1, categorie: "incontournable", lat: 42.698, lng: 2.895 },
{ id: 75, commune: "Pézilla-la-Rivière", description: "Arboretum de St-Martin de Jussens", niveau: 1, categorie: "incontournable", lat: 42.694, lng: 2.771 },
{ id: 76, commune: "Planès", description: "Église de Planès", niveau: 3, categorie: "suggéré", lat: 42.491, lng: 2.140 },
{ id: 77, commune: "Ponteilla", description: "Le Jardin Exotique", niveau: 3, categorie: "suggéré", lat: 42.625, lng: 2.814 },
{ id: 78, commune: "Port-Vendres", description: "Site classé de l'Anse de Paulilles, Phare du Cap Béar, Tour Madeloc, Obélisque et Centre Charles Rennie Mackintosh", niveau: 1, categorie: "incontournable", lat: 42.520, lng: 3.106 },
{ id: 79, commune: "Porté-Puymorens", description: "Étang de Font Vive, Lac du Lanoux et Lac du Passet", niveau: 3, categorie: "suggéré", lat: 42.548, lng: 1.821 },
{ id: 80, commune: "Prades", description: "Canigo Grand Site, Église St-Pierre et son Trésor, Espaces Casals et Martin Vives, Manufacture Henri Privat", niveau: 1, categorie: "incontournable", lat: 42.617, lng: 2.423 },
{ id: 81, commune: "Prats-de-Mollo-la-Preste", description: "Ville fortifiée, Fort Lagarde, Réserve naturelle, Pic de Costabonne, Église Stes-Juste-et-Ruffine et La Verneda (CIAP)", niveau: 1, categorie: "incontournable", lat: 42.404, lng: 2.479 },
{ id: 82, commune: "Prunet-et-Belpuig", description: "Chapelle de la Trinité", niveau: 3, categorie: "suggéré", lat: 42.562, lng: 2.624 },
{ id: 83, commune: "Rivesaltes", description: "Mémorial du Camp de Rivesaltes et Musée du Maréchal Joffre", niveau: 1, categorie: "incontournable", lat: 42.771, lng: 2.874 },
{ id: 84, commune: "Sahorre", description: "Église Saint-Étienne de Sahorre", niveau: 3, categorie: "suggéré", lat: 42.532, lng: 2.361 },
{ id: 85, commune: "Saint-André", description: "Église Romane et Maison de l'Art Roman", niveau: 3, categorie: "suggéré", lat: 42.552, lng: 2.973 },
{ id: 86, commune: "Saint-Cyprien", description: "Collections de Saint-Cyprien, Jardin des Plantes des Capellans et Parc de la Prade", niveau: 1, categorie: "incontournable", lat: 42.616, lng: 3.003 },
{ id: 87, commune: "Saint-Féliu-d'Avall", description: "Le lac des Bouzigues", niveau: 3, categorie: "suggéré", lat: 42.681, lng: 2.738 },
{ id: 88, commune: "Saint-Génis-des-Fontaines", description: "Abbaye (Cloître et Église) et Chapelle Sainte-Colombe de Cabanes", niveau: 1, categorie: "incontournable", lat: 42.544, lng: 2.921 },
{ id: 89, commune: "Saint-Jean-Lasseille", description: "Église Saint-Jean l’Évangéliste", niveau: 3, categorie: "suggéré", lat: 42.581, lng: 2.868 },
{ id: 90, commune: "Saint-Jean-Pla-de-Corts", description: "Lac de Saint-Jean-Pla-de-Corts", niveau: 2, categorie: "remarquable", lat: 42.512, lng: 2.792 },
{ id: 91, commune: "Saint-Laurent-de-Cerdans", description: "Maison du Patrimoine (CIAP) et Création Catalane - Toiles du Soleil", niveau: 3, categorie: "suggéré", lat: 42.389, lng: 2.613 },
{ id: 92, commune: "Sainte-Léocadie", description: "Musée de Cerdagne", niveau: 3, categorie: "suggéré", lat: 42.436, lng: 2.006 },
{ id: 93, commune: "Saint-Marsal", description: "Village et site", niveau: 3, categorie: "suggéré", lat: 42.538, lng: 2.621 },
{ id: 94, commune: "Sainte-Marie-la-Mer", description: "Village, site et Église Notre-Dame de l’Assomption", niveau: 1, categorie: "incontournable", lat: 42.724, lng: 3.017 },
{ id: 95, commune: "Saint-Michel-de-Llotes", description: "Village et site", niveau: 3, categorie: "suggéré", lat: 42.648, lng: 2.622 },
{ id: 96, commune: "Saint-Nazaire", description: "Village et site de l'étang", niveau: 2, categorie: "remarquable", lat: 42.667, lng: 3.003 },
{ id: 97, commune: "Saint-Paul-de-Fenouillet", description: "Gorges de Galamus (Ermitage St-Antoine), Clue de la Fou, l'Agly et Le Chapitre", niveau: 1, categorie: "incontournable", lat: 42.812, lng: 2.486 },
{ id: 98, commune: "Sainte-Colombe", description: "Village et site", niveau: 2, categorie: "remarquable", lat: 42.588, lng: 2.743 },
{ id: 99, commune: "Salses-le-Château", description: "Forteresse de Salses et Mémorial du Camp de Rivesaltes", niveau: 1, categorie: "incontournable", lat: 42.833, lng: 2.918 },
{ id: 100, commune: "Sauto", description: "Pont Gisclard (ou Pont de Cassagne)", niveau: 3, categorie: "suggéré", lat: 42.513, lng: 2.091 },
{ id: 101, commune: "Serdinya", description: "Église Saint-Marcel de Flassa", niveau: 3, categorie: "suggéré", lat: 42.567, lng: 2.319 },
{ id: 102, commune: "Serralongue", description: "Tours de Cabrenc, Église Ste-Marie et village", niveau: 3, categorie: "suggéré", lat: 42.398, lng: 2.556 },
{ id: 103, commune: "Sorède", description: "Les Micocouliers – La Fabrique des Fouets", niveau: 3, categorie: "suggéré", lat: 42.530, lng: 2.956 },
{ id: 104, commune: "Targassonne", description: "Thémis Solaire Innovation et Chaos de Targassonne", niveau: 2, categorie: "remarquable", lat: 42.499, lng: 1.996 },
{ id: 105, commune: "Tautavel", description: "Musée de Préhistoire et Tour del Far", niveau: 1, categorie: "incontournable", lat: 42.814, lng: 2.848 },
{ id: 106, commune: "Thuès-Entre-Valls", description: "Gorges de la Carança", niveau: 3, categorie: "suggéré", lat: 42.523, lng: 2.222 },
{ id: 107, commune: "Thuir", description: "Caves Byrrh", niveau: 1, categorie: "incontournable", lat: 42.633, lng: 2.756 },
{ id: 108, commune: "Torreilles", description: "Chapelle de Juhègues et site du Bourdigu", niveau: 2, categorie: "remarquable", lat: 42.755, lng: 3.001 },
{ id: 109, commune: "Toulouges", description: "Parc de Clairfont", niveau: 3, categorie: "suggéré", lat: 42.671, lng: 2.831 },
{ id: 110, commune: "Trouillas", description: "Église Saint-Assiscle", niveau: 2, categorie: "remarquable", lat: 42.612, lng: 2.808 },
{ id: 111, commune: "Ur", description: "Église Saint-Martin de Ur", niveau: 3, categorie: "suggéré", lat: 42.463, lng: 1.936 },
{ id: 112, commune: "Valcebollère", description: "Vallée de Valcebollère", niveau: 3, categorie: "suggéré", lat: 42.438, lng: 2.046 },
{ id: 113, commune: "Valmanya", description: "Forêt du Canigou", niveau: 1, categorie: "incontournable", lat: 42.538, lng: 2.534 },
{ id: 114, commune: "Vernet-les-Bains", description: "Village Arboretum", niveau: 1, categorie: "incontournable", lat: 42.548, lng: 2.389 },
{ id: 115, commune: "Villefranche-de-Conflent", description: "Cité UNESCO (Remparts), Fort Libéria, Église St-Jacques et Grotte Cova Bastera", niveau: 1, categorie: "incontournable", lat: 42.587, lng: 2.367 },
{ id: 116, commune: "Villelongue-dels-Monts", description: "Prieuré Santa Maria del Vilar", niveau: 3, categorie: "suggéré", lat: 42.525, lng: 2.871 },
{ id: 117, commune: "Vinça", description: "Lac des Escoumes, barrage et Église St-Julien et Ste-Basélisse", niveau: 2, categorie: "remarquable", lat: 42.645, lng: 2.529 },
{ id: 118, commune: "Vingrau", description: "Cirque de Vingrau", niveau: 2, categorie: "remarquable", lat: 42.851, lng: 2.779 },
];

export async function GET() {
  return NextResponse.json(pyreneesOrientalesSites);
}
